### ISSUE TITLE
Improve timeout handling in closing Connection/Session/Share

### ISSUE THREAD

**Issue by hierynomus** [hierynomus/smbj#102]
Copied comment on #86 from @oranoran: 

PR #101 makes sure there are no hang situations, but the unwinding process in case of a server failure may still take a long time.

A typical error handling sequence in case of timeout would make a close() request on the Session, which in turn triggers close() requests on individual shares. In case the server is not responding, each one of these requests would wait the full "transact" timeout period, so the full recovery process can take a few minutes, blocking the calling thread for the duration.

A possible set of improvements would be:

TreeConnect.close() could use a separate "close" timeout value, that would be by default much shorter than the "transact" value.
Session.close() could wait on all the Future objects of the various shares together, rather than one at a time. This requires changing the Share interface to expose the needed Future objects.
Session.close() doesn't really need to wait for the server's response to its own logoff request. Or - it can also wait wait for the shorter "close" timeout period.
Thoughts?

**Comment by bli-r7** [comment]
In my opinion, there's definitely use case where we don't need to wait for a reply from Session's close request at all. For instance, in Connection#close().

**Comment by hierynomus** [comment]
Actually it is good citizenship to nicely terminate the sessions, so that the server can also clean up.
We could introduce a `Connection#close(boolean force)` to prevent waiting.

I will in any case make it so that it closes all the sessions and then waits for the completion/timeout to happen.

**Comment by bli-r7** [comment]
I agree with the close(boolean force) approach.

**Comment by oranoran** [comment]
I think the question of whether or not to wait can be decoupled from the question whether to use a very clean&careful close sequence or just close the connection.

There can be a very careful and elaborate close sequence, but it can be done asynchronously the the user's call to close the connection would return immediately.

**Comment by bli-r7** [comment]
@hierynomus How is the timed out session currently cleaned up from the session table? The Connection#sessionLogOff seems to be unused.

**Comment by hierynomus** [comment]
It is handled by the eventbus.

Op 24 jul. 2017 4:29 p.m. schreef "bli-r7" <notifications@github.com>:

@hierynomus <https://github.com/hierynomus> How is the timed out session
currently cleaned up from the session table? The Connection#sessionLogOff
seems to be unused.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/hierynomus/smbj/issues/102#issuecomment-317440511>, or mute
the thread

**Comment by hierynomus** [comment]
Closing as I think this is now handled better, we have a `close(force)` call on the connection.

**Comment by cliviu** [comment]
Unfortunately,  SmbClient.close() calls the connection.close() with no force parameter.  
`   @Override
    public void close() {
        logger.info("Going to close all remaining connections");
        for (Connection connection : connectionTable.values()) {
            try {
                connection.close();
            } catch (Exception e) {
                logger.debug("Error closing connection to host {}", connection.getRemoteHostname());
                logger.debug("Exception was: ", e);
            }
        }
    }`

I have again a forever hanging thread: 
`"Thread-618" Id=1215 in TIMED_WAITING on lock=java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@364a9e
at sun.misc.Unsafe.park(Native Method)
at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2163)
at com.hierynomus.protocol.commons.concurrent.Promise.tryRetrieve(Promise.java:170)
at com.hierynomus.protocol.commons.concurrent.Promise.retrieve(Promise.java:134)
at com.hierynomus.protocol.commons.concurrent.PromiseBackedFuture.get(PromiseBackedFuture.java:58)
at com.hierynomus.protocol.commons.concurrent.CancellableFuture.get(CancellableFuture.java:84)
at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:38)
at com.hierynomus.smbj.session.Session.logoff(Session.java:247)
at com.hierynomus.smbj.session.Session.close(Session.java:274)
at com.hierynomus.smbj.connection.Connection.close(Connection.java:153)
at com.hierynomus.smbj.connection.Connection.close(Connection.java:128)
at com.hierynomus.smbj.SMBClient.close(SMBClient.java:136)`

Ideal will be a  `SmbClient.close(boolean force) ` . Any thoughts  ?
