### ISSUE TITLE
Exception with SMBClient

### ISSUE THREAD

**Issue by tandhy** [hierynomus/smbj#103]
Hi,

I am trying to connect to a shared drive: \\\sharedDrive\parent folder\theFolder.
The following is the code I used:
	```
	
```
try {
      final SMBClient client = new SMBClient();
    	    Connection connection = client.connect("sharedDrive");
    	    Session session = connection.authenticate(new AuthenticationContext("username", "password".toCharArray(), null));
    	    Share share = session.connectShare("parent folder\\theFolder");
	    share.close();
```
However, I got an exception when Java creates the client:
```
Exception in thread "main" java.lang.NoSuchMethodError: net.engio.mbassy.bus.SyncMessageBus: method <init>()V not found
	at com.hierynomus.smbj.event.SMBEventBus.<init>(SMBEventBus.java:30)
	at com.hierynomus.smbj.SMBClient.<init>(SMBClient.java:46)
	at com.hierynomus.smbj.SMBClient.<init>(SMBClient.java:41)
```

I used the codes from SMB2FileIntegrationTest.groovy.

Do you know what is causing the issues?
I will try to find the source as well.

**Comment by hierynomus** [comment]
Are you using it in a project where mbassador has a newer version?

Op 21 jun. 2017 8:34 p.m. schreef "Tandhy B.P. Simanjuntak" <
notifications@github.com>:

**Comment by hierynomus** [comment]
Just checked, the latest version of mbassador even has the no-args constructor.
Which version are you using?

**Comment by tandhy** [comment]
Thanks Jeroen,

I will double check that and share it here.

**Comment by tandhy** [comment]
Hi @hierynomus , thanks for the info.
I've updated the mbassador to the latest one. it works.
