### ISSUE TITLE
Async transport with NIO

### ISSUE THREAD

**Issue by oranoran** [hierynomus/smbj#109]
Currently there is a PacketReader thread doing a mostly-idle read for each active connection.
This can add up to a lot of threads.

It would be nice to use asynchronous I/O and have a single thread (or a small number of threads) doing reads and writes for all connections.

As a prerequisite, need to break the current coupling of the Connection class to the underlying synchronous transport layer. Currently there is a rather elaborate class hierarchy that makes this decoupling complex and doesn't deliver value, e.g the SocketClient object.

After the suggested refactoring, the Connection would not know anything about sockets or reader threads, and leave all of that to the DirectTcpTransport implementation. Also since the abstraction of Packet already exists, it's best for TransportLayer implementations to not even know that they are working specifically with SMB2 packets.

I will shortly create a PR with the suggested refactoring, and once the dust settles on that we can get to work an the actual issue of async transport.

**Comment by hierynomus** [comment]
Sounds like a nice improvement indeed. Let's fix it :)

**Comment by hierynomus** [comment]
Merged #110
