### ISSUE TITLE
SMBClient persists connection that could already be disconnected.

### ISSUE THREAD

**Issue by bli-r7** [hierynomus/smbj#114]
SMBClient getEstablishedOrConnect method does not check if the existing Connection in the connectionTable is still connected.

Assuming that the connection to the host is no longer connected, it is no longer possible to establish Connection to the same host using the same SMBClient instance. Is this working as intended?

See: https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/SMBClient.java#L80

**Comment by hierynomus** [comment]
You're right, that is unintended behaviour and a bug. Will fix it!
