### ISSUE TITLE
[Question] Expected TransportLayer#isConnected behaviour

### ISSUE THREAD

**Issue by bli-r7** [hierynomus/smbj#117]
TransportLayer#isConnected lacks javadoc.

Currently the DirectTcpTransport implementation returns true if the underlying socket has ever been connected, which would return true even if the connected socket is now closed.

The javadoc should specify the expected behaviour in this case.

**Comment by hierynomus** [comment]
You're right. It should not return true once disconnect() has been called. I'll update the JavaDoc and fix the bug. 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hierynomus** [comment]
Closing this as #118 is merged.
