### ISSUE TITLE
Open a FileId once, and re-use that for multiple operations on the file (existence, read, write, fileinfo, etc)

### ISSUE THREAD

**Issue by hierynomus** [hierynomus/smbj#12]

**Comment by pepijnve** [comment]
I'm working on this in https://github.com/pepijnve/smbj/tree/fileops
Idea is to add a bunch of instance methods to DiskEntry, File and Directory. I've added these next to the methods that take a FileId in DiskShare, but maybe the instance methods should actually replace those instead. What do you think?

**Comment by hierynomus** [comment]
Hi pepijn,

Indeed, that would be my preference also for the File and Directory
instances to have their own methods. Instead of coding everything on the
DiskShare.

Op 10 jun. 2017 4:03 p.m. schreef "Pepijn Van Eeckhoudt" <
notifications@github.com>:
