### ISSUE TITLE
java.lang.NoSuchMethodError immediately after Connection.close()

### ISSUE THREAD

**Issue by DigitalPigeon** [hierynomus/smbj#128]
For me, this simple code

```
SMBClient client = new SMBClient();
Connection connection = client.connect(server); 
connection.close(); 
```

throws the following exception after the close (it should be noted I can create sessions and authenticate just fine with the connection - but I always get the exception immediately following the connection close. This is the simplest form of the code that throws the exception.

```
Root Exception stack trace:
java.lang.NoSuchMethodError: net.engio.mbassy.bus.common.PubSubSupport.publish(Ljava/lang/Object;)Lnet/engio/mbassy/bus/IMessagePublication;
	at com.hierynomus.smbj.event.SMBEventBus.publish(SMBEventBus.java:46)
	at com.hierynomus.smbj.connection.Connection.close(Connection.java:109)
	at soapdoc.ZediFileManagerTest.getSmbj(ZediFileManagerTest.java:153)

```

Using mbassador-1.2.4.2 and smbj-0.2.0

Thanks in advance for any help you can offer.

**Comment by hierynomus** [comment]
Hi, can you check whether you use the same mbassador version as that smbj
0.2.0 is compiled against?

Op 17 jul. 2017 7:41 p.m. schreef "Chris Friedel" <notifications@github.com

**Comment by DigitalPigeon** [comment]
Wow hierynomus, you are too fast!! :)

Sorry, I was looking at the wrong version of smbj on maven - and so I grabbed the wrong mbassador. Moving to mbassafor 1.3 works (this is actually a dupe of item #103 it turns out).

Sorry for the mistake

Chris
