### ISSUE TITLE
Question about accessing files in sub folders of shares

### ISSUE THREAD

**Issue by DigitalPigeon** [hierynomus/smbj#129]
Hello All
SMBJ is working great for us, except we aren't clear how to access files that are in sub directories of shares.
I've been searching the test cases and code for a couple of hours, but don't see any hints on the correct way to deal with this.

In the case of **\\host\share\file.txt** the following works great
```
SMBClient client = new SMBClient(SmbConfig.builder().build());
Connection connection = client.connect("host");
Session session = connection.authenticate(auth);
DiskShare share = (DiskShare)session.connectShare("share");

file = share.openFile("file.txt", 
  new HashSet<>(Arrays.asList(AccessMask.GENERIC_READ)),
  new HashSet<>(Arrays.asList(FileAttributes.FILE_ATTRIBUTE_NORMAL)),
  SMB2ShareAccess.ALL,
  SMB2CreateDisposition.FILE_OPEN,
  new HashSet<>(Arrays.asList(SMB2CreateOptions.FILE_DIRECTORY_FILE)));
```

However, in the case of  **\\host\share\dir1\dir2\dirx\file.txt** we can not open the file. We have tried the same code as above, but passing to openFile all of the following combinations
`file = share.openFile("\\dir1\\dir2\\dirx\\file.txt"`
`file = share.openFile("dir1\\dir2\\dirx\\file.txt"`
`file = share.openFile("/dir1/dir2/dirx/file.txt"`
`file = share.openFile("dir1/dir2/dirx/file.txt"`

But this always provides STATUS_OBJECT_NAME_NOT_FOUND

We see the share.openDirectory - but do not see any way to open a child directory or file from that object.

Is there any example code someone could point me to, or just give a rough idea of the API call order we would use to open files in sub directories?

Thank you very much again for the help!

**Comment by hierynomus** [comment]
Hi @DigitalPigeon,

I've just added an integration test case that passes on my VM. Have a look whether this answers your question.
Testcase -> https://github.com/hierynomus/smbj/blob/master/src/it/groovy/com/hierynomus/smbj/SMB2FileIntegrationTest.groovy#L96

**Comment by DigitalPigeon** [comment]
Thank you for the test case hierynomus. 
Not sure what on earth I was doing wrong before, but redid everything from scratch as per your example, and everything works great now.
Thank you again - amazing work!

**Comment by satya081** [comment]
@DigitalPigeon Could you please share the code which is creating subfolder automatically before creating the file.

**Comment by DigitalPigeon** [comment]
Oops, I think you may have accidentally replied to the wrong issue?

Sent from a mobile device.
________________________________

**Comment by antoinemalinur** [comment]
> Hi @DigitalPigeon,
> 
> I've just added an integration test case that passes on my VM. Have a look whether this answers your question. Testcase -> https://github.com/hierynomus/smbj/blob/master/src/it/groovy/com/hierynomus/smbj/SMB2FileIntegrationTest.groovy#L96

Hello, i have the same issue and the test case is not accessible anymore. Can you help thanks
