### ISSUE TITLE
Is there anyone working on supporting "skip" or "seek" on the stream?

### ISSUE THREAD

**Issue by Varsha-Nagarajan** [hierynomus/smbj#132]
The idea behind this would be to allow file copy to resume from a point where we left it rather than doing the entire thing all over again (something similar to checkpoints). Jcifs has a "skip" implementation for its stream but could not find the same for smbj . Are there any plans to support this use case or is there some existing way to do this (which I might have overlooked) ?

**Comment by hierynomus** [comment]
Currently the library already supports reading and writing from an offset. Which is I think what you are looking for? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Varsha-Nagarajan** [comment]
Actually, the implementation is done is such a way that I would be requiring a stream with pointer advanced to the location of the offset. So that the subsequent reads on the stream would start from that point onward. Earlier we have been depending on jcifs library which advances a pointer (count variable) based on the offset. Subsequent reads on that stream, continue from where the pointer now points. I hope I'm able to explain the issue I'm facing. This is the reason, an overridden implementation of the InputStream's "skip" method in accordance to the library's current read/write would help me a lot.

**Comment by bli-r7** [comment]
@Varsha-Nagarajan 
You should be able to write a simple wrapper that keeps the file pointer that gets used when calling the underlying File#read with the offset and the number of bytes read was added to the file pointer.

**Comment by tliebeck** [comment]
I ran into this same issue and added this implementation of skip() to FileInputStream.
Please bear in mind this is not 100% tested, may be flawed, and I'm not a developer on this project.  

    @Override
    public long skip(long n) throws IOException {
        if (buf == null) {
            offset += n;
        } else if (curr + n < buf.length) {
            curr += n;
        } else {
            buf = null;
            offset += n;
        }
        return n;
    }

**Comment by hierynomus** [comment]
@tliebeck Fixed it, you were right there was a slight flaw in it, which was exposed using some added tests.
