### ISSUE TITLE
SymbolicLinkError.readOffsettedString - underflow exception

### ISSUE THREAD

**Issue by mice777** [hierynomus/smbj#135]
Should not this:
`s = buffer.readString(StandardCharsets.UTF_16, length);`

be rather
`s = buffer.readString(StandardCharsets.UTF_16, length / 2);`

Each time when `buffer.readString` is used with UTF16 variant, length is halved, except of this line. And I get underflow exception here.

**Comment by hierynomus** [comment]
Thanks for catching that.

Op 28 jul. 2017 1:34 p.m. schreef "mice777" <notifications@github.com>:
