### ISSUE TITLE
SymbolicLinkError.read() bug

### ISSUE THREAD

**Issue by mice777** [hierynomus/smbj#136]
In SymbolicLinkError.read, you forget to read field `ReparseDataLength` as written in specification, resulting in nonsense rest of data.

**Comment by mtamassia** [comment]
Thank you @mice777 per https://msdn.microsoft.com/en-us/library/cc246542.aspx it looks like you are correct, the current code skips 4 bytes for `SymLinkErrorTag`, then 4 bytes for `ReparseTag` and then the 2 bytes for UnparsedPathLength. I can submit a PR with the missing piece but I need your help to replicate the issue. What is the easiest way for me to replicate the issue so I can test the code change?

**Comment by mice777** [comment]
I have Windows7 and it shows "Users" share, inside this are some symbolic links for example "All users" or "Default User". Opening these folders (e.g. for listing) returns error with instantiation of SymbolicLinkError.
