### ISSUE TITLE
Is it possible to detect quickly if the server does not support SMBv2/v3?

### ISSUE THREAD

**Issue by SuperPat45** [hierynomus/smbj#137]
Hi,

I need to add support for SMB v2/3 shares and keeping compatibility of SMBv1 shares (through jcifs).
I have my own API based on URL scheme like smb://domain;user:password@host/share

If I try to connect to a SMB v1 only share  (on a Windows Server 2003), smbj throw after one minute:
> Exception in thread "main" com.hierynomus.smbj.common.SMBRuntimeException: java.util.concurrent.TimeoutException: Timeout expired
> 	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
> 	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
> 	at com.hierynomus.protocol.commons.concurrent.Promise.retrieve(Promise.java:140)
> 	at com.hierynomus.smbj.connection.Request$1.get(Request.java:125)
> 	at com.hierynomus.smbj.connection.Request$1.get(Request.java:71)
> 	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:38)
> 	at com.hierynomus.smbj.connection.Connection.negotiateDialect(Connection.java:238)
> 	at com.hierynomus.smbj.connection.Connection.connect(Connection.java:94)
> 	at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:82)
> 	at com.hierynomus.smbj.SMBClient.connect(SMBClient.java:62)
> 	at TestSMB.getSMB2Share(TestSMB.java:84)
> 	at TestSMB.main(TestSMB.java:28)
> Caused by: java.util.concurrent.TimeoutException: Timeout expired
> 	... 10 more

I don't know if it is possible to detect quickly if the server does not support SMBv2/v3 to falling back to jcifs.

Would it be possible to have a better and immediate exception? (like SMBv2NotSupportedException or SMBv1OnlyShareException)
Or maybe with a new function in SMBClient to detect the min/max API level supported (1.0, 2.0, 2.1, 3.0) by the server?

**Comment by pepijnve** [comment]
This is possible within the SMB protocol, but smbj currently doesn't support this yet. To do this smbj would have to send a CIFS (SMB 1.0) style negotiate message to the server. At the moment it sends the SMB 2 only negotiate message. Sections 4.1 and 4.2 provide some examples of this.
