### ISSUE TITLE
Remove the mbassador library log message: "No error handler has been configured to handle exceptions during publication."

### ISSUE THREAD

**Issue by SuperPat45** [hierynomus/smbj#138]
Hi,

The mbassador library add this log this message (since version 1.1.7) each time a new SMBClient is instanciated:
> INFO: No error handler has been configured to handle exceptions during publication.
> Publication error handlers can be added by IBusConfiguration.addPublicationErrorHandler()
> Falling back to console logger.

I found this message can be easily removed by changing the SMBEventBus constructor:
```
public class SMBEventBus {

    private PubSubSupport<SMBEvent> wrappedBus;

    public SMBEventBus() {
        this(new SyncMessageBus<SMBEvent>());
    }
//....
```
by:
```
public class SMBEventBus {

    private PubSubSupport<SMBEvent> wrappedBus;

    public SMBEventBus() {
        this(new SyncMessageBus<SMBEvent>(new IPublicationErrorHandler.ConsoleLogger()));
    }
//....
```

**Comment by mtamassia** [comment]
@SuperPat45 I submitted a Pull Request #146 with the changes you have above. Thank you.

**Comment by SuperPat45** [comment]
Thanks
