### ISSUE TITLE
Status Sharing Violation

### ISSUE THREAD

**Issue by jpaintern** [hierynomus/smbj#141]
Hello,

I am brand new to github and currently working an internship. 

I'm trying to use smbj in the project to connect to a folder on a remote server and copy all the txt files to the local machine .

Here is my code:

`Security.addProvider(new BouncyCastleProvider());
		SMBClient smb = new SMBClient();
		Connection con = smb.connect("ServerName");
		Session ses = con.authenticate(new AuthenticationContext("Username", "Password".toCharArray(), "LoginDomain"));
		DiskShare share = (DiskShare) ses.connectShare("ShareName");`
		
		for (FileInfo f : share.list("")) {
            System.out.println("File : " + f.getFileName());
            File dest = new File("/temp/2/" + f.getFileName());
			System.out.println(f.getFileName() + " " + share.getShareInformation() + "_ " + share.getTreeConnect());
			com.hierynomus.smbj.share.File randomAccess = share.openFile(f.getFileName(),
	                EnumSet.of(AccessMask.GENERIC_READ),
	                SMB2CreateDisposition.FILE_OPEN);
			Files.copy(randomAccess.getInputStream(), dest.toPath());
        }`

When I run this code, I can successfully connect to the server and the getFileName() calls work. However, I get the following error message on the openFile() call:

`STATUS_SHARING_VIOLATION(3221225539/3221225539): Create failed for example.txt`

I don't know how to fix this and I'm not trying to create a file, just copy one. If I go to the Windows File Explorer I can open the document with no issues. Does anyone have any suggestions? 

Thanks for your help.

**Comment by mtamassia** [comment]
@jpaintern I use smbj for a similar use-case without issues. Please make sure you are using the latest release.

Also, here is portion of the code I am using, in case you want to try it.

```

try (OutputStream os = new FileOutputStream(targetFile)) {
 try (File file = share.openFile(filePathInSMB, EnumSet.of(AccessMask.GENERIC_READ), EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL), EnumSet.of(SMB2ShareAccess.FILE_SHARE_READ), SMB2CreateDisposition.FILE_OPEN, EnumSet.noneOf(SMB2CreateOptions.class))) {
    file.read(os);
  }
}

```

**Comment by jpaintern** [comment]
How do I make sure I'm using the latest release? I installed it using the Maven link on the front page. I'm new to Maven too. Thanks for your help though I will try it!

**Comment by jpaintern** [comment]
Aww got it! Referenced this file https://github.com/hierynomus/smbj/blob/master/src/it/groovy/com/hierynomus/smbj/SMB2FileIntegrationTest.groovy

Thanks!
