### ISSUE TITLE
Print question

### ISSUE THREAD

**Issue by gidravlic** [hierynomus/smbj#142]
Hello! In the old version of the library(0.9) i could print through method:
```java
static void write(PrinterShare share, String remotePath, InputStream is) throws IOException, SMBApiException {
        SMB2FileId fileId = share.open(
                remotePath,
                AccessMask.FILE_WRITE_DATA.getValue(),
                EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL),
                EnumSet.of(SMB2ShareAccess.FILE_SHARE_WRITE),
                SMB2CreateDisposition.FILE_CREATE,
                EnumSet.of(SMB2CreateOptions.FILE_WRITE_THROUGH));
        com.hierynomus.smbj.share.File file = new File(fileId, share.getTreeConnect(), remotePath, 0L);
        file.write(new InputStreamByteChunkProvider(is));
        file.close();
}
```
With latest version of the library, this code don't work. 
How to print to printer right now?
Thanks!

**Comment by gidravlic** [comment]
Hi @hierynomus !
After searching problem, i'm discovered that File class constructor takes only DiskShare parameter. I changed PrinterShare class, instead:
```java 
public class PrinterShare extends Share 
```
I extend PrinterShare from DiskShare
```java
public class PrinterShare extends DiskShare {

    public PrinterShare(SmbPath smbPath, TreeConnect treeConnect) {
        super(smbPath, treeConnect);
    }

    public void print(String fileName, InputStream content) {
        try (File file = openFile(
                fileName,
                EnumSet.of(AccessMask.FILE_WRITE_DATA),
                EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL),
                EnumSet.of(SMB2ShareAccess.FILE_SHARE_WRITE),
                SMB2CreateDisposition.FILE_CREATE,
                EnumSet.of(SMB2CreateOptions.FILE_WRITE_THROUGH))) {
            file.write(new InputStreamByteChunkProvider(content));
        }
    }
}
```
calling work perfectly
```java
printerShare.print("test.txt", new ByteArrayInputStream("Test Test Test".getBytes(StandardCharsets.UTF_8)));
```
I do not quite understand the whole architecture of the library in order to make appropriate changes to it. What thoughts?

Thanks!

**Comment by pepijnve** [comment]
@gidravlic I submitted a pull request that solves this in a slightly better way. Extending DiskShare is not ideal since that allows a lot of operations to be attempted on a printer share that don't make sense (creating directories, creating symlinks, deleting files, ...). The idea is that only those methods that make sense on a particular type of share are exposed as public methods.

**Comment by pepijnve** [comment]
@gidravlic What are you using as filename in practice BTW? The spec says the filename should always be `null` when opening printer files, but perhaps that doesn't work in practice.

**Comment by hierynomus** [comment]
Indeed, the spec says this

**3.2.4.3.2 Application Requests Sending a File to Print**
For sending a file to a printer, the application opens the root of a print share, writes data, and closes the file. The semantics and parameters are the same as specified in section 3.2.4.3, except that **TreeConnect.ShareName** will be the name of a printer share, and the share relative path MUST be NULL.

I think the windows server side might not strictly check on this. But I could imagine samba would for instance.

**Comment by gidravlic** [comment]
Yes, you are right! My mistake, but it work :) Thanks for the quick solution 👍

**Comment by gidravlic** [comment]
> I submitted a pull request that solves this in a slightly better way. Extending DiskShare is not ideal since that allows a lot of operations to be attempted on a printer share that don't make sense (creating directories, creating symlinks, deleting files, ...).
@pepijnve Yes, right. Therefore, I asked how it would be better. Thanks! 👍
