### ISSUE TITLE
Not connecting to Microsoft azure (SMB3)

### ISSUE THREAD

**Issue by debarghya85** [hierynomus/smbj#151]
Can I connect Microsoft azure file share storage through Normal SMB3 connection of this package?. I have developed code to connect fileshare in Windows Server2012 via SMB3. But while connecting in azure its not working though Azure supports SMB3.
com.hierynomus.smbj.common.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Authentication failed for XXX using com.hierynomus.smbj.auth.NtlmAuthenticator

**Comment by hierynomus** [comment]
What is the error you're getting? Please add some logs on debug or trace
level

Op 9 aug. 2017 8:27 a.m. schreef "debarghya85" <notifications@github.com>:

**Comment by debarghya85** [comment]
My code:
------------

String filename = "xyz"+ java.io.File.separator+"abc.txt";
// connection params
String sambaDomain 		= null; // can be null
String sambaUsername 	= "My User Name";
String sambaPass 		= "My Access Key";
String sambaIP 			= "My End Point IP";
String sambaSharedPath 	= "My Shared";
try {

	SmbConfig cfg 		= SmbConfig.builder().build();
	SMBClient client 	= new SMBClient(cfg);
	com.hierynomus.smbj.connection.Connection connection 	= client.connect(sambaIP);

	com.hierynomus.smbj.session.Session session 			= connection.authenticate(new AuthenticationContext(sambaUsername, sambaPass.toCharArray(), sambaDomain));
}catch (Exception exc) {
	exc.printStackTrace();
	
}


Stack Trace I Got
-------------------
com.hierynomus.smbj.common.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Authentication failed for 'My User Name' using com.hierynomus.smbj.auth.NtlmAuthenticator@116b08c2
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:150)
	
	
	
Same code Working for Windows Server 2012 File share with SMB3 Enable With SMBJ Library.

**Comment by hierynomus** [comment]
It seems that the credentials are not correct?

**Comment by debarghya85** [comment]
But with same AccountName and AccountKey with Microsoft Library Its working. I am confused Why its not working with SMBJ library as it also supports SMB3.

**Comment by hierynomus** [comment]
Can you try using the SPNego authenticator?

ie. Construct the SmbConfig as follows: `SmbConfig.builder().withAuthenticators(new SpnegoAuthenticator.Factory()).build()`.

Also, which version of SMBJ are you using?

**Comment by hierynomus** [comment]
SMB2.02 and SMB2.1 support are done, SMB3.x support is in the works. If
Azure only supports SMB3, then it would have failed earlier (ie. during
protocol negotiation).

2017-08-09 11:27 GMT+02:00 debarghya85 <notifications@github.com>:

**Comment by debarghya85** [comment]
I am using SMBJ 0.2.0

**Comment by hierynomus** [comment]
Can you post the entire trace log of a connection attempt?

2017-08-09 14:33 GMT+02:00 debarghya85 <notifications@github.com>:

**Comment by hierynomus** [comment]
As I said you should give SPNEGO a try, what I forgot to say is that you need to pass a different AuthenticationContext to SMBJ, ie. `GSSAuthenticationContext`.

Maybe that works?

**Comment by debarghya85** [comment]
This is the debug and info log while auth (Normal auth, Till now not tested with Spengo)

com.hierynomus.protocol.commons.socket.ProxySocketFactory - Connecting to "My Azure Share Endpoint"/IP:445
com.hierynomus.smbj.transport.PacketReader - Starting PacketReader on thread: Packet Reader for "My Azure Share Endpoint"
com.hierynomus.smbj.connection.Connection - Negotiating dialects [SMB_2_0_2, SMB_2_1] with server "My Azure Share Endpoint"
com.hierynomus.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 0 >>
com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_NEGOTIATE with message id << 0 >>
[Packet Reader for "My Azure Share Endpoint"] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_NEGOTIATE with message id << 0 >>
[Packet Reader for "My Azure Share Endpoint"] INFO com.hierynomus.smbj.connection.Connection - Server granted us 1 credits for SMB2_NEGOTIATE with message id << 0 >>, now available: 1 credits
com.hierynomus.smbj.connection.Connection - Negotiated the following connection settings: ConnectionInfo{
  serverGuid="My Server GUID",
  serverName='"My Azure Share Endpoint"',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_2_1, maxTransactSize=1048576, maxReadSize=1048576, maxWriteSize=1048576},
  clientGuid="My Client GUID",
  clientCapabilities=null,
  serverCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LEASING, SMB2_GLOBAL_CAP_LARGE_MTU],
  clientSecurityMode=0,
  serverSecurityMode=3,
  server='null'
}
com.hierynomus.smbj.connection.Connection - Successfully connected to: "My Azure Share Endpoint"
com.hierynomus.smbj.auth.NtlmAuthenticator - Initialized Authentication of "My Account Name" using NTLM
com.hierynomus.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 1 >>
com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_SESSION_SETUP with message id << 1 >>
[Packet Reader for "My Azure Share Endpoint"] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_SESSION_SETUP with message id << 1 >>
[Packet Reader for "My Azure Share Endpoint"] INFO com.hierynomus.smbj.connection.Connection - Server granted us 1 credits for SMB2_SESSION_SETUP with message id << 1 >>, now available: 1 credits
com.hierynomus.smbj.common.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Authentication failed for '"My Account Name"' using com.hierynomus.smbj.auth.NtlmAuthenticator@19b35853Disconnected from the target VM, address: '127.0.0.1:54895', transport: 'socket'
com.hierynomus.smbj.common.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Authentication failed for '"My Account Name"' using com.hierynomus.smbj.auth.NtlmAuthenticator@19b35853
	at com.hierynomus.smbj.connection.Connection.authenticate(Connection.java:150)

**Comment by hierynomus** [comment]
What authentication does your MS library use, I think that the problem here is that NTLM authentication is either not enabled, or allowed. The protocol negotiation is OK, and SMB2.1 has been negotiated. This really is in the authentication layer.

**Comment by debarghya85** [comment]
which NTLM version SMBJ used?

**Comment by hierynomus** [comment]
NTLMv2 is implemented in the NTLMAuthenticator.

**Comment by debarghya85** [comment]
I want to know , is SMBJ supports Microsoft Azure Cloud FileShare(Both Authentication and Fileshare)? 

I have checked Microsoft Library for azure storage file share. In that they are using like following code
public static final String storageConnectionString ="DefaultEndpointsProtocol=http;AccountName=your_account_name;AccountKey=your_account_key";

CloudStorageAccount account = CloudStorageAccount.parse(storageConnectionString);
CloudFileClient fileClient = account.createCloudFileClient();
share = fileClient.getShareReference("sampleshare");

But in SMBJ coding is different. and I have not found any area where I can turn on NTLM in azure.
So I want to know ,Is SMBJ support Azure Cloud Fileshare and its authentication.

**Comment by pepijnve** [comment]
[This troubleshooting guide from Microsoft](https://docs.microsoft.com/en-us/azure/storage/storage-troubleshoot-windows-file-connection-problems#cause-3-ntlmv1-is-enabled) seems to indicate NTLMv2 is supported.

@debarghya85 as far as I know SMBJ doesn't have any specific code or support for Azure Files. It implements an SMB 2.0+ client library and should in theory be able to communicate with any spec compliant SMB server.

**Comment by hierynomus** [comment]
Can you try to capture a network trace (pcap file) from a connection to
Azure using the MS library?

2017-08-11 11:19 GMT+02:00 Pepijn Van Eeckhoudt <notifications@github.com>:

**Comment by pepijnve** [comment]
> DefaultEndpointsProtocol=http

and [the note in this Microsoft tutorial](https://docs.microsoft.com/en-us/azure/storage/storage-dotnet-how-to-use-files) make me think the .net library is actually using the HTTP REST interface; not SMB.

**Comment by hierynomus** [comment]
I think you're right @pepijnve. But the note also specifies it is possible to access through SMB, just no link how it does that.

**Comment by pepijnve** [comment]
The [Windows](https://docs.microsoft.com/en-us/azure/storage/storage-file-how-to-use-files-windows), [Linux](https://docs.microsoft.com/en-us/azure/storage/storage-how-to-use-files-linux) and [Mac](https://docs.microsoft.com/en-us/azure/storage/storage-file-how-to-use-files-mac) pages describe that.

**Comment by debarghya85** [comment]
@pepijnve Map network drive also tested. Its also not supporting through SMBJ. drive is not recognized by SMBJ.

**Comment by hierynomus** [comment]
Judging from the note it is this restriction that is blocking it:

    In order to mount an Azure File share outside of the Azure region it is hosted in, such as on-premises or in a different Azure region, the OS must support the encryption functionality of SMB 3.0. 

And currently encryption has not been implemented yet, only signing (and signature verification)

**Comment by john-latham** [comment]
I have the same issue with a requirement for SMB3 encryption. Actually, requiring encryption seems to be the recommended way to enforce SMB3-only access to a network resource.

On Windows 2012 R2 server the powershell commands to set this up are:

Set-SmbServerConfiguration -EnableSMB1Protocol $false
Set-SmbServerConfiguration -EnableSMB2Protocol $true﻿
Set-SmbServerConfiguration –EncryptData $true

Source: https://blogs.technet.microsoft.com/filecab/2012/05/03/smb-3-security-enhancements-in-windows-server-2012/

Any indication of when encryption is likely to be supported?

I have an AWS sandbox server set up with SMB3 and encryption required (as described above) that I can IP-whitelist if it helps contributors.

**Comment by hierynomus** [comment]
@john-latham Thanks for the offer. Currently I'm trying to fix DFS support (which is a nasty beast ;)).  After that it would be a good addition to add encryption. But in the meantime feel free to start a PR! Any help is welcome.

**Comment by debarghya85** [comment]
Thanks for all the communication.I will surely looking forward with the enhancement.

**Comment by john-latham** [comment]
KRACK makes this enhancement rather more urgent, IMO, since we can no longer rely on wifi security to prevent eavesdropping of data in transit.

**Comment by gfenyvesi** [comment]
Hi Jeroen,
Just out of curiosity, do you have any progress in SMB3 encryption?
And thanks for the great library :)

**Comment by hierynomus** [comment]
Hi,

No I have not been able to make any progress on this as of yet due to
work/home obligations ;)
But it is top-of-mind. I do welcome a helping hand / PR ;)

2018-03-10 13:53 GMT+01:00 gfenyvesi <notifications@github.com>:

**Comment by hierynomus** [comment]
Merged to master with #455
