### ISSUE TITLE
ClassCastException in NtlmAuthenticator.java

### ISSUE THREAD

**Issue by mice777** [hierynomus/smbj#160]
Following code has problem:

```
Object msvAvFlags = challenge.getAvPairObject(AvId.MsvAvFlags);
if (msvAvFlags != null && ((int) msvAvFlags & 0x00000002) > 0) {
```

The `msvAvFlags` is actually stored as Long in `NtlmChallenge.readTargetInfo`, so if it is set, you get guaranteed ClassCastException "java.lang.Long cannot be cast to java.lang.Integer"

Safe fix:
`if((msvAvFlags instanceof Long) && ((long)msvAvFlags&2)>0){`

**Comment by mtamassia** [comment]
Thank you @mice777 
I submitted the PR #162 with the fix

**Comment by mtamassia** [comment]
@hierynomus please take a look at the PR #162 when you have a chance.

**Comment by ecki** [comment]
`if ((msvAvFlags instanceof Number) && ((Number)msvAvFlags).intValue() & 2)==2)` would be more generic (or longValue() to not truncate).

But then again, maybe changing it to `Long` type is better for that field.


    {
         return ((Number) obj).intValue();
