### ISSUE TITLE
DiskShare.list(path, pattern)

### ISSUE THREAD

**Issue by gidravlic** [hierynomus/smbj#163]
Hello!
When i call method with non exist file pattern/mask i'm catch exception:
```java
com.hierynomus.smbj.common.SMBApiException: UNKNOWN(4294967295/3221225487): Query directory failed for SMB2FileId{persistentHandle=b0 03 00 00 28 00 00 00}
        at com.hierynomus.smbj.share.Share.receive(Share.java:328)
        at com.hierynomus.smbj.share.Share.sendReceive(Share.java:312)
        at com.hierynomus.smbj.share.Share.queryDirectory(Share.java:183)
        at com.hierynomus.smbj.share.Directory$DirectoryIterator.queryDirectory(Directory.java:173)
        at com.hierynomus.smbj.share.Directory$DirectoryIterator.<init>(Directory.java:129)
        at com.hierynomus.smbj.share.Directory.iterator(Directory.java:107)
        at com.hierynomus.smbj.share.Directory.list(Directory.java:62)
        at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:166)
        at com.hierynomus.smbj.share.DiskShare.list(DiskShare.java:147)
```
Maybe better to return an empty list?
```java
Collections.emptyList();
```
Thanks!

**Comment by mtamassia** [comment]
@hierynomus I can submit a PR for this if you agree with the approach above (empty list) vs. throwing an exception.

**Comment by hierynomus** [comment]
The empty list is only warranted for the status_no_such_file (ie. The
status number you posted.) any other ntstatus code should result in an
exception.

Op 18 aug. 2017 7:29 p.m. schreef "mtamassia" <notifications@github.com>:

**Comment by mtamassia** [comment]
@hierynomus I think the best approach here might be to change the `Set<NtStatus> successResponses` passed in for the Query directory from `SUCCESS_OR_NO_MORE_FILES` to a new `EnumSet<NtStatus> SUCCESS_OR_NO_MORE_FILES_OR_NO_SUCH_FILE`. This will prevent the exception from being thrown in all query directory calls if the file doesn't exist. 

Please let me know if you agree and I will work on it.

**Comment by hierynomus** [comment]
Makes sense!

Op 18 aug. 2017 8:35 p.m. schreef "mtamassia" <notifications@github.com>:

**Comment by gidravlic** [comment]
Why did I write about this? I'm trying to write a new project using new java 8-9 language features. And if I use lambda, I get a problem with exceptions. Maybe I do not know how to cook them(lambda) :) ?

**Comment by mtamassia** [comment]
@gidravlic I think what you are bringing up is totally reasonable. I am working on it.

**Comment by mtamassia** [comment]
See Pull Request #165

**Comment by gidravlic** [comment]
Nice! And I find some miscommunication with checking (., ..) file names (isFile - isDirectory). I will open issue at beginning next weekday. Thanks all!

**Comment by mtamassia** [comment]
@gidravlic the pull request has been merged. The issues can be closed @hierynomus

**Comment by gidravlic** [comment]
@hierynomus Hi! It is very good. My code will be clearer, more compact and understandable.
Thanks to all!
