### ISSUE TITLE
[Question] Can we cut a new release?

### ISSUE THREAD

**Issue by bli-r7** [hierynomus/smbj#164]
Can we cut a new release on the current master? 
We would like to start using the latest build as it contains a number of improvements. 

I understand https://github.com/hierynomus/smbj/pull/155 is still in progress so we'll leave that alone for now.

If @hierynomus prefers this kind of request goes through an email instead of opening issues please let me know.

**Comment by hierynomus** [comment]
I don't mind the issue. Keeps the discussion nice and transparent :). I'll fix some things over the weekend i hope and will make the release start of next week. Agreed? 

_Sent from my Samsung SM-G950F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bli-r7** [comment]
@hierynomus Sounds good. Thank you.

**Comment by bli-r7** [comment]
@hierynomus Any news on cutting a new release?

**Comment by hierynomus** [comment]
Done! v0.3.0 has been released just now!
