### ISSUE TITLE
File separator

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#170]
Hi,
  Does anybody know how to get the file separator of the remote file system ? 

  Thanks.

**Comment by hierynomus** [comment]
Good question. Which OS are you connecting to? I'm guessing not Windows :)

**Comment by cliviu** [comment]
actually I must support Windows/Linux. because I do not have yet a linux SMBv2 I'm testing with a Windows share :-( . But basically I must be able to connect to both of them

**Comment by cliviu** [comment]
The problem is how can I get the "directory" part of a path. the JCIFS API has a SmbFile.getParent() method that I have to replace somehow (or you know an equivalent of it in smbj ). Thanks !

**Comment by pepijnve** [comment]
Path names in SMB2 always adhere to [MS-FSCC 2.1.5](https://msdn.microsoft.com/en-us/library/cc422524.aspx). This specifies that the path separator is always `\` regardless of the OS the SMB server is running.

**Comment by cliviu** [comment]
thanks @pepijnve !
