### ISSUE TITLE
Could not find smbj-0.2.0 Java extension for this JVM

### ISSUE THREAD

**Issue by atanuiitd** [hierynomus/smbj#172]
Hi ,
I am trying to incorporate smbj-0.2.0 jar in project for accessing SMB2 based CIFS share . 
During build process Jenkins is throwing error
 /usr/bin/build-jar-repository: error: **Could not find smbj-0.2.0 Java extension for this JVM.**

I have copied the jar in the lib folder & all import statements[import com.hierynomus.smbj.SMBClient;] are resolved properly.

Any idea why this error is thrown ?

**Comment by ecki** [comment]
This is hard to answer without knowing your buildjob. The build-jar-Repository is part of the jpackages tool and search the JAR in a specified lib dir. Maybe you specified the wrong libdir or do not want to use the tool for custom JARs at all.

It is certainly no smbj bug.

**Comment by hierynomus** [comment]
@ecki Thanks for the comment. You're right indeed. This is no SMBJ bug.

I'm closing this issue.
