### ISSUE TITLE
Testing SMB2 from Java

### ISSUE THREAD

**Issue by IrynaZhumatiy** [hierynomus/smbj#173]
Hello.
Could you please tell how can I test connection via SMB2?
I have some code:
`SMBClient smbClient = new SMBClient();
        try (Connection connection = smbClient.connect(exportSessionVO.getRemHost(), exportSessionVO.getPort())) {
            AuthenticationContext authenticationContext = new AuthenticationContext(exportSessionVO.getUserName(), exportSessionVO.getPassword().toCharArray(), exportSessionVO.getRemDomain());
            Session session = connection.authenticate(authenticationContext);` ....
Could you please give me an advise how to test this from Java?
If I call smbClient.connect with dummy data, I get SocketTimeoutException: connect timed out.
Thanks!

**Comment by hierynomus** [comment]
Yes, getting the SocketTimeout probably means that it cannot find the host you're connecting to.
If you look at the test cases, you can inject a dummy transport into the config, which allows you to stub out the real connection.

**Comment by IrynaZhumatiy** [comment]
Thank you for your answer!
How can I inject a dummy transport into the config?
And which test cases I can look? What do you mean?
I need to dummy data not real.

**Comment by pepijnve** [comment]
See https://github.com/hierynomus/smbj/blob/bdf20c29f768211e9e05031a7cc39668b2094600/src/test/groovy/com/hierynomus/smbj/share/FileReadSpec.groovy for an example.

**Comment by IrynaZhumatiy** [comment]
Thanks.
It's very useful link!
But when I want to inject StubTransportLayerFactory  - I cannot see this class from Intellij.
The class does not exist.
I use smbj-0.2.0

**Comment by pepijnve** [comment]
Should be available in the groovy test source tree. See https://github.com/hierynomus/smbj/blob/v0.2.0/src/test/groovy/com/hierynomus/smbj/connection/StubTransportLayerFactory.groovy

**Comment by hierynomus** [comment]
Correct, it is test code, so it is not contained in the production jar.

The question is, why are you (unit) testing SMBJ in your application :). Typically you should abstract away the network(protocol) layers of your app and stub them for unit tests. Only for integration tests you use real implementations, but then you would also have real machines you can test with, so no need for dummy data.

**Comment by IrynaZhumatiy** [comment]
Thanks a lot for your answers!

**Comment by hierynomus** [comment]
Sure, if you have no more questions, I assume we can close the ticket?

**Comment by IrynaZhumatiy** [comment]
Yes, of course.

**Comment by hierynomus** [comment]
Thanks, let me know if you've got more questions, or run into bugs!
