### ISSUE TITLE
Add support for server side copy

### ISSUE THREAD

**Issue by pepijnve** [hierynomus/smbj#175]
Within a single SMB server it is possible to perform server-side copies. This avoids having to send data to the client and back which can greatly improve copy performance. At the SMB protocol level this is supported via ioctl requests.

First you need to request a resume key for the source file by sending the `FSCTL_SRV_REQUEST_RESUME_KEY` (0x00140078) ioctl with an empty data buffer. That should result in an ioctl response with an [`SRV_REQUEST_RESUME_KEY`](https://msdn.microsoft.com/en-us/library/cc246804.aspx) struct in the data buffer.

Using that resume key, then send either a `FSCTL_SRV_COPYCHUNK` (0x001440F2) or `FSCTL_SRV_COPYCHUNK_WRITE` (0x001480F2) ioctl request to the destination file with a [`SRV_COPYCHUNK_COPY`](https://msdn.microsoft.com/en-us/library/cc246547.aspx) struct in the databuffer. Use `FSCTL_SRV_COPYCHUNK` when the target file was opened with `FILE_READ_DATA` and `FILE_WRITE_DATA`; use `FSCTL_SRV_COPYCHUNK_WRITE` when it was opened with only `FILE_WRITE_DATA`.
The response to the `SRV_COPYCHUNK` requests contains a [`SRV_COPYCHUNK_RESPONSE `](https://msdn.microsoft.com/en-us/library/cc246549.aspx) which indicates how much of the write request was successfully executed.

**Comment by hierynomus** [comment]
Thanks @pepijnve for the detailed explanation. This should not be too hard to implement.

Do you know whether it is allowed to send the `FSCTL_SRC_COPYCHUNK_WRITE` when the file was opened with both read and write? It would simplify the implementation :)

**Comment by pepijnve** [comment]
No idea. I got that from [2.2.31 SMB2 IOCTL Request](https://msdn.microsoft.com/en-us/library/cc246545.aspx) where it says
> FSCTL_SRV_COPYCHUNK and FSCTL_SRV_COPYCHUNK_WRITE FSCTL codes are used for performing server side copy operations. These FSCTLs are issued by the application against an open handle to the target file. FSCTL_SRV_COPYCHUNK is issued when a handle has FILE_READ_DATA and FILE_WRITE_DATA access to the file; FSCTL_SRV_COPYCHUNK_WRITE is issued when a handle only has FILE_WRITE_DATA access.

**Comment by pepijnve** [comment]
Add some hyperlinks to the original description to make it easier to find the relevant bits in the spec.

**Comment by JozefDropco** [comment]
Hi,
Its not the cleanest code, but it works to copy on server side, also with the CHUNK size negotiation. Can you please integrate it? 
[copy.txt](https://github.com/hierynomus/smbj/files/1727884/copy.txt)

Kind regards,
Jozef

**Comment by pepijnve** [comment]
@JozefDropco could you make a pull request for this. The code needs some cleanup work, but it's hard to point out where the problems are without the code review tools that come with PRs.

**Comment by JozefDropco** [comment]
@pepijnve I sent pull request. I tried to make it more readable than the patch I have added here

**Comment by felipecaparelli** [comment]
@pepijnve do you have any news about this feature?

**Comment by pepijnve** [comment]
For reference, this is PR #294.

@felipecaparelli I'm only a contributor to the project; I don't have write access to merge PRs. Up to @hierynomus.

**Comment by hierynomus** [comment]
Implemented with #366. Thanks @pepijnve!
