### ISSUE TITLE
AccessMask

### ISSUE THREAD

**Issue by IrynaZhumatiy** [hierynomus/smbj#182]
Hello All,
Could you please provide me what each values from AccessMask mean?
(com.hierynomus.msdtyp.AccessMask)
Or let me know where can i read about this?

I want to use some value for transfer file via network share for some report. Maybe it should be more secure.
Thanks

Regards,
Iryna

**Comment by pepijnve** [comment]
In general, the package names `msdtyp` refer to the relevant specification; [[MS-DTYP]](https://msdn.microsoft.com/en-us/library/cc230273.aspx) in this case. You can find the access mask documentation in [section 2.4.3](https://msdn.microsoft.com/en-us/library/cc230294.aspx). That's typically mentioned in the [class-level javadoc](https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/msdtyp/AccessMask.java#L21).

**Comment by hierynomus** [comment]
@IrynaZhumatiy Does @pepijnve's answer answer your question?

**Comment by IrynaZhumatiy** [comment]
Yes. Thanks a lot for the answer, @pepijnve :)

**Comment by gidravlic** [comment]
@IrynaZhumatiy  close issue :)
