### ISSUE TITLE
Status_Access_Denied while accessing Samba Share on Linux

### ISSUE THREAD

**Issue by Varsha-Nagarajan** [hierynomus/smbj#184]
Scenario : Unable to access samba share mounted on a linux system (SUSE Linux Enterprise)
Samba server version : 3.6.3
I am using anonymous and guest authentication context but the connection to the share fails with:

com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Could not connect to \\ipaddress\shareName
	at com.hierynomus.smbj.session.Session.connectTree(Session.java:113)
	at com.hierynomus.smbj.session.Session.connectShare(Session.java:98)
	at TestIllegalArgument.main(TestIllegalArgument.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

The smbd log file says:

[2017/09/07 20:47:41.270463,  0] ../lib/util/util.c:415(dump_data)
  [0000] 61 EB 0C 0E A9 95 C4 E9   0F 17 AE 8D 46 7E F4 36   a....... ....F~.6
[2017/09/07 20:47:41.270587,  0] ../lib/util/util.c:415(dump_data)
  [0000] 69 43 23 A7 4B 21 28 80   F8 E4 C8 8F 89 83 A4 4A   iC#.K!(. .......J
[2017/09/07 20:47:53.799473,  0] smbd/smb2_signing.c:129(smb2_signing_check_pdu)
  Bad SMB2 signature for message

The SMB conf file looks like:

[content-repo]
        browseable = Yes
        path = path to share
        public = Yes
        writeable = Yes
        read only = Yes
        read list = nobody guest
        valid users = nobody guest
        create mask = 0664

Please tell me whether there is anything else that needs to be configured. I verified that the share permits SMBv2 connections. Both anonymous and guest authentication keeps failing. The folder being shared has all permissions and is being owned by "nobody".

I have tried adding guest account = nobody, guest ok = yes and force user = nobody. Still no luck.

**Comment by hierynomus** [comment]
Which version of smbj are you using?

Op 7 sep. 2017 6:43 p.m. schreef "Varsha-Nagarajan" <
notifications@github.com>:

**Comment by Varsha-Nagarajan** [comment]
smbj-0.3.0

**Comment by hierynomus** [comment]
It seems that Samba is compaining that the message signature is bad. Not so much the authentication.

**Comment by Varsha-Nagarajan** [comment]
But I changed the protocol to SMBv1 and tried accessing using jcifs. It
went through fine. Are you sure it's the samba server?

**Comment by Varsha-Nagarajan** [comment]
Attached are the wireshark traces of the two scenarios:
1. Accessing using windows explorer.
2. Accessing using code ( not working)

Please let me know if this is a bug or requires some additional configuration?

[wireshark_Traces.zip](https://github.com/hierynomus/smbj/files/1287409/wireshark_Traces.zip)

**Comment by Varsha-Nagarajan** [comment]
Some more logs:

[main] INFO com.hierynomus.smbj.connection.Connection - Successfully connected to: 10.71.67.180
[main] INFO com.hierynomus.smbj.connection.Connection - Successfully authenticated  on 10.71.67.180, session is 2227810112
[main] INFO com.hierynomus.smbj.session.Session - Connecting to \\10.71.67.180\content-repo on session 2227810112
[Packet Reader for 10.71.67.180] ERROR com.hierynomus.smbj.session.PacketSignatory - Signatures for packet SMB2_TREE_CONNECT with message id << 4 >> do not match (received: [-45, -36, -95, -79, 70, 119, 47, 48, 9, -34, 67, 105, -105, 122, 74, 84], calculated: [57, -29, 85, -128, -104, -62, 75, 33, 22, -96, 54, -121, -51, 49, 59, -44, 117, -10, -19, 64, 100, -63, 45, -7, -115, -36, 111, 17, 41, -54, -117, 88])
[Packet Reader for 10.71.67.180] WARN com.hierynomus.smbj.connection.Connection - Invalid packet signature for packet SMB2_TREE_CONNECT with message id << 4 >>
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Could not connect to \\10.71.67.180\content-repo
	at com.hierynomus.smbj.session.Session.connectTree(Session.java:113)
	at com.hierynomus.smbj.session.Session.connectShare(Session.java:98)
	at TestProgram.main(TestProgram.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by bli-r7** [comment]
I've seen the same signature failure when accessing samba on smbv2. Since the session authentication was complete I don't think it was the signature themselves that caused the issue.

**Comment by hierynomus** [comment]
We only start signing after the session has been established. So it is
pretty likely the issue.

Op 8 sep. 2017 7:51 p.m. schreef "bli-r7" <notifications@github.com>:

**Comment by bli-r7** [comment]
There was a similar issue before due to how message length wasn't calculated correctly and how certain message wasn't read properly. I would debug this in PacketSignatory to confirm.

**Comment by bli-r7** [comment]
Also double check **server signing** and **client signing** in Samba config.

https://www.samba.org/samba/docs/man/manpages-3/smb.conf.5.html

**Comment by Varsha-Nagarajan** [comment]
None of the server and client signing combinations seem to solve the issue. I get the same logs as mentioned above.

**Comment by Varsha-Nagarajan** [comment]
Hi,

Any update on this? I have exhausted all my ideas :(

**Comment by gidravlic** [comment]
Hi! @Varsha-Nagarajan, as i correct understand SmbPath class return \\host\share. But in you error message contains \10.71.67.180\content-repo. Maybe this is the problem?

**Comment by Varsha-Nagarajan** [comment]
Hi @gidravlic , nope, thats not the issue. Connection goes through fine. There is some signature issue which is highlighted in the logs above. Waiting for @hierynomus  and @bli-r7  to identify the issue.

**Comment by tosmun-r7** [comment]
I've hit this as well. Creating a guest session, and attempting to connect to `IPC$` will result in the expected `ACCESS_DENIED` response, but the signature validation will fail client side. I haven't discovered any obvious deviations between the implementation and spec.

**Comment by hierynomus** [comment]
Does it work with an authenticated (real user) connection @tosmun-r7 @Varsha-Nagarajan ? Else the error might be in authentication part when you auth as guest/anonymous user... Could be that the flow for those authentications should be different.

**Comment by tosmun-r7** [comment]
Yes, it does work for an authenticated connection. I believe you're right, there must be some deviation, perhaps in calculation of the secretKey.

**Comment by hierynomus** [comment]
Yes, that is my guess also. I did not see this in my testing on a windows machine with a guest user, but it might be that I had not set signatures to be required.

**Comment by tosmun-r7** [comment]
In MS-SMB2, I noticed the following:

> If the SMB2_SESSION_FLAG_IS_GUEST bit is set in the SessionFlags field of the SMB2 SESSION_SETUP Response and if Session.SigningRequired is TRUE, this indicates a SESSION_SETUP failure and the connection MUST be terminated. If the SMB2_SESSION_FLAG_IS_GUEST bit is set in the SessionFlags field of the SMB2 SESSION_SETUP Response and if RequireMessageSigning is FALSE, Session.SigningRequired MUST be set to FALSE.

And also here: https://blogs.msdn.microsoft.com/openspecification/2017/05/26/smb-2-and-smb-3-security-in-windows-10-the-anatomy-of-signing-and-cryptographic-keys/
> To sign a message, the first two prerequisites are:
• Existence of the signing key: SessionId field has a non-zero value, otherwise there would be no possible signing key. **The exception is a guest or anonymous session, which does not have a signing key even there’s a SessionId.**
• Signing requirement: SessionId requires signing, i.e. its Session.SigningRequired is equal to TRUE as outlined previously.

**Comment by tosmun-r7** [comment]
Sounds like we should not be enforcing signing if the session ends up being a guest or anonymous login?

**Comment by hierynomus** [comment]
@Varsha-Nagarajan does the discussion solve the issue? I'm slightly inclined to closing it and making a fix for #184 to detect this situation.

**Comment by Varsha-Nagarajan** [comment]
Hi,

No, this discussion hasn't solved the issue because anonymous or guest
authentication is still failing for samba server running on Linux system.

I'm actually looking forward for a fix as it's an important usecase in the
product I'm working for. Please could you look into it?
