### ISSUE TITLE
Question/request: is it possible to watch share changes?

### ISSUE THREAD

**Issue by ndimitry** [hierynomus/smbj#188]
Our project wants to be able to watch for changes on the share, for example to find out when a new document is created or when an old one is renamed.
Is that somehow possible using smbj?

**Comment by pepijnve** [comment]
The SMB2 protocol supports this via the CHANGE_NOTIFY message, but this isn't supported in smbj yet.

**Comment by ndimitry** [comment]
Is there a plan to support this operation in future?
Or, if it's not in the short list, can we ourselves contribute to the project?

**Comment by pepijnve** [comment]
I can't speak for @hierynomus, but I'm pretty sure a PR that adds this would be appreciated. The [java.nio.file.WatchService](https://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchService.html) and related classes might be a good source of inspiration for an API for this feature.

**Comment by hierynomus** [comment]
Sure, such a PR would be welcome :)

2017-09-11 19:08 GMT+02:00 Pepijn Van Eeckhoudt <notifications@github.com>:

**Comment by ndimitry** [comment]
I've talked with our architect, he sees this as an option to move from jsifc-ng to some other lib, among which smbj looks as a good alternative. We plan to do this after some period of time (after couple of weeks maybe).
I will keep in touch with you, I think there will be some questions.

Thanks for being open and fast to react!

**Comment by ndimitry** [comment]
I found it possible to send the CHANGE_NOTIFY request (and get changes), so currently it seems smbj has all our project needs (@pepijnve thank you for a hint on CHANGE_NOTIFY message, keeping in mind I know few in SMB and the MS-SMB2 documentation has more than 400 pages this hint was vital).

Maybe I will have time to create a PR and implement it, but unfortunately seems like not now, sorry.

**Comment by saranya1988** [comment]
Hi,
Do we have Watch service implemented in smbj?

**Comment by hierynomus** [comment]
You can use the SMB2_CHANGE_NOTIFY by calling the `Directory.watchAsync(...)` method. This will return a future for a response. After the response you should again call `watchAsync`.

**Comment by lawern** [comment]
> You can use the SMB2_CHANGE_NOTIFY by calling the `Directory.watchAsync(...)` method. This will return a future for a response. After the response you should again call `watchAsync`.

Thanks, this works great!
Is there a way to recognise with a FileNotifyInformation {action=FILE_ACTION_REMOVED, ...} if a file or a directory has been removed or is this only possible with two registrations with different SMB2CompletionFilters?

**Comment by cliviu** [comment]
> You can use the SMB2_CHANGE_NOTIFY by calling the `Directory.watchAsync(...)` method. This will return a future for a response. After the response you should again call `watchAsync`.

Hi. I have the problem that when I copy multiple files in the watched directory I am notified only about one file. How can I improve this? Even if I immediately call 'watchAsync' I am not informed about the other files ...
