### ISSUE TITLE
VM hangs with no console and network access

### ISSUE THREAD

**Issue by srik545** [hierynomus/smbj#192]
In a multi-threaded environment when multiple requests are sent to a single CIFS server suddenly I see that, CPU shoots up to 100% on a single core ( 50% on a 2 core machine). What is making me surprise is **No network access and console access** - this is making  it harder to trace where is the issue. Any help in this regard is really great full. I am using v0.3.0. And it is sometimes consistently reproducible and sometimes its harder to reproduce.

Thanks in Advance,
Srikanth

**Comment by pepijnve** [comment]
A stack dump of all threads should show where things are stuck. You can get that using `stack` or by sending a SIGQUIT (3) to the Java process.

**Comment by mtamassia** [comment]
@srik545 depending on your JDK/JRE version and OS, you can also run
 `jcmd PID Thread.print >> dump.txt`
 replacing PID with the java process ID and send us the content of the dump.txt

**Comment by hierynomus** [comment]
@srik545 Any update?

**Comment by srik545** [comment]
Sorry Guys, I was on vacation.  Here is the information i collected so far. I have a process running in the background and taking jstack every 30 seconds to catalina.log. This process was taking all the thread dump but when the issues occurs, from then on no update to catalina.log. 
Information about my setup:  My VM is a linux VM running on ESXi v6.5.0 and deployed on tomcat.

Thanks,
Srikanth

**Comment by hierynomus** [comment]
@srik545 Why do you think it's in SMBJ? Are you closing all your connections etc correctly?

**Comment by hierynomus** [comment]
Also there is no data attached to your comment, so there is no way for us to confirm it's SMBJ related.

FWIW We've run SMBJ in production for quite some time but have not heard anything similar yet.

**Comment by srik545** [comment]
Thanks guys for the inputs. After taking memory dump in hang state, I found that I am hitting https://bugzilla.kernel.org/show_bug.cgi?id=191201 issue. My instances are running on ESXi 6.5 version. We are planning to upgrade the ESXi version.
