### ISSUE TITLE
[Question] Can we cut a new release?

### ISSUE THREAD

**Issue by bli-r7** [hierynomus/smbj#194]
@hierynomus 

Can we cut a new release with the connection and session information that went in with the last commits?

Thank you.

**Comment by hierynomus** [comment]
Let's wait if #195 is a bug (I don't think so) and #196 is merged via #199

**Comment by ndimitry** [comment]
Hope #198 will also be there (:

**Comment by mtamassia** [comment]
@hierynomus it looks like the issues you intended to be fixed have made to master so it would be great if we could cut a new release.

**Comment by hierynomus** [comment]
@mtamassia Yes, I was looking at that too. Though it would be a shame if we missed #206 / #207, which would make a nice feature for the new release. So I want to wait on that.

**Comment by Varsha-Nagarajan** [comment]
@hierynomus  Any tentative date on when this is being planned?

**Comment by hierynomus** [comment]
Yes, hopefully today.

**Comment by mtamassia** [comment]
We know you are busy @hierynomus . Any updates?

**Comment by hierynomus** [comment]
https://github.com/hierynomus/smbj/releases/tag/v0.4.0

**Comment by hierynomus** [comment]
Waiting for the sync to central...

**Comment by hierynomus** [comment]
And it's already here: https://bintray.com/hierynomus/maven/smbj

**Comment by ndimitry** [comment]
Really, thanks for your effort on creation of this lib and on enhancements! That's valuable!
