### ISSUE TITLE
File write Not working for file type pdf

### ISSUE THREAD

**Issue by debarghya85** [hierynomus/smbj#195]
I am trying to get the OutputStream from a file pointer of type com.hierynomus.smbj.share.File. I will put the byte array into the OutputStream and write. But If I write in .txt file then it is writting into the file but not writting for .pdf file.

For getting OutputStream I have used  getOutputStream() of com.hierynomus.smbj.share.File.

fileOutputStream.write("ASDF".getBytes());
fileOutputStream.flush();
fileOutputStream.close();

**Comment by hierynomus** [comment]
Do you have some example code and trace level logging to help debug this?

**Comment by debarghya85** [comment]
Following is my code snippet.Whenever I am sending any pdf file name, then no error is generating and file is generating in shared folder but with no content and file size 0 byte.But If I just change the name of the file to txt then file is generating with proper content.

                SmbConfig cfg = SmbConfig.builder().build();
		SMBClient client = new SMBClient(cfg);
		Connection connection = client.connect(ex);
		Session session = connection.authenticate(new AuthenticationContext(username, password.toCharArray(), domain));
		DiskShare share = (DiskShare)session.connectShare(sambaSharedPath);
        
        File f = null;
        int idx = filePath.lastIndexOf("/");
        String folder = "";
        String onlyFileName = filePath.substring(idx + 1, filePath.length());
        if(idx > -1) {
            folder = filePath.substring(0, idx);
        }

        boolean isFileAlreadyExist = false;

        try {
            f = share.openFile(folder + java.io.File.separator + onlyFileName, new HashSet(Arrays.asList(new AccessMask[]{AccessMask.GENERIC_ALL})), (Set)null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_CREATE, (Set)null);
        } catch (SMBApiException var12) {
            isFileAlreadyExist = true;
        }

        if(isFileAlreadyExist) {
            try {
                f = share.openFile(folder + java.io.File.separator + onlyFileName, new HashSet(Arrays.asList(new AccessMask[]{AccessMask.GENERIC_ALL})), (Set)null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OVERWRITE, (Set)null);
            } catch (SMBApiException var11) {
                throw new Exception("Could not open file for write.");
            }
        }

        OutputStream outputStream = null;
        if(f != null) {
            outputStream = f.getOutputStream();
           outputStream .write(str.getBytes());
        outputStream .flush();
        outputStream .close();
        }

**Comment by hierynomus** [comment]
Hi @debarghya85,

This does not seem to be a SMBJ issue then, if only changing the filename leads to correct contents being written. I would then focus on your target machine and see whether that is running a virusscanner or something that blocks uploads of pdf files.

**Comment by debarghya85** [comment]
This is my traces. I am also not sure whether it is SMBJ issue because I am thinking how to set the MIME type in outputstream without response.Probably that will sought out the issue.

[main] INFO com.hierynomus.protocol.commons.socket.ProxySocketFactory - Connecting to /[Share_IP]:445
[main] INFO com.hierynomus.smbj.transport.PacketReader - Starting PacketReader on thread: Packet Reader for [Share_IP]
[main] INFO com.hierynomus.smbj.connection.Connection - Negotiating dialects [SMB_2_0_2, SMB_2_1] with server [Share_IP]
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 0 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_NEGOTIATE with message id << 0 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_NEGOTIATE with message id << 0 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 1 credits for SMB2_NEGOTIATE with message id << 0 >>, now available: 1 credits
[main] INFO com.hierynomus.smbj.connection.Connection - Negotiated the following connection settings: ConnectionInfo{
  serverGuid=ea6aa752-6200-47a8-aaa1-d4381e6bfc98,
  serverName='[Share_IP]',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_2_1, maxTransactSize=8388608, maxReadSize=8388608, maxWriteSize=8388608},
  clientGuid=5c993396-b6ab-4bf5-bb2c-4dde6a6ad8e4,
  clientCapabilities=null,
  serverCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LEASING, SMB2_GLOBAL_CAP_LARGE_MTU],
  clientSecurityMode=0,
  serverSecurityMode=1,
  server='null'
}
[main] INFO com.hierynomus.smbj.connection.Connection - Successfully connected to: [Share_IP]
[main] INFO com.hierynomus.smbj.auth.NtlmAuthenticator - Initialized Authentication of User using NTLM
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 1 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_SESSION_SETUP with message id << 1 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_SESSION_SETUP with message id << 1 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 1 credits for SMB2_SESSION_SETUP with message id << 1 >>, now available: 1 credits
[main] INFO com.hierynomus.smbj.connection.Connection - More processing required for authentication of User using com.hierynomus.smbj.auth.NtlmAuthenticator@5d40f8c3
[main] INFO com.hierynomus.smbj.auth.NtlmAuthenticator - Received token: a1 81 e2 30 81 df a0 03 0a 01 01 a1 0c 06 0a 2b 06 01 04 01 82 37 02 02 0a a2 81 c9 04 81 c6 4e 54 4c 4d 53 53 50 00 02 00 00 00 16 00 16 00 38 00 00 00 15 82 8a e2 d6 46 9e 11 b7 71 1a 71 00 00 00 00 00 00 00 00 78 00 78 00 4e 00 00 00 06 03 80 25 00 00 00 0f 57 00 49 00 4e 00 2d 00 44 00 45 00 56 00 2d 00 4c 00 41 00 42 00 02 00 16 00 57 00 49 00 4e 00 2d 00 44 00 45 00 56 00 2d 00 4c 00 41 00 42 00 01 00 16 00 57 00 49 00 4e 00 2d 00 44 00 45 00 56 00 2d 00 4c 00 41 00 42 00 04 00 16 00 57 00 49 00 4e 00 2d 00 44 00 65 00 76 00 2d 00 6c 00 61 00 62 00 03 00 16 00 57 00 49 00 4e 00 2d 00 44 00 65 00 76 00 2d 00 6c 00 61 00 62 00 07 00 08 00 3f f5 4f 63 a6 36 d3 01 00 00 00 00
[main] INFO com.hierynomus.ntlm.messages.NtlmChallenge - Windows version = WindowsVersion[WINDOWS_MAJOR_VERSION_6, WINDOWS_MINOR_VERSION_3, 9600, NTLMSSP_REVISION_W2K3]
[main] INFO com.hierynomus.smbj.auth.NtlmAuthenticator - Received NTLM challenge from: WIN-DEV-LAB
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 2 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_SESSION_SETUP with message id << 2 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_SESSION_SETUP with message id << 2 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_SESSION_SETUP with message id << 2 >>, now available: 33 credits
[main] INFO com.hierynomus.smbj.connection.Connection - Successfully authenticated User on [Share_IP], session is 61587347996757
[main] INFO com.hierynomus.smbj.session.Session - Connecting to \\[Share_IP]\myFolder on session 61587347996757
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 33) credits to SMB2_TREE_CONNECT with message id << 3 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_TREE_CONNECT with message id << 3 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_TREE_CONNECT with message id << 3 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_TREE_CONNECT with message id << 3 >>, now available: 65 credits
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 65) credits to SMB2_CREATE with message id << 4 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_CREATE with message id << 4 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_CREATE with message id << 4 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_CREATE with message id << 4 >>, now available: 97 credits
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 97) credits to SMB2_CLOSE with message id << 5 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_CLOSE with message id << 5 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_CLOSE with message id << 5 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_CLOSE with message id << 5 >>, now available: 129 credits
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 129) credits to SMB2_CREATE with message id << 6 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_CREATE with message id << 6 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_CREATE with message id << 6 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_CREATE with message id << 6 >>, now available: 161 credits
not[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 161) credits to SMB2_CREATE with message id << 7 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_CREATE with message id << 7 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_CREATE with message id << 7 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_CREATE with message id << 7 >>, now available: 193 credits
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 193) credits to SMB2_CREATE with message id << 8 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_CREATE with message id << 8 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_CREATE with message id << 8 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_CREATE with message id << 8 >>, now available: 225 credits
[main] INFO com.hierynomus.smbj.share.File - Writing to ddw\bbw\xeyez433.pdf from offset 0
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 225) credits to SMB2_WRITE with message id << 9 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_WRITE with message id << 9 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_WRITE with message id << 9 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_WRITE with message id << 9 >>, now available: 257 credits
[main] INFO com.hierynomus.smbj.share.FileOutputStream - EOF, 20 bytes written
[main] INFO com.hierynomus.smbj.connection.Connection - Granted 1 (out of 257) credits to SMB2_CLOSE with message id << 10 >>
[main] INFO com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport - Writing packet SMB2_CLOSE with message id << 10 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.transport.PacketReader - Received packet SMB2_CLOSE with message id << 10 >>
[Packet Reader for [Share_IP]] INFO com.hierynomus.smbj.connection.Connection - Server granted us 33 credits for SMB2_CLOSE with message id << 10 >>, now available: 289 credits

**Comment by hierynomus** [comment]
I'm not sure what you mean, but the SMB protocol has no knowledge of MIME types. It just copies the bytes over the line using the right protocol. As such it does not care about the extension of a file. So in this case I would really investigate the remote system to see what it is doing.
The traces sent by you do not show an error on the SMB side of things.

**Comment by hierynomus** [comment]
@debarghya85 Any update on this? I'm inclined to dismissing this, as it is not an SMBJ bug, at least not if only changing the filename suddenly makes the bytes not appear for exactly the same program.

**Comment by debarghya85** [comment]
Till now no update...till now not solved...can give you update on 2nd oct.

On 28-Sep-2017 5:37 PM, "Jeroen van Erp" <notifications@github.com> wrote:

@debarghya85 <https://github.com/debarghya85> Any update on this? I'm
inclined to dismissing this, as it is not an SMBJ bug, at least not if only
changing the filename suddenly makes the bytes not appear for exactly the
same program.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hierynomus/smbj/issues/195#issuecomment-332816269>, or mute
the thread

**Comment by hierynomus** [comment]
@debarghya85 Let me know if you have an update. Also a tcpdump could help if you really think this is in the library.

**Comment by debarghya85** [comment]
Its working now.
Some mistake in my coding makes the issue. Sorry for inconvenience caused. Some object referance issue occurred. I have rectified in my coding and its working fine.

**Comment by hierynomus** [comment]
Great that you found it. Good luck with your project.
