### ISSUE TITLE
SMBApiException: STATUS_OBJECT_PATH_NOT_FOUND

### ISSUE THREAD

**Issue by IrynaZhumatiy** [hierynomus/smbj#197]
Hello All,

Could you please help me with some issue?
I'm trying to put a file to a directory that does not exist. Is there a way that java could test for the destination directory?
I get SMBApiException: STATUS_OBJECT_PATH_NOT_FOUND.

Thanks a lot!

Best regards,
Iryna

**Comment by gidravlic** [comment]
Hi! 
Look class [DiskShare](https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/share/DiskShare.java) method folderExists

**Comment by ndimitry** [comment]
Something like this should work (this checks that folder \\host\ShareName\test1\test2 exists):

```
    private static void smbjFolderExists() throws Exception {
        SMBClient client = new SMBClient();

        try (Connection connection = client.connect("host")) {
            AuthenticationContext ac = new AuthenticationContext("user", "password".toCharArray(), "userDomain");
            Session session = connection.authenticate(ac);

            // Connect to Share
            try (DiskShare share = (DiskShare) session.connectShare("ShareName")) {
                System.out.println(share.folderExists("test1\\test2"));
            }
        }
    }
```

**Comment by IrynaZhumatiy** [comment]
Thanks a lot to everyone!
I've found this method :)

**Comment by hierynomus** [comment]
Ok, can this be closed?

**Comment by IrynaZhumatiy** [comment]
Yes, thanks!

**Comment by rathnaum** [comment]
How do I create folders if it does not exist? I am getting this error, STATUS_OBJECT_PATH_NOT_FOUND

**Comment by ndimitry** [comment]
Try this with combination of the comment above
``
            try (DiskShare share = (DiskShare) session.connectShare("Share2")) {
                    share.openDirectory("testFolder",
                            EnumSet.of(AccessMask.FILE_WRITE_DATA),
                            null, // attributes, null works fine (don't know their purpose)
                            SMB2ShareAccess.ALL,
                            SMB2CreateDisposition.FILE_CREATE,
                            null); // create options, null works fine (don't know their purpose)
            }
``
SMB protocol has a lot of stuff in it, I know the very shallow stuff. This code at least worked for me.
In this case SMB2CreateDisposition.FILE_CREATE tells the server to create the folder (it is possible to open, overwrite, overwrite if not present). It is possible also to set SMB2CreateDisposition.FILE_OPEN_IF
