### ISSUE TITLE
Signature verification for CHANGE_NOTIFY fails

### ISSUE THREAD

**Issue by ndimitry** [hierynomus/smbj#198]
All other tested requests seem to work fine (open, close, list, delete, read and write).
As for the watch it returns correct contents but produces warnings which state that signature verification fails. Here's a warning example that I get:
ERROR | Signatures for packet SMB2_CHANGE_NOTIFY with message id << 504251 >> do not match (received: [-44, 12, -16, -51, 46, -47, -124, -120, -67, -72, 92, 44, 31, -120, 71, -61], calculated: [-29, -122, -92, 11, -109, 50, -11, 104, 45, -118, 126, -20, -48, -119, -100, 109, -30, -85, 77, 44, 41, 114, -103, -22, -114, -91, 18, -76, -124, -5, 37, -33])

Connection#verifyPacketSignature fails since a calculated and returned signatures are different. Either I do something wrong, either there is some kind of a defect there.

Here is a peace of code that faces this issue.

```
    void smbjWatch() throws Exception {
        SMBClient client = new SMBClient();

        try (Connection connection = client.connect("host")) {
            AuthenticationContext ac = new AuthenticationContext("user", "password".toCharArray(), "");
            Session session = connection.authenticate(ac);

            // Connect to Share
            try (DiskShare share = (DiskShare) session.connectShare("share")) {
                Set<AccessMask> accessMasks = new HashSet<>();
                accessMasks.add(AccessMask.FILE_LIST_DIRECTORY);
                // Open the root share folder
                try (Directory directory = share.openDirectory("", accessMasks, null,
                        SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null)) {
                    // Track all changes until program is terminated
                    while (true) {
                        Set<SMB2CompletionFilter> completionFilter = new HashSet<>();
                        completionFilter.add(SMB2CompletionFilter.FILE_NOTIFY_CHANGE_FILE_NAME);
                        SMB2ChangeNotifyRequest request = new SMB2ChangeNotifyRequest(
                                session.getConnection().getNegotiatedProtocol().getDialect(),
                                session.getSessionId(),
                                share.getTreeConnect().getTreeId(),
                                directory.getFileId(),
                                completionFilter,
                                65536,
                                true);

                        Future<SMB2ChangeNotifyResponse> future = session.send(request);
                        SMB2ChangeNotifyResponse response = future.get();
                        // just some output to make life easier
                        for (SMB2ChangeNotifyResponse.FileNotifyInfo notifyInfo : response.getFileNotifyInfoList()) {
                            System.out.println(notifyInfo);
                        }
                        System.out.println();
                    }
                }
            }
        }
    }
```

**Comment by hierynomus** [comment]
@ndimitry Can you check what the status is of the SMB2_CHANGE_NOTIFY response?
Most of the signature verifications fail when the status is not success. Fo rthat one there is an exception for teh ENUM_DIR status, but that is purely from the docs, I think that actually contains different contents than is expected

**Comment by ndimitry** [comment]
Actually the status is success (packet.header.status which I examined with help of the debugger)
![image](https://user-images.githubusercontent.com/18209884/30974211-c1d570b6-a477-11e7-9a9e-5bf7562c9c1b.png)

**Comment by ndimitry** [comment]
@hierynomus If there might give a clue, the evident difference between all other requests and this one was that Buffer's rpos value is not equal to wpos and size. For all other these values are the same (but I guess they might be not equal and this is not the root of an issue).

**Comment by ndimitry** [comment]
@hierynomus Ok, this is most likely an smbj issue.
I've just "hacked" rpos and packet.messageEndPossition and after this the signature became fine. Here it is:
![image](https://user-images.githubusercontent.com/18209884/30977792-57f73af8-a481-11e7-85ed-7328419c19f7.png)

So the question is why the packet's messageEndPossition is set to the value less then the whole packet.

**Comment by ndimitry** [comment]
@hierynomus Here's the defect.
In SMB2ChangeNotifyResponse#readFileNotifyInfo we have:
```
        do {
            nextEntryOffset = (int) buffer.readUInt32();
            FileNotifyAction action = EnumWithValue.EnumUtils.valueOf(buffer.readUInt32(), FileNotifyAction.class, null);
            fileNameLen = buffer.readUInt32();
            fileName = buffer.readString(StandardCharsets.UTF_16LE, (int) fileNameLen / 2);
            notifyInfoList.add(new FileNotifyInfo(action, fileName));
            currentPos += nextEntryOffset;
            buffer.rpos(currentPos);
        } while (nextEntryOffset != 0);
```
In case there are 2 or more FileNotifyActions the last one will contain the `nextEntryOffset` set to 0.
This will result in currentPos being set close to the beginning of the last FileNotifyAction which is not the end of the message.

There should be something like
```
if (nextEntryOffset != 0) {
    currentPos += nextEntryOffset;
    buffer.rpos(currentPos);
} else {
    buffer.rpos(currentPos + 4 + fileNameLen); // where 4 stands for 32 bits which contain the filename
}
```

**Comment by ndimitry** [comment]
Now let me play with GIT and pull requests (:

**Comment by hierynomus** [comment]
Good find! And thanks for the PR ;)

**Comment by ndimitry** [comment]
You are welcome! And I was lucky though, but as I like to say thanks God I was (:

Can I create a pull request out of an issue only if I'm an approved contributor? (For example, I haven't found the way to create a pull request out of this issue.) Or is an issue a separate thing from the pull request here on github?

**Comment by hierynomus** [comment]
Yes, issues and PRs are separate :) So the way you did it is the right way.

**Comment by ndimitry** [comment]
Great! Thanks for clarification and I'm glad all worked well (:
