### ISSUE TITLE
Add support for retrieving via DiskShare the file system information

### ISSUE THREAD

**Issue by niggemannmj** [hierynomus/smbj#20]
While the underlying protocol support libraries seem to support getting the FileFsSizeInformation via SMB2QueryInfoRequest, it would be more useful if this were exposed as a simpler method call in DiskShare, similar to the getFileInformation() method, but for the share file system instead. Perhaps call it getFileSystemInformation()

**Comment by hierynomus** [comment]
Agreed, the APIs are still in flux and I am cleaning them up.

**Comment by niggemannmj** [comment]
This was fixed in commit  53970ed.
