### ISSUE TITLE
Close failed for SMB2FileId{persistentHandle

### ISSUE THREAD

**Issue by IrynaZhumatiy** [hierynomus/smbj#204]
Hello All,

When I'm trying to close com.hierynomus.smbj.share.File, I get the exception:
STATUS_FILE_CLOSED(3221225768/3221225768): Close failed for SMB2FileId{persistentHandle=71 14 00 00 42 00 00 00}
Could you please take a look for this issue?
Thanks!

Best regards,
Iryna

**Comment by hierynomus** [comment]
Hi @IrynaZhumatiy,
This is due to the file already being closed. I'll add a case for that to treat it as a success (ie. make close an idempotent operation for this case).

Thx!

**Comment by hierynomus** [comment]
Closed via a948028

**Comment by IrynaZhumatiy** [comment]
Thanks!
