### ISSUE TITLE
STATUS_STOPPED_ON_SYMLINK : link is not followed

### ISSUE THREAD

**Issue by zerikv** [hierynomus/smbj#206]
When we open a file on a share the SMB2 Create command returns an error if the file is a link (in my test case the link has been created with the mklink command).
This behaviour is explained in "2.2.2.2.1 Symbolic Link Error Response" https://msdn.microsoft.com/en-us/library/cc246542.aspx

SMBJ handles this kind of response (by building a `SymbolicLinkError`) but it seems that the data extracted from the Symbolic Link Error Response are lost after the `Share#receive`.
This method throws a `SMBApiException`, the error in the `SMB2Packet` is lost, then the caller has no way to follow the link.

I think it would be nice if SMBJ could follow the link automatically by default, 
with the possibility if needed to disable the automatic following and to get a special exception with the data of the SymbolicLinkError and convenient methods to get the full path of the target.

What do you think about ?

**Comment by hierynomus** [comment]
Hi Erik,

Makes sense, let me work on it, shouldn't be too hard. Thanks for the suggestion.

**Comment by pepijnve** [comment]
Just FYI, the win32 api (CreateFile) also follows symlinks transparently. In order to open the symlink itself you need to use the ‘open reparse point’ open flag. Perhaps it’s sufficient to mimic this behaviour.
The same logic applies to junctions, DFS referrals, etc. Basically anything that’s implemented using reparse points.

**Comment by zerikv** [comment]
Hi Pepijn,

Thank you for pointing the flag FILE_OPEN_REPARSE_POINT.

I have just tryied it by adding the following at the begining of the method `com.hierynomus.smbj.share.Share#createFile` :
```java
    SMB2CreateResponse createFile(String path, SMB2ImpersonationLevel impersonationLevel, Set<AccessMask> accessMask, Set<FileAttributes> fileAttributes, Set<SMB2ShareAccess> shareAccess, SMB2CreateDisposition createDisposition, Set<SMB2CreateOptions> createOptions) {
        EnumSet<SMB2CreateOptions> actualCreateOptions = createOptions != null ? EnumSet.copyOf(createOptions) : EnumSet.noneOf(SMB2CreateOptions.class);
        actualCreateOptions.add(SMB2CreateOptions.FILE_OPEN_REPARSE_POINT);
        ...
```

For the test I use a symbolic link ceated as follow:
```
C:\Program Files\Java>mklink /d jre1.8.0 jre1.8.0_131
Symbolic link created for jre1.8.0 <<===>> jre1.8.0_131
```

When I call `DiskShare.open` with the path of this link "Program Files\Java\jre1.8.0" and the create option FILE_OPEN_REPARSE_POINT set, the link is successfully opened (no more error STATUS_STOPPED_ON_SYMLINK).

But if I try with a path under the link (for example with "Program Files\Java\jre1.8.0\java\bin") the error STATUS_STOPPED_ON_SYMLINK is back:
```
com.hierynomus.mssmb2.SMBApiException: STATUS_STOPPED_ON_SYMLINK(2147483693/2147483693): Create failed for Program Files\Java\jre1.8.0\bin\java
	at com.hierynomus.smbj.share.Share.receive(Share.java:341)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:321)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:136)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
    ...
```

Apparently we need to implement the Handling of the Symbolic Link Error Response like describe in 2.2.2.2.1.1 https://msdn.microsoft.com/en-us/library/dd358040.aspx

**Comment by pepijnve** [comment]
`FILE_OPEN_REPARSE_POINT` opens the symlink object itself, it doesn't follow the symlink. This is useful if you want to read or write the symlink target rather than following it. If this is what you want that's fine, but that's not the impression I got from your explanation.

**Comment by pepijnve** [comment]
@zerikv PR #207 is a first attempt at implementing symlink resolution. You could give that a try already.

**Comment by zerikv** [comment]
Thank you Pepijn for your effort on this issue !
I'm going to try with your PR.

In the same time I have worked on it on my side,
You can see it: https://github.com/zerikv/smbj/commit/c31c64257f8e43db74d1ac84ad7e3ceffd9201cc
This implementation is partial, the following cannot be disable, and this doesn't work if the target is absolute on another disk. Also I have used java.nio.file.Paths to normalize the relative path, it's probably a bad idea because implementation is OS dependend.

**Comment by pepijnve** [comment]
We're essentially doing the same thing. 😄 
It's preferable to use the 'status values to consider as success' over an exception for this since it's a common case. Using exceptions for flow control is not ideal. Something very similar is already done for DFS referrals. See https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/share/DFSDiskShare.java#L75

**Comment by pepijnve** [comment]
> Also I have used java.nio.file.Paths to normalize the relative path, it's probably a bad idea because implementation is OS dependend.

Indeed it is. You don't want to use platform dependent code in smbj.

**Comment by zerikv** [comment]
I have just tried the PR#207

The case when the symbolic link targets a relative path works fine.

But if the target path is absolute, the subsituteName is not usable :
```
com.hierynomus.mssmb2.SMBApiException: STATUS_INVALID_PARAMETER(3221225485/3221225485): Create failed for \??\C:\Program Files\Java\jdk1.6.0_45
	at com.hierynomus.smbj.share.Share.receive(Share.java:380)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:360)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:137)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:145)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	...
```
The absolute path is prefixed by \??\C:\ which  should be removed.
 
btw there is a main() method at the end of SMB2Functions, it seems not intented.

**Comment by pepijnve** [comment]
See the example at https://msdn.microsoft.com/en-us/library/dd358040.aspx That's how it's supposed to work. It's kind of expected that you're going to see issues with absolute symlinks over SMB.

That main function is a mistake indeed, I'll get rid of it.

**Comment by hierynomus** [comment]
Merged #207.

**Comment by pepijnve** [comment]
@hierynomus do you think the symlink resolution logic is sufficiently robust? I tested it with some unit tests and using one of my local SMB servers. Seemed to work correctly, but I definitely didn't do rigorous testing.

**Comment by hierynomus** [comment]
In this case it's better at least than what we had (no support), and it seems to follow most of the common paths. That's why I merged it.
