### ISSUE TITLE
Implement a basic extensible server as reference

### ISSUE THREAD

**Issue by bhagyas** [hierynomus/smbj#209]
Should serve from the local filesystem for a start.

**Comment by hierynomus** [comment]
Can you elaborate?

**Comment by pepijnve** [comment]
Seems out of scope for an SMB client library project. What value would this add?

**Comment by bhagyas** [comment]
I'm looking at org.alfresco.jlan.smb.server.SMBServer class. 

This would make it easier to build SMB supported file servers using smbj.

**Comment by pepijnve** [comment]
> This would make it easier to build SMB supported file servers using smbj.

I agree that adding a server implementation would make the task of making a server easier. But I still think it's out of scope for a project that aims to provide an SMB client implementation. Maybe @hierynomus wants to tackle this, but I would expect client features and bugfixes to all be much higher on the priority list than implementing a server.

**Comment by hierynomus** [comment]
For the coming time this will be very low in the backlog. As @pepijnve already said, there are more features to add and bugs to squash ;).
I can foresee thst a server is useful in the long run, but don't expect one to be added any time soon.

**Comment by bhagyas** [comment]
Thanks, as long as it's in the backlog I'm sure someone would contribute their server code. I had started one based on the BasicPacketProcessor example, but at the moment not having enough time to spend more on it. 

This would be really important since there is no open source Java server library for SMBv2+.

**Comment by hierynomus** [comment]
This is 5 years old, and no-one has yet taken an interest in this... Closing this for now, who knows in the future....
