### ISSUE TITLE
STATUS_BAD_NETWORK_NAME(): Could not connect to <path>

### ISSUE THREAD

**Issue by brielga** [hierynomus/smbj#213]
I'm facing this error at me moment and I'm stuck because I do not have much knowledge of SMB protocol.

I'm using somethink like:
client.connect("<servername>")

DiskShare share = (DiskShare) session.connectShare("<path\to\folder>");

I'm getting the SMB2TreeConnectResponse from Session.connectTree method with errorData empty 
and status = STATUS_BAD_NETWORK_NAME and statusCode = 3221225676.

I really appreciate any help you can provide.

**Comment by gidravlic** [comment]
As far as I know you MUST call connectShare(<only Share name>) without path.

**Comment by hierynomus** [comment]
Indeed, but also you need a hostname. Localhost or the ip works, empty string is a bad name I think.

**Comment by hierynomus** [comment]
@brielga any update?

**Comment by brielga** [comment]
Hi, sorry about not updating here.
The issue was that I didn't know the correct servername, sharename and share path. I was using the whole path sharename/sharepath in the session.connectShare() parameter. 
So I fixed it using session.connectShare(<shareName>) and then DiskShare.openFile(path + filename, ...)
