### ISSUE TITLE
Nested SMB2 share not connecting 

### ISSUE THREAD

**Issue by atanuiitd** [hierynomus/smbj#215]
Hi ,

Suppose the share name is like \\100.96.21.43\Image\smbj
So the server name is 100.96.21.43 
Share name is Image\smbj 
Now this share is not getting connected . 
smbjDiskShare = (DiskShare)smbjSession.connectShare(share);

But if the share value is only Image then it is getting connected .
But our requirement is to connect to Image\smbj share .

How to achieve this ?

**Comment by hierynomus** [comment]
A share does not contain `\` characters far as I'm aware. So the share name is `Image`. However if you use DFS, then `smbj` might indeed be a DFS share name, in which case you should enable DFS in the config.

**Comment by atanuiitd** [comment]
please let me know how to enable DFS .

**Comment by hierynomus** [comment]
`config.withDfsEnabled(true)`. But then still you would call `session.connectShare("Image").openDirectory("smbj")` or something similar.

**Comment by atanuiitd** [comment]
Hi , 
please give me concrete examples for accessing nested share like 
\\a\b\c\d.iso

**Comment by ecki** [comment]
There is no such thing as a nested share, a UNC path consist of \\server\share\dir\dir\file

**Comment by pepijnve** [comment]
> a nested share

The closest thing I can think of are DFS referrals as @hierynomus already mentioned. But I don't think that's the issue here.

@atanuiitd you need to connect to the share and then open the file. Something like this
```
SMBClient client = new SMBClient();
Connection connection = client.connect("server");
Session session = connection.authenticate(new AuthenticationContext("user", "password".toCharArray(), "domain"));
DiskShare share = (DiskShare)session.connectShare("share");
File file = share.openFile("a\\b\\c\\d.iso", ...);
```

**Comment by atanuiitd** [comment]
Thanks for the code snippet .

**Comment by hierynomus** [comment]
@atanuiitd Can we close this ticket?

**Comment by atanuiitd** [comment]
sure .
Please close this ticket
