### ISSUE TITLE
ByteChunkProvider offset should be long and should be protected access, not private.

### ISSUE THREAD

**Issue by niggemannmj** [hierynomus/smbj#22]
The offset for the SMB2WriteRequest message is defined to be UInt64. The ByteChunkProvider getOffset() method is used to provide the file offset where writing is to begin. Since this is an int, the maximum positive offset would be 2GB. Believe it or not, I work in the medical imaging industry and we have image datasets that are larger than 2GB.

Furthermore, the ByteChunkProvider should make the offset value as protected to allow for derived classes to set the offset to an initial value. The reason for this is to allow for the ability to append to an existing file. You need to form a SMB2WriteRequest that skips over anything that the application has previously written. In other word, set the offset to the size of the current file and you have append.

**Comment by hierynomus** [comment]
Yes agreed. If you have some time I would love a Pull Request :)

Also can you give some background as to what you're using (going to use) SMBj for? Would be nice to build a list of projects that it is being used in 😃 .

**Comment by niggemannmj** [comment]
I am still evaluating whether we're going to use SMBJ. Right now, we're using JCIFS and since it's locked into the deprecated SMB1/CIFS we need something to replace it with several of our Java applications since our customers are moving on to SMB3 based storage solutions and won't be enabling SMB1/CIFS.
