### ISSUE TITLE
Get current "share" as DiskEntry

### ISSUE THREAD

**Issue by ahbonsu** [hierynomus/smbj#224]
Is it possible to get the current share I'm connected to (connectShare("share")) as DiskEntry?

I tried with \\, \\., ..\\share, etc.

Example:
`DiskEntry de = diskShare.open("\\.", 
    			EnumSet.of(AccessMask.GENERIC_ALL),
...
`
Thanks for any advice!

**Comment by kevmct** [comment]
Not sure what you would want to achieve with that? As far as I've understood the lib, the share can be represented as a DiskShare. While DiskEntry represents files/directories.

`DiskShare share = (DiskShare) connectShare("share")
DiskEntry entry = share.open(...);`

**Comment by pepijnve** [comment]
You need to use an empty string for that.

`DiskEntry de = diskShare.open("", EnumSet.of(AccessMask.GENERIC_ALL), ...`

**Comment by ahbonsu** [comment]
@kevmct  because the share itself is also a directory, I thought this would be possible. At least it would come in handy for my Implementation of smbj.

@pepijnve I already tried that, resulting in:
`Exception in thread "main" com.hierynomus.mssmb2.SMBApiException: STATUS_SHARING_VIOLATION(3221225539/3221225539): Create failed for 
	at com.hierynomus.smbj.share.Share.receive(Share.java:364)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:344)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:136)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:55)
	at Test.SMBJ.App.main(App.java:65)`

using:

`DiskEntry de = diskShare.open("",  //BOTH, files and directories 
    			EnumSet.of(AccessMask.GENERIC_ALL),
    			null,
			EnumSet.of(SMB2ShareAccess.FILE_SHARE_READ),
			SMB2CreateDisposition.FILE_OPEN,
			null);`

**Comment by pepijnve** [comment]
`STATUS_SHARING_VIOLATION` means someone else has the directory open and you didn't specify any compatible sharing modes yourself. Could you give `SMB2ShareAccess.ALL` instead of `EnumSet.of(SMB2ShareAccess.FILE_SHARE_READ)` a try?

See the table at https://msdn.microsoft.com/en-us/library/windows/desktop/aa363874(v=vs.85).aspx for the details. This discusses the Win32 CreateFile function; SMB servers work the same way.

**Comment by ahbonsu** [comment]
Wow, thanks for that superb explanation - works like a charm!
