### ISSUE TITLE
NetShareInfo502 support?

### ISSUE THREAD

**Issue by djdkedev** [hierynomus/smbj#229]
Does SMBJ library support 'NetShareInfo502' structure to get  'shi502_security_descriptor' ACL information? Refer:https://msdn.microsoft.com/en-us/library/windows/desktop/bb525410(v=vs.85).aspx

Thanks,
Dhananjay

**Comment by pepijnve** [comment]
Share information is accessible via the MS-SRVS RPC interface. There's basic support for that in an add-on project called [smbj-rpc](https://github.com/rapid7/smbj-rpc/blob/master/src/main/java/com/rapid7/client/dcerpc/mssrvs/ServerService.java). It doesn't support NetShareInfo502 at the moment it seems, but that's something that should be straightforward to add.

[SecurityDescriptor#read](https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/msdtyp/SecurityDescriptor.java) is already in place in the smbj project. You can use that to parse the binary representation of a security descriptor into Java objects.
