### ISSUE TITLE
Junk file created in SMBv2 based CIFS share 

### ISSUE THREAD

**Issue by atanuiitd** [hierynomus/smbj#232]
Hi ,
While accessing SMB2 based CIFS share some junk files of size (0 KB ) gets created .
Although they are not affecting any functionality , they should  not get created . 
These file has name like 

a02a7978-6f86-424e-9924-f7f54174c567
3da0dee6-e2a7-4ba8-bc47-c72d49033d97

Any idea why are these files get created ?
Sometimes it is found that they are not created . 
I mean the issue is intermittent.

**Comment by hierynomus** [comment]
Those are uuid file names. This is not something smbj does as far as I'm
aware. Isnt this internal to how you use the library? I have not seen this
in any tests.

Op 2 nov. 2017 13:31 schreef "atanuiitd" <notifications@github.com>:

**Comment by atanuiitd** [comment]
Not understanding "Isnt this internal to how you use the library?".
Can you please elaborate more ?

**Comment by hierynomus** [comment]
What I mean is that this is probably in your own code somewhere, where
you're calling the SMBJ APIs. SMBJ doesn't create (temporary) UUID
filenames by itself.

2017-11-03 5:33 GMT+01:00 atanuiitd <notifications@github.com>:

**Comment by atanuiitd** [comment]
I cant delete this file also .It is telling File Access Denied while trying to delete the file .
It is also seen that this file is created when CIFS share has read,write access . 
In case of read only CIFS share this is not created . 
Does that mean while writing to the CIFS share anything is fishy ?
My code is as bellows ::
com.hierynomus.smbj.share.File smbjFile = null;

accessMasks.add(AccessMask.GENERIC_ALL);
shareAccesses.add(SMB2ShareAccess.FILE_SHARE_WRITE);
			 		
smbjFile = smbjDiskShare.openFile(path,accessMasks,
		                    new HashSet<>(Arrays.asList(FileAttributes.FILE_ATTRIBUTE_NORMAL)),
		                    shareAccesses,
		                    SMB2CreateDisposition.FILE_CREATE,
		                    new HashSet<>(Arrays.asList(SMB2CreateOptions.FILE_DIRECTORY_FILE)) );

**Comment by hierynomus** [comment]
@atanuiitd Any update?

**Comment by atanuiitd** [comment]
close this issue Please . I have used smbjfile.deleteonclose () which was giving trouble.
Now smbjfile.close has solved this problem .

**Comment by hierynomus** [comment]
Can you describe more clearly what the issue was and how it was solved. That will allow people who experience something similar to be helped :)

**Comment by atanuiitd** [comment]
I was using the method deleteonclose() on the file object which was creating some 0KB junk files having names 
a02a7978-6f86-424e-9924-f7f54174c567.
Perhaps the file closure was not done properly.
Later I changed to close method which resolved the issue.

**Comment by pepijnve** [comment]
FYI, calling `deleteOnClose` sends a message to the server telling it that the 'delete pending' flag should be set; that's all. For some reason the SMB server your working with decides that it needs to create files with a GUID as name. I've never seen this happen before. What type of server are you using?

**Comment by atanuiitd** [comment]
Microsoft server 2012
