### ISSUE TITLE
How to check if a file can read or written into

### ISSUE THREAD

**Issue by NadigNikhil** [hierynomus/smbj#233]
We have a requirement to check if we can read a file or we can write into that file. Is there any way can we achieve this using the SMBJ. Currently using version 0.3.0.

Requirement is that we need to check if the file can be read and only then we need to read it.
Similarly we need to check if the file can be written and only then we need to write into it.

**Comment by pepijnve** [comment]
The SMB protocol doesn't provide a dedicated message for this. Try to open the file for read and/or write purposes (see the AccessMask parameter) and see if you get permission denied errors or not.

**Comment by hierynomus** [comment]
@NadigNikhil Does @pepijnve's comment answer your question?

**Comment by NadigNikhil** [comment]
Yeah!! it answers my question.. 

@pepijnve : thank you.
