### ISSUE TITLE
DiskShare.folderExists throws exception if the path given is a file

### ISSUE THREAD

**Issue by ronchalant** [hierynomus/smbj#235]
If you specify a path that references a file on `DiskShare.folderExists`, an `SMBApiException` with `NtStatus.STATUS_NOT_A_DIRECTORY`

Possible fix would be to add this status to the list ignored by the system here: https://github.com/hierynomus/smbj/blob/481fcd342f9fcef5ef292e75db73bf9ad8b034a7/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L124

If this is deemed a suitable fix I can issue a pull request with the change.

**Comment by hierynomus** [comment]
Fixed. Thanks for reporting.
