### ISSUE TITLE
SMBApiException: UNKNOWN(4294967295/3221225586): Authentication failed for 'user' using com.hierynomus.smbj.auth.NtlmAuthenticator@428640fa

### ISSUE THREAD

**Issue by IrynaZhumatiy** [hierynomus/smbj#239]
Hello All,
I login to network share with disabled user and get the next cause:
com.hierynomus.mssmb2.SMBApiException: UNKNOWN(4294967295/3221225586): Authentication failed for 'user' using com.hierynomus.smbj.auth.NtlmAuthenticator@428640fa.
But I want to get status ACCOUNT_DISABLED or something like that. But I get status UNKNOWN.
Could you please comment on this?
Thank you!

**Comment by pepijnve** [comment]
Only error codes that have a corresponding enum constant in https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/mserref/NtStatus.java are reported as such. Everything else is mapped to `NtStatus.UNKNOWN`. You should be able to get the actual status code out via `SMBApiException#getStatusCode` or `SMB2Header#getStatusCode`.

**Comment by hierynomus** [comment]
Status added.

**Comment by IrynaZhumatiy** [comment]
Thanks for the quick reply and fix.
One more question...
I've updated smbj version to 0.5.1 in my build.gradle but I don't see the new status :(
Could you please explain me what i do wrong?

**Comment by hierynomus** [comment]
Because 0.5.1 was released before I added that status. There is no new release yet which contains the status.

**Comment by IrynaZhumatiy** [comment]
I understood.
Could you tell when the new version will released?
Thank you!

**Comment by hierynomus** [comment]
I want to tackle a few other issues / prs first, so definitely not this week.

**Comment by IrynaZhumatiy** [comment]
Ok, I'm waiting.
Thanks a lot for your reply!
