### ISSUE TITLE
Directory creation or existance checking method not working properly

### ISSUE THREAD

**Issue by debarghya85** [hierynomus/smbj#241]
I have a path, suppose smb:// ip/ share_folder/dir1/dir2/abc.pdf
For / , I have used java.io.File.seperator.
Its working fine if my project is deployed in windows server. But it is not workin if it is deployed in linux server.

**Comment by ecki** [comment]
An UNC path does never use platform file separators, it always uses \

Gruss
Bernd
--
http://bernd.eckenfels.net
________________________________

**Comment by hierynomus** [comment]
@debarghya85 Please don't confuse URI's with actual disk paths used in SMBJ. There is currently no direct way of opening a URI/L using SMBJ.

Also as @ecki has correctly noted, paths use `\` as they are always windows / UNC paths. The reason why it works in a windows server is that `java.io.File.separator is then `\`. Whereas in a linux server it is set to `/`.

**Comment by hierynomus** [comment]
@debarghya85 Is this enough information to close this issue?

**Comment by debarghya85** [comment]
Yes you can close it.. thanks for the information.

On 15-Nov-2017 7:54 PM, "Jeroen van Erp" <notifications@github.com> wrote:

@debarghya85 <https://github.com/debarghya85> Is this enough information to
close this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/hierynomus/smbj/issues/241#issuecomment-344607290>, or mute
the thread
