### ISSUE TITLE
Connect to server where SMBv1 is enabled 

### ISSUE THREAD

**Issue by IrynaZhumatiy** [hierynomus/smbj#242]
One more question..
When I connect to server where running SMBv1 only (or the client that only supports v2 or v3) should have returned that “PROTOCOL” status.
Do we have such opportunity?
So... For now when I connect to server where SMBv1 is enabled only, I get the next exception:
java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset
Maybe it may be status like STATUS_PROTOCOL_UNREACHABLE.
Could you please help me?
Thanks!

**Comment by hierynomus** [comment]
If you set the `config.withMultiProtocolNegotiate(true)`, you will get a better error.

**Comment by IrynaZhumatiy** [comment]
@hierynomus Thanks for the reply!

**Comment by hierynomus** [comment]
I assume we can close this?

**Comment by IrynaZhumatiy** [comment]
I think so)
But it would be more convenient to get the status code, because in this case (`config.withMultiProtocolNegotiate(true)`) I catch TransportException as previously (without config).
Thanks!

**Comment by hierynomus** [comment]
But now you get a specialized subtype, i.e. `SMB1NotSupportedException`. The `NtStatus` statuses are defined in the `MS-ERREF` specification. I'm not going to add one there that does not exist.

**Comment by IrynaZhumatiy** [comment]
Whart about STATUS_CONNECTION_RESET?

**Comment by hierynomus** [comment]
`TransportException` does not have an attached NtStatus, and it's the only type of exception that is logically thrown from that layer. So in this case I will not make this 'nicer'. You can just add an extra catch block for the `SMB1NotSupportedException` exception type.

**Comment by IrynaZhumatiy** [comment]
If I catch `SMB1NotSupportedException`, I fall into the block `IOException`.
my code:
          catch (FileNotFoundException e) {
            .....
        } catch (UnknownHostException e) {
            .....
        } catch (SMBApiException e) {
            ......
        } catch (SMB1NotSupportedException e) {
            ......
        } catch (IOException e) {
            .......
        }

**Comment by RatneshChauhan** [comment]
Is this resolved ? I'm falling into the <code>IOException</code> even if I catch <code>SMB1NotSupportedException </code> when only SMBv1 is enabled on share

**Comment by hierynomus** [comment]
Have you enabled multiProtocolNegotiate on the SmbConfig? Else it will not
work indeed.

Op wo 13 jun. 2018 12:37 schreef Ratnesh Chauhan <notifications@github.com>:

**Comment by RatneshChauhan** [comment]
Yes I have enabled <code>config.withMultiProtocolNegotiate(true)</code>. I did mention that.
Do I need to <code>catch (TransportException e)</code> and then <code>throw new SMB1NotSupportedException </code> within that catch block

**Comment by hierynomus** [comment]
Which version of smbj are you using? Can you send a trace level log of the
connection attempt?

Op wo 13 jun. 2018 18:03 schreef Ratnesh Chauhan <notifications@github.com>:

**Comment by hierynomus** [comment]
Can you get me a stacktrace of the transportexception? That one should not occur...
