### ISSUE TITLE
Signing key lost after Kerberos authethicate

### ISSUE THREAD

**Issue by ujmas** [hierynomus/smbj#243]
version: 0.5.1
package: com.hierynomus.smbj.connection
class: Connection
method: public Session authenticate(AuthenticationContext authContext)
line 178
176                if (receive.getSecurityBuffer() != null) {
177                    // process the last received buffer
**178                    authenticator.authenticate(authContext, receive.getSecurityBuffer(), session);**
179                }
180                session.init(receive);
cause: AuthenticateResponse is not consumed and consequently not checked if it contains a signing key resulting in session not having the signing key (like i happens in method authenticationRound in lines 197-202)

**Comment by hierynomus** [comment]
Hi @ujmas,

Could you explain more plainly what you mean? Do you have an example where there is an error/exception?

I think what you mean is that the return from the `authenticator.authenticate` is not used as the `receive` object that is passed to `session.init`.

**Comment by ujmas** [comment]
The result is not checked for signing key e.g.
```
AuthenticateResponse resp = authenticator.authenticate(...)
if (resp.getSigningKey() != null) {
            session.setSigningKey(resp.getSigningKey());
        }
```
And without it this results in an exception
_com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Message signing is required, but no signing key is negotiated
	at com.hierynomus.smbj.session.Session.connectTree(Session.java:173)_

**Comment by hierynomus** [comment]
@ujmas Can you check with the latest master if this solves the problem?

**Comment by ujmas** [comment]
Got current master...
Built as 0.5.2-SNAPSHOT...
Imported...
Run...
It works!
:)

**Comment by hierynomus** [comment]
Yay! Great news. Thanks
