### ISSUE TITLE
Cannot delete local file which is used by FileByteChunkProvider

### ISSUE THREAD

**Issue by IrynaZhumatiy** [hierynomus/smbj#249]
Hello.
I'm transfer file via network share using smbj.
For this I create temporary local file, transfer it and then I want to delete it.
But I cannot.
Could you tell me how I can close all resources (remoteFile, fileByteChunkProvider etc.) before delete local file?
Thanks!

**Comment by hierynomus** [comment]
Hi @IrynaZhumatiy,

Each of the classes you get from SMBJ has a `close()` method, which ensures all resources are released.
However if you cannot delete the local file, it would seem that the `FileInputStream` you're using is not closed and hence is still locked.

If you share your code, it should be obvious what's missing.

**Comment by IrynaZhumatiy** [comment]
I create remoteFile (smbj), create fileByteChunkProvider using constructor with java.io.File parameter:
File remoteFile = new File(remotePath);
FileByteChunkProvider fileByteChunkProvider = new FileByteChunkProvider(new java.io.File(localFilePath));
remoteFile.write(fileByteChunkProvider);
remoteFile.close;
And then I want to delete local file.
Thanks a lot!

**Comment by pepijnve** [comment]
I just had a look at FileByteChunkProvider. That class isn't really usable at the moment since it opens a FileInputStream internally and there's no way to close it. I've made PR #251 to fix that.

**Comment by pepijnve** [comment]
You can work around this issue by using InputStreamByteChunkProvider instead.

```
try(InputStream is = new BufferedInputStream(new FileInputStream(localFilePath))) {
  ByteChunkProvider fileByteChunkProvider = new InputStreamByteChunkProvider(is);
  ...
}
```

**Comment by hierynomus** [comment]
Thanks @pepijnve. You beat me to the fix. I've merged it.

**Comment by IrynaZhumatiy** [comment]
@pepijnve @hierynomus Thanks a lot for your help!!!

**Comment by hierynomus** [comment]
I've made all ByteChunkProviders implement Closeable. This should clean it up :)

**Comment by kilokahn** [comment]
Hey guys - when can we expect the next version of smbj that will incorporate this fix? Thanks!
