### ISSUE TITLE
Always using a DFSDiskShare

### ISSUE THREAD

**Issue by ahbonsu** [hierynomus/smbj#250]
Hi there!

I'm currently working on an implementation of SMBJ into Apache Commons VFS (see my repo [https://github.com/ahbonsu/commons-vfs](https://github.com/ahbonsu/commons-vfs)) and im wondering whether there is a disadvantage of always using a DFSDiskShare over a "normal" DiskShare. The reason for this question is, that I dont know if a DFS Share is used based on an URI. For example:

`FileSystemManager man = VFS.getManager();
FileObject fo = man.resolveFile("smb2://user:password@someHost/someShare");`

The other solution for this problem would be to explicitly define a query string to use DFS, e.g.:

`FileObject fo = man.resolveFile("smb2://user:password@someHost/someShare?isDFS=true");`

Thanks for any advice!

**Comment by hierynomus** [comment]
Hi @ahbonsu,

I don't think you should even need to care. the DFSDiskShare is an extension of the regular DiskShare and does not contain additional operations, it just enhances the logic to resolve DFS shares. There is no need to create these yourself, as SMBJ will return the correct type when you open the share via `Session.connectShare`.

The main question is do you enable DFS in the `SmbConfig` or not, I think for your usecase you should either always enable it, or make it configurable.

**Comment by hierynomus** [comment]
@ahbonsu Do you need more help?

**Comment by ahbonsu** [comment]
Thanks @hierynomus !
Using the SmbConfig solved my problem. I just had an reinitialization of the SmbClient without the config due some sloppy refactoring. This was also the reason of the arbitrary behavior and using the DFSDiskShare explicitly solved the problem in this specific case.
Thanks for your help, I really appreciate it.

**Comment by hierynomus** [comment]
Ok! Good luck with the implementation. Should be a great addition for the commons-vfs userbase!
