### ISSUE TITLE
Append data to an existing file

### ISSUE THREAD

**Issue by saranya1988** [hierynomus/smbj#252]
We need to append data to an existing file and we are using the following code to do it. But it overwrites the file instead of appending to it. We are using smbj-0.3.0-sources.jar
> Set<AccessMask> accessMask = new HashSet<>(EnumSet.of( AccessMask.MAXIMUM_ALLOWED, AccessMask.FILE_APPEND_DATA));

> Set<SMB2ShareAccess> shareAccesses = new HashSet<>(EnumSet.of(FILE_SHARE_READ, FILE_SHARE_WRITE, FILE_SHARE_DELETE));

> Set<SMB2CreateOptions> createOptions = new HashSet<>(EnumSet.of(SMB2CreateOptions.FILE_NON_DIRECTORY_FILE));

> com.hierynomus.smbj.share.File file = diskShare.openFile("/dir1/file1.txt", accessMask, null, shareAccesses, SMB2CreateDisposition.FILE_SUPERSEDE, createOptions);

> OutputStream os = file.getOutputStream();

> byte[] readBytes = new byte[5000];

> while ((inputStream.read(readBytes)) != -1) {

>  os.write(readBytes);

> }

> os.flush();

Can you please help with this issue?

**Comment by hierynomus** [comment]
You're using the `Smb2CreateDisposition.FILE_SUPERSEDE `, which will overwrite the file

**Comment by hierynomus** [comment]
For appending use `SMB2CreateDisposition.OPEN[_IF]`.

Let me know whether that solves your problem.

**Comment by saranya1988** [comment]
Hi,
We tried that and it is not working

**Comment by pepijnve** [comment]
@hierynomus the internal file offset of ByteChunkProvider in the FileOutputStream always starts at 0 and I don't think there's a way to advance it manually. If you want to append using that API you would need some way to 'seek' to the correct location. The alternative is to use the `File#write` methods directly instead of going through the OutputStream.

**Comment by saranya1988** [comment]
It is working now. PFB the code

> long fileOffset = 0;
> byte[] buffer= new byte[1024];
> int length = inputStream.read(buffer);
> while (length != -1) {
  >    fileOffset = diskShare.getFileInformation("/dir1/file1.txt").getStandardInformation().getEndOfFile();
   >    file.write(buffer, fileOffset, 0, length );
> }

**Comment by hierynomus** [comment]
@pepijnve I think that is indeed the only solution, normally you can't forward `OutputStream`s to a specific point. I think @saranya1988 implemented it correctly now.

**Comment by hierynomus** [comment]
@saranya1988 Can we close this ticket?

**Comment by pepijnve** [comment]
> normally you can't forward OutputStreams to a specific point

With the regular java IO apis, that's correct. [SeekableByteChannel](https://docs.oracle.com/javase/8/docs/api/java/nio/channels/SeekableByteChannel.html) and ImageIO's [ImageOutputStream](https://docs.oracle.com/javase/8/docs/api/javax/imageio/stream/ImageOutputStream.html) do support seeking though. Lower-level interfaces like POSIX' [fseek](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fseek.html) also allow you to do this.

**Comment by hierynomus** [comment]
Adding it would mean that we need to do some extra bounds checking etc. I would prefer to keep the `OutputStream` regular. Especially since you can do it using the more fine-grained APIs.

**Comment by pepijnve** [comment]
All good for me; I'm just providing extra information.

Perhaps something like the [append java.io.FileOutputStream constructor](https://docs.oracle.com/javase/8/docs/api/java/io/FileOutputStream.html#FileOutputStream-java.lang.String-boolean-) would be nice to have as a convenience for users.

**Comment by hierynomus** [comment]
That makes sense!

**Comment by saranya1988** [comment]
Please close the issue. Thanks for the inputs.
