### ISSUE TITLE
Could not connect to Share folder in DFS 

### ISSUE THREAD

**Issue by harisingh-highq** [hierynomus/smbj#254]
Hi @hierynomus
I have tried with below code as sample:-
SmbConfig config = SmbConfig.builder()
			    .withMultiProtocolNegotiate(true)
			    .withSigningRequired(true)
			    .withDfsEnabled(true)
			    .build();
			SMBClient client = new SMBClient(config);
			Connection conn = client.connect("domain name");
			Session session = conn.authenticate(new AuthenticationContext("hari.singh", "hari".toCharArray(), ""));
			DiskShare share = (DiskShare) session.connectShare("data\\abc.xyz");

The below exceptions occurs after above code execution:-
com.hierynomus.mssmb2.SMBApiException: STATUS_BAD_NETWORK_NAME(3221225676/3221225676): Could not connect to \\domain name\data\haresh.bhatt
	at com.hierynomus.smbj.session.Session.connectTree(Session.java:147)
	at com.hierynomus.smbj.session.Session.connectShare(Session.java:132)
	at TestSMBJ_DFS.dfsConnection(TestSMBJ_DFS.java:66)
	at TestSMBJ_DFS.main(TestSMBJ_DFS.java:37)

With same DFS server configuration, i have tried with JCIFS library and it succeed with DFS which ensures that DFS environment is correct but it could not resolve DFS properly with SMBJ library

Here, if i try with withDfsEnabled() property set to false in SMB client then also it throws same error.

Can you please help me to sort out this issue?

**Comment by pepijnve** [comment]
This is most likely the same issue as #212. Possible fix in PR #222.

**Comment by hierynomus** [comment]
Also a problem could be that you're trying to connect to this share:

`DiskShare share = (DiskShare) session.connectShare("data\abc.xyz");`

However a share name does not contain a `\`. The share is `data`, and then you can open a file/folder called `abc.xyz`. If it is a DFS share, it will then transitively resolved to the correct directory.

**Comment by harisingh-highq** [comment]
Hi @hierynomus 
I have already tried with data share folder only but its not working fine.
In our infrastructure, we have data folder under domain name and abc.xyz folder is shared in DFS like this domain name\\data\\abc.xyz.

**Comment by hierynomus** [comment]
Yes, but from SMB perspective, the DFS is transparent. This means that abc.xyz is treated as a folder/directory, not as a share.

What happens when you split that up? What is the exception and logging you're getting then?

**Comment by harisingh-highq** [comment]
Hi @pepijnve 
Thanks a lot for your valuable response.

FYI
After replacing your committed changes of PR #222 in my source code, it is working fine now.
So i have a question about related jar with above changes. 
Have you launched updated jar in GitHub because i am not able to find changes in smbj-0.5.0 jar?

**Comment by harisingh-highq** [comment]
Hi @hierynomus 
Thank you so much.

After merging your committed changes of PR #222 in my source code and tried with only data as a share folder, it is working fine now.

**Comment by hierynomus** [comment]
Ill merge #222 soon. Want to make a pass over it still.

**Comment by harisingh-highq** [comment]
Okay. I look forward to release from you soon. Thanks for your prompt reply.

**Comment by harisingh-highq** [comment]
Hi @hierynomus 
In my DFS infrastructure, we have 2 servers and 4 DC distributed with one domain name space.
Out of those 2 servers, if one is stopped and other one is in running state then if i connect it with below code:-
Connection conn = client.connect("dev.india");
			Session session = conn.authenticate(new AuthenticationContext("abc.raj", "Hari".toCharArray(), "hqdev.india"));
			DiskShare share = (DiskShare) session.connectShare("data");

then it throws below exception:-
com.hierynomus.smbj.common.SMBRuntimeException: Could not connect to DFS root \\FILESER2BIND1.hqdev.india\data
	at com.hierynomus.smbj.session.Session.connectTree(Session.java:160)
	at com.hierynomus.smbj.session.Session.connectShare(Session.java:132)
	at TestSMBJ_DFS.dfsConnection(TestSMBJ_DFS.java:66)
	at TestSMBJ_DFS.main(TestSMBJ_DFS.java:37)

But if i try with JCIFS library then it connect with other server and not throwing such exception.
So i think it should connect to other server which is in running state in SMBJ as well.
Can you please help me?

**Comment by pepijnve** [comment]
@hierynomus I think some fallback logic is still missing in the DFS resolver. Currently the `TargetHint` entry is always used. [MS-DFSC 3.1.5.2](https://msdn.microsoft.com/en-us/library/cc227031.aspx) says that in case of errors the other entries from `TargetList` should be tried as well. Also see [DFS client target failover](https://msdn.microsoft.com/en-us/library/cc226984.aspx#gt_a8f123fe-166f-488c-861a-a1e28e6fed52).

**Comment by niravravalhighq** [comment]
Hi, @hierynomus ,
DFS support is now given or still in development phase in SMBJ library?

**Comment by hierynomus** [comment]
Dfs support works for most cases now. The only part that's still missing is this issue. So it is definitely usable.

**Comment by hierynomus** [comment]
Dfs support works for most cases now. The only part that's still missing is this issue. So it is definitely usable.

**Comment by niravravalhighq** [comment]
ok thanks @hierynomus ,
So same is released in JAR of SMBJ or not? Because I am unable to find new version of JAR,. The older one is smbj-0.5.0.

**Comment by raptordzuricsko** [comment]
In case anyone else stumbles upon this issue - dfs seems to be working well enough for me on 0.6.0. Thanks everyone who worked on this

**Comment by andershermansen** [comment]
I tried the smbj with DFS. I had the `STATUS_BAD_NETWORK_NAME` error. After talking to the network admin it seems the server listed in `TargetHint` is not active, but another one lister in `TargetList` is working. So I just put a workaround in `step3` in `DFSPathResolver` to use the last entry in the `TargetList` instead of `TargetHint`. This is working for me, but not a good solution for the project. I'm not sure how to do the retry properly.

**Comment by pepijnve** [comment]
That bit is indeed still to be done (see my comment above from Nov 2017). I wasn't quite sure how we could fit this into the DFS resolver either. Best I can come up with is that a `Consumer<SmbPath>` or `Function<SmbPath, T>` is passed in to `com.hierynomus.smbj.paths.PathResolver#resolve`. That consumer or function would then contain the actual operation we're trying to perform. That way the PathResolver has a means of checking if the resolved path is actually valid or not.

**Comment by pepijnve** [comment]
Just realised the project is targeting Java 7, not Java 8 so no `@FunctionalInterface`s. 😞
But we can do the same thing with a de facto functional interface and anonymous inner classes.

**Comment by andershermansen** [comment]
What about returning an Array or List of SmbPath instead that the caller could try?

**Comment by pepijnve** [comment]
That will work too of course, but then the cache can't be smart and always use the last successful path since it won't know which one that is.

**Comment by andershermansen** [comment]
@pepijnve Very good point.

**Comment by hierynomus** [comment]
I definitely prefer to handle this transparently to the client app. So do
this internally and return the right instance to the client.

Op 14 mrt. 2018 14:37 schreef "Pepijn Van Eeckhoudt" <
notifications@github.com>:

**Comment by pepijnve** [comment]
Prep work for my suggestion translated into code is in PR #303

@hierynomus any idea at which point we need to retry? The target hint is used in steps 3, 9 and 11. 

The main one to deal with is 3 I think; not sure about the other ones. What I think we need to do is call step8 in a loop going over each entry in the target list. When an entry succeeds, we store that fact in the referral cache entry so that we try it first the next time we use the cache entry. Does that make sense?

**Comment by hierynomus** [comment]
I'll need to reread msdfsc to remember the details. It is specified in there I remember.

**Comment by pepijnve** [comment]
[MS-DFSC 3.1.5.2](https://msdn.microsoft.com/en-us/library/cc227031.aspx) is the relevant bit I think. My thinking based on that is that we only need to deal with specific failure conditions that happen in step 8. That's the step where the actual I/O operation is supposed to happen, but where we currently just return the path.

My PR replaces that with a `ResolveAction` (awful name I know, out of inspiration) which represents the I/O operation. `step8` is only called from `step3` which is where the target hint is used to derive the target path.

Putting all that together I think `step3` should catch errors from `step8` and retry with the other entries.

But... since DFS resolution can be a recursive process, one could argue that you need to retry at all levels. That would pull in steps 9 and 11 as well. Not sure what the 'correct' answer is.
