### ISSUE TITLE
How to get the access rights of a File?

### ISSUE THREAD

**Issue by saranya1988** [hierynomus/smbj#257]
I want to find out if the file has read/write access.
I am using fileAllInformation.getAccessInformation().getAccessFlags(), and it returns an int number like 1179785. What does this mean? And how can I find out the access rights of a file?
Thanks

**Comment by pepijnve** [comment]
File information classes are documented in the MS-FSCC spec. See https://msdn.microsoft.com/en-us/library/cc232116.aspx for instance. The encoding of this particular value is documented in the SMB2 specification at https://msdn.microsoft.com/en-us/library/cc246503.aspx. You can convert to the corresponding enum in SMBJ using `EnumWithValue.EnumUtils. toEnumSet(fileAllInformation.getAccessInformation().getAccessFlags(), AccessMask.class)`

**Comment by saranya1988** [comment]
I get the same set of 8 AccessMask for every file, without considering the AccessMask used for creating the file. They are
0 = {AccessMask@15787} "FILE_READ_DATA"
1 = {AccessMask@15788} "FILE_LIST_DIRECTORY"
2 = {AccessMask@15789} "FILE_READ_ATTRIBUTES"
3 = {AccessMask@15790} "FILE_READ_EA"
4 = {AccessMask@15791} "READ_CONTROL"
5 = {AccessMask@15792} "SYNCHRONIZE"
6 = {AccessMask@15793} "ADS_RIGHT_DS_CREATE_CHILD"
7 = {AccessMask@15794} "ADS_RIGHT_DS_SELF"

Also, I found this closed issue addressing the same problem in a different way. Can you please confirm which is the best way to find out the access rights of a file? - https://github.com/hierynomus/smbj/issues/233

**Comment by pepijnve** [comment]
I think that the result you're seeing is to be expected. Check the documentation on FileAccessInformation. It says

> This information class is used to query the access rights of a file that were granted when the file was opened.

I'm going to assume you always open the file with the same access mask (looks like GENERIC_READ) and that access is always being granted. As a consequence the FileAccessInformation reply always contains the same value.

I think what you're looking for are the effective permissions the current user has wrt a certain file or directory. Unfortunately the answer to that question can not be obtained in a simple way.
Access control checks on most servers is implemented using a discretionary access control list (DACL). This type of ACL is associated with both the share and with each file or directory. The share level and file/directory level ACL are both evaluated and the strictest of the two determines the effective access. So for example if you want write access, both the share level ACL and the file level ACL need to allow it.

The file level ACL can be obtained using the `DiskEntry#getSecurityInformation` method. To get the share level ACL you need to an MS-SRVS RPC call. That's not supported by SMBJ itself yet and SMBJ-RPC doesn't seem to support the specific call you need (see https://github.com/rapid7/smbj-rpc/blob/master/src/main/java/com/rapid7/client/dcerpc/mssrvs/ServerService.java).

Once you have the ACLs you would have to evaluate both of them for the user account you're interested in. That's also not straightforward. First of all, the ACL contains security identifiers (SIDs), not user names. So you'll need to resolve the user name to a SID using another RPC call. IIRC you need the LSA and service for that.
You also need to take into account (transitive) group membership. To do that you need to use another set of RPC calls to ask the server which groups the user is a member of.

All this to illustrate that it's complicated. If all you need is a simple 'is access <x> allowed?' answer, a simpler option (which I suggested in #233) is to connect to the server using the account you're trying to check access for and try to open the file using the access mask you want to check. If that's successful the user in question is allowed the access you requested. So in your case, try to open the file with `(GENERIC_READ |GENERIC_WRITE)`.

As an alternative (haven't tried this myself yet), you could try opening the file using `AccessMask.MAXIMUM_ALLOWED` and then query the `FileAccessInformation` to see what the effective access is that you got from the server.

**Comment by saranya1988** [comment]
Hi,
Thanks for the answer. We used the solution from #233 and it worked. Closing the ticket.
