### ISSUE TITLE
Not enough credits (33 available) to hand out 1 sequence numbers...

### ISSUE THREAD

**Issue by kdegrace** [hierynomus/smbj#259]
We are occasionally seeing confusing errors of this nature:

com.hierynomus.smbj.common.SMBRuntimeException: Not enough credits (33 available) to hand out 1 sequence numbers

```java
class SequenceWindow {
...
  long[] get(int credits) {
        try {
            if (available.tryAcquire(credits, MAX_WAIT, TimeUnit.MILLISECONDS)) {
                long lowest = lowestAvailable.getAndAdd(credits);
                return range(lowest, lowest + credits);
            }
        } catch (InterruptedException e) {
            //ignore
        }
        throw new SMBRuntimeException("Not enough credits (" + available.availablePermits() + " available) to hand out " + credits + " sequence numbers");
  }
...
)
```

I'm assuming this happens when an InterruptedException is thrown.  I think in this case, it might make sense to attach a different message to that SMBRuntimeException.

**Comment by hierynomus** [comment]
This was fixed in 474a96f3ab268d2ba3bfe6ef463afd91374798e2
