### ISSUE TITLE
Does smbj library support shares on NetApp filers?

### ISSUE THREAD

**Issue by djdkedev** [hierynomus/smbj#261]
The ONTAP version is 9 and SMBv1, SMBv2 and SMBv3 are enabled by default.
I am getting an error "SMBv1 is not supported BY SMBJ"
could you please help.

Thanks,
Dhananjay

**Comment by hierynomus** [comment]
It seems that the server then prefers to use SMBv1. Is there a setting maybe that defines the preferred protocols? Smbj itself only supports SMBv2.002 and up.

**Comment by pepijnve** [comment]
I just did a quick check with a system running ontap 9.2. Seems to work fine. These cifs options of the SVM I tested look like this

```
cdot::vserver cifs> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

cdot::vserver cifs*> options show

Vserver: xyz

...
                                Shadowcopy Enabled: true
                                      SMB1 Enabled: true
                  Max Buffer Size for SMB1 Message: 65535
                                      SMB2 Enabled: true
                                      SMB3 Enabled: true
                                    SMB3.1 Enabled: true
...
```

**Comment by ecki** [comment]
Can you turn SMB1 off for testing? Also can you try without the negotiation option in jcifs? Can you provide a packet capture?

**Comment by djdkedev** [comment]
The connection is established after setting 'useMultiProtocolNegotiate' to false in SmbConfig.
In which case 'useMultiProtocolNegotiate' should be set to true?

**Comment by ecki** [comment]
I think as long as smbj does not support 3.x using the negotiate option only is useful to get better error messages with Cifs/smb1 endpoints. It does however require the server to be sane, which it seems is not the case for your appliance.

**Comment by djdkedev** [comment]
Thank you all.
