### ISSUE TITLE
Getting NullPointerException when opening DFS link

### ISSUE THREAD

**Issue by djdkedev** [hierynomus/smbj#263]
The DFS is enabled in the SMBConfig.
Share:"\\\ServerHostName\NS"  (Standalone namespace)
DiskShare share=(Diskshare)Session.connectShare("NS");
for(FileIdBothDirectoryInformation f: share.list(""))
{
      String fileName = f.getFileName();
      //This fileName is DFS folder which is link to another directory
      //Check for FILE_ATTRIBUTE_DIRECTORY flag in f.getFileAttributes() and if directory then open it to get its children else print file information

     Directory dir = share.openDirectotry(filename,  EnumSet.of(AccessMask.GENERIC_ALL), null,      SMB2ShareAccess.ALL, SMB2CreateDisposotion.FILE_OPEN, null);
//Throws NPE
}
SMBJ version:0.5.1

How to get the children of the folder referred by one of the child link of the DFS share
(server\NameSpace)? Does SMBJ supports nested DFS links?
Could you please share an example to traverse through the DFS namespace and all its links?

Thanks,
Dhananjay

**Comment by hierynomus** [comment]
Can you post a full example, nicely indented/formatted and an example setup? I unfortunately cannot make heads or tails of this ticket.

**Comment by djdkedev** [comment]
SMBJ version: 0.5.1
DFS share: \\\DJSERVER\DFSNS which contains the DFSFolder link to shared folder

Issue: Getting NPE when opening directory which is DFSFolder link

`Code snippet:

       public void testDFSShare() 
       {
		String serverName = "DJSERVER";
		String userName = "Administrator";
		String password = "test#123";
		String shareName = "DFSNS";

		try {
			SmbConfig config = SmbConfig.builder().withMultiProtocolNegotiate(false).withSigningRequired(true)
					.withDfsEnabled(true).build();

			SMBClient client = new SMBClient(config);
			Connection connection = client.connect(serverName);
			AuthenticationContext ac = new AuthenticationContext(userName, password.toCharArray(), "");
			Session session = connection.authenticate(ac);
			DiskShare share = (DiskShare) session.connectShare(shareName);
			for (FileIdBothDirectoryInformation f : share.list("")) {
				String fileName = f.getFileName();

				if (fileName.equals(".") || fileName.equals("..")) {
					continue;
				}
				try {
					Directory directory = share.openDirectory(fileName, EnumSet.of(AccessMask.GENERIC_READ), null,
							EnumSet.of(SMB2ShareAccess.FILE_SHARE_READ, SMB2ShareAccess.FILE_SHARE_WRITE),
							SMB2CreateDisposition.FILE_OPEN, null);
					for (FileIdBothDirectoryInformation f2 : directory.list()) {
						String fileNameInDFSFolder = f2.getFileName();
						System.out.println("DFS folder fileName:" + fileNameInDFSFolder);
					}
				} catch (Exception e) {
					System.out.println("Failed to get children of DFS folder due to error:" + e);
				}
			}
		}

		catch (Exception e) {
			System.out.println("Failed to process DFS share due to error:" + e);
		}
	}
`

**Comment by hierynomus** [comment]
What is the exact stacktrace of the exception?

**Comment by djdkedev** [comment]
java.lang.NullPointerException
	at com.hierynomus.smbj.share.DiskShare.getDiskEntry(DiskShare.java:64)
	at com.hierynomus.smbj.share.DFSDiskShare.open(DFSDiskShare.java:71)
	at com.hierynomus.smbj.share.DiskShare.openDirectory(DiskShare.java:82)
	at Scan.main(Scan.java:101)

**Comment by pepijnve** [comment]
The DFS support has changed quite a bit in the meantime; that stack trace is no longer relevant wrt the current development version. Could you retest using the `master` branch?

**Comment by djdkedev** [comment]
This issue is resolved with master branch version. 
Thank you all.
