### ISSUE TITLE
Errors relating to ASN1Primitive

### ISSUE THREAD

**Issue by manasBelekar** [hierynomus/smbj#266]
I am getting couple of errors after the latest pull from master.
Could you please suggest resolution for it.

![error](https://user-images.githubusercontent.com/23233930/33897929-27bf2d92-defa-11e7-92eb-3de3d3c0b609.jpg)

There is some misconfiguration on Spengo side, which I am not able to resolve.

Thanks

**Comment by manasBelekar** [comment]
Any help on this is appreciated.

cause for these errors related to SPNEGO definition
![bouncy_castle](https://user-images.githubusercontent.com/23233930/33919346-92f7906c-df4b-11e7-9fd3-a277a01d0657.jpg)

**Comment by manasBelekar** [comment]
I found the root cause for it. bcprov-jdk15-136.jar in my env is causing it. 

I could see no error now in project, but still i am **not able to build it** perfectly.
Groovy is causing errors. Any pointers to solve this.

![groovy_err](https://user-images.githubusercontent.com/23233930/33920143-b0c29a84-df4f-11e7-9346-e8a1ed2ee505.jpg)

**Comment by manasBelekar** [comment]
I have double checked the version of bouncyCastle. there are no conflicting jars.

Any help/ resolution is highly appreciated.

**Comment by manasBelekar** [comment]
hi @hierynomus / @pepijnve ,

could you please help here

**Comment by hierynomus** [comment]
This is definitely something in your environment. What JDK are you running?

**Comment by manasBelekar** [comment]
Jdk1.8.0_152

**Comment by hierynomus** [comment]
There are a number of references if you would just google it. For instance: https://confluence.atlassian.com/stashkb/ssh-not-working-after-stash-upgrade-695242070.html

You somewhere have an incompatible version of BC loaded in your JDK/classpath

**Comment by manasBelekar** [comment]
I had referred the same link. Hence made sure that BC loaded are same. It is failing at compileTestGroovystartup stage.

[stacktrace.txt](https://github.com/hierynomus/smbj/files/1555058/stacktrace.txt)

**Comment by pepijnve** [comment]
Could you run gradle with the `--debug` flag, capture the output and attach it here?

**Comment by manasBelekar** [comment]
Attached file:

[debugInfo.txt](https://github.com/hierynomus/smbj/files/1555180/debugInfo.txt)

**Comment by pepijnve** [comment]
AFAICT the correct version of bouncy castle is being used. It's being loaded from `C:\Users\Administrator\git\smbj\caches\modules-2\files-2.1\org.bouncycastle\bcprov-jdk15on\1.57\f66a135611d42c992e5745788c3f94eb06464537\bcprov-jdk15on-1.57.jar`. You could try verifying that jar file manually to make sure it's not corrupt. You can use `jarsigner -verify -verbose <path to jar file>` to do that.

**Comment by manasBelekar** [comment]
jar verified.

Warning:
This jar contains entries whose certificate chain is not validated.
This jar contains signatures that does not include a timestamp. Without a timestamp, users may not b
e able to validate this jar after the signer certificate's expiration date (2020-04-24) or after any
 future revocation date.

**Comment by manasBelekar** [comment]
Hi @pepijnve,

As i am not able to build the smbj in my environment. Could you please do me a favor of sharing the jar with fix for #265 . It would be great help to me. I am blocked with this.

Thanks

**Comment by hierynomus** [comment]
Can you run the build using another (freshly installed) JDK?

2017-12-13 13:01 GMT+01:00 MANAS BELEKAR <notifications@github.com>:

**Comment by manasBelekar** [comment]
This is solved now. Thanks for help.

However, I am not able to run the code throughout.
i am getting jar signature error, around the changes done earlier for **ASN1ObjectIdentifier**

I tried verifying signatures for bcprov-jdk15on-1.57.jar referenced. it says it is verified.

I googled about the issue and got some pointers saying:
make sure to use same jar in all references : _done but no luck_ 
try removing signature info from menifest.mf file and run: _done but no luck_
Tried downloading latest jar file from bouncycastle website: _didn't worked either_

I have clean build my project countless time but nothing works out. Attaching stacktrace, Any suggestions for resolving this is most welcome.
[stacktrace.txt](https://github.com/hierynomus/smbj/files/1559064/stacktrace.txt)

the source of error pointing the same line, which recently got changed.
` private static final ASN1ObjectIdentifier NTLMSSP = new ASN1ObjectIdentifier("1.3.6.1.4.1.311.2.2.10");`

Also attaching my sample class
`package com;

import java.io.IOException;
import java.util.concurrent.TimeUnit;

import com.hierynomus.smbj.SMBClient;
import com.hierynomus.smbj.SmbConfig;
import com.hierynomus.smbj.auth.AuthenticationContext;
import com.hierynomus.smbj.connection.Connection;
import com.hierynomus.smbj.session.Session;
import com.hierynomus.smbj.share.DiskShare;

public class Sample
{

    public static void main(String[] args) throws IOException
    {
        SmbConfig config = SmbConfig.builder()
            .withTimeout(120, TimeUnit.SECONDS) // Timeout sets Read, Write,and Transact timeouts (default is 60 seconds)
            .withSoTimeout(180, TimeUnit.SECONDS) // Socket Timeout (default is 0 seconds, blocks forever)
            .build();
        SMBClient client = new SMBClient(config);

        try (Connection connection = client.connect("clm-pun-023390"))
        {
            AuthenticationContext ac = new AuthenticationContext("administrator", "Adm1n".toCharArray(),"abc.com");
            Session session = connection.authenticate(ac);
            // TODO add sharename
            try(DiskShare diskShare = (DiskShare)session.connectShare("/c$/temp/stage")){
                diskShare.folderExists("/c$/temp/shage/manas");
            }catch (Exception e) {
                e.printStackTrace();
            }

        }catch (Exception e) {
            e.printStackTrace();
        }
        System.out.println("Hello");

    }

}
`

**Comment by pepijnve** [comment]
Class signatures are saved in the manifest file of a jar. You could try locating where the problematic manifests are coming from at runtime using the bit of quickly hacked together code:

```
public static void findManifests(Class contextClass) throws IOException
{
    ClassLoader classLoader = contextClass.getClassLoader();
    Enumeration<URL> manifestFiles = classLoader.getResources("META-INF/MANIFEST.MF");
    while (manifestFiles.hasMoreElements()) {
        URL url = manifestFiles.nextElement();
        String content = readManifest(url);
        if (content.contains("bouncy")) {
            System.out.println("Found bouncy castle manifest at " + url);
        }
    }
}

private static String readManifest(URL url) throws IOException
{
    ByteArrayOutputStream tmp = new ByteArrayOutputStream();
    try (InputStream inputStream = url.openStream()) {
        byte[] buffer = new byte[4096];
        int bytesRead;
        while ((bytesRead = inputStream.read(buffer)) != -1) {
            tmp.write(buffer, 0, bytesRead);
        };
    }
    tmp.close();
    return new String(tmp.toByteArray(), StandardCharsets.US_ASCII);
}
```

Call `findManifests` with `SMBClient.class` as parameter for instance. You can use a similar approach to figure out where the bouncycastle classes are being loaded from. Replaced `META-INF/MANIFEST.MF` with `org/bouncycastle/asn1/ASN1Primitive.class` for instance (and then don't try to read the contents as a String of course).

**Comment by manasBelekar** [comment]
Many Thanks for the support. It got resolved :)

**Comment by pepijnve** [comment]
Would you be able to share what was wrong in the end and how you resolved it? Could be useful for other people that run into similar issues.

**Comment by manasBelekar** [comment]
I had changed my java.security file (kept under <jre/lib/security> directory) which i forgot later. I have some conflicting setting which was causing that issue. 
The fresh java installation worked perfectly.
