### ISSUE TITLE
Checking if File/Directory is Hidden

### ISSUE THREAD

**Issue by travisennis** [hierynomus/smbj#267]
I upgraded from 0.0.10 to 0.5.1 and the following code

`                boolean isHidden = EnumWithValue.EnumUtils.isSet(
                    file.getFileAttributes(), FileAttributes.FILE_ATTRIBUTE_HIDDEN );`

no longer correctly indicates if the file or directory is hidden. Has the API moved to a different method for determining this file attribute or is this a bug in the current version?

I'm looking for a way to filter out "." and ".." and this used to be a good way to do that.

**Comment by hierynomus** [comment]
Can you give a full reproduction code block?

**Comment by travisennis** [comment]
For example:

`        Session session = null;
        try {
            //Connect to server
            session = createConnection();
            DiskShare share = this.getShare( session, requestPath );

            List<FileIdBothDirectoryInformation> files = share.list( SMBUtils.getSharePath( fullPath ) );
            files.stream().forEach( (file) -> {
                boolean isHidden = EnumWithValue.EnumUtils.isSet(
                    file.getFileAttributes(), FileAttributes.FILE_ATTRIBUTE_HIDDEN );

                if( !isHidden || getConfig().isShowHiddenFilesEnabled() ) {
                    // do stuff
                }
            } );
        }
        catch( SMBApiException | TransportException | StonewareException ex ) {
            // log error
        }
        finally {
            closeConnection( session );
        }`

**Comment by pepijnve** [comment]
> I'm looking for a way to filter out "." and ".." and this used to be a good way to do that.

The code you're using is the correct way to check for hidden files. As far as I know that hasn't changed.

Filtering out `.` and `..` shouldn't be done using the hidden attribute though. I don't think there's any clause in the SMB spec that requires that all servers report that attribute as being set for those files. You should simply check for the `.` and `..` filename; those are reserved. See https://msdn.microsoft.com/en-us/library/ee381481.aspx

**Comment by hierynomus** [comment]
The reason why this doesn't (always) work is most probably because Samba (on Linux) marks any file starting with `.` as hidden, as this is the *Nix way of making files hidden. However Windows has a specific hidden file attribute, which is not set on `.` and `..` (which would make the current directory hidden in Windows).

Also this behavior changed in SMBJ, because initially SMBJ was filtering out `.` and `..` in the file listings. This changed in commit aa93958a3baa9808e23abee89ed2a8434ccbbf6c

**Comment by travisennis** [comment]
Thanks for the update and clarification. I can easily filter out `.` and `..` now that I know the code is not misbehaving. I will close this issue.

**Comment by jansohn** [comment]
What was the reason for not filtering out `.` and `..` anymore? I can't think of any reason where this information would be useful when listing directory contents to be honest...

**Comment by pepijnve** [comment]
The rationale is that smbj is trying to be a low-level smb client directory. As such it should not hide information that is returned by the server from the user. The `.` and `..` entries provide the requested info level data for the directory being queried and its parent directory. This can be useful information for some users; simply discarding would be making arbitrary decisions for the user of the library.

FWIW, if you're using SMB through the NT (`NtQueryDirectoryFile`) or POSIX (`readdir`) API you will get those entries just as well.
