### ISSUE TITLE
Last accessed date gets affected when reading a file from NetApp filers shares 

### ISSUE THREAD

**Issue by djdkedev** [hierynomus/smbj#268]
Reading a file from the DFS share or Windows shares does not changed the last accessed date of a file but it gets changed for a file on shares on NetApp filers.

code snippet
`File openedFile = share.openFile(fileName, EnumSet.of(AccessMask.GENERIC_READ), EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL), SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, EnumSet.noneOf(SMB2CreateOptions.class));
 int readBytes = openedFile.read(buffer, 0);`

Before read Change time: Tue Dec 19 09:27:40 MVT 2017
Before read Access time: Tue Dec 19 10:54:23 MVT 2017
Before read Write time: Tue Dec 19 09:27:40 MVT 2017
File readBytes: 5
File data: hello
After read, Change time: Tue Dec 19 09:27:40 MVT 2017
After read Access time: Tue Dec 19 11:42:17 MVT 2017
After read, Write time: Tue Dec 19 09:27:40 MVT 2017

Thanks,
Dhananjay

**Comment by pepijnve** [comment]
That’s how last accessed time is intended to work. You’re accessing the file, last access time gets updated.
This is done by the server; not by the client.
There is a way to prevent this by setting the last access time to -1 using a set info message. That signals to the server that you don’t want it to be updated by subsequent requests. Not sure if all servers respect this though.
Additionally you can typically turn atime tracking off using a server side option. On 7mode filers this is done using the `no_atime_update` volume option. Cdot probably has something similar.

**Comment by djdkedev** [comment]
Thanks! Setting File.SetFileInformation() with DONT_UPDATE filetime value before reading a file resolved this issue.
