### ISSUE TITLE
[Question] do we really required Java 1.7

### ISSUE THREAD

**Issue by hmkmajeed** [hierynomus/smbj#272]
Hi ,
Presently my project is using jcifs-1.3.15.jar to support the SMB protocol. However this jar is support only SMB1. Since our Windows server is upgraded and support for SMB1 is limited or no longer exist. 
So, we will be moving to support SMB2 or SMB3. While searching I found smbj.jar is the best to use for SMB2 or higher.
However, the limitation is for Java version, our current project running under Java 1.6 and if we need to upgrade then its big deal. 
So, can @hierynomus please suggest whether Java 1.6 is flexible to use smbj?

Many thanks.
Majeed.

**Comment by hierynomus** [comment]
Hi Majeed,
Thank you for your interest in the library. Unfortunately some of the dependencies require Java7 already. And also part of the codebase uses Java7 constructs, so rewriting them is not really something I am keen on to do.
Furthermore, given that Java 1.6 has been EOL for a considerable time, I would strongly advise you to upgrade 😉 (Even Java7 is already EOL).

**Comment by hmkmajeed** [comment]
Many Thanks @hierynomus for the prompt response.
I will try to make the necessary changes. Will get back to you if found any.

Thanks once again :)
