### ISSUE TITLE
GetInfo Request failing (NT_Status: STATUS_NOT_SUPPORTED (0xc00000bb)

### ISSUE THREAD

**Issue by obit91** [hierynomus/smbj#273]
Hello.
I've been trying to access two samba hosts using the same code. One succeeds whilst the other fails.
I captured the traffic and couldn't quite figure the difference between the two packets.

[smb2PacketsHeaders.txt](https://github.com/hierynomus/smbj/files/1603336/smb2PacketsHeaders.txt)

I use the same code to access them.
"newFile.getFileInformation().getStandardInformation().getEndOfFile();"

This is how I create the DiskEntry object called "newFile".
```
String innerPath = Samba.removeSMBPathPrefix(pathOnShare, share);
Set<AccessMask> accessMasks = new HashSet<>(EnumSet.of(AccessMask.FILE_READ_DATA, AccessMask.FILE_READ_ATTRIBUTES, AccessMask.FILE_READ_EA, AccessMask.SYNCHRONIZE));
Set<SMB2ShareAccess> shareAccess = new HashSet<>(EnumSet.of(SMB2ShareAccess.FILE_SHARE_READ, SMB2ShareAccess.FILE_SHARE_WRITE, SMB2ShareAccess.FILE_SHARE_DELETE));
Set<SMB2CreateOptions> createOptions = new HashSet<>(EnumSet.of(SMB2CreateOptions.FILE_NON_DIRECTORY_FILE));
return share.openFile(innerPath, accessMasks, null, shareAccess,SMB2CreateDisposition.FILE_OPEN,createOptions);
```

**Comment by pepijnve** [comment]
The 'bad' response contains the error code `STATUS_NOT_SUPPORTED`. So the server is saying it doesn't support what you're asking it to do. The `getFileInformation` method uses the `FILE_ALL_INFORMATION` information class; you could try querying the a smaller set of data and see if that works. For instance, try querying just the `FILE_STANDARD_INFORMATION`.

**Comment by obit91** [comment]
Someone hand this man a cookie!
Thank you very much for the quick reply.
