### ISSUE TITLE
Get list of all share folders from root

### ISSUE THREAD

**Issue by niru888** [hierynomus/smbj#274]
Hi,

I try to get a list of all share folders on root but i getting an exception.
How can I get all shares folder from root?

The following is the code I run and the exception that throw
```
   SMBClient client = new SMBClient();
    try (Connection connection = client.connect("192.168.75.11")) {
                AuthenticationContext ac = new AuthenticationContext("admin", "password".toCharArray(), "domainName");
      Session session = connection.authenticate(ac);
      // Connect to Share
      try (DiskShare share = (DiskShare) session.connectShare(null)) {
         for (FileIdBothDirectoryInformation f : share.list("", "*")) {
             System.out.println("File : " + f.getFileName());
         }
      }
    }catch (Exception e) {
          assertTrue(e.getMessage(), false);
    }             

e: com.hierynomus.mssmb2.SMBApiException: STATUS_INVALID_PARAMETER(3221225485/3221225485): Could not connect to \\192.168.75.11

**Comment by hierynomus** [comment]
Hi @niru888,

You cannot connect to the `null` share. That causes the `STATUS_INVALID_PARAMETER`. Listing all shares of a machine is an `IOCTL` RPC request. This specific request is currently not (yet) implemented in SMBJ itself.

**Comment by civilu** [comment]
@niru888, I'm currently trying to use SMBJ in a project and ran into the same problem as you.

See #131 for more details about it and specifically the comment mentioning using https://github.com/rapid7/smbj-rpc for listing the shares available on a host.
