### ISSUE TITLE
Question: Is FILE_READ_DATA flag necessary on diskShare.getFileInformation()?

### ISSUE THREAD

**Issue by yin19941005** [hierynomus/smbj#276]
Hi all,

At this line: 
[https://github.com/hierynomus/smbj/blob/ea13ee9fe93884a967d8a085bc7ead3443d075a0/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L242](https://github.com/hierynomus/smbj/blob/ea13ee9fe93884a967d8a085bc7ead3443d075a0/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L242)

We are using `GENERIC_READ` flag which is combination of access flags listed above: `FILE_READ_DATA| FILE_READ_ATTRIBUTES| FILE_READ_EA| SYNCHRONIZE| READ_CONTROL`

I tried to use flags combination `FILE_READ_ATTRIBUTES| FILE_READ_EA| SYNCHRONIZE| READ_CONTROL` to get the `FileAllInformation` and it had succeed. I am wondering is there any file information is requiring this flag to got the file information. I am concerning this one is because this would cause `STATUS_SHARING_VIOLATION` if we mis-setting the `FILE_READ_DATA` flag on.

**Comment by pepijnve** [comment]
In order to query `FILE_ALL_INFORMATION` I think `FILE_READ_ATTRIBUTES | FILE_READ_EA` is actually sufficient. `SYNCHRONIZE` is not relevant and `READ_CONTROL` is only necessary when querying the DACL of the file/directory. As you stated `FILE_READ_DATA` is only required if the contents of a file or directory are going to be read which is not the case here either.

**Comment by yin19941005** [comment]
Hi @pepijnve ,

Thank you for your reply! I see your point. Now, I think always using `FILE_READ_ATTRIBUTES | FILE_READ_EA` for the method `public <F extends FileQueryableInformation> F getFileInformation(String path, Class<F> informationClass) {}` is sufficient.

And for the getSecurityInfo method `public SecurityDescriptor getSecurityInfo(String path, Set<SecurityInformation> securityInfo) throws SMBApiException {}` on this line:
[https://github.com/hierynomus/smbj/blob/ea13ee9fe93884a967d8a085bc7ead3443d075a0/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L374](https://github.com/hierynomus/smbj/blob/ea13ee9fe93884a967d8a085bc7ead3443d075a0/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L374)

It would require `FILE_READ_ATTRIBUTES | FILE_READ_EA | READ_CONTROL`, am I right?

I would make a pull request to avoid requesting so much privilege on querying those information.

**Comment by pepijnve** [comment]
> It would require FILE_READ_ATTRIBUTES | FILE_READ_EA | READ_CONTROL, am I right?

I'm not sure if you even need `FILE_READ_ATTRIBUTES` and `FILE_READ_EA` to read the security descriptor. Based on the documentation just `READ_CONTROL` might actually be sufficient (and `ACCESS_SYSTEM_SECURITY` if the SACL is being queried). Easy enough to test against a real server I guess.

**Comment by yin19941005** [comment]
Hi @pepijnve ,

Lots of thanks! I tested with those flags with my environment and the code in the pull request works and fix the issue!

**Comment by hierynomus** [comment]
Closing this ticket as the PR hsa been merged.
