### ISSUE TITLE
unable to copy file from local to remote location

### ISSUE THREAD

**Issue by saga134** [hierynomus/smbj#278]
Hello,
I am trying to copy some excel file from my local folder to some remote location. i am using smbj-0.5.1 version. I am getting create failed on the remote location. i am not understanding  what is the difference between the DiskShare and the the over all destination where the file is to be copied. It is creating the correct path on the logs as "\\10.165.14.66\Business Services$\BSC-CentralLakeRidge\Data\Daily\" and i need to copy the C:\Report\Report – 01-08-2018-1601741.xls File to "\\10.165.14.66\Business Services$\BSC-CentralLakeRidge\Data\Daily\"  path. but I am getting the below exception. any help would be greatly appreciated..

public static void upload1(String filename)  {			
			try{ SmbConfig cfg = SmbConfig.builder()
			    		.withMultiProtocolNegotiate(true)
			    		.withSigningRequired(false)
			    		.withDfsEnabled(false)
			    		.build();
			    SMBClient client = new SMBClient(cfg);			   
			   Connection connection = client.connect("10.165.14.66");			  
			   Session session = connection.authenticate(new AuthenticationContext("cdvprov", "Dlsu1254".toCharArray(),  null));		    
			    DiskShare share = (DiskShare) session.connectShare("Business Services$");			   
			    File source = new File(filename);
			     
			    String destPath="\\BSC-CentralLakeRidge\\XPG Data\\Daily\\";			    
			  SmbFiles.copy(source, share, destPath, true);
			   
			}catch (Exception ex){
				ex.printStackTrace();
			}
			
			
		
    }

======stack trace========
Jan 11, 2018 3:47:51 PM com.hierynomus.smbj.connection.Connection connect
INFO: Successfully connected to: 10.165.14.66
Jan 11, 2018 3:47:51 PM com.hierynomus.smbj.connection.Connection authenticate
INFO: Successfully authenticated cdvprov on 10.165.14.66, session is 250691671035165
Jan 11, 2018 3:47:51 PM com.hierynomus.smbj.session.Session connectTree
INFO: Connecting to \\10.165.14.66\Business Services$ on session 250691671035165
com.hierynomus.mssmb2.SMBApiException: STATUS_INVALID_PARAMETER(3221225485/3221225485): Create failed for \\10.165.14.66\Business Services$\BSC-CentralLakeRidge\XPG Data\Daily\
	at com.hierynomus.smbj.share.Share.receive(Share.java:364)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:344)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:136)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:59)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:100)
	at com.hierynomus.smbj.utils.SmbFiles.copy(SmbFiles.java:51)

**Comment by saga134** [comment]
it worked finally..
public static void upload(String filename)  {
			try{
			   // SmbConfig cfg = SmbConfig.builder().build();
				//SmbConfig cfg = SmbConfig.builder(). withMultiProtocolNegotiate(true).withSecurityProvider(new JceSecurityProvider(new BouncyCastleProvider())).build();
			    SmbConfig cfg = SmbConfig.builder()
			    		.withMultiProtocolNegotiate(true)
			    		.withSigningRequired(false)
			    		.withDfsEnabled(false)
			    		.build();
			    SMBClient client = new SMBClient(cfg);
			    //ILNLKCAFSN02
			   Connection connection = client.connect("10.165.14.66");
			    //Connection connection = client.connect("ILNLKCAFSN02");			  
			    Session session = connection.authenticate(new AuthenticationContext("cdvprov", "Dlsu1254".toCharArray(),  null));			    
			    DiskShare share = (DiskShare) session.connectShare("Business Services$");		    
			   
			     File source = new File(filename);
			     System.out.println("Filename:"+source.getName());			     
			     String destPath="BSC-CentralLakeRidge\\XPG Data\\Daily\\Daily\\"+source.getName();			    
			     SmbFiles.copy(source, share, destPath, true);
			    
			}catch (Exception ex){
				ex.printStackTrace();
			}

**Comment by kaushikramabhotla** [comment]
Hello @saga134 , @hierynomus , @pepijnve , @ilx , @adityakalia 

my case is different, I need to copy files from a remote server(windows) to my local server(linux), I am able to connect to the remote server, but unable to copy files from the remote server to my local (linux)

There are no error either, the file simply won't copy :


`public static void upload(String filename) {
		try{
		SMBClient client = new SMBClient();
		String decrypt = "WindPower07!";
		Connection connection = client.connect("windows IP");
		System.out.println("connected successfully !");
		AuthenticationContext ac = new AuthenticationContext("useriD",password.toCharArray(), "some domain");
		Session session = connection.authenticate(ac);
		DiskShare share = (DiskShare) session.connectShare("C$");
		System.out.println("share details : "+share.getSmbPath());
		File source = new File(filename);
	    System.out.println("Filename is: "+source);

	    
       for (FileIdBothDirectoryInformation f : share.list("Users/Administrator/Desktop/xml/", "*.TXT")) {
           System.out.println("Files that are in windows system are : " + f.getFileName());

       }
       
       SmbFiles.copy(source, share, destPath, true);
    
	    
	    System.out.println("copied..");
		connection.close();
		client.close();
		}catch (Exception ex){
					ex.printStackTrace();
		}
}`
