### ISSUE TITLE
SPNEGO support

### ISSUE THREAD

**Issue by ckherrmann** [hierynomus/smbj#28]
Looks like the SPNEGO authentication support is not implemented--there's just a stub class.  

I do actually have something working, but I'm wondering if anyone else is trying to do this.

**Comment by hierynomus** [comment]
Haven't worked on this yet :)

**Comment by hierynomus** [comment]
@ckherrmann I've refactored the authentication part. I'm wondering if the first `authenticate` method is needed. Does the SPNEGO authenticator have the same initial step?

**Comment by hierynomus** [comment]
Ok, well after reading the GSS specs a bit more, refactored the authentication even further. Have a look to see whether you can fit the SPNEGO authenticator in this, or whether we need to change it.
The NTLM authenticator now does what it's supposed to, without depending on the "protocol" that is using the authentication.

The Authenticator now is a stateful object, so you can use it as such also :).

**Comment by ckherrmann** [comment]
I haven't looked at your new refactoring yet, but I did push my SPNEGO/Kerberos authentication onto a branch in my fork.  Which means you can look at it if you like, while I work on it to get it ready to merge.
Here is the link to compare: https://github.com/hierynomus/smbj/compare/master...ckherrmann:spnego

**Comment by ckherrmann** [comment]
Started with looking at the refactoring.  Main issue is that I need to change my code to remove the message pump since you put that into Connection (where it probably belongs anyway), so it might take a little while.  But I think what you have currently should work pretty well.

**Comment by ckherrmann** [comment]
The latest issue is that the type of authentication credentials you have available influences what authentication mechanism you can use.  If you have a username/password/domain (ie, a AuthenticationContext), then you have to use NTLM; if you have a [Kerberos]Subject (ie, a GSSAuthenticationContext), you have to use SPNEGO.  I'm thinking the factory for a mechanism could inspect the context for compatibility, and decline if it's not the right credentials.  What are your thoughts?

**Comment by hierynomus** [comment]
I would suggest the authenticator has the boolean method. We could also
merge the two authentication contexts if we maie the credentials an Object
(a string password or an gss subject)?

Op 11 nov. 2016 9:08 p.m. schreef "ckherrmann" <notifications@github.com>:

**Comment by ckherrmann** [comment]
The order of things right now is:
1. make a "AuthContext" which is basically a Credentials-holder
2. start a connection
3. negotiate available protocols
4. pick the first auth protocol that is available
5. create an authenticator for that auth protocol using the auth protocol's factory
6. perform the authentication loop using the authenticator

You're suggesting that 5. should be:
5. create an authenticator for the auth protocol using the auth protocol's factory
5a. ask the authenticator if the given AuthContext is OK
5b. if it is not OK, pick the next auth protocol and go back to 5.

So you can end up creating an authenticator and then throwing it away.

**Comment by hierynomus** [comment]
Yes, but the authenticators are pretty cheap to create, so I don't worry
about that too much.
The sequence seems right indeed.

2016-11-11 22:05 GMT+01:00 ckherrmann <notifications@github.com>:

**Comment by hierynomus** [comment]
This was implemented :) Closing the ticket.
