### ISSUE TITLE
Can I make SMBJ Client Object singleton in my application for get Connection?

### ISSUE THREAD

**Issue by niravravalhighq** [hierynomus/smbj#280]
Hi @hierynomus / @pepijnve ,
In My application, I have used below method to make SMB Connection.
```
private Connection getSmbjRepoConn() throws Exception
{
	SMBClient client = new SMBClient();
	Map<String,String> mapParam=repDBO.getParams();
	Connection connection = client.connect(mapParam.get(HybridConstants.SMBJ_HOST).trim());
	return connection;
}
```

- Now, in each operations (test connection / upload file /download file /rename file) I called this method at first to get connection.  And if you observer, Here for each operation, one new Object of SMBClient will be created every time. 
- So can I make it **singleton**? 

**Note: And my Application will have bulk simultaneous operations with SMBJ.** 

Please suggest. 

Thanks
Nirav Raval

**Comment by hierynomus** [comment]
Hi Nirav,

Yes this is possible. SMBJ will try to minimize the number of connections and sessions per connection by reusing them where possible. The only state the SMBClient instance maintains is the connection cache, which is threadsafe.

**Comment by niravravalhighq** [comment]
Ok @hierynomus.

- So I will make make **SMBClient** Object as **Singleton** and will reuse for each new connection for each file operation.
- And as you said, it will work.

Thanks a lot.
I will change the code for same and will update soon.

Thanks
Nirav Raval
