### ISSUE TITLE
Can you please provide set of properties which I need to set for SMBJ Connection like socket timeout, responseTimeOut and  sessionLimit - which was supported by JCIFS?

### ISSUE THREAD

**Issue by niravravalhighq** [hierynomus/smbj#281]
Hi @hierynomus  / @pepijnve ,
You have done wonderful job by implementing SMB protocol with Java. I have use it and check that almost all the operation which JCIFS supported is also support with SMBJ library.

I am doing migration of my code from JCIFS to SMBJ and where I found some properties which was set in JCIFS code and same also I need to integrate in my new SMBJ code to make application working without any break.

**Below are those properties:**
- jcifs.smb.client.soTimeout - use to set Socket Time out
- jcifs.smb.client.responseTimeout - use to set Response Time out
- jcifs.smb.client.ssnLimit - use to set Maximum Session Limit

Out of above, I come up with below one property which may serve the **jcifs.smb.client.soTimeout**. Correct me if I am wrong.
`SmbConfig config = SmbConfig.builder() .withSoTimeout("35000");`

So please provide other two properties for SMBJ library.

Thanks,
Nirav Raval

**Comment by niravravalhighq** [comment]
Hi, @hierynomus  / @pepijnve ,

Please help in this case. We need to roll out changes in Live server and this thing only is remaining.

Thanks,
Nirav Raval

**Comment by pepijnve** [comment]
@niravravalhighq sorry that's just not how this works. I contribute my spare time for free to this project; that doesn't mean I implement features on command.
If you need this functionality urgently, you're welcome to contribute the necessary changes in a pull request and I'm sure @hierynomus will be happy to integrate them.

**Comment by hierynomus** [comment]
@pepijnve is right! Also to add to that, I build and maintain this in my spare time. I also do not get paid directly for this. Both Pepijn and myself use the library at our respective employers products, but maintaining SMBJ is not part of the day job.

To answer part of your question, you can set the read/write/transact timeouts, those should be pretty similar to what JCIFS offered as responseTimeout. There is no notion of a session limit in SMBJ. If you can give me a good usecase as to why this should be part of the library, and a decent implementation, I'm more than happy to merge it.

**Comment by niravravalhighq** [comment]
Sorry Mate for my comment. But I am very much appreciate your efforts for such a great work.

**Comment by hierynomus** [comment]
@niravravalhighq Unless there are other questions, or you can provide a good usecase, I'm inclined to close this PR...

**Comment by niravravalhighq** [comment]
ok.
