### ISSUE TITLE
Can I build by java6?

### ISSUE THREAD

**Issue by demisstif** [hierynomus/smbj#284]
The server'jdk is 6, I can't use. The ReadMe show should use java7 to build, Can I build by java6?
Thank you

**Comment by hierynomus** [comment]
No, requirements are java7 and higher.

**Comment by demisstif** [comment]
when I wirte
`SmbConfig cfg = SmbConfig.builder().
                withMultiProtocolNegotiate(true).
                withSecurityProvider(new JceSecurityProvider(new BouncyCastleProvider())).
                build();`, I found I can use it in local dev with java6.
but in server it not work, so **Can I use it with jdk6 in project?** Thank you

**Comment by hierynomus** [comment]
Tue project is compiled with java7, so you will get unsupported class
version errors. So no, running on java6 is not supported.

Op 29 jan. 2018 9:11 a.m. schreef "demisstif" <notifications@github.com>:

**Comment by demisstif** [comment]
Thanks , I have to find another jar.
