### ISSUE TITLE
File sparseness

### ISSUE THREAD

**Issue by goroskob** [hierynomus/smbj#288]
There is a way to create sparse file if host filesystem supports it by using FileAttributes#FILE_ATTRIBUTE_SPARSE_FILE attribute. Is there a way to check existing file sparseness?

**Comment by pepijnve** [comment]
I would assume you can read back the same value by querying the file attributes using the `getFileInformation` method. The `FileBasicInformation` information class contains the attributes.

Actually punching holes and querying existing holes is done using FSCTL requests. See [FSCTL_SET_ZERO_DATA](https://msdn.microsoft.com/en-us/library/cc232053.aspx) and [FSCTL_QUERY_ALLOCATED_RANGES](https://msdn.microsoft.com/en-us/library/cc232035.aspx) for details.

Support for that isn't provided in smbj itself yet, but you can send these request from your application using the low-level `ioctl` methods. See `DiskEntry#ioctl`. You'll need to use the `ctlCode` values from [the MS-FSCC spec](https://msdn.microsoft.com/en-us/library/cc232013.aspx) and set the `isFsCtl` flag to `true`. Binary encoding of the requests and response is as per the `FSCTL_...` links above.

**Comment by hierynomus** [comment]
You beat me to it @pepijnve. Indeed the `FileBasicInformation` allows you to query the `FileAttributes`. 

```java
FileBasicInformation info = file.getFileInformation(FileBasicInformation.class);
EnumWithValue.EnumUtils.isSet(info.getFileAttributes(), FileAttributes.FILE_ATTRIBUTE_SPARSE_FILE);
```

**Comment by goroskob** [comment]
Thank you, you're the best guys
