### ISSUE TITLE
Error Reading Directories, STATUS_INSUFFICIENT_RESOURCES

### ISSUE THREAD

**Issue by obit91** [hierynomus/smbj#289]
Hello.
I'm accessing a share using SMB2 protocol and attempting to read a few thousand directories.
Upon reading the 1025th directory, I'm getting a "STATUS_INSUFFICIENT_RESOURCES(3221225626/3221225626)" error. I tried using .withNegotiatedBufferSize() since it seems to be using the maximum size, yet I'm still getting the error.
Would really appreciate some help.
This is the way I access a directory on the share:
```
private static DiskEntry parseDir(String pathOnShare, DiskShare share) {
	String innerPath = Samba.removeSMBPathPrefix(pathOnShare, share);
	Set<AccessMask> accessMasks = new HashSet<>(EnumSet.of(AccessMask.FILE_READ_DATA, AccessMask.FILE_READ_ATTRIBUTES, AccessMask.FILE_READ_EA, AccessMask.SYNCHRONIZE, AccessMask.FILE_LIST_DIRECTORY));
	Set<SMB2ShareAccess> shareAccess = new HashSet<>(EnumSet.of(SMB2ShareAccess.FILE_SHARE_READ, SMB2ShareAccess.FILE_SHARE_WRITE, SMB2ShareAccess.FILE_SHARE_DELETE));
	Set<SMB2CreateOptions> createOptions = new HashSet<>(EnumSet.of(SMB2CreateOptions.FILE_DIRECTORY_FILE));
	return share.openDirectory(innerPath, accessMasks, null, shareAccess, SMB2CreateDisposition.FILE_OPEN,
		createOptions);
    }
```
Thanks.

**Comment by hierynomus** [comment]
You're running out of file handles. You need to close the opened
directories.

Op 11 feb. 2018 11:54 schreef "obit91" <notifications@github.com>:

**Comment by obit91** [comment]
(1024 did seem to be a magic number set somewhere and ringed a few bells).
Is there any way for me to set the handles on my own? I access the files simultaneously.
Thank you for the quick reply.

P.S
Is there a real issue with opening multiple directories? or is the limit just a default..?

**Comment by hierynomus** [comment]
The limit is determined by the server. So the library has no control over
this. I would advise you to rethink the strategy. Is it really necessary to
keep all the file handles open?

Op 11 feb. 2018 19:17 schreef "obit91" <notifications@github.com>:

**Comment by obit91** [comment]
Prior to asking I had revised my code to be more efficient and name based instead of actual directory instances.
Was just curious regarding the reason behind the error and wanted to assure that programmers won't fall in this pitfall.
Moreover, I was wondering what's the difference between the way Windows 10 accesses the Share compared to SMBJ since browsing it manually works. Might you be familiar with it? I recorded some packets but didn't really delve into the main difference.
Thanks a bunch and have a great week!

**Comment by hierynomus** [comment]
When browsing using the Explorer, Windows will actually send `SMB2_CLOSE` requests to prevent this exact problem. When programming against SMB using SMBJ, you are in control of opening/closing. Same as with programming other file systems.

**Comment by obit91** [comment]
Thanks mate, have a great week!
