### ISSUE TITLE
Issue with Credits when uploading large file

### ISSUE THREAD

**Issue by sbellan** [hierynomus/smbj#29]
Looks like Windows 2012 servers in DC mode, is granting clients only up to a max of 128 credits at any given time. When upload a large file, the negotiated maxWriteSize is 8M, but for 8M we need 128 ((payLoadSize - 1)/65536) + 1) credits, but since we want keep at least 1 credit, we reduce the credits by 1 to 127. But this is not enough to send 8M payload and call fails with INVALID_PARAMETER. 

Windows 2012 server in non DC mode, does not seem to have the 128 limit.

**Comment by hierynomus** [comment]
Yes, I think I know what is wrong, was looking at the Multicredit stuff yesterday. Will see whether I can fix this tomorrow.

**Comment by hierynomus** [comment]
@sbellan Can you check branch https://github.com/hierynomus/smbj/tree/issue-29 and see whether that fixes the issue?

**Comment by sbellan** [comment]
@hierynomus I think I still got the same error. Wireshark packet capture attached. I'm running the SmbJTest.testBasic against a AD server which has got signatures enabled. (I had to make small change in DiskShare.java, where we were still calling connection.send to session.send)


[issue-29.zip](https://github.com/hierynomus/smbj/files/586778/issue-29.zip)
