### ISSUE TITLE
How to get the file name and how to read only files/directories

### ISSUE THREAD

**Issue by swaechter** [hierynomus/smbj#290]
I was looking for a JCIFS replacement and was really impressed by the smbj project and glad & relieved to see that there is a usable & well maintained JCIFS replacement. We knew that JCIFS is more or less a ticking time bomb & a dead end.

The company I work for provides an SMB explorer as website, similar to the Windows explorer. Hence, we wrote a File/Directory wrapper for JCIFS. I wanted to do the same thing for smbj but had a few problems/questions and would be glad for your input and feedback.

1.) What is the fastest and most reliable way to get the file name (and not the disk share path) of a directory/file?

Example: Samba Server `127.0.0.1` with Share `MyShare`:

```
/Dir1Dir2/MyFile.txt --> MyFile.txt
/Dir1/Dir2 --> Dir2
```

My first approach was to split the path for backslashes and use the last part. This works, but is problematic because a file/directory name in Samba (I guess in general) can contain backslashes (MyFile_backslash_\\_Name.txt).

Another approach would be to use DiskShare.list(path) and loop over all items and get the file name via FileIdBothDirectoryInformation.getFileName(). This requires a different handling for files and directories and is not really performance friendly

Another approach I wasn't able to use because the full path is returned is this one:

```
FileAllInformation fileAllInformation = diskShare.getFileInformation(smbPath.getPath());
String fileName = fileAllInformation.getNameInformation();
```
2.) What is the right way to only list directory or only files (aka non directories)? This code returns directories and files (Not only directories)? Do I use the API the wrong way?
```
Set<FileAttributes> fileAttributes = new HashSet<>();
fileAttributes.add(FileAttributes.FILE_ATTRIBUTE_DIRECTORY);
Directory directory = diskShare.openDirectory("", EnumSet.of(AccessMask.GENERIC_ALL), fileAttributes, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN_IF, null);
for (FileIdBothDirectoryInformation fileIdBothDirectoryInformation : directory.list()) {
    System.out.println(fileIdBothDirectoryInformation.getFileName());
}
```
Background: The idea is to improve the implementation of getDirectories/getFiles in https://github.com/swaechter/smbjwrapper/blob/master/src/main/java/ch/swaechter/smbjwrapper/SharedDirectory.java#L70

Again: Thank you very much for this modern & maintained SMB library. Keep up the work. Finally no sleepless nights due security issues :)

**Comment by swaechter** [comment]
Hey there, any thoughts on this?

Best,
Simon

**Comment by pepijnve** [comment]
> My first approach was to split the path for backslashes and use the last part. This works, but is problematic because a file/directory name in Samba (I guess in general) can contain backslashes (MyFile_backslash_\_Name.txt).

Backslash is the path component separator in SMB (see https://msdn.microsoft.com/en-us/library/cc422524.aspx). SMB servers should never return a filename or directory containing a backslash.

> What is the right way to only list directory or only files (aka non directories)? This code returns directories and files (Not only directories)? Do I use the API the wrong way?

I think you're using it wrong. Or at least trying to use parameters for something they're not intended for. The attributes that are passed to `open` provide a constraint on the type of file system object you're trying to open. In your example, the presence of `FILE_ATTRIBUTE_DIRECTORY` will cause an error when the path does not actually refer to a directory.

As far as I know there's no way to do what you're asking for in the SMB protocol itself. You pretty much have to do a normal listing and filter out the entries you're not interested in using the attributes contained in the `FileIdBothDirectoryInformation` object.
You could improve your code a little bit by using a common method that takes a `Predicate<FileIdBothDirectoryInformation>` parameter, but that will only remove the code duplication. Besides that there's no better way to do this that I know of.

**Comment by swaechter** [comment]
> Backslash is the path component separator in SMB (see https://msdn.microsoft.com/en-us/library/cc422524.aspx). SMB servers should never return a filename or directory containing a backslash.

Thank you. I created a file/directory with an illegal character on a local file system and created a local share. The file name is encoded (Mangled?), so no harm at all.

> I think you're using it wrong. Or at least trying to use parameters for something they're not intended for. The attributes that are passed to open provide a constraint on the type of file system object you're trying to open. In your example, the presence of FILE_ATTRIBUTE_DIRECTORY will cause an error when the path does not actually refer to a directory.

Yes, I had something wrong in mind. I refactored the method and now use a predicate on `FileAllInformation`.

So I am going to close this issue :)
