### ISSUE TITLE
QUESTION: How to create file on network disk using your lib?

### ISSUE THREAD

**Issue by penguinInSpring** [hierynomus/smbj#291]
Hey,
thank you for the interesting lib! I stumbled across it while searching for good ways to connect to a network drive independent from the system calling. So far, I successfully connected to my network drive and were able to read the files in a specific folder (thank you for the examples given). I am wondering though, how I would proceed actually writing a new file. I am rather new to Java and this is my first try to write to a secured network.
I thought it might be done with 
DiskShare share ....
share.ioctl(...),
but I am not sure what to put into "ctlCode" as it must be a long. Google hasn't helped me out on this one, so I would be really glad if you could help me with some input.
I've also seen that in the method open(...) the private method createFileAndResolve() is called. Would that be a better approach? I am also stumbling about some of the arguments there.
Thank you for your answer!

**Comment by hierynomus** [comment]
Creating a new file is as simple as calling `DiskShare.open` file with `SMB2CreateDisposition.FILE_CREATE` set, and then writing to the returned file handle using one of the `write` or `getOutputStream` methods.
