### ISSUE TITLE
Question: Creating multiple directories 

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#296]
Hi,  
  How is creating multiple directories supposed to work? I have tried DiskShare.mkdir() but it works only for one directory, for example "dir1". If I want to create something like mkdir("dir1/dir2") it does not work. 

   Thanks !

**Comment by pepijnve** [comment]
`mkdir` does what the command of the same name does without the `-p` option. You need to make sure all parent directories exist before you can create a subdirectory.

Not that in SMB you must always use `\` as separator; not `/`.

**Comment by cliviu** [comment]
Thanks, I will try it.

**Comment by cliviu** [comment]
It worked, thanks !

**Comment by satya081** [comment]
@cliviu Could you please share me the code here how you created directories and subdirectories using SMBJ library?

**Comment by hierynomus** [comment]
[`SmbFiles.](https://github.com/hierynomus/smbj/blob/8224c1aebce8aace3827dd5229cbdc7d1149b84a/src/main/java/com/hierynomus/smbj/utils/SmbFiles.java#L71)

**Comment by hierynomus** [comment]
It's part of SMBJ already ;)

**Comment by mzatko** [comment]
Why aren't SmbFiles.mkdirs methods static? The same as SmbFiles.copy
