### ISSUE TITLE
Question: How to deal with special characters in password ?

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#297]
Hi,
 My password contains special characters like :  @/%.  The authentication fails. 
I have tried to encode the special characters in password when passing to the API (%40%2F%25 )but with no success. Any ideas  ? 
  Thanks !

**Comment by hierynomus** [comment]
The library itself just adds the unicode bytes of your password to an MD4 digest needed for the NTLM authentication. It really doesn't care about "special" characters. My guess is that your client code interprets them?

**Comment by hierynomus** [comment]
@cliviu Is this solved already?

**Comment by cliviu** [comment]
yes, I will close it, thanks
