### ISSUE TITLE
Creating a file on DFS share needs explicit resolving

### ISSUE THREAD

**Issue by jborza** [hierynomus/smbj#302]
Hi,
Using smbj 0.6.0 with dfsEnabled(true) I still need to resolve DFS paths manually as I'm getting a STATUS_PATH_NOT_COVERED on my attempts to open a file.

Using a setup (`\\dc` as the root, `\\dc\dfs\share\link` pointing to server1), I connect as in example 1 on smbj main page:

```
    try (Connection connection = client.connect("dc")) {
        AuthenticationContext ac = new AuthenticationContext("USERNAME", "PASSWORD".toCharArray(), "DOMAIN");
        Session session = connection.authenticate(ac);

        // Connect to Share
        try (DiskShare share = (DiskShare) session.connectShare("dfs")) {
            for (FileIdBothDirectoryInformation f : share.list("share\link", "*.txt")) {
                System.out.println("File : " + f.getFileName());
            }
        }
    }
```
I'm getting a `STATUS_PATH_NOT_COVERED`, so the current implementation of `DiskShare.createFileAndResolve` https://github.com/hierynomus/smbj/blob/99b79eb4900f1afc8d7eae7df532ed209ce0b2c9/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L79 throws an exception at that first line.

The same happens with opening a file for reading / write, as it all goes through the same `DiskShare.createFileAndResolve` private method.

As a workaround I need to manually create a `SmbResponsePacket` with status `STATUS_PATH_NOT_COVERED`, and use the `DFSPathResolver` in the same way `createFileAndResolve` attempts to resolve the path. 

I'm guessing that the DFS root I'm initially connecting to with the `connectShare` should be able to tell me what the target path is resolved to.

I suspect there must be something I'm missing as the code from smbj 0.6.0 seems to do some resolution with `createFileAndResolve`, but it fails in this case.

**Comment by andershermansen** [comment]
You are sure you have enabled DFS support correctly?

I'm doing it like this:
```
        SmbConfig smbConfig = SmbConfig.builder().withDfsEnabled(true).build();
        SMBClient client = new SMBClient(smbConfig);
```

Also you should see something like this in the log output when DFS is enabled:
`c.h.smbj.paths.DFSPathResolver - DFS Share myshare does not cover XXX, resolve through DFS`

**Comment by jborza** [comment]
Hi, 
@andershermansen yes - my bad, I was fiddling with the configuration and code so much that this seemed to disappear somehow.
