### ISSUE TITLE
How to get the SMB protocol commands

### ISSUE THREAD

**Issue by bsanastasov** [hierynomus/smbj#305]
Hi @hierynomus . I am using smbj mostly fot uploading and downloading files and I need to know which protocol command is used by the time of calling it. I make connection, session but I cannot see where I can get the MessageCommandCode. Do you know how can I get it? Thanks in advance :)

**Comment by hierynomus** [comment]
Can you send a piece of sample code to show where you're stuck? You shouldn't need the messagecommandcodes.

**Comment by bsanastasov** [comment]
try (DiskShare diskShare = (DiskShare) mSession.connectShare(share)) {
            filePath = addSeparator(filePath);
            String smbFilePath = new StringBuilder().append(filePath).append(fileName).toString();
            if (diskShare.fileExists(smbFilePath)) {
                File smbFile = diskShare.openFile(smbFilePath, EnumSet.of(AccessMask.GENERIC_READ), null,
                        SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null);
                
Here for example. After this operation can I get the MessageCommandCode without creating various SMB2Packet? Because as much as I've seen I need SMBHeader to get MessageCommandCode and I need a class, extending SMB2Packet to get this SMBHeader.

**Comment by pepijnve** [comment]
It's not clear to me what you're trying to achieve exactly. What do you need the `SMB2MessageCommandCode` values for?

If you're interested in what's being sent over the wire and don't really need the data in your code, packet capture and analysis is the simplest solution. [Wireshark](https://www.wireshark.org) has a builtin SMB2 protocol dissector that shows you the internal structure and values of SMB2 messages.

If you really need to intercept the messages that are being sent out in code, then your best option is probably to implement a decorating `com.hierynomus.smbj.transport.TransportLayerFactory`. That would allow you to inject a decorating `com.hierynomus.protocol.transport.PacketSerializer`. That last class will receive all outgoing SMB packets from which you can extract the header and message command codes.

**Comment by bsanastasov** [comment]
I need these commands to log appropriate information, containing them. Thanks

**Comment by hierynomus** [comment]
Still not sure what you want to achieve @bsanastasov. What is the usecase you're trying to solve?

**Comment by hierynomus** [comment]
Closing this due to lack of response.
