### ISSUE TITLE
STATUS_OBJECT_NAME_INVALID(3221225523/3221225523) error when try to access a DFS folder

### ISSUE THREAD

**Issue by stefmartin** [hierynomus/smbj#306]
Hi,
I'm upgrading some utility class and replace jcifs with smbj but I have an issue when I try to access a DFS folder.

```
public static Share connect(String host, String share, AuthenticationContext authContext) throws Exception {
		String methodName  = new Exception().getStackTrace()[0].getMethodName();		
		if (isDebug) {
			System.out.println( "BEGIN - " + methodName);
		}
		SmbConfig config = SmbConfig.builder()
			.withMultiProtocolNegotiate(true)
			.withSigningRequired(true)
			.withDfsEnabled(true)
			.build();
		SMBClient client = new SMBClient(config);
		if (isDebug) {
			System.out.println( "   host: " + host);
			System.out.println( "   share: " + share);
		}
		Connection connection = client.connect(host);
		Session session = connection.authenticate(authContext);
		if (isDebug) {
			System.out.println( "END - " + methodName);
		}
		return session.connectShare(share);
	}
	
	private static void getSmbContent(String host, String share, String filePath, AuthenticationContext auth) throws Exception {
		String methodName  = new Exception().getStackTrace()[0].getMethodName();
		if (isDebug) {
			System.out.println( "BEGIN - " + methodName);
		}
		DiskShare diskShare = (DiskShare) connect(host, share, auth);
		System.out.println("isDfsShare: " + diskShare.getTreeConnect().isDfsShare());		
		System.out.println( "Does " + filePath + " exists? " + diskShare.folderExists(filePath) + ". Here the content:");
		for (FileIdBothDirectoryInformation f : diskShare.list(filePath, "*.*")) {
			System.out.println("   "  + f.getFileName());
		}
		if (isDebug) {
			System.out.println( "END - " + methodName);
		}
	}
```

Here the log:
BEGIN - getSmbContent
BEGIN - connect
   host: bio.corpnet1.com
   share: apps
END - connect
isDfsShare: true
com.hierynomus.mssmb2.SMBApiException: STATUS_OBJECT_NAME_INVALID(3221225523/3221225523): Create failed for /LbwExchange/1_Developpement/Documentum/temp
	at com.hierynomus.smbj.share.Share.receive(Share.java:342)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:322)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:135)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:79)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:69)
	at com.hierynomus.smbj.share.DiskShare.exists(DiskShare.java:169)
	at com.hierynomus.smbj.share.DiskShare.folderExists(DiskShare.java:165)
	at com.gskbio.smb.TESTSmb.getSmbContent(TESTSmb.java:88)
	at com.gskbio.smb.TESTSmb.main(TESTSmb.java:40)

Any idea of what could be the problem?
Thx
Stefano

**Comment by stefmartin** [comment]
Hi,
I have found the issue, the filePath of the folder must have back slash instead of slash .
with  filePath = "LbwExchange\\1_Developpement\\Documentum\\temp" it works 
with  filePath = "LbwExchange/1_Developpement/Documentum/temp"  it doesn't.

Stefano

**Comment by pepijnve** [comment]
@hierynomus '/' is not allowed in filenames (see [MS-FSCC 2.1.5.2](https://msdn.microsoft.com/en-us/library/ff469917.aspx), so it should be safe to do a `replace('/', '\\')` on paths in the high level parts of the library (e.g., `DiskShare#open`). That would eliminate this silly pitfall. Good idea?

**Comment by stefmartin** [comment]
Yes it was exactly this.
I closed the issue.

Thanks
Stefano
