### ISSUE TITLE
How can get the ACL properties(domain name and account name)  from the SID

### ISSUE THREAD

**Issue by rahulgangarde** [hierynomus/smbj#309]
File smbFile = //
                        Set<SecurityInformation> securityInfo = new HashSet<>();
			 securityInfo.add(SecurityInformation.GROUP_SECURITY_INFORMATION);
			 securityInfo.add(SecurityInformation.OWNER_SECURITY_INFORMATION);
			 securityInfo.add(SecurityInformation.DACL_SECURITY_INFORMATION);
		         SecurityDescriptor securityInformation = smbFile.getSecurityInformation(securityInfo);
			 ACL dacl = securityInformation.getDacl();
			 List<ACE> aces = dacl.getAces();
			 for(ACE ace : aces) {
				SID sid = ace.getSid();//here 
                                //System.out.println(sid.getDomainName() + " "+ sid.getAccountName());
				
				byte[] clone = sid.getSidIdentifierAuthority().clone();
				System.out.println(new String(clone).toString());
			 }

How can get the ACL properties(domain name and account name)  from the SID like we are getting in the **jcifs** 
below is the jcifs code

                 SmbFile  jcifsSmbfile
                   ACE[] acl = jcifsSmbfile.getSecurity();
			for (ACE ace : acl) {
				SID sid = ace.getSID();
				System.out.println(sid.getDomainName() + "  " + sid.getAccountName());
			}

**Comment by pepijnve** [comment]
This is also something that's not part of SMB itself. A SID does not contain the domain or account name, it only contains the binary identifier of the account. To translate it to a name you need to perform an RPC call; something that smbj doesn't provide out of the box at the moment.

You can use https://github.com/rapid7/smbj-rpc/blob/master/src/main/java/com/rapid7/client/dcerpc/mslsad/LocalSecurityAuthorityService.java to do this though. Have a look at `lookupNamesForSIDs` specifically.

**Comment by rahulgangarde** [comment]
I have tried with the smbj-rpc code but  getting below exception. I don't have much knowledge of this so could you please help me to resolve the below exception

com.rapid7.client.dcerpc.transport.exceptions.RPCFaultException: Fault: nca_op_rng_error (0x1C010002)
	at com.rapid7.client.dcerpc.transport.exceptions.RPCFaultException.read(RPCFaultException.java:42)
	at com.rapid7.client.dcerpc.transport.RPCTransport.call(RPCTransport.java:111)
	at com.rapid7.client.dcerpc.service.Service.call(Service.java:46)
	at com.rapid7.client.dcerpc.service.Service.callExpect(Service.java:55)
	at com.rapid7.client.dcerpc.service.Service.callExpectSuccess(Service.java:50)
	at com.rapid7.client.dcerpc.mssamr.SecurityAccountManagerService.openServer(SecurityAccountManagerService.java:151)
	at com.rapid7.client.dcerpc.mssamr.SecurityAccountManagerService.openServer(SecurityAccountManagerService.java:137)
	at com.rapid7.client.dcerpc.mssamr.SecurityAccountManagerService.openServer(SecurityAccountManagerService.java:125)
	at test.Test.main(Test.java:85)

**Comment by pepijnve** [comment]
You'll have to ask the smbj-rpc developers about this. According to http://pubs.opengroup.org/onlinepubs/9629399/apdxe.htm that error means

> The operation number passed in the request PDU is greater than or equal to the number of operations in the interface.

but I can't tell you much more than that myself either.

**Comment by hierynomus** [comment]
Closing this as it pertains to smbj-rpc.
