### ISSUE TITLE
Share sessions

### ISSUE THREAD

**Issue by mreiterer** [hierynomus/smbj#312]
As is saw in the implementation the Connection instances are shared/cached within the SMBClient.

When i authenticate on a connection i get a Session instance. Is there any reason i should not cache / re-use session instances ? I saw that the open sessions are kept in a private member of the Connection (sessionTable) to be able to close all the sessions when the connection is closed.
But everytime "authenticate" is called on the connection a new session is created.

Does a session has a timeout ? 

I have a service class which encapsulates the smbj library and gives me for istance an OutputStream of a remote file. Questions is when to close the underlying session / share ... 

Thanks for the answer,
Markus

**Comment by mreiterer** [comment]
Maybe my question was not precise enough.

Can i safely re-use sessions, is a session object thread-safe ? Thanks for your answer.

**Comment by hierynomus** [comment]
Hi Markus, I think this should be possible. I'd have to check to make sure

**Comment by hierynomus** [comment]
Hi Markus, the Session can be shared, also the spec is in accordance with that usecase.
