### ISSUE TITLE
Question: Why some field is ignored on SMB2CreateResponse?

### ISSUE THREAD

**Issue by yin19941005** [hierynomus/smbj#314]
I am currently working with smbj library and required the [`CreateAction`](https://github.com/hierynomus/smbj/blob/df2d1bdfd28766030b91db86daad32f9c1be785b/src/main/java/com/hierynomus/mssmb2/messages/SMB2CreateResponse.java#L47) field on the SMB2CreateResponse to complete my task. 

I am wondering is it simply not yet implemented or it got some reasons, such as dialect related issue, to ignored it for now. If it just simply not yet implemented, then maybe I could help to implement it.

Thanks in advance.

**Comment by pepijnve** [comment]
I don't think there's any particular reason that this was omitted other than that it takes some work to define an enum for this, add the field, etc. Simply the current state of the code. I'm pretty sure a patch that adds this would get accepted quickly.

**Comment by yin19941005** [comment]
Hi @pepijnve ,

Thank you for your reply! I just added the enum and commited for this issue. Thanks a lot!
