### ISSUE TITLE
help wanted integrating library

### ISSUE THREAD

**Issue by andreasql** [hierynomus/smbj#321]
hi All,
If this is not the right place to ask for usage, please kindly redirect me to the appropriate one... :)

I'm actually a Visual Studio dev and I'm unfortunately not that familiar with Android Studio, but I'm in charge to produce PDF documents on android devices and transfer them to Windows shares... 
the pdf task is already up and running, using KitKat's PdfDocument implementation... now I've to find the way to transfer those generated files from device's local storage to the designed windows share...
In the past I already used jcifs jar lib, but it seems jcifs is unable to work over smb2, so I have seen reference to this library on StackOverflow that should overcome that issue...
I downloaded smbj-0.6.0.jar from maven and referenced it in the Android Studio project...
the build.gradle (Module: app) looks like
apply plugin: 'com.android.application'
<pre>
android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.insulinpower.amsigntool"
        minSdkVersion 19
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation files('src/main/java/com/insulinpower/amsigntool/libs/jcifs-1.3.19.jar')
    implementation files('src/main/java/com/insulinpower/amsigntool/libs/smbj-0.6.0.jar')
}
</pre>

the apps compiles without troubles...
I'm running my simple trivial test in an asynctask, looking like
<pre>
......
try {
   SMBClient client = new SMBClient();

   AuthenticationContext authenticationContext = null;
   Connection connection = client.connect(serverName);

   if (TextUtils.isEmpty(this.m_Params.serverSetting.serverUser)) {
      authenticationContext = new AuthenticationContext("", new char[0], null);
   } else {
      authenticationContext = new AuthenticationContext(this.m_Params.serverSetting.serverUser, this.m_Params.serverSetting.serverPwd.toCharArray(), this.m_Params.serverSetting.serverDomain);
   }

   Session session = connection.authenticate(authenticationContext);

   try {
      DiskShare share = (DiskShare) session.connectShare(shareName);
      if ( !share.isConnected() ) {
         throw new Exception(this.m_Context.getString(R.string.ERR_SHARE_Unavailable));
      }
      for(int loop=0; loop < m_Params.allFiles.size(); loop++){
         String fileCurrentName = m_Params.allFiles.get(loop);
         this.m_processedFile = fileCurrentName;

         File fileIn = new File(dirOut.getCanonicalPath(), fileCurrentName);
         //https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/utils/SmbFiles.java
         try{
            int writtenB = SmbFiles.copy(fileIn, share, fileCurrentName, true);
            // TODO; have to compare writtenB with original byte len of fileIn
            this.m_Params.is_Success = true;
         }
         catch (Exception e){
            this.m_Params.is_Success = false;
            this.m_Params.Exception  += "\n\n" + e.getMessage();
         }
         
         if ( !this.m_Params.is_Success ){
            // break??
            break;
         }
      }
      session.close();
      connection.close(true);

   } catch (Exception e) {
      if (session != null){
         session = null;
      }
      if ((connection != null) && (connection.isConnected())){
         connection.close(true);
      }
      connection =  null;

      this.m_Params.is_Success = false;
      throw new Exception(e);
   }
} catch (Exception e) {
   this.m_Params.is_Success = false;
   this.m_Params.Exception += "\n\n" + e.getMessage();
}
</pre>

but I'm having troubles in the very first smbobj invocation, 
SMBClient client = new SMBClient();

which results, in debug mode, opening the Android Studio AsyncTask.class window indicating "Decompiled .class file, bytecode version: 52,0 (Java8) - Source code for 'Android API 26 Platform' not found."
and in the "variable" pane "this" is set for it's outcome as "java.lang.NoClassDefFoundError: org.slf4j.LoggerFactory"

I'm out of idea on how to work it around, even more becouse I'm not that confident with Android Studio...
any hint would be very appreciated :D

thank you in advance for your kind support, and please excuse my poor english and my lack of expertise...
Andrea

**Comment by andreasql** [comment]
Hi, and thank you for your input...
Can you please help referencing the library from maven and not directly as I did, with reference to the provided build.gradle?
Or suggesting what other have I to do? 
TIA
Andrea

**Comment by pepijnve** [comment]
I would suggest the following changes:

* Move `src/main/java/com/insulinpower/amsigntool/libs/jcifs-1.3.19.jar` to the `libs` folder at the root of your project. `src/main/java` should only contain `.java` files; better to store local libraries somewhere else.
* Delete the line `implementation files('src/main/java/com/insulinpower/amsigntool/libs/jcifs-1.3.19.jar')` from `build.gradle`. 
* Delete `src/main/java/com/insulinpower/amsigntool/libs/smbj-0.6.0.jar`
* Replace the line `implementation files('src/main/java/com/insulinpower/amsigntool/libs/smbj-0.6.0.jar')` in `build.gradle` with `implementation 'com.hierynomus:smbj:0.6.0'`
* Add `implementation 'de.psdev.slf4j-android-logger:slf4j-android-logger:1.0.5'` in the `dependencies` section of `build.gradle`.

**Comment by andreasql** [comment]
hi Pepijin,
thnk you for your time, I really appreciate it.. but it still fails...

dev machine with Android Studio 3.1.2
Java SE Development Kit 8 Update 31
Java 8 Update 31

java - version:
java version "1.8.0_45"
Java (tm) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot (tm) 64-Bit Server VM (build 25.45-b2, mixed mode)

my current scenario is a Windows WorkGroup with NO limitation to the involved Share, ok, not safe, but at time of writing "everyone" has full control...
the connection setting is this way implied to grant connection without providing UserName and Password to log in, so
authenticationContext = new AuthenticationContext("", new char[0], null);
runs...

but, after having my project little redefined in it's setting, it still fails...

"repro":
<----------->
<pre>
SmbConfig config = SmbConfig.builder()
     .withTimeout(5, TimeUnit.SECONDS) // Timeout sets Read, Write, and Transact timeouts (default is 60 seconds)
     .withSoTimeout(5, TimeUnit.SECONDS) // Socket Timeout (default is 0 seconds, blocks forever)
     .build();


try {
   SMBClient client = new SMBClient(config);

   AuthenticationContext authenticationContext = null;
   Connection connection = client.connect(serverName);

   if (TextUtils.isEmpty(this.m_Params.serverSetting.serverUser)) {
      authenticationContext = new AuthenticationContext("", new char[0], null);
   } else {
      authenticationContext = new AuthenticationContext(this.m_Params.serverSetting.serverUser, this.m_Params.serverSetting.serverPwd.toCharArray(), this.m_Params.serverSetting.serverDomain);
   }

   Session session = connection.authenticate(authenticationContext);    // <---- here it fails

   try {
      DiskShare share = (DiskShare) session.connectShare(shareName);
      if (!share.isConnected()) {
         throw new Exception(this.m_Context.getString(R.string.ERR_SHARE_Unavailable));
      }
      // files to upload
      for(int loop=0; loop < m_Params.allFiles.size(); loop++){
         String fileCurrentName = m_Params.allFiles.get(loop);
         // fileName to be shown in the ProgressDialog
         this.m_processedFile = fileCurrentName;

         File fileIn = new File(dirOut.getCanonicalPath(), fileCurrentName);

         if (loop > 0){
            // to clear and init a ProgressDialog
            onPreExecute();
         }
         //https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/utils/SmbFiles.java
         try{
            int writtenB = SmbFiles.copy(fileIn, share, fileCurrentName, true);
            //TODO check writtenB with original file size?
            
            this.m_Params.is_Success = true;
         }
         catch (Exception e){
            this.m_Params.is_Success = false;
            this.m_Params.Exception  += "\n\n" + e.toString();
         }

         if (loop < this.m_Params.allFiles.size()){
            // to show ProgressDialog END
            onPostExecute( this.m_Params);
         }
         else{
            this.m_Params.isEnd = true;
         }
         if (! this.m_Params.is_Success){
            // interrompe??
            break;
         }
      }
      session.close();
      connection.close(true);

   } catch (Exception e) {
      if (session != null){
         session = null;
      }
      if ((connection != null) && (connection.isConnected())){
         connection.close(true);
      }
      connection =  null;

      this.m_Params.is_Success = false;
      throw new Exception(e);
   }
} catch (Exception e) {
   this.m_Params.is_Success = false;
   this.m_Params.Exception = e.toString;
}
</pre>
<----------->

I tried before using a traditional AsyncTask, where I put all the preceeding code, but it now fails with with a "An error occured while executing doInBackground()" exception...

so I tried a very unfortunate alternative (knowing on before that Android would not like it) putting that code in a sync class method, and obviously the "android.os.NetworkOnMainThreadException" exception is thrown...
 

having a look at https://stackoverflow.com/questions/668788/android-java-lang-verifyerror I think the problem should rely on a discrepancy between my Android SDK version and the required one...
but... I'm having to support KitKat devices

gradle now is
<--------->
<pre>
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    defaultConfig {
        applicationId "com.insulinpower.amsigntool"
        minSdkVersion 19
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}


dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:25.0.1'
    implementation 'com.android.support:design:25.0.1'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    implementation 'com.hierynomus:smbj:0.6.0'
    implementation 'de.psdev.slf4j-android-logger:slf4j-android-logger:1.0.5'
}
</pre>
</--------->

I know this is quiet out of direct "smbj kind support" problem, but I'd welcome your hint, whenever possible
TIA
Andrea

**Comment by pepijnve** [comment]
@hierynomus not sure if you want to do this or not, but PR #327 makes the necessary changes to support Android API level 19 (KitKat / 4.4).

**Comment by hierynomus** [comment]
I'll release a new version. Try that to see whether it works (better)

**Comment by hierynomus** [comment]
Release 0.7.0 is available. It should now be compatible with android 19.

**Comment by andreasql** [comment]
hi All, and thank you for your support...
having a try with 0.7.0 as indicated but personally I still get exceptions...
and it fails in
Session session = connection.authenticate(authenticationContext); // <--- fails

<pre> 
SMBClient client = new SMBClient(config);

AuthenticationContext authenticationContext = null;
Connection connection = client.connect(serverName);
authenticationContext = new AuthenticationContext("", new char[0], null);

Session session = connection.authenticate(authenticationContext); // <--- fails
</pre>
opening AsyncTask.java
<pre>
public AsyncTask(){
    ......
    
    mFuture = new FutureTask<Result>(mWorker) {
            @Override
            protected void done() {
                try {
                    postResultIfNotInvoked(get());
                } catch (InterruptedException e) {
                    android.util.Log.w(LOG_TAG, e);
                } catch (ExecutionException e) {
                    throw new RuntimeException("An error occured while executing doInBackground()",
                            e.getCause());
                } catch (CancellationException e) {
                    postResultIfNotInvoked(null);
                }
            }
}
</pre>

here enclosed I prepared my trivial repro....
again:
dev machine with Android Studio 3.1.2
Java SE Development Kit 8 Update 31
Java 8 Update 31

java - version:
java version "1.8.0_45"
Java (tm) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot (tm) 64-Bit Server VM (build 25.45-b2, mixed mode)

my current scenario is a Windows WorkGroup with NO limitation to the involved Share, ok, not safe, but at time of writing "everyone" has full control...

the enclosed zip include a png of Android Studio variable monitor...
please create a directory in external storage /somedir and add some files to it; then modify GENERIC.getFlushArgs 'storagePath' as required and 'ServerName' accordingly to a Windows Share like '192.168.1.x/SomeShareName'.
Press Send button when ready, OR  NavBar ->Send menu item.

[andreaTest.zip](https://github.com/hierynomus/smbj/files/1975113/andreaTest.zip)

again, the prj is required to support KitKat, and is currenty debugged on a Samsung SM-T113 tablet running Android 4.4.4

and again, yes, I'm kinda newby in Android... I do not know if I shoud "dare" here, but I'm a Visual Studio and SQL Server developer :)
thank you for your support....
Andrea

**Comment by pepijnve** [comment]
FYI, you should be able to just copy/paste that from your logcat output on your computer. See https://developer.android.com/studio/debug/am-logcat

**Comment by andreasql** [comment]
hi All,
hope this is the info you required me to provide...

[.intent.action.TIME_TICK.txt](https://github.com/hierynomus/smbj/files/1976484/default.intent.action.TIME_TICK.txt)
![smbj error](https://user-images.githubusercontent.com/18520588/39661600-82818178-5054-11e8-8275-e3bc9de99e62.png)

thanking your for your time and patience.... :)
Andrea

**Comment by pepijnve** [comment]
> hope this is the info you required me to provide...

Unfortunately not really. Write the exception to the Android log like you're doing for the InterruptedException (i.e., `android.util.Log.e(LOG_TAG, e)`). That will print the error message and stack trace to the log.
Then copy paste the text of the stack trace from the logcat window. Just the relevant error; not the entire contents of logcat.

It will look something like this (this is a different error of course)

```
05-05 10:01:14.146 27629-27789/com.insulinpower.amsigntool I/Slf4jAndroidLogger: PacketReader error, got exception. [PacketReader:run:52] Thread[Packet Reader for 192.168.1.32,5,main]
    com.hierynomus.protocol.transport.TransportException: java.net.SocketTimeoutException
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:53)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)
        at java.lang.Thread.run(Thread.java:841)
     Caused by: java.net.SocketTimeoutException
        at java.net.PlainSocketImpl.read(PlainSocketImpl.java:491)
        at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
        at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:70)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
        at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
        at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)†
        at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)†
        at java.lang.Thread.run(Thread.java:841)†
```

Why is this necessary? It contains the essential information that someone else who doesn't know your code needs to be able to help you:
- The exact error message and type that's happening
- Exactly where in the code the error is happening

The are dozens of things that can potentially go wrong; without knowing what and where there's really no way to help.

**Comment by andreasql** [comment]
hi pepijnve,
I'm really sorry to be that imprepared in Android Studio....

I copyed what in the "Console" pane appeared...
[andrea1.txt](https://github.com/hierynomus/smbj/files/1976801/andrea1.txt)

that means "this" window pane
![andrea_console](https://user-images.githubusercontent.com/18520588/39664875-d0fa982c-508a-11e8-93a2-09846beb0d73.png)

**Comment by pepijnve** [comment]
I'm not really sure what's going on to be honest. The screenshot from May 5th seems to indicate there's still a VerifyError, which is a class loading issue. This image seems to indicate you're getting a network timeout error. Not sure which one it is.
Have you tried connecting to the same server using smbj using JavaSE on the desktop?

**Comment by pepijnve** [comment]
I did some experiments with an Android simulator. The short answer is that the default smbj configuration is still not usable on Android.

Adding the following bits to your code where you build the `SmbConfig` seems to be sufficient to get things working with 0.7.0.

```
.withAuthenticators(Arrays.<Factory.Named<Authenticator>>asList(new NtlmAuthenticator.Factory()))
.withSecurityProvider(new BCSecurityProvider())
```

**Comment by pepijnve** [comment]
@hierynomus I've created PR #329 with a slightly different approach that makes `getDefaultConfig()` return a usable config on Android. Makes the library 'just work'.

**Comment by andreasql** [comment]
hi All,
and thank you all for your support...
FWIW, tried again with 0.7.0 to get more info for you for trying helping you figure out where/what the problem is...

I put a breakpoint at the offending line in my code, 
<pre>
String serverName = "192.168.1.32";
String shareName = "My Valid Share With FullControl for Everyboy"; // shareName really contains blanks 
 
try {
   SMBClient client = new SMBClient(config);

   AuthenticationContext authenticationContext = null;
   Connection connection = client.connect(serverName);

   if (TextUtils.isEmpty(this.m_Params.serverSetting.serverUser)) {
      authenticationContext = new AuthenticationContext("", new char[0], null);
   } else {
      authenticationContext = new AuthenticationContext(this.m_Params.serverSetting.serverUser, this.m_Params.serverSetting.serverPwd.toCharArray(), this.m_Params.serverSetting.serverDomain);
   }

   Session session = connection.authenticate(authenticationContext);  //<---- OFFENDIGN LINE

   try {
      DiskShare share = (DiskShare) session.connectShare(shareName);
      .....
      
</pre>

and here I cleared LogCat before executing the offending line, then LogCat results in
<pre>
05-07 10:44:23.190 32254-32274/com.insulinpower.andreasmb I/dalvikvm: Could not find method org.ietf.jgss.GSSManager.getInstance, referenced from method com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession
05-07 10:44:23.190 32254-32274/com.insulinpower.andreasmb W/dalvikvm: VFY: unable to resolve static method 45470: Lorg/ietf/jgss/GSSManager;.getInstance ()Lorg/ietf/jgss/GSSManager;
05-07 10:44:23.190 32254-32274/com.insulinpower.andreasmb D/dalvikvm: VFY: replacing opcode 0x71 at 0x0018
05-07 10:44:23.200 32254-32274/com.insulinpower.andreasmb I/dalvikvm: Could not find method org.ietf.jgss.GSSContext.initSecContext, referenced from method com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession
05-07 10:44:23.200 32254-32274/com.insulinpower.andreasmb W/dalvikvm: VFY: unable to resolve interface method 45465: Lorg/ietf/jgss/GSSContext;.initSecContext ([BII)[B
05-07 10:44:23.200 32254-32274/com.insulinpower.andreasmb D/dalvikvm: VFY: replacing opcode 0x72 at 0x0059
05-07 10:44:23.200 32254-32274/com.insulinpower.andreasmb W/dalvikvm: VFY: unable to resolve exception class 6401 (Lorg/ietf/jgss/GSSException;)
    VFY: unable to find exception handler at addr 0x91
    VFY:  rejected Lcom/hierynomus/smbj/auth/SpnegoAuthenticator;.authenticateSession (Lcom/hierynomus/smbj/auth/GSSAuthenticationContext;[BLcom/hierynomus/smbj/session/Session;)Lcom/hierynomus/smbj/auth/AuthenticateResponse;
    VFY:  rejecting opcode 0x0d at 0x0091
    VFY:  rejected Lcom/hierynomus/smbj/auth/SpnegoAuthenticator;.authenticateSession (Lcom/hierynomus/smbj/auth/GSSAuthenticationContext;[BLcom/hierynomus/smbj/session/Session;)Lcom/hierynomus/smbj/auth/AuthenticateResponse;
    Verifier rejected class Lcom/hierynomus/smbj/auth/SpnegoAuthenticator;
</pre>

again, thank you for your help, and of course I'll even follow #329
Andrea

**Comment by pepijnve** [comment]
@andreasql did you try adding the two lines I listed above to your code? I used your example project and after adding those two things worked for me on a Lollipop AVD.

**Comment by andreasql** [comment]
hi All, hi pepijnve,
did not understand that comment was for me... thought it was for hyeronimus... sorry...
and thank you so much, it seems to be working... :)

I'm testing it right now under more pressure to verify it is reliable :)
thank you so much for all your efforts.... and keep up the good work... I'll keep checking for new builds as well... 
BTW, did not find a <donate> button here... is it available somewhere?
TIA
Andrea
