### ISSUE TITLE
STATUS_ACCESS_DENIED(3221225506/3221225506)

### ISSUE THREAD

**Issue by cliviu** [hierynomus/smbj#328]
Hi,
  I have a STATUS_ACCESS_DENIED(3221225506/3221225506) when trying to write a file on a share, even if my credential are ok and I can create a file from windows explorer using that credentials.
   I connect to a share and I want to write this file  **smb**\junit_pleasedonotdelete\test3.txt. **smb** is a link to another smbv2 share. If I connect direct to the share where the **smb** points, with the same credentials, I can write the file. 
  Does anybody have an idea what it can be wrong ? 
Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED(3221225506/3221225506): Create failed for smb\junit_pleasedonotdelete\test3.txt
	at com.hierynomus.smbj.share.Share.receive(Share.java:342)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:322)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:135)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:79)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:69)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:146)

**Comment by pepijnve** [comment]
Sounds like a DFS issue where the write request is targeted at the DFS referral rather than at the target of the DFS referral.

**Comment by cliviu** [comment]
The exception comes directly here  : File newFile  = rootShare.openFile(relativePath,
                          new HashSet<>(Arrays.asList(AccessMask.GENERIC_ALL)),
                          null,
                          SMB2ShareAccess.ALL,
                          overwrite ? SMB2CreateDisposition.FILE_OVERWRITE_IF : SMB2CreateDisposition.FILE_CREATE,
                          null) 
Do you see something wrong when opening the file ?

**Comment by pepijnve** [comment]
The DFS resolver only kicks in when it gets a PATH_NOT_COVERED error at the moment. The server is probably returning a different error code.

**Comment by cliviu** [comment]
I have tried now with the latest product 0.7.0 . Reading works 
2018-05-07 12:15:36,736|Signal              |DEBUG|Wait For 60000
2018-05-07 12:15:36,738|Connection          |DEBUG|Granted 1 (out of 512) credits to SMB2_CREATE with message id << 5 >>
2018-05-07 12:15:36,738|DirectTcpTransport  |DEBUG|Writing packet SMB2_CREATE with message id << 5 >>
2018-05-07 12:15:36,740|Promise             |DEBUG|Awaiting << 5 >>
2018-05-07 12:15:36,741|PacketReader        |DEBUG|Received packet SMB2_CREATE with message id << 5 >>
2018-05-07 12:15:36,741|Connection          |DEBUG|Server granted us 2 credits for SMB2_CREATE with message id << 5 >>, now available: 513 credits
2018-05-07 12:15:36,741|Promise             |DEBUG|Setting << 5 >> to `SMB2_CREATE with message id << 5 >>`
STATUS_ACCESS_DENIED (0xc0000022): Create failed for **\\host.de\zDFS\smb\junit_pleasedonotdelete\test3.txt**
de.znt.services.base.ServiceException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for \\host.de\zDFS\smb\junit_pleasedonotdelete\test3.txt
Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for \\host.de\zDFS\smb\junit_pleasedonotdelete\test3.txt
	at com.hierynomus.smbj.share.Share.receive(Share.java:343)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:322)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:135)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:80)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:70)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:148)

**Comment by cliviu** [comment]
The problem is that in DiskShare.createFileAndResolve, super.createFile fails before the resolver kicks.

**Comment by pepijnve** [comment]
> super.createFile fails before the resolver kicks.

That's what I expected indeed. @hierynomus or myself will have to go back and reread the DFS spec to figure out how this is supposed to be implemented.

**Comment by cliviu** [comment]
ok, thanks

**Comment by cliviu** [comment]
Is it any setting that I can use when creating the file so that it will not fail ? File newFile  = rootShare.openFile(relativePath,
                          new HashSet<>(Arrays.asList(AccessMask.GENERIC_ALL)),
                          null,
                          SMB2ShareAccess.ALL,
                          overwrite ? SMB2CreateDisposition.FILE_OVERWRITE_IF : SMB2CreateDisposition.FILE_CREATE,
                          null);

**Comment by cliviu** [comment]
> Nothing that's practical. Best workaround I can come up with is opening the parent directory, querying the actual directory path and then using that to create the file.

Do you know how to query the actual directory path ?

**Comment by pepijnve** [comment]
Looks like that information is not available. The DFS resolver has the value of course, but I don't think there's a way to get it out. I mistakenly thought you could query FileNameInformation, but that's not actually queryable.

**Comment by cliviu** [comment]
yes, I have searched a while for it as it would have been worth trying. Probably for read operations instantiating the file works because the file is there. That's why I thought that I have used the wrong options when opening the file for writing..  Can you send a link to the right part of the DFS docu ? we need the feature, maybe we can invest some time to dig into it.

**Comment by jborza** [comment]
Hi, 
@cliviu I'm doing the proactive approach in camel-smbj,
see 
https://github.com/jborza/camel-smbj/blob/master/src/main/java/com/github/jborza/camel/component/smbj/SmbShare.java - connect() and connectDfsShare() and getDfsShare() where the resolved path is memorized as well as target share.

**Comment by cliviu** [comment]
@jborza , thanks, i will try it

**Comment by jokovacs** [comment]
@cliviu ,
I have the same problem and the same exception.
I use the smbj 0.7.0 to access the **\\\host\DFSShare** directory, and I should create new directories and files to a subfolder **\\\host\DFSShare\Folder1\Folder2\Folder3\newDirectory\newFile.txt**.
But when I ran the _mkdir(newDirectory)_ method, I got the same STATUS_ACCESS_DENIED error.
Did you managed to solve the problem?

How can I set the **Folder3** as a root directory? Maybe in that case, there would be no exception.

Thank you in advance for the help!

**Comment by jborza** [comment]
@jokovacs if your share is a DFS share I suggest you do the following for the time being:

            SMBClient client = ...
            SMB2Echo responsePacket = new SMB2Echo();
            responsePacket.getHeader().setStatus(NtStatus.STATUS_PATH_NOT_COVERED);
            String path = "\\host\DFSShare\Folder1\Folder2\Folder3\newDirectory\newFile.txt"
            SmbPath resolvedPath = client.getPathResolver().resolve(session, responsePacket, path);
            
then if resolvedPath is on a different host, establish a new SmbSession and use resolvedPath.getPath() for the new parameter to mkdir()

something like here: https://github.com/hierynomus/smbj/blob/65f4f8434a5657950090f511473adf2e0b9c0daa/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L79
            
also keep in mind that mkdir() creates only one directory at a time, so you'd need to create the directories in the hierarchy one by one if they don't exist, see 
https://github.com/jborza/camel-smbj/blob/2a5c4f1f7e03402e4fedb5e755f1df0991f56ba1/src/main/java/com/github/jborza/camel/component/smbj/SmbShare.java#L224

**Comment by jokovacs** [comment]
Sorry for the late post.
I created a resolvedPath as you mentioned above, then I confronted that the resolvedPath is on different host than the original DFSShare. Therefore, I created a new session and a new DiskShare.
Finally I was able to create, rename and delete new directories and files too.

Thanks again, @jborza !

**Comment by cliviu** [comment]
@hierynomus, thanks for the fix ! When is the next release planned  ?

**Comment by hierynomus** [comment]
Exactly the same?

**Comment by cliviu** [comment]
Sorry, my fault, I have not seen that is not merged yet to master. Now I have built it from "issue-328" and tested and it works ! Many thanks !  When do you think it will be released ?

**Comment by pavel-spacil** [comment]
Hello, any news about merging this to master and having the JAR with fix available? Thanks

**Comment by cliviu** [comment]
I have tested now with smbj-0.8.0 and the STATUS_ACCESS_DENIED problem persists. With that build from 20 Juni from the Issue-328 Branch the problem was fixed. Can it be that the fix was not merged in 0.8.0 ?
