### ISSUE TITLE
Unable to access an SMB share that doesn't require credentials

### ISSUE THREAD

**Issue by AngusBerry** [hierynomus/smbj#330]
I'm trying to access an SMB share that does not challenge for credentials. From a command prompt on Mac, I can successfully mount the share as follows:
mount -t smbfs //<server_name>/<share_name> <local_dir>
e.g.
mount -t smbfs //windows_server_name/shared_folder_name temp_dir_name
...and it mounts no problem

I can even add a user name and it still mounts (since it's configured so I'm not challenged for credentials):
mount -t smbfs //user_name@windows_server/shared_folder temp_dir
...I can even add the password too:
mount -t smbfs //user_name:password@windows_server/shared_folder temp_dir
(user_name / password are substituted for valid ones)

So everything's good on the native Mac OS using it's own Samba client.

Hwoever, using smbj 0.7.0, from Maven, I've tried using 
authContext = new AuthenticationContext("user_name", "password".toCharArray(), "DOMAIN");
(the above works fine... but the below fails)
authContext = AuthenticationContext.anonymous();
authContext = AuthenticationContext.guest();

Can you please suggest how I should access an 'unchallenged' SMB share?

Thanks...

**Comment by hierynomus** [comment]
What "doesn't work". Unfortunately, my kid dropped my crystal ball so I cannot debug this for you without information...

**Comment by hierynomus** [comment]
@AngusBerry questions:
- Can you provide some trace logging?
- Are you sure you're using a share that permits anonymous or guest credentials?
- Doesn't the mac client use your logon credentials by default or something to that extent?

**Comment by hierynomus** [comment]
@AngusBerry Any update?

**Comment by hierynomus** [comment]
Closing this due to lack of response.
