### ISSUE TITLE
Documentation: reverse copy Share->Android and InputStream

### ISSUE THREAD

**Issue by andreasql** [hierynomus/smbj#331]
hi All,
here again to annoy all of you, seeking for documentation :)...
after having performed a copy from android to a windows share, (thanking hyeronimus and pepijnve for their friendly support and time) I'm trying to understand how to do the reverse... copy from windows share to android \Dowload folder...
is it just a matter of providing the AndroidPath + fileName as the destPath parameter of the SmbFiles.copy method, like
<pre>
String androidDirectory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)).getPath();
String inFileName = "fileName.txt" 

File fileIn = new File(androidDirectory, inFileName);
int writtenB = SmbFiles.copy(fileIn, share, **androidDirectory + "/" + inFileName**, true);
</pre>

?

and what about reading a share inputstream?
for instance, jcifs provided a SmbFileInputStream to read similarly to
<pre>
StringBuilder outBuilder = new StringBuilder();
BufferedReader reader = null;
String lineReader = null;
try {
   SmbFile smbFile = new SmbFile(fileName, auth);
   if (smbFile.exists()) {
      reader = new BufferedReader(new InputStreamReader(new **SmbFileInputStream(smbFile)**));

      while ((lineReader = reader.readLine()) != null) {
         if (outBuilder.length() > 0) {
            outBuilder.append("\n");
         }
         outBuilder.append(lineReader);
      }
   }
} catch (Exception ex) {
   m_Params.Exception = ex.getMessage();
} finally {
   try {
      if ( reader != null) { reader.close(); }
      reader = null;
   } catch (Exception ex) {
      m_Params.Exception = ex.getMessage();
   }
}
</pre>

does the project provide similar features?
TIA
Andrea

**Comment by neoxpert** [comment]
Unfortunately it is not that simple but smbj does offer retrieving input streams for files on a share.

I don't know if someone already implemented a shorter solution, but usually to have to perform severel steps:

- Create a new SmbClient instance
- Retrieve a Connection instance to a given host using the SmbClient instance
- Create a new Session on the Connection instance using some user credentials
- Connect to a share using the authenticated session
- Use the connected share to open a file and call getInputStream on this file

The very basic code could look like:

```
SMBClient client = new SMBClient();

try (Connection connection = client.connect("hostname");
     Session session = connection.authenticate(new AuthenticationContext("username", 
                                     "password".toCharArray(), ""));
     Share smbShare = session.connectShare("share")) {
	File file = ((DiskShare) smbShare).openFile("pathToFileRelativeToShare",
			EnumSet.of(AccessMask.GENERIC_READ), null, SMB2ShareAccess.ALL, 
                                 SMB2CreateDisposition.FILE_OPEN,null);
			
	InputStream input = file.getInputStream();

	input.close();
			
	file.close();
} catch (IOException e) {
	e.printStackTrace();
} catch (Exception e) {
	e.printStackTrace();
}
```

It is important to close retrieved connections, sessions and so one after you are finished with whatever you used them for. I suggest writing a wrapper class that implements the InputStream interfaces that takes care about all of those required actions.

**Comment by hierynomus** [comment]
One option also now is to use the following method once you've obtained the remote File.
https://github.com/hierynomus/smbj/blob/a9dc976595ebafd291e3313db391c3e7ce2964f0/src/main/java/com/hierynomus/smbj/share/File.java#L166-L173

**Comment by andreasql** [comment]
thank you very muc, Jeroen... and have a happy new year :)
-- 
Andrea
