### ISSUE TITLE
STATUS_USER_SESSION_DELETED when connecting to an IBM Share

### ISSUE THREAD

**Issue by mtamassia** [hierynomus/smbj#334]
When connecting to an IBM iSeries Share setup for SMBv2 via the library, I am receiving STATUS_USER_SESSION_DELETED (0xc0000203)

The logs show that the client session ID is set to 0 for whatever reason. This issue is only happening with shares on IBM iSeries and does not happen on many other types of environments using the same exact code.

[qtp1364987723-38] INFO com.hierynomus.smbj.connection.Connection - Successfully connected to: S105H9ZM
[qtp1364987723-38] INFO com.hierynomus.smbj.connection.Connection - Successfully authenticated ISRS on S105H9ZM, session is 0
[qtp1364987723-38] INFO com.hierynomus.smbj.session.Session - Connecting to \\S105H9ZM on session 0
[qtp1364987723-38] INFO com.hierynomus.smbj.session.Session - Logging off session 0 from host S105H9ZM
[qtp1364987723-38] INFO com.hierynomus.smbj.connection.Connection - Closed connection to S105H9ZM
[Packet Reader for S105H9ZM] INFO com.hierynomus.smbj.transport.PacketReader - Thread[Packet Reader for S105H9ZM,5,main] stopped.

Any ideas of what could be causing it? I found this issue on a python library and I was wondering if it is related to the issue I am experiencing https://github.com/CoreSecurity/impacket/commit/dc4606822e489e62d276bc3c928af31cd860f4a0

Finally, I have a wireshark capture and if you can point me to what to look for I can provide more info.

Thanks,
Marcelo

**Comment by hierynomus** [comment]
You could try to take a look at the contents of the `SMB2_SESSION_SETUP` response. That message should include the newly created sessionId. 

How are you constructing the `SmbConfig` instance? Are you manually setting a `clientGuid`?

**Comment by mtamassia** [comment]
Thank you @hierynomus 

I am sending attached the relevant portion of the packet capture. It is pretty small.  As you can see, it is not returning a new sessionId. 

No, I am not setting a clientGuid. Here is how I am building the SmbConfig

```        final int REQUEST_TIMEOUT_SECS
[SMB_Traffic.zip](https://github.com/hierynomus/smbj/files/2132959/SMB_Traffic.zip)

 = 20;
        final int SOCKET_TIMEOUT_SECS = 30;

        // Build config
        SmbConfig config = SmbConfig.builder()
                .withTimeout(REQUEST_TIMEOUT_SECS, TimeUnit.SECONDS) // Timeout sets Read, Write, and Transact timeouts (default is 60 seconds)
                .withSoTimeout(SOCKET_TIMEOUT_SECS, TimeUnit.SECONDS) // Socket Timeout (default is 0 seconds so socket blocks forever)
                .build();
```

Thank you,
Marcelo

**Comment by hierynomus** [comment]
Hi Marcelo,

Thanks the packet capture showed what the problem is. The `SMB2_SESSION_SETUP` response only contains the `sessionId` at the very last response, not on the intermediate responses. This is inline with the spec. Should now be fixed on master.
