### ISSUE TITLE
non-ASCII filenames

### ISSUE THREAD

**Issue by oglueck** [hierynomus/smbj#337]
File f = share.openFile("föö bär.txt", ...)

ends up on the share as: f�� b�r.txt

**Comment by oglueck** [comment]
It looks like SMB2Functions should use UTF_16, not UTF_16LE.
According to the SMB2 docs https://msdn.microsoft.com/en-us/library/cc246497.aspx
"textual strings MUST be in Unicode version 5.0 format, as specified in [UNICODE], using the 16-bit Unicode Transformation Format (UTF-16) form of the encoding"

According to https://en.wikipedia.org/wiki/UTF-16 UTF-16 means big endian without BOM.
UTF-16LE was used by SMB1.

**Comment by pepijnve** [comment]
I'm 99% sure it's little-endian UTF-16 that's needed. You would get errors all characters otherwise; not just non-ascii ones.

Could you provide some additional context for this issue? Which server (operating system) are you using?

**Comment by hierynomus** [comment]
The only thing transmitted big-endian ordering is the packet size of the SMB2Packet. This should be transmitted in network byte order (big-endian)

**Comment by oglueck** [comment]
Yes you are right. Retesting revealed that the encoding was mangeled in the argument passing. smbj alone does the right thing.
