### ISSUE TITLE
How to list folders at the "root of sharing"?

### ISSUE THREAD

**Issue by fiasko131** [hierynomus/smbj#344]
Hello,
I'm trying to use your library in my android application since windows no longer accepts the default smb1 protocol.
Here is the code snippet that I use to try to list the folders at the root of the share:
````java
      ..........
      @Override
        protected Void doInBackground(Void... voids) throws InterruptedException {
            String sambaDomain = null; 
            String sambaUsername = "steph";
            String sambaPass = "blabliblablou";
            String sambaIP = ipAdress;
            String sambaSharedPath = "\\"; //<----- my issue
            SmbConfig cfg = SmbConfig.builder().
                    withMultiProtocolNegotiate(true).
                    withSecurityProvider(new JceSecurityProvider(new BouncyCastleProvider())).
                    build();
            SMBClient client = new SMBClient(cfg);
            Connection connection = null;
            try {
                connection = client.connect(sambaIP);
            } catch (IOException e) {
                e.printStackTrace();
            }

            try {
                Session session = connection.authenticate(new AuthenticationContext(sambaUsername, sambaPass.toCharArray(), sambaDomain));
                DiskShare share = (DiskShare) session.connectShare(sambaSharedPath);
                for (FileIdBothDirectoryInformation f : share.list("")) {
                    Log.i("smb2files","File : " + f.getFileName());
                }
            }catch (Exception e){
                e.printStackTrace();
            }


            return null;
        }
        .........
````
I take for example a machine under Windows with this tree:
\\\192.168.1.96 \ folder1
\\\ 192.168.1.96 \ folder2
So the question is how to write the path with "\\" separator, because I get the following errors:

> java.lang.IllegalArgumentException: Share name (\) cannot contain '\\' characters.

with:
````java
 String sambaSharedPath = "\\";
````
and:

> com.hierynomus.mssmb2.SMBApiException: STATUS_INVALID_PARAMETER (0xc000000d): Could not connect to \\192.168.1.96

with:
````java
String sambaSharedPath = "";
````
Thanks for your help

**Comment by hierynomus** [comment]
In smb, listing all shares is an rpc call. I've not yet added a method for that. You could use the smbj-rpc library for that

**Comment by fiasko131** [comment]
Ok I'll watch that ..
So at the moment, your library allows me to list folder1 with
````java
String sambaSharedPath = "folder1";
DiskShare share = (DiskShare) session.connectShare ("");
````
I get a list with childFolderf1, childFolder2 etc ...

But I can not do:
````java
String sambaSharedPath = "folder1";
DiskShare share = (DiskShare) session.connectShare ("\\" + childFolder1);
````
or
````java
String sambaSharedPath = "folder1+"\\"+childFolder1;
DiskShare share = (DiskShare) session.connectShare ("");
````
I get the same error:

> java.lang.IllegalArgumentException: Share name () cannot contain '\\' characters.

How to write the paths for a windows machine?

**Comment by hierynomus** [comment]
Once you've connected to a `DiskShare`, you can list files/folders on that.
For instance:

`share.list(childFolder1)` or `share.list(childFolder1 + "\\sub")`

**Comment by fiasko131** [comment]
Ok thank you very much for your quick response!
I know this is not the right place but can you tell me how to implement the smbj_rpc librairy in my project ... there is no maven repository?
I am a beginner :))

**Comment by hierynomus** [comment]
Have a look at the homepage for that one: https://github.com/rapid7/smbj-rpc

**Comment by fiasko131** [comment]
I have already looked but there is no guide on how to include the library in project??

**Comment by fiasko131** [comment]
Sorry I reopened the issue, but I do not see any details on how to import this library?

**Comment by pepijnve** [comment]
@fiasko131 you should ask the authors of that library. I couldn't find it in any public maven repository either. They probably haven't published it yet.

**Comment by fiasko131** [comment]
@pepijnve
Yes I did this ... because without this library I can not use yours without knowing the name of the shared folders of departure for a given pc ...

**Comment by fiasko131** [comment]
I was able to compile smbj-rpc library successfully and so I can list all the patches for a given ip address.
For those who are interested I can share the module.

**Comment by VladSolfior** [comment]
@fiasko131, hello, I'm working on simiar things, so can I ask you some questions about implementation of listing shares on a server. my emai is: fuentes.vlad@gmail.com

**Comment by ashutosh-stha** [comment]
@fiasko131 Hello, Could please share the module for smbj-rpc ? It will be great help to my project. My email is ashutosh.stha14@gmail.com. Thanks you.

**Comment by bustanil** [comment]
If someone wants to use the smbj-rpc library, here is the published one: https://mvnrepository.com/artifact/com.rapid7.client/dcerpc
