### ISSUE TITLE
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for <Remote File location>

### ISSUE THREAD

**Issue by NavidHeydari** [hierynomus/smbj#363]
Hi All -- I faced an exception when I tried to use the framework.

below is the code I am using. I am able to log in and get the list of all the item under the location so my authentication is working fine. however, It's throwing an error. any idea how can I read, write and delete the files using the same framework?

com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for <full path including share hostname to the file>
	at com.hierynomus.smbj.share.Share.receive(Share.java:342)
	at com.hierynomus.smbj.share.Share.sendReceive(Share.java:322)
	at com.hierynomus.smbj.share.Share.createFile(Share.java:135)
	at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:80)
	at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:70)
	at com.hierynomus.smbj.share.DiskShare.openFile(DiskShare.java:148)

try (Connection connection = client.connect(serverName)) {
			AuthenticationContext ac = new AuthenticationContext(username, password.toCharArray(), domain);
			Session session = connection.authenticate(ac);

			try (DiskShare share = (DiskShare) session.connectShare("<root directory in shared location>")) {
							
				for (FileIdBothDirectoryInformation file : share.list("<sub directory under root directory>")) {
					
					if (file.getFileName().equalsIgnoreCase("<the file I am trying to read>")) {
	// I can reach here without any issues and all the information seems fine.
	// it's throwin Exception in below line when it tries to connect to the file.
						com.hierynomus.smbj.share.File sharedFileRef = share.openFile(
								"<subDirectory>/<file I am trying to read>", EnumSet.of(AccessMask.GENERIC_ALL), null,
								SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null);

						InputStream in = sharedFileRef.getInputStream();
					}
				}
			}
		} catch (Exception e) {
			e.printStackTrace();
		}

**Comment by pepijnve** [comment]
@hierynomus this (and similar) question pops up quite regularly. Perhaps we should make a small FAQ section with pointers to the relevant msdn pages?

**Comment by hierynomus** [comment]
Indeed, let's add a section to the `README.adoc`.

**Comment by pepijnve** [comment]
First draft in #364

**Comment by NavidHeydari** [comment]
Appreciate your help, actually, that was the issue. I played around with that and it fixed the issue. closing this item.
