### ISSUE TITLE
Files became directories

### ISSUE THREAD

**Issue by DGGomez** [hierynomus/smbj#369]
Hello,

So I switched from jcifs to smbj now I noticed some of the files are now directories, they even contain the parent directory's folders as well (seemingly infinitely repeating ex. path/path/path). I was hoping if anyone knew why or had any idea.

Thanks!

**Comment by hierynomus** [comment]
Sorry my crystal ball is broken. I don't onow what you're doing or getting. This problem has not been reported before and also our integration tests do not show this. Please be more clear

**Comment by DGGomez** [comment]
Sorry about that, I made a samba client api that connects to a server to view and delete files/directories. The server is already up and everything else is working fine, but it came to my attention that some of the files were now considered directories that even had folders in them that weren't there before. I'm not sure the cause of this so I was just hoping someone else experienced this here. Since this isn't the case thanks for your quick response.
