### ISSUE TITLE
NegTokenInit.parseTagged throw exception when required token elements are present

### ISSUE THREAD

**Issue by niggemannmj** [hierynomus/smbj#37]
The NegTokenInit.parseTagged should not throw an exception when it parses the reqFlags or mechListMIC ASN1TaggedObject. These should simply be ignored. This fields are commonly set by Samba and thus you won't be able to interoperate with Samba. The fix is to add cases for 1 and 3 and ignore them instead of dropping through to the default case.

**Comment by hierynomus** [comment]
Fixed by bfffb2a
