### ISSUE TITLE
EOF while reading packet when connecting to IBM iSeries

### ISSUE THREAD

**Issue by mtamassia** [hierynomus/smbj#370]
Thank you for the fix for #334 @hierynomus , it has really improved the situation and now I can authenticate. With the latest release, the session ID is being returned (it is a negative number but at least it has passed the point where it was breaking before #334).

I am sending below the stack of the error and attached the network data capture. I am now able to authenticate but I can't read the share. I noticed in the capture it has a "STATUS_BAD_NETWORK_NAME" but I have already triple checked the name of the server and the share. I can connect to it via Windows Explorer without issues so something is still at play. I am also hoping that the attached data capture will help explain the errors below.

[SMBv2.zip](https://github.com/hierynomus/smbj/files/2259064/SMBv2.zip)

```[qtp1982103336-25] INFO com.hierynomus.smbj.connection.Connection - Successfully connected to: S105H9ZM
[qtp1982103336-25] INFO com.hierynomus.smbj.connection.Connection - Successfully authenticated ISRS_PRISM on S105H9ZM, session is -783907810139176704
[qtp1982103336-25] INFO com.hierynomus.smbj.session.Session - Connecting to \\S105H9ZM on session -783907810139176704
[qtp1982103336-25] INFO com.hierynomus.smbj.session.Session - Logging off session -783907810139176704 from host S105H9ZM
[Packet Reader for S105H9ZM] INFO com.hierynomus.smbj.transport.PacketReader - PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:72)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: EOF while reading packet
	... 6 more
[Packet Reader for S105H9ZM] INFO com.hierynomus.smbj.connection.Connection - Closed connection to S105H9ZM
[qtp1982103336-25] INFO com.hierynomus.smbj.connection.Connection - Closed connection to S105H9ZM```

**Comment by mtamassia** [comment]
@hierynomus and @pepijnve I know you guys are very busy but if you could quickly look at the data capture and point me in the right direction I would appreciate.

**Comment by pepijnve** [comment]
This looks like an issue I've seen with the macOS SMB server as well. As soon as the last session of a connection is terminated the server closes the underlying TCP connection. SMBJ doesn't/didn't have code to handle this situation and simply dumped the exception.
Might be something else, but it definitely looks similar.

**Comment by pepijnve** [comment]
`\\S105H9ZM` is not going to work for a tree connect. Needs to be of the form `\\<server>\<share>`. Are you passing an empty string as share name or null?

**Comment by mtamassia** [comment]
Thank you so much for the response @pepijnve. Let me triple check my code to see if there is any possibility the share name could be passed empty.

**Comment by mtamassia** [comment]
@pepijnve this was a bug on our end. Sorry for wasting your time. Thank you as always for the great library and support!

**Comment by hierynomus** [comment]
Can you explain what the bug/problem was? Is there anything we could improve to prevent this situation? That would potentially help other users of smbj.

**Comment by mtamassia** [comment]
Sure thing @hierynomus the issue was that although the sharename was passed in, the folder name was being passed blank. The error message was non-descriptive so it boils down to better error trapping or reporting since SMB error codes are very generic.
