### ISSUE TITLE
Continue to get EOF Exceptions even when everything has been closed/logged out

### ISSUE THREAD

**Issue by pecks2** [hierynomus/smbj#372]
I continue to get EOF exceptions, EOF While reading packet.. even though I am closing everything.. and see logging off messages.

Code:

public static DiskShare getShare() throws Exception
    {

        if(share == null){
            SmbConfig cfg = SmbConfig.builder().withDfsEnabled(true).build();
            SMBClient client = new SMBClient(cfg);
            Log.info("CREATE SHARE");
            connection = client.connect(sambaIP);
            session = connection.authenticate(new AuthenticationContext(sambaUsername, sambaPass.toCharArray(), sambaDomain));
            share = (DiskShare) session.connectShare(sambaSharedName);

        }
        return(share);

    }

    public static File open(String filename) throws Exception{
        getShare();
        Set<SMB2ShareAccess> s = new HashSet<>();
        s.add(SMB2ShareAccess.ALL.iterator().next());
        filename = filename.replace("//acct.upmchs.net/eba/","");
        return(share.openFile(filename, EnumSet.of(AccessMask.GENERIC_READ), null, s,  SMB2CreateDisposition.FILE_OPEN, null));
    }

public static void releaseShare() throws Exception{

        share.close();
        session.close();
        connection.close();
        share = null;
        session = null;
        connection = null;

    }

How I USE:

try(File f = Smb.open(fixFilename(filename))){
.
.
}

Everything seems to work... and even though the try should close each connection after its done, I do call the releaseShare, when I am fully done processing all files..

Yet after maybe 10 minutes or so I I get the TransportExceptions/EOFException errors.  

What am I missing?

It doesn't seem to harm anything, but I would like to not have them showing up

**Comment by hierynomus** [comment]
Did the answer on StackOverflow help? :)

For the record:
Since 0.8.0 `SMBClient` is now also `Closeable` to ensure all resources are correctly disposed of.

**Comment by pecks2** [comment]
Yes,

I had 0.8.0 in my POM, but apparently I hadn’t refreshed so I was still using 0.7.0… once I forced the pom refresh the .close() was avaialable and the error disappeared.  Thank you.

**Comment by hierynomus** [comment]
Closing this issue as it has been resolved.
