### ISSUE TITLE
Buffer Underflow exception for IOCTL response: STATUS_INVALID_PARAMETER incorrectly treated as successfully

### ISSUE THREAD

**Issue by nsoleeva** [hierynomus/smbj#374]
Hello, I would like to highlight the issue which I has when I'm trying to connect to Windows 8 machine.

It seems that smbj lib incorrectly process STATUS_INVALID_PARAMETER NtStatus by treating it as "Success" case instead "Failure" case. As result, it trying to read message and get BufferUnderflow error.

If you look at SMB2IoctlResponse.isSuccess(NtStatus status) method, you will see that method will return "succes" if status == NtStatus.STATUS_INVALID_PARAMETER.
According to MS-SMB2 spec 3.3.4.4 which is also mentioned in doc annotation to this method, you can find that STATUS_INVALID_PARAMETER should be treated as a success code only for "FSCTL_SRV_COPYCHUNK and FSCTL_SRV_COPYCHUNK_WRITE response, when returning an SRV_COPYCHUNK_RESPONSE as described in section 3.3.5.15.6.2."

In my case, I execute FSCTL_PIPE_TRANSCEIVE IOCTL request.

Could you please take a look and re-check my thoughts and correct me if I wrong?
Also, should it be possible to fix this issue in some future release if it is really the issue?
If any additional information is required please let me know.

One more point here: 
Could you please also assist with the reason of STATUS_INVALID_PARAMETER? May be I should move it to another question or issue, but I would like to figure out the reason at first.

I have smbclient which can successfully connect to this Windows 8 machine. But smbj couldn't connect to this host.
In tcpdump I see that IOCTL request failed with STATUS_INVALID_PARAMETER. As result in log I have stacktrace with final BufferUnderflow exception, as I already mention, I think the reason of this exception the smbj incorrect behavior. But I couldn't understand why such STATUS_INVALID_PARAMETER response occurred.
I have mentioned several small difference in IOCTL request which send smbj versus smbclient:
SMB2 Header(smbj | smbclient):
Credit Charge: 16 | Credit Charge: 1
Credits requested: 415 | Credits requested: 8065
Flags: 0x00000008 
.... .... .... .... .... .... .... 1... = Signing: This pdu is SIGNED
vs in smbclient Flags: 0x00000000

In IOCTL request part
Max Ioctl Out Size: 1048576 | Max Ioctl Out Size: 4280

In DCE/RPC request part:
Max Xmit Frag: 16384 | Max Xmit Frag: 4280
Max Recv Frag: 16384 | Max Recv Frag: 4280

May be you will have some ideas about this STATUS_INVALID_PARAMETER based on provided data.
Thank you for any help!

**Comment by hierynomus** [comment]
I think you're right, I'll have a quick read through the spec tomorrow and fix it.

the most likely reason for a STATUS_INVALID_PARAMETER with an IOCTL is that the specified buffer size is too small. You would be able to retrieve the needed buffer size once the message is recognized as an error message.

**Comment by nsoleeva** [comment]
@hierynomus Thanks a lot for quick response!
I will try to compile the lib locally with removing STATUS_INVALID_PARAMETER from "success" case, but as I see in wireshark, ByteCount field of IOCTL error response is 0, so I'm not sure it will be very helpful according to my understanding of spec for SMB ERROR Response  :-(

**Comment by nsoleeva** [comment]
May be it will be helpful for somebody in future: 
As a workaround for the issue with WIN8 connect it's possible to set config.transactBufferSize to 4280: SmbConfig.builder().withTransactBufferSize(4280).build() on current 0.8.0 version of smbj.

**Comment by hierynomus** [comment]
Hi @nsoleeva,

Can you check whether your workaround is obsolete now with the current PR #378. The message should now correctly be flagged as an Error packet.

**Comment by nsoleeva** [comment]
Thank you for your work! I think I will be able to execute some tests on this weekends. I'll let you now about results as soon as it will be possible.

**Comment by hierynomus** [comment]
@nsoleeva Did you manage to run some tests?
