### ISSUE TITLE
STATUS_ACCESS_DENIED for DFS

### ISSUE THREAD

**Issue by mcvkr** [hierynomus/smbj#380]
https://stackoverflow.com/questions/52086829/smbj-status-access-denied-for-dfs

here is the issue, I can carry it over here if you want/it is more convenient. Thanks in advance.

**Comment by andershermansen** [comment]
https://github.com/hierynomus/smbj#when-i-try-to-open-a-file-or-directory-my-code-fails-with-status_access_denied-how-can-i-fix-this

**Comment by ramlraml** [comment]
I knew that readme section and I tried different masks and options but it did not fix it, do you think is it the code below or the user that is used do not have enough permissions?

 ```
   SmbConfig config = SmbConfig.builder()
            .withMultiProtocolNegotiate(true)
            .withSigningRequired(true)
            .withDfsEnabled(true)
            .build();

    this.client = new SMBClient(config);
    this.connection = client.connect(serverName);
    this.ac = new AuthenticationContext(username, password.toCharArray(), domain);
    this.session = connection.authenticate(ac);
    this.share = (DiskShare) session.connectShare(sharename);

    for( FileIdBothDirectoryInformation item : this.share.list("myprojectname\\testfoldername") ){
        System.out.println(item.getFileName()+" ");
    }

   File f = this.share.openFile("myprojectname\\testfoldername\\try-a-new-file.txt",
            new HashSet<>(Arrays.asList(AccessMask.FILE_ADD_FILE)),
            new HashSet<>(Arrays.asList(FileAttributes.FILE_ATTRIBUTE_NORMAL)),
            SMB2ShareAccess.ALL,
            SMB2CreateDisposition.FILE_OPEN_IF,
            new HashSet<>(Arrays.asList(SMB2CreateOptions.FILE_DIRECTORY_FILE))
    );
```

**Comment by andershermansen** [comment]
@ramlraml I really don't know that well, just wanted to point you to the FAQ where this is described.

Did you try AccessMask.GENERIC_WRITE instead of AccessMask.FILE_ADD_FILE ?
AccessMask.FILE_ADD_FILE seems like som directory access mask.

**Comment by ramlraml** [comment]
Thank you. Actually AccessMask.GENERIC_WRITE was the first mask I used, then I changed it to FILE_ADD_FILE after reading the faq, when I used the address that the DFSResolver resolves, this is working. I started thinking to do something like this https://github.com/hierynomus/smbj/issues/328#issuecomment-394071034

**Comment by hierynomus** [comment]
Is this resolved @ramlraml ?

**Comment by mcvkr** [comment]
Yes @hierynomus
