### ISSUE TITLE
File Transfers not working on IBM Shares - InputStream read() returning 0 

### ISSUE THREAD

**Issue by mtamassia** [hierynomus/smbj#384]
When attempting to transfer a file from an IBM iSeries Share, the `InputStream.read()` returns 0 instead of -1 so the file never completes since we are only checking for `!= -1`. This puts the code in a loop as we keep waiting for a value other than `-1` and we only always get `0` (the `InputStream.read(buf)` method will return `0` if you pass `buf = 0` ).

If I change com.hierynomus.smbj.share.File `public void read(OutputStream destStream, ProgressListener progressListener)` method from

`while ((numRead = is.read(buf)) != -1) {`

to this

`while ((numRead = is.read(buf)) >0) {`

Everything works. 

Please let me know if you agree with the approach and I can send in a PR.

**Comment by ecki** [comment]
Hello @mtamassia the case of first `numRead==0` would terminate the proposed `while(...>0)`, is that really correct? I would expect it would leve empty outputs behind. And I also do not see how it would loop if it returns 0 only on the first read. What is `share.getReadBufferSize()` in your case?

**Comment by ecki** [comment]
Returning readLen==0 is quite strange, working around that is dangerous (as I can imagine other implementations could possibly have 0 reads). Maybe digging a bit deeper into the protocol state of the reason for the numRead==0 for IBM can be found there would be better? (or at least retry numRead==0 at least once?)

**Comment by mtamassia** [comment]
> 
> 
> Hello @mtamassia the case of first `numRead==0` would terminate the proposed `while(...>0)`, is that really correct? I would expect it would leve empty outputs behind. And I also do not see how it would loop if it returns 0 only on the first read. What is `share.getReadBufferSize()` in your case?

@ecki it is at the end of the copy process (not the beginning)

**Comment by mtamassia** [comment]
@ecki today if `buf` is set to `0`  by `share.getReadBufferSize()`, the code goes into a loop. Maybe the issue is that `share.getReadBufferSize()` should never return `0` in the first place?

**Comment by mtamassia** [comment]
BTW, if you check the comments on issue #334, you will see SRZC brought up the same issue.

**Comment by mtamassia** [comment]
@hierynomus @pepijnve please let me know your thoughts on this.

**Comment by pepijnve** [comment]
Returning `0` from `InputStream#read` is actually not valid. Implementations should (from the java doc):

>  If no byte is available because the end of the stream has been reached, the value -1 is returned. This method blocks until input data is available, the end of the stream is detected, or an exception is thrown.

The loop in question is actually correct. Seems like there's an issue with the InputStream implementation.

**Comment by pepijnve** [comment]
`share.getReadBufferSize()` should indeed never return `0`; that doesn't make any sense. If it is `0` in practice an infinite loop will indeed occur. We'll need to figure out why the buffer size is `0` then.

I wouldn't recommend changing the loop. The read buffer size issue should be dealt with by checking that the value is `> 0` before entering the loop and throwing an exception if that's not the case.

**Comment by mtamassia** [comment]
@pepijnve @hierynomus it looks like the flow is this:
- `Share getReadBufferSize()` is getting 0 from `NegotiatedProtocol getMaxReadSize()`
- `NegotiatedProtocol getMaxReadSize()` is getting 0 from `SMB2NegotiateResponse getMaxReadSize()`
- ` SMB2NegotiateResponse getMaxReadSize()` is getting 0 from `Buffer readUInt32AsInt()`
- `Buffer readUInt32AsInt()` is getting 0 from `Endian readUInt32()`

Looking thru each one of those steps, I don't see anywhere a validation for 0. 

Assuming you still believe we should throw an exception, at what point do we need to start throwing it? At the SMB2NegotiateResponse level perhaps and all the way up to `File read()` ?

**Comment by pepijnve** [comment]
Is `0` a valid value for max read size? Need to reread the protocol spec. Maybe that has some special semantics.

**Comment by pepijnve** [comment]
All the spec says is
> MaxReadSize (4 bytes): The maximum size, in bytes, of the Length in an SMB2 READ Request (section 2.2.19) that the server will accept.

So if the server is saying `0`, I have no idea how we should interpret that. Don't read at all? 😂 

Could you double check with wireshark (or any other packet capture tool) if max read size is effectively 0 in the server response?

**Comment by mtamassia** [comment]
@pepijnve if you check the Lenght of the SMB2 Read Request (section 2.2.19), it says

> Length (4 bytes): The length, in bytes, of the data to read from the specified file or pipe. The length of the 
> data being read can be zero bytes.

**Comment by mtamassia** [comment]
Thank you @pepijnve. I am going to try to capture the transfer of the same file from Windows Explorer (which works fine today) as well as SMBJ. I will try to interpret and compare them but I might need some help. I will post both captures here for sure.

**Comment by ecki** [comment]
I think that getReadBufferSize() should sanitize some more. Not only handling 0 but also larger values (especially bigger than 2gb, but most likely anything bigger than 2mb should be clamped (bigger arrays would trigger for example G1 Huge allocs and seem to be not an advantage for reads, right?)

**Comment by pepijnve** [comment]
Not disagreeing. Capping the read buffer size is already possible via the config object. We could add an extra overload for read where the buffer size is a parameter.

> seem to be not an advantage for reads, right?

Hard to say in general. In high latency setups it makes a big difference since you can significantly reduce the number of roundtrips to the server. No idea where the sweet spot is. Probably server dependent.

**Comment by mtamassia** [comment]
@pepijnve I am sending attached the two captures. One for Windows and one for SMBj.

For SMBj you can see the loop in action when downloading the file JDE_719207.log. 

Unless I am reading this incorrectly, if you look at packet 2, you will see that the Negotiated Max Read Size responded by the server is 65536 (not 0) so I am not sure what's going on. 

[Capture.zip](https://github.com/hierynomus/smbj/files/2404073/Capture.zip)

**Comment by pepijnve** [comment]
Indeed definitely 64k in the negotiate response. I'm going to have to use you as teletype since I can't test this myself. What I would suggest you do next is, using the code that generated this trace, to run the code with the debugger and put a breakpoint in the negotiate response unmarshalling code in smbj. Also have wireshark running at the same time. When you hit the breakpoint, have a look at the dissected negotiate response in wireshark to confirm the max read size is 64k. Then step through the unmarshalling function in the debugger field by field and see where smbj starts disagreeing with what wireshark is showing. If you start seeing different values in the debugger compared to what you're seeing in wireshark, I would expect the bug on the smbj side to be pretty obvious at that point (if there is one). If we do get the right values during unmarshalling in smbj, then it's a matter of stepping through the code to see where it's getting lost.

**Comment by pepijnve** [comment]
The good news is that we shouldn't have to add special logic to deal with `maxReadSize == 0` in smbj. Adding some parameter validation during the negotiation and throwing an exception is enough for now I think and will avoid the infinite loop already.

**Comment by mtamassia** [comment]
Thank you @pepijnve . I have to coordinate access to the IBM server, which is on a segregated network but let me see what I can do.

**Comment by hierynomus** [comment]
Forgot to type the conclusion: IBM is not behaving according to the MS-SMB2 spec. We can work around it by checking in the InputStream whether there were `0` bytes returned, in which case we'll also signal EOF

**Comment by pepijnve** [comment]
Well spotted; I hadn't looked beyond the negotiate exchange.

Indeed not compliant. Spec says the following in 3.3.5.12

> If the read returns fewer bytes than specified by the MinimumCount field of the request, the server MUST fail the request with STATUS_END_OF_FILE.

On the SMBJ side, I agree that treating the case `request.MinimumCount > 0 && response.DataLength == 0` as an end of file as well is the best you can do. With a comment that this is not spec compliant but deals with certain incorrectly implemented servers.

Based on the windows capture, it looks like Windows is using a different strategy. It only issues a single read request. There's no end of file indication either. That probably means the file size, which is queried using STREAM_INFO just before the read, is being used to terminate the read loop.
That's also an option, but still won't help in certain concurrent access cases. If the file gets truncated in between querying the stream info and executing the read loop you could get into an infinite loop situation again.

**Comment by hierynomus** [comment]
Either that, or windows assumes that if less bytes are returned than the max requested, it is also EOF. Which in itself is also a dangerous assumption.

Also from MS-SMB2 in 2.2.20 SMB2 READ Response:

> A variable-length buffer that contains the data read for the response, as described
by DataOffset and DataLength. The minimum length is 1 byte. If 0 bytes are returned from the
underlying object store, the server MUST send a failure response with status equal to
STATUS_END_OF_FILE.

It seems like the IBM implementation has not STATUS_END_OF_FILE implemented as both these cases are ignored

**Comment by hierynomus** [comment]
This sentence in 2.2.20 actually means that we can trust that `response.dataLength` can be used as a terminator condition without the STATUS_END_OF_FILE being present.

**Comment by mtamassia** [comment]
Thank you so much @hierynomus @pepijnve I will give it a test once a new release is out and report back.
