### ISSUE TITLE
ZIP Files

### ISSUE THREAD

**Issue by sudhiksk** [hierynomus/smbj#385]
I need to zip remote files. Does anybody have ideas for zipping remote files with smbj

**Comment by ecki** [comment]
You would have to read the files and write the result. Since ZIP works best if using a seekable target most likely you would even have to generate a local temp file before finishing the ZIP archive and uploading it. It would be much better to execute the ZIP code on the server.

**Comment by sudhiksk** [comment]
Thanks, I thought so too but middleware team in my company doesn't want me to write temp files on server.

**Comment by ecki** [comment]
You mean server = application server = smb client I guess?

Anyway, there are some implementations which can work for smaller ZIP files in memory or for a seekable stream (see org.apache.commons.compress.archivers.zip.ZipArchiveOutputStream). And I think unless you use STORE (uncpompressed) they should also work with a purely append only output stream. As smbj seems to not yet have a random access variant: https://github.com/hierynomus/smbj/issues/349

**Comment by hierynomus** [comment]
@sudhiksk Can you please clearly specify your question? What do you want to achive? Do you want to call a command line zip client on the remote end to zip a (directory of) file(s)?
Do you want to copy the files to your local machine and write them into a zip there?
Do you want to enable compression on the transport channel like for instance ssh can?

**Comment by sudhiksk** [comment]
I wanted to zip files that are on shared location and put the zip there itself. Without copying the files to my local system.

I achieved this as below. Issue can be closed from my perspective.

public void zipFiles(String zipFileName, ArrayList<String> fileNames){
        try {
            String filePathParts[] = getPartsOfSharedPath(zipFileName);
            SMBClient client = new SMBClient();
            Connection conn = client.connect(filePathParts[0]);
            Session session = conn.authenticate(auth);
            DiskShare share = (DiskShare)session.connectShare(filePathParts[1]);
            
            com.hierynomus.smbj.share.File zipFile = share.openFile(filePathParts[2], EnumSet.of(AccessMask.GENERIC_WRITE), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN_IF, null);
            
            OutputStream fos = zipFile.getOutputStream();
            ZipOutputStream zos = new ZipOutputStream(fos);
 
            for (String aFile : fileNames) {                
                zos.putNextEntry(new ZipEntry(getFileName(aFile)));
                InputStream is = getInputStream(aFile);
                int bytesRead;
                byte[] buffer = new byte[1024];
                while((bytesRead = is.read(buffer)) != -1) {
                    zos.write(buffer, 0, bytesRead);
                }
                is.close();
                zos.closeEntry();
            }
            zos.flush();
            zos.close();
            zipFile.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

**Comment by rathnaum** [comment]
How do i unzip a zipped file which is on smb share?

**Comment by hareluya86** [comment]
Hey @sudhiksk just want to ask u about the performance of this approach - if the zipping faster than copying individual files to your local machine?
Just wondering if the zipping action still requires those individual file streams to be read to your local machine first before pushing it back to the remote machine to be added to the zip file.

**Comment by sudhiksk** [comment]
Performance is expected to be the same for both approaches. It’s better not to being files to local because you will waste time to delete the files later

- Sudh¡k
