### ISSUE TITLE
is there a way we can transfer a folder along with sub folders using smbj?

### ISSUE THREAD

**Issue by pathipakakiran** [hierynomus/smbj#387]
Hi ,

I want to copy a folder along with sub folders to remote share directory , 
how can we achieve that using smbj ?

thanks,
kiran.

**Comment by pepijnve** [comment]
The SMB protocol does not provide this functionality. SMBJ also does not contain this type of higher level functionality at the moment. I believe this is considered out of scope for the library (correct me if I'm wrong @hierynomus).

To implement this you will need to write code that recursively traverses the directory tree, creates directories and copies files. An enterprise scale version of essentially this is the commercial product I work on. This can be very simple, but I can say from experience that this can get very complex if you want to support all kinds of edge cases. Describing how to implement this in detail is not something I can fit in this comment box 😄

**Comment by hierynomus** [comment]
You're right @pepijnve, the goal of SMBJ is not to provide these higher level building blocks. It's also not that hard to write a basic recursive copy method. Contrary to what @pepijnve's company builds you probably do not need any of the corner cases. Just iterate the files, for a directory call mkdir and do an iteration of the subdirectory to copy its entries.

If you use the nio api's you could try and adapt the example here: https://stackoverflow.com/questions/29076439/java-8-copy-directory-recursively
