### ISSUE TITLE
OutOfMemory error while performing load tests with smbj lib

### ISSUE THREAD

**Issue by PrateepT** [hierynomus/smbj#389]
Hello,

Before using smbj we were using jcifs library and we have migrated to use smbj library to perform network file operations. When we are performing load tests using smbj library we are seeing OutOfMemory errors. The same load with jcifs is working normally.

Please suggest what could be going wrong, is there any configuration change I can make to solve this issue quickly? 

Currently the maximum heap memory allocated is 1024MB and we are processing around 5000 files and each file is of 60KB

Below is the error log:
Exception in thread "main" java.lang.OutOfMemoryError: Failed to create a thread: retVal -1073741830, errno 22
	at java.lang.Thread.startImpl(Native Method)
	at java.lang.Thread.start(Thread.java:972)
	at com.hierynomus.smbj.transport.PacketReader.start(PacketReader.java:84)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.initWithSocket(DirectTcpTransport.java:99)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpTransport.connect(DirectTcpTransport.java:91)
	at com.hierynomus.smbj.connection.Connection.connect(Connection.java:112)
	at com.hierynomus.smbj.SMBClient.getEstablishedOrConnect(SMBClient.java:102)
	at com.hierynomus.smbj.SMBClient.connect(SMBClient.java:76)
	at colruyt.baseframelib.file.AbstractNetworkFileServiceImpl.findFile(AbstractNetworkFileServiceImpl.java:517)
	at colruyt.baseframelib.file.FileService.findFile(FileService.java:216)
	at colruyt.baseframelib.file.FileService.move(FileService.java:587)
	at colruyt.baseframelib.file.FileService.move(FileService.java:553)
	at colruyt.dats24salesinvoicesxps.SalesInvoicesXps.run(SalesInvoicesXps.java:268)
	at colruyt.xpsframelib.JobMgr.runJob(JobMgr.java:184)
	at colruyt.xpsframelib.JobMgr.main(JobMgr.java:283)

Thanks,
Prateep.

**Comment by hierynomus** [comment]
What does the code look like that you're using to connect to SMB? Are you reusing the SMBClient or not?

It says it "Failed to create a thread". This typically means that you're running out of file descriptors, not heap. Are you correctly closing each connection?

**Comment by PrateepT** [comment]
Below is the code snippet:
public boolean exists(Cx cx, File file) throws FileException {			
		SMBClient client = null;
		Connection connection = null;
		Session session = null;
		DiskShare share = null;
		PathInfo pathInfo = SmbjUtil.getPathInfo(file.getPath());
		try {
			client = new SMBClient(config);
			connection = client.connect(pathInfo.getHostName());
			session = connection.authenticate(getAuthentication(cx));
			share = (DiskShare) session.connectShare(pathInfo.getShareName());
			FrameLogger.logDebug("Connected to network share" + hasDirectoryPath(cx, file));
			return exists(cx, file, share, pathInfo);
		} catch (SMBApiException smbApiExec) {
			if (smbApiExec.getStatus() == NtStatus.STATUS_OBJECT_NAME_INVALID) {
				return false;
			}
			throw smbApiExcToFileExc(smbApiExec);
		} catch (Exception e) {
			throw excToFileExc(e, file);
		} finally {
			SmbjUtil.closeDiskShare(cx, share);
			SmbjUtil.closeSession(cx, session);
			SmbjUtil.closeConnection(cx, connection);
		}		
	}

private boolean exists(Cx cx, File file, DiskShare share, PathInfo pathInfo)
			throws SMBApiException, InvalidPathFileException {
		try {			
			boolean folderExists = folderExists(share, pathInfo);
			FrameLogger.logDebug("folder exists: " + folderExists);
			if (folderExists) {
				return folderExists;
			}
			boolean fileExists = fileExists(share, pathInfo);
			FrameLogger.logDebug("file exists: " + fileExists);
			return fileExists;
		} catch (SMBApiException smbApiException) {
			if (smbApiException.getStatus() == NtStatus.STATUS_OBJECT_NAME_INVALID) {
				return false;
			}
			throw smbApiException;
		}
	}

private boolean folderExists(final DiskShare share, final PathInfo pathInfo) throws InvalidPathFileException {
		return share.folderExists(pathInfo.getSmbPath());
	}

private boolean fileExists(final DiskShare share, final PathInfo pathInfo) throws InvalidPathFileException {		
		return share.fileExists(pathInfo.getSmbPath());
	}

SmbjUtil.java:
      static void closeDiskShare(final Cx cx, final DiskShare diskShare) {
		if (diskShare != null) {
			try {
				diskShare.close();
			} catch (IOException e) {				
				FrameLogger.logError(cx, "Unable to close disk share");
			}
		}
	}
	
	static void closeDiskEntry(final Cx cx, final DiskEntry diskEntry) {
		if (diskEntry != null) {
			try {
				diskEntry.close();
			} catch (Exception e) {				
				FrameLogger.logError(cx, "Unable to close disk entry");
			}
		}
	}
	
	static void closeSession(final Cx cx, final Session session) {
		if (session != null) {
			try {
				session.close();
			} catch (Exception e) {
				FrameLogger.logError(cx, "Exception occured while closing session");
			}
		}
	}

       static void closeConnection(final Cx cx, final Connection connection) {
		if (connection != null) {
			try {
				connection.close(true);
			} catch (Exception e) {
				FrameLogger.logError(cx, "Exception occured while closing connection");
			}
		}
	}

**Comment by PrateepT** [comment]
For closing the connection I'm using connection.close(true) instead of connection.close()

**Comment by PrateepT** [comment]
For each file operation a new SBMClient instance is being created, is this an issue?

**Comment by mtamassia** [comment]
@PrateepT It looks like all your functions are using the same share, so could create the SmbConfig 
and the SMBClient for sure outside of your methods.

In addition to that, you can create the connection, the session, and the share references outside of your functions and then just pass the share to the method.

If you use try with resources you don't need to worry about closing anything. Check the example C on the readme.

**Comment by PrateepT** [comment]
@mtamassia  I've come across thread hang situation earlier during load tests and followed the solution mentioned in [#102](https://github.com/hierynomus/smbj/issues/102) started using connection.close(boolean true) and this is the reason I'm not using try with resources. 
Is it possible to trigger connection.close(boolean true) try with resources?

I'll try two things today: (i) Reuse SMBClient instance (ii) use connection.close() instead of connection.close(boolean true)

**Comment by PrateepT** [comment]
OutOfMemory error is not occurring anymore.
(i) Reusing the SMBClient instance and (ii) connection.close() instead of connection.close(boolean true) has resolved the issue.

Thanks a lot for your help :+1:
