### ISSUE TITLE
Help needed: folderExists() of Diskshare.java always returning true

### ISSUE THREAD

**Issue by gauravpanday007** [hierynomus/smbj#390]
Hello Team,

I am trying to check whether a folder is accessible for particular user or not, but folderExists() method is returning true for the users which don't have access to the folder.

Please see the scenario below:
\\servername\sharename\folder1\user1 - User1 has access to user1 folder 
\\servername\sharename\folder1\user2 - User2 has access to user2 folder

But even when I pass the credentials of User2, folderExists("folder1\\user1 ") returns true.

It might be possible that I am missing something obvious here, it would be great if you can help me out on this.
 
Thanks,
Gaurav

**Comment by hierynomus** [comment]
Existence is `true`, as the folder exists. However you probably do not get write access to the folder.

**Comment by gauravpanday007** [comment]
Thanks for your reply :)

Just wanted to know Is there a way by which we can check if the folder has been shared or not with the user for which we are passing the credentials?

**Comment by pepijnve** [comment]
You could try opening it with access mask value `MAXIMUM_ACCESS` and then query the actual access granted using the `FileAccessInformation` info level. `MAXIMUM_ACCESS` means grant the largest set of permissions I'm allowed to get. If you get access denied on the open then you definitely don't have access.

**Comment by gauravpanday007** [comment]
Hello @pepijnve , Thanks for your suggestions.

I tried what you have suggested. But I have few doubts, please have a look at my code snippet below.

com.hierynomus.smbj.share.Directory remoteSmbjDirectory = share.openDirectory(directoryPath,
EnumSet.of(AccessMask.MAXIMUM_ALLOWED), null, null, SMB2CreateDisposition.FILE_OPEN, null);	
			
logger.info("Access Flag: " + remoteSmbjDirectory.getFileInformation().getAccessInformation().getAccessFlags());

Here, I am able to open the directory irrespective user has access or not. But, when user has access I am getting the accessFlag as 1179817 and when user does not have access then, access flag is 128. 

I want to know whether the way I am doing this is fine? Also, where can I find the mapping for the access flag value returned. Any help would be appreciated.

Also, I have to make my code generic for both directory path as well as file path. Is there a way I can check that the path corresponds to a directory or file?

Thanks.

**Comment by pepijnve** [comment]
Have a look at https://github.com/hierynomus/smbj/blob/1494c5ca68912c9d58331f0461c30ca16af65a59/src/main/java/com/hierynomus/msdtyp/AccessMask.java for details on how to interpret the access mask value. It's a bit field so a single access mask value corresponds to a set of access rights.

 They're easier to interpret in hexadecimal or binary notation. `128` or `0x80` means just `FILE_READ_ATTRIBUTES`; in other words you can't list the directory, add or delete stuff, etc.
`1179817 ` or `0x1200A9` is a whole set of rights. Check the constants in AccessMask to pull this apart.

Smbj actually has utility methods to convert the `int` value to a `Set<AccessMask>`. The access information class should probably make use of those.

**Comment by ecki** [comment]
Just a side note in many situations it is much better to simply try the operation you want to do and see if it fails, trying to re-implement alll semantics of access control often fails and you will get an error anyway. 

Of course in your specific case there might be a reaason not to. In that case you would probably have to check for intended operations  (I.e. list directory if you need to scan or read file if you open them blindly - write and delete accordingly)

**Comment by gauravpanday007** [comment]
Thanks a lot @pepijnve for your help. 
May I know what are those utility methods to convert int value to Set<AccessMask>?

**Comment by hierynomus** [comment]
`EnumWithValue.EnumUtils.toEnumSet(long, AccessMask.class);`

**Comment by gauravpanday007** [comment]
Thank you all for your help and suggestions. 

Now when I tried opening to call the open() using Access Mask: READ_CONTROL, I am getting com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): QueryInfo failed for SMB2FileId{persistentHandle=97 00 00 00 6d 00 00 00} exception even when the user is having the access. Please check my code snippet below:

com.hierynomus.smbj.share.DiskEntry remoteSmbjEntry = share.open(path, EnumSet.of(AccessMask.READ_CONTROL), null, null, SMB2CreateDisposition.FILE_OPEN, null);

System.out.println("Access Flag: " + remoteSmbjEntry.getFileInformation().getAccessInformation().getAccessFlags()); //Exception thrown on this line for getFileInformation.

I checked the set of access masks for which user has access using the below code. 

com.hierynomus.smbj.share.DiskEntry remoteSmbjEntry = share.open(filePath,
EnumSet.of(AccessMask.MAXIMUM_ALLOWED), null, null, SMB2CreateDisposition.FILE_OPEN, null);
int accessFlag = remoteSmbjEntry.getFileInformation().getAccessInformation().getAccessFlags();
				
Set<AccessMask> setAccessMask = EnumWithValue.EnumUtils.toEnumSet(accessFlag, AccessMask.class);
for(AccessMask mask: setAccessMask) {
	logger.info("Access Mask: " + mask);
}

Please help me in identifying what might be causing the problem.

**Comment by gauravpanday007** [comment]
Hello guys,

I think I found the problem with my above code. I changed my code as below and it worked.

com.hierynomus.smbj.share.DiskEntry remoteSmbjEntry = share.open("path",
EnumSet.of(AccessMask.FILE_READ_ATTRIBUTES, AccessMask.FILE_READ_DATA), null, null, SMB2CreateDisposition.FILE_OPEN, null);
int accessFlag = remoteSmbjEntry.getFileInformation().getAccessInformation().getAccessFlags();
Set<AccessMask> setAccessMask = EnumWithValue.EnumUtils.toEnumSet(accessFlag, AccessMask.class);
for(AccessMask mask: setAccessMask) {
	System.out.println("Access mask: " + mask);
}

Now, I can open the directory or file with the Access mask I want and it does not open if access is not there. When access is not there, it throws below exceptions while opening:

1. For directory:
com.hierynomus.mssmb2.SMBApiException: STATUS_OBJECT_NAME_NOT_FOUND (0xc0000034): Create failed for <path to the directory>

2. For file:
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for <path to the file>

So, I can check whether the remote directory or file is shared with the user credentials I am passing or not. 

Please let me know if this is fine. Once again a lot of thanks for your time and help.

**Comment by gauravpanday007** [comment]
As my issue has been solved, I am closing this issue.
