### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by KevinMcT** [hierynomus/smbj#396]
Lib is great, and I'm currently using it.

However, my current implementation is set to version 0.5.1 of the library. And am currently planning on upgrading to the latest. And seeing that there is no changelog with each new release, I've got to manually go through the commits/issues to look for breaking changes and just push the version in to se what breaks.

Could we get a changelog with all new releases to track changes being made?

**Comment by TheRealHypo** [comment]
Any updates on that ? Currently using 0.9 but have no clue what's new in the Releases.

**Comment by l3ender** [comment]
Another request for changelog...thanks!
