### ISSUE TITLE
Question for signingRequired on SMB2NegotiateRequest

### ISSUE THREAD

**Issue by yin19941005** [hierynomus/smbj#398]
Hi @hierynomus,

I am wondering why the value assigned is `0x03` on this line : https://github.com/hierynomus/smbj/blob/14c50735c448ab36d55f351b425cc3c3b5034174/src/main/java/com/hierynomus/mssmb2/messages/SMB2NegotiateRequest.java#L73

I checked the git history, you had changed it from `0x02` to `0x03` on this commit https://github.com/hierynomus/smbj/commit/4521a31e9d301256efc47372411f9679cd422705.

Based on the [[MS-SMB2] document section `3.2.4.2.2.2 SMB2-Only Negotiate`](https://msdn.microsoft.com/en-us/library/cc246624.aspx?f=255&MSPPError=-2147217396), 

> If RequireMessageSigning is TRUE, the client MUST set the SMB2_NEGOTIATE_SIGNING_REQUIRED bit to TRUE in SecurityMode. If RequireMessageSigning is FALSE, the client MUST set the SMB2_NEGOTIATE_SIGNING_ENABLED bit to TRUE in SecurityMode. The client MUST store the value of the SecurityMode field in Connection.ClientSecurityMode.

Also on [[MS-SMB2] document section `3.2.4.2.2.2 SMB2-Only Negotiate`](https://msdn.microsoft.com/en-us/library/cc246543.aspx?f=255&MSPPError=-2147217396), 

> Value | Meaning
> -- | --
> SMB2_NEGOTIATE_SIGNING_ENABLED 0x0001 | When set, indicates that security signatures are enabled on the client. The client MUST set this bit if the SMB2_NEGOTIATE_SIGNING_REQUIRED bit is not set, and MUST NOT set this bit if the SMB2_NEGOTIATE_SIGNING_REQUIRED bit is set. The server MUST ignore this bit.
> SMB2_NEGOTIATE_SIGNING_REQUIRED 0x0002 | When set, indicates that security signatures are required by the client.

It sounds only one flag should be set on the client side. 

Any issue had encountered at that time to make this changes?

**Comment by hierynomus** [comment]
Yes, I think there were some issues indeed, not every server type correctly ignores the `ENABLED` bit. I need to do some digging.

**Comment by hierynomus** [comment]
See the comment on a9dc976. I've now set it to 0x02. If anyone will run into trouble, then we know why this was at 0x03. Thanks for spotting!
