### ISSUE TITLE
Check out the prototype of the camel integration of your library

### ISSUE THREAD

**Issue by cchet** [hierynomus/smbj#401]
Hello guys,
I have started to implement a camel component for your library, because there is no proper support for newer versions of the SMB protocol in camel. Maybe you find the time to take a look at it, and give me some feedback about the usage of your library. 

### This is the repository of the prototype:
https://github.com/cchet-camel-extras/camel-smbj
### This is the apache camel website:
http://camel.apache.org/
### See the following class where y our library is used: 
https://github.com/cchet-camel-extras/camel-smbj/blob/master/src/main/java/at/ihet/camel/extras/smbj/SmbFileOperations.java

Thank you for implementing and sharing of your SMBJ library.

**Comment by hierynomus** [comment]
Thanks for working on this. I'm wondering about the exact opposite, do you have any feedback on the APIs and ease of the library?

**Comment by cchet** [comment]
camel-smbj is an camel component for the camel framework for accessing smb shares in an enterprise integration environment (for instance with [RedHat Fuse 7](https://www.redhat.com/en/technologies/jboss-middleware/fuse)). Camel provides a camel-jcifs component, but this one uses [JCIFS](https://www.jcifs.org/) which only supports smb 1 and is maintenance only. During a consulting session for one of our customers, the need for an camel component supporting smb 2.x, 3.x shares came up and I started camel-smbj, which is actually a re-factored version of the camel-jcifs component. 

The API is already defined by the Camel framework and integrates smbj for accessing smb shares.

**Comment by hierynomus** [comment]
Closing this issue.
