### ISSUE TITLE
 API to copy the files from fileshare to my local machine

### ISSUE THREAD

**Issue by Vikas6206** [hierynomus/smbj#405]
I am new to SMBJ. Can anyone please let me know the  API to copy the files from fileshare (directory) to my local machine ?

**Comment by hierynomus** [comment]
From the `File` class:

https://github.com/hierynomus/smbj/blob/a9dc976595ebafd291e3313db391c3e7ce2964f0/src/main/java/com/hierynomus/smbj/share/File.java#L166-L173
