### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by tellisnz** [hierynomus/smbj#409]
Hi there,

Just wondering when the next release is that will include #400 and #402 ? Is it possible to push these as a patch release to maven?

Cheers,

Tom

**Comment by cliviu** [comment]
I subscribe to @tellisnz request. I know is not up to us to decide when the new release comes but just to let you know that is something there that is waiting for the fixes. Thanks again @hierynomus , @pepijnve for the amazing work !

**Comment by hierynomus** [comment]
Released 0.9.1 ;)

Good luck guys!

**Comment by cliviu** [comment]
This was quick :-) Thanks !
