### ISSUE TITLE
url smb://share:share@13.250.102.143/home/data/ Connection timeout

### ISSUE THREAD

**Issue by as8829412** [hierynomus/smbj#414]
jcifs.smb.SmbException: Failed to connect: 0.0.0.0<00>/13.250.102.143
jcifs.util.transport.TransportException: Connection timeout
	at jcifs.util.transport.Transport.connect(Transport.java:174)
	at jcifs.smb.SmbTransport.connect(SmbTransport.java:307)
	at jcifs.smb.SmbTree.treeConnect(SmbTree.java:156)
	at jcifs.smb.SmbFile.doConnect(SmbFile.java:911)
	at jcifs.smb.SmbFile.connect(SmbFile.java:954)
	at com.example.smbjdemo.utils.SmbUtil.init(SmbUtil.java:38)
	at com.example.smbjdemo.utils.SmbUtil.<init>(SmbUtil.java:22)

**Comment by hierynomus** [comment]
This is an exception from jcifs, not smbj

**Comment by as8829412** [comment]
![image](https://user-images.githubusercontent.com/31031777/49636073-861f9a80-fa3c-11e8-8f33-dd956fdbff86.png)





> This is an exception from jcifs, not smbj

This is my use smb code：
![image](https://user-images.githubusercontent.com/31031777/49636284-2249a180-fa3d-11e8-8b71-cb0b1840d1bd.png)
But also report connection problems
![image](https://user-images.githubusercontent.com/31031777/49636357-54f39a00-fa3d-11e8-9bf1-e09b0c0fd604.png)

**Comment by hierynomus** [comment]
The exception signals you have either a network problem, or the server is protected with a firewall

**Comment by as8829412** [comment]
> The exception signals you have either a network problem, or the server is protected with a firewall

thank you for your reply

**Comment by hierynomus** [comment]
@as8829412 Any update on whether you were able to solve it? Else I want to close the issue.
