### ISSUE TITLE
OutOfMemory error while doing an Excel file copy of size more than 200MB (few million records)

### ISSUE THREAD

**Issue by IrynaZhumatiy** [hierynomus/smbj#416]
Hello Team,

I have a problem during an Excel file copy of size more than 200MB (few million records) to network share.
It is occurred on this line of code:
arrayByteChunkProvider = new ArrayByteChunkProvider(IOUtils.toByteArray(fileInputStream), 0);

Could you please give me advice how can I fix this?
Thanks in advance!

**Comment by hierynomus** [comment]
Well, you have 2 options;

1. Increase the heap size of your JVM, as it is probably too small to contain the entirety of your file in memory.
2. Don't use `IOUtils.toByteArray` to load the entire file in memory, but rather us the `InputStreamByteChunkProvider` to stream the bytes.

**Comment by IrynaZhumatiy** [comment]
@hierynomus Thanks a lot for the quick reply!
And your second proposal has helped!
No error occurred!

**Comment by hierynomus** [comment]
Ok, closing this issue :)
