### ISSUE TITLE
Java 9-11 compatibility (illegal reflective access operation)

### ISSUE THREAD

**Issue by hdsdi3g** [hierynomus/smbj#425]
Any chance to ride of this anoying JVM message:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.hierynomus.security.jce.JceMessageDigest (file:/home/hdsdi3g/.m2/repository/com/hierynomus/smbj/0.9.1/smbj-0.9.1.jar) to method sun.security.provider.MD4.getInstance()
WARNING: Please consider reporting this to the maintainers of com.hierynomus.security.jce.JceMessageDigest
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Actually with this JVM:
```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Debian-2bpo91)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Debian-2bpo91, mixed mode, sharing)
```

Triggered by this code:
```
    /**
     * Special case, MD4 is available on Oracle JDK, but not enabled by default.
     *
     * @throws SecurityException If the MD4 digest could not be loaded
     */
    private void tryMd4(NoSuchAlgorithmException originalException) throws SecurityException {
        try {
            Class<?> md4Class = Class.forName("sun.security.provider.MD4");
            this.md = (java.security.MessageDigest) md4Class.getMethod("getInstance").invoke(null);
        } catch (ClassNotFoundException | IllegalAccessException | InvocationTargetException | NoSuchMethodException e1) {
            throw new SecurityException(originalException);
        }
    }
```

**Comment by yin19941005** [comment]
Hi @hdsdi3g,

Could you check the behavior with using ` --illegal-access=deny` command line flag? 

Based on this document (https://docs.oracle.com/en/java/javase/11/migrate/migration-guide.pdf), on section **Understanding Runtime Access Warnings** (on page 9), I guess it would throw `IllegalAccessException` when trying to the refection and this is already caught and re-throw the  `NoSuchAlgorithmException` on the code.

**Comment by Kabennsky** [comment]
Tested it on jdk-12.0.2 with using --illegal-access=deny command line flag as expected following is thrown:
com.hierynomus.security.SecurityException: java.security.NoSuchAlgorithmException: MD4 MessageDigest not available

Is this project still getting updates? A fix would be nice before Java blocks it.
WARNING: All illegal access operations will be denied in a future release

**Comment by hierynomus** [comment]
Yes, still working on it. Need to look into this.

Op do 3 okt. 2019 om 21:44 schreef Kabennsky <notifications@github.com>:

**Comment by kadirchisty** [comment]
Hi,
Below line is giving compile error when updated smbj jar to 0.10.0 version.

SMB2Echo responsePacket = new SMB2Echo();
responsePacket.getHeader().setStatus(NtStatus.STATUS_PATH_NOT_COVERED);

Compile error : The method setStatus(NtStatus) is undefined for the type SMB2Header

Trying to resolve below warnings:

WARNING: An illegal reflective access operation has occurred WARNING: Illegal reflective access by com.hierynomus.security.jce.JceMessageDigest (file:/C:/Users/s0wjvm/git/lhft/sr-lhft-parent/sr-lhft-web/webContent/WEB-INF/lib/smbj-0.6.0.jar) to method sun.security.provider.MD4.getInstance() WARNING: Please consider reporting this to the maintainers of com.hierynomus.security.jce.JceMessageDigest WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations WARNING: All illegal access operations will be denied in a future release

Please advice
