### ISSUE TITLE
Question: Is there any way to get correct directory size?

### ISSUE THREAD

**Issue by borsik** [hierynomus/smbj#429]
I'm trying to get correct directory size. `endOfFile` in `FileStandardInformation` works for file size, but for directories, it doesn't count nested files. Is there any way to correctly calculate nested file sizes without recursive traversal?

**Comment by pepijnve** [comment]
I assume you mean the total amount of disk space used by all the files underneath a particular directory. As far as I know there's no way to get that directly with a simple query.
Filesystem typically don't keep track of this information themselves (APFS being a notable exception). 

If I understand it correctly, the size of a directory is the size of the binary representation of the directory, i.e. the size of the internal representation of the list of direct children. That's not what you're looking for I think.
