### ISSUE TITLE
Is SMB v3.x in fact supportes in smbj-0.9.1?

### ISSUE THREAD

**Issue by grigsogomon** [hierynomus/smbj#432]
Below test code throws an exception saying "SMB 3.x support is not yet implemented". Exception is thrown from "SMB2NegotiateRequest.putCapabilities(SMBBuffer buffer)" method.

Below is the code snippet that opens the connection. The ides is to establish connection with server which supports any of the mentioned dialect version.

        SMB2Dialect [] supportedSmdDialects = {
                SMB2Dialect.SMB_2_0_2,
                SMB2Dialect.SMB_2_1,
                SMB2Dialect.SMB_2XX,
                SMB2Dialect.SMB_3_0,
                SMB2Dialect.SMB_3_0_2,
                SMB2Dialect.SMB_3_1_1
        };
        SmbConfig cfg = SmbConfig.builder().
                withDialects(supportedSmdDialects).
                withMultiProtocolNegotiate(true).
                build();
        SMBClient client = new SMBClient(cfg);
        Connection conn = client.connect(host);

Thanks,
Grigor

**Comment by hierynomus** [comment]
Hi Grigor,

Correct, SMB3 support has nog been implemented yet. So smbj itself cannot claim to support that dialect.

**Comment by hierynomus** [comment]
Merged to master with #455

**Comment by hierynomus** [comment]
0.10.0 does not yet contain the SMB3 support. This is only on master currently.

**Comment by mseleng** [comment]
Thanks for the info. Do you have any estimate when there might be a release?
Also, is master considered stable? I am just asking because the description states that this is SMB3 also.
