### ISSUE TITLE
Question: how to detect SMB version?

### ISSUE THREAD

**Issue by arif10520** [hierynomus/smbj#433]
I am using JCIFS library for windows share on android, recently started using smbj 0.9.1 for smb v2/3 support. I need to support all three smb v1/2/3. Is there a way using smbj to detect the windows share version, if it is smb v1, then I use JCIFS library?

**Comment by hierynomus** [comment]
Yes, configure `useMultiprotocolNegotiate()` in the `Config`. Then it
should throw a `SMBv1NotSupportedException` if the share only supports
SMBv1.

Op ma 18 feb. 2019 om 14:16 schreef arif10520 <notifications@github.com>:

**Comment by arif10520** [comment]
Thank you very much!

**Comment by hierynomus** [comment]
Closing this issue.
