### ISSUE TITLE
Is it necessary to display the logs about: "received packet and "Server granted...."?

### ISSUE THREAD

**Issue by gitvlad** [hierynomus/smbj#434]
Is it necessary to display the logs about: "received packet and "Server granted...."?

I have code like this:

`SMBClient client = new SMBClient();
		
		
		try (Connection connection = client.connect(SERVER_ADDRESS)) {
			AuthenticationContext ac = new AuthenticationContext(remoteUser, remotePass.toCharArray(), "domain.local");
			Session session = connection.authenticate(ac);
			// Connect to Share

			try (
					DiskShare share = (DiskShare) session.connectShare(SHARE_NAME)
					
					
					) 
			
			{`
![smb](https://user-images.githubusercontent.com/1778728/52956171-d8f7c580-338e-11e9-91ff-0625f2f55e93.PNG)

**Comment by pepijnve** [comment]
What is or is not printed is determined by the logging framework you're using. If you don't want smbj logging you should configure the log level for the respective packages and/or classes according to what you want to see logged.

**Comment by hierynomus** [comment]
In addition, this is all `debug` level logging, which you can turn off using your logging framework configuration as @pepijnve already indicated. I would suggest using `info` and higher. `debug` is useful during troubleshooting, which is why it is so verbose.

**Comment by gitvlad** [comment]
@hierynomus @pepijnve You're right. 
Sometimes the solutions are simple ;)

**Comment by hierynomus** [comment]
ok, closing this issue!
