### ISSUE TITLE
PacketReader error close to SMB2_NEGOTIATE

### ISSUE THREAD

**Issue by burkolter** [hierynomus/smbj#437]
I see a strange behaviour in the logs trying to establish a connection to a share. The server administrator of my client claims that SMB1, 2 and 3 are enabled. This issue is also only seen on a specific server. Unfortunatly, he doesn't provide any further information on the server.

We are using version 0.8.0 of the library.

Is it save to say that the server is not supporting SMB2?

Remote access on the machine is difficult as there are security restrictions. Hence, I could not do any other analysis on the system so far.

(NetworkUtil is a helper class to create a connection)
`05.03.2019 14:06:48,274 DEBUG NetworkUtil.getSmbClient - SMBJ transaction timeout (s): 120000
05.03.2019 14:06:48,275 DEBUG NetworkUtil.getSmbClient - SMBJ socket timeout (s): 5000
05.03.2019 14:06:48,275 DEBUG NetworkUtil.getSmbClient - SMBJ write buffer size (byte): 4194304
05.03.2019 14:06:48,277 DEBUG NetworkUtil.getSmbClient - SMBJ read buffer size (byte): 4194304
05.03.2019 14:06:48,539 DEBUG ProxySocketFactory.createSocket - Connecting to /172.17.0.13:445
05.03.2019 14:06:48,545 DEBUG PacketReader.start - Starting PacketReader on thread: Packet Reader for 172.17.0.13
05.03.2019 14:06:48,557 DEBUG Connection.negotiateDialect - Negotiating dialects [SMB_2_0_2, SMB_2_1] with server 172.17.0.13
05.03.2019 14:06:48,568 DEBUG Connection.send - Granted 1 (out of 1) credits to SMB2_NEGOTIATE with message id << 0 >>
05.03.2019 14:06:48,582 TRACE DirectTcpTransport.write - Acquiring write lock to send packet << SMB2_NEGOTIATE with message id << 0 >> >>
05.03.2019 14:06:48,583 DEBUG DirectTcpTransport.write - Writing packet SMB2_NEGOTIATE with message id << 0 >>
05.03.2019 14:06:48,604 TRACE DirectTcpTransport.write - Packet SMB2_NEGOTIATE with message id << 0 >> sent, lock released.
05.03.2019 14:06:48,612 INFO  PacketReader.run - PacketReader error, got exception.
com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readFully(DirectTcpPacketReader.java:72)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.readTcpHeader(DirectTcpPacketReader.java:59)
	at com.hierynomus.smbj.transport.tcp.direct.DirectTcpPacketReader.doRead(DirectTcpPacketReader.java:48)
	at com.hierynomus.smbj.transport.PacketReader.readPacket(PacketReader.java:69)
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:47)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: EOF while reading packet
	... 6 more
05.03.2019 14:06:48,616 DEBUG Promise.tryRetrieve - Awaiting << 0 >>
05.03.2019 14:06:48,633 DEBUG PacketReader.stop - Stopping PacketReader...
05.03.2019 14:06:48,633 ERROR Promise.tryRetrieve - << 0 >> woke to: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.io.EOFException: EOF while reading packet
05.03.2019 14:06:48,639 INFO  Connection.close - Closed connection to 172.17.0.13`

I'd also like to say thank you for this great library.

**Comment by burkolter** [comment]
I was having access to the remote "smb-client"-system. This indeed seems to be a version issue. The customer will make a last verification on the server itself.

**Comment by burkolter** [comment]
I suggest to close this issue. The customer is reluctant to hand me over the required information about the SAMBA config.

**Comment by hierynomus** [comment]
Ok, no problem. Feel free to re-open the issue if you've got more info.
