### ISSUE TITLE
What is the order to close the smb share, session, client?

### ISSUE THREAD

**Issue by subodhrathi** [hierynomus/smbj#444]
Hi,

This is my first time using the library.

I am getting following stack trace error while trying to close the share, connection, session, client in the following order.
share.close()
connection.close()
session.close()
client.close()

Can someone help me understand if I am doing something wrong here? I am building the client like this:
```
  val smbConfig = SmbConfig.builder()
      .withSigningRequired(true)
      .withDfsEnabled(true)
      .withMultiProtocolNegotiate(true)
      .withBufferSize(8*1024*1024)
      .withTransactTimeout(120, TimeUnit.SECONDS)
      .build()
    val client = new SMBClient(smbConfig)

```
```
ERROR Promise: << 13 >> woke to: {}
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Session requires signing, but packet SMB2_LOGOFF with message id << 13 >> was not signed
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:27)
	at com.hierynomus.smbj.common.SMBRuntimeException$1.wrap(SMBRuntimeException.java:21)
	at com.hierynomus.protocol.commons.concurrent.Promise.deliverError(Promise.java:95)
	at com.hierynomus.smbj.connection.OutstandingRequests.handleError(OutstandingRequests.java:88)
```

**Comment by subodhrathi** [comment]
Hi,

Any updates on this?

Thanks!

**Comment by subodhrathi** [comment]
Okay, so I removed session.close as it appears that when I close the share, the session is already getting disconnected. Kindly let me know if I am missing anything here.

**Comment by hierynomus** [comment]
Close in reverse order from opening... So share, session, connection, client



Op za 23 mrt. 2019 15:26 schreef subodhrathi <notifications@github.com>:

**Comment by subodhrathi** [comment]
So, I tried the sequence as suggested and below is the error I am getting now.
```
share.close
sssion.close
connection.close
client.close

```
```
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Session requires signing, but packet SMB2_LOGOFF with message id << 142 >> was not signed
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:29)
	at com.hierynomus.protocol.transport.TransportException$1.wrap(TransportException.java:23)
	at com.hierynomus.protocol.commons.concurrent.Futures.get(Futures.java:43)
	at com.hierynomus.smbj.session.Session.logoff(Session.java:240)
	at com.hierynomus.smbj.session.Session.close(Session.java:267)
```


Note: When I set withSigningRequired to false, it works fine but doesn't work with true. What does this setting do? In addition, I believe, we should keep withSigningRequired as true, right?

**Comment by subodhrathi** [comment]
Hi,

Any updates on this error?

Thanks!

**Comment by yin19941005** [comment]
Hi @subodhrathi,

It looks your server didn't sign the response packet for SMB2_LOGOFF. The `withSigningRequired` works fine in my testing env (both Windows Server 2012 R2 and 2016). What's the server are you using?

**Comment by subodhrathi** [comment]
Hi,

I will check the details of server and get back to you. Meanwhile, what is the workaround if server settings cannot be changed? What is the impact of changing "withSigningRequired" to false? Does it impact the security.

**Comment by subodhrathi** [comment]
Hi,

So I got this detail. It's a NAS (network attached storage) server which uses NetApp Array in the backend that provides NFS/CIFS protocol exports. There is no windows server underneath. Kindly let me know if this information is enough.

**Comment by yin19941005** [comment]
Hi,

The exception should be throw on this line: https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/smbj/connection/Connection.java#L446

I searched by the phase `Session requires signing` and only got one result in Smbj Library Code. You may double confirm by your own.

```
private void verifyPacketSignature(SMB2Packet packet, Session session) throws TransportException {
        if (packet.getHeader().isFlagSet(SMB2MessageFlag.SMB2_FLAGS_SIGNED)) {
            if (!session.getPacketSignatory().verify(packet)) {
                logger.warn("Invalid packet signature for packet {}", packet);
                if (session.isSigningRequired()) {
                    throw new TransportException("Packet signature for packet " + packet + " was not correct");
                }
            }
        } else if (session.isSigningRequired()) {
            logger.warn("Illegal request, session requires message signing, but packet {} is not signed.", packet);
            throw new TransportException("Session requires signing, but packet " + packet + " was not signed");
        }
    }
```

This means your server somehow didn't set the `signed` flag on the SMB2_LOGOFF response packet (assuming we parse the packet correctly) on a `SigningRequired` session. And I guess it is also high chance that it is not signed (the signature field is "empty") as well. 

In my point of view, this looks like the Server misbehavior rather than you didn't close the session correctly. I think you can confirm it by comparing to the behavior on connecting on Windows Server or checking the packet by WireShark. If this is the case, I guess you need checkout what's going on with NetApp Server.

> What is the impact of changing "withSigningRequired" to false? Does it impact the security.
Yes, it will impact the security. Without this option, the SMB client can sign the packet selectively (and the SMB Server need to sign the corresponding response). And this option is forcing the SMB client always sign the packet.

**Comment by subodhrathi** [comment]
Thank you for the details. I am not sure if much can be done on the server side. What are my other options?

1. Do not close the session which may in a period of time give me out of sessions error unless the opened session gets closed by server after a certain timeout period a day or 2 based on how the server is configured. I guess in this way atleast we are not compromising security but dealing with other risk of losing out on max sessions.

2. How to ensure that server signs the packet during logoff? From what I understand, packet is getting signed while the connection is getting established, also I am able to get the files however while logging off, the server is not signing the packet. Any other solution or references for this kind of behavior? Thanks again.

**Comment by subodhrathi** [comment]
I was looking at this article. Here it shows packet not signed. Is that what is happening with our NAS storage as well ? [Microsoft link]
(https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/a0a08d74-204e-464e-9db8-09fdaa6b3379)

**Comment by pepijnve** [comment]
> It's a NAS (network attached storage) server which uses NetApp Array in the backend that provides NFS/CIFS protocol exports.

@subodhrathi could you be a bit more specific about the type/model of NAS you're using. Is the NetApp providing the NAS services or is it being used as a block device in a SAN? If the NetApp is the NAS, which version of ONTAP is it running? If something else provides the NAS layer, what software are you using for that?

**Comment by hierynomus** [comment]
> I was looking at this article. Here it shows packet not signed. Is that what is happening with our NAS storage as well ? [Microsoft link]
> (https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/a0a08d74-204e-464e-9db8-09fdaa6b3379)

Yes, but the session in that example has not been setup with signing enabled. If you look at this part of the spec:

https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/d594481c-f6d5-4de5-8842-9099063d41e7

You see that the SMB2_LOGOFF message should be signed, as the first condition specifies:
- client signed the SMB2_LOGOFF request
- SMB2_LOGOFF contains a non-zero SessionId
- SMB2_LOGOFF contains a zero TreeId
- Session.SigningRequired = True for the Session identified by SessionId.

This really seems that the NetApp device is misbehaving.

**Comment by yin19941005** [comment]
> How to ensure that server signs the packet during logoff? From what I understand, packet is getting signed while the connection is getting established, also I am able to get the files however while logging off, the server is not signing the packet. Any other solution or references for this kind of behavior? 

Take a look on SMB2 document section 3.3.4.1.1 Signing the Message:
https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/d594481c-f6d5-4de5-8842-9099063d41e7

> The server SHOULD<195> sign the message under the following conditions:
> 
> If the request was signed by the client, the response message being sent contains a nonzero SessionId and a zero TreeId in the SMB2 header, and the session identified by SessionId has Session.SigningRequired equal to TRUE.
> 
> If the request was signed by the client, the response message being sent contains a nonzero SessionId, and a nonzero TreeId in the SMB2 header, and the session identified by SessionId has Session.SigningRequired equal to TRUE, if either global EncryptData is FALSE or Connection.ClientCapabilities does not include the SMB2_GLOBAL_CAP_ENCRYPTION bit.
> 
> If the request was signed by the client, and the response is not an interim response to an asynchronously processed request.

Of course, the SMB2_LOGOFF request will have nonzero SessionId to indicate which session to logoff and the client will sign the request when `SigningRequired` is TRUE. So, I don't think such valid case exist based on the SMB2 document.

**Comment by ecki** [comment]
As the logoff was processed most likely by the server you can maybe just catch and ignore the specific signing exception from `session.close();` and continue with closing the client?

**Comment by subodhrathi** [comment]
@ecki- I ended up doing the same eventually.

All - I will try to get more information on other comments.

**Comment by hierynomus** [comment]
Closing this due to age.
