### ISSUE TITLE
How do I know shareName

### ISSUE THREAD

**Issue by mrlsm** [hierynomus/smbj#448]
Hi，team： 
If I want to know only the IP address, I need to access all the files under this Shared file, is there an easy way to do this? 
Or how do I get all the subfiles under the Shared file？ （List all share files on computer）

Thanks for sharing

**Comment by hierynomus** [comment]
The functionality to list all shares is currently not (yet) in SMBJ. There is a separate library https://github.com/rapid7/smbj-rpc which uses SMBJ and implements this functionality.
