### ISSUE TITLE
Kerberos Authentication broken in OpenJDK 1.8 because of PR #373

### ISSUE THREAD

**Issue by dwissk** [hierynomus/smbj#449]
The current master contains code from PR #373 that breaks Kerberos authentication in OpenJDK 1.8.

Initialization of `com.hierynomus.smbj.auth.ExtendedGSSContext` fails because `com.sun.security.jgss.InquireType` cannot be cast to `com.sun.security.jgss.ExtendedGSSContext`.

```
java.lang.ExceptionInInitializerError
	at com.hierynomus.smbj.auth.SpnegoAuthenticator.authenticateSession(SpnegoAuthenticator.java:96)
	[...]
Caused by: java.lang.ClassCastException: Cannot cast com.sun.security.jgss.InquireType to com.sun.security.jgss.ExtendedGSSContext
	at java.lang.Class.cast(Class.java:3369)
	at java.lang.invoke.MethodHandles.insertArguments(MethodHandles.java:2378)
	at com.hierynomus.smbj.auth.ExtendedGSSContext.getKrb5GetSessionKeyFunction(ExtendedGSSContext.java:52)
	at com.hierynomus.smbj.auth.ExtendedGSSContext.<clinit>(ExtendedGSSContext.java:29)
     [...]
```

It seems to me that this could be fixed by changing the `pos` argument in [`ExtendedGssContext. getKrb5GetSessionKeyFunction()`](https://github.com/hierynomus/smbj/commit/bd1e608c986339793481a48b45ecb21b91a3d019#diff-e3c786664caa6ff023501f16ea4ee075R52) from

`return MethodHandles.insertArguments(handle, 0, getSessionKeyConst).asType(MethodType.methodType(Key.class, GSSContext.class));`

to
`return MethodHandles.insertArguments(handle, 1, getSessionKeyConst).asType(MethodType.methodType(Key.class, GSSContext.class));`

because apparently, in OpenJDK, the class of a method is listed as a parameter type when listing the paramter types using the MethodHandles.insertArguments method:

<img width="1283" alt="MethodHandle insertArguments openjdk" src="https://user-images.githubusercontent.com/3786617/55864811-82805980-5b7d-11e9-9d15-e1e369441f7b.png">

I am currently working around this by catching exceptions in `SpnegoAuthenticator`

```
Key key;
try {
   key = ExtendedGSSContext.krb5GetSessionKey(gssContext);
} catch (ExceptionInInitializerError | NoClassDefFoundError ex) {
   com.sun.security.jgss.ExtendedGSSContext e = (com.sun.security.jgss.ExtendedGSSContext) gssContext;
   key = (Key) e.inquireSecContext(InquireType.KRB5_GET_SESSION_KEY);
}
```

Now, this is hardly a good solution. If anybody can point me in the right direction, I'm happy to provide a PR.

**Comment by ecki** [comment]
Did you report that to OpenJDKs security-dev mailing list yet? (I don’t understand the issue completely to say if it would be a incompatibility they would want to fix)

**Comment by dwissk** [comment]
I don't think it's a security related but yes, could very well be an OpenJDK issue... I have not filed a report yet.

**Comment by pepijnve** [comment]
It’s indeed not a security issue. The code in question is calling methods of internal implementation classes via reflection. These parts of the GSS implementation are not part of JavaSE unfortunately.
Compatability issues like this are to be expected. The reflection setup code probably just needs to be made a bit more robust so that it can deal with various variants of those internal classes.
