### ISSUE TITLE
Exception after logoff

### ISSUE THREAD

**Issue by kprateek777** [hierynomus/smbj#45]
Hi hierynomus team,

I'm getting the exception

![image](https://cloud.githubusercontent.com/assets/13343959/25338521/2524f21c-291d-11e7-9935-70d929cc643d.png)

what could be the reason behind it?

Thanks,
Prateek

**Comment by hierynomus** [comment]
What does the client code look like? Are you calling `Connection.close()`?

**Comment by kprateek777** [comment]
I'm calling session.close() but not Connection.close()

**Comment by hierynomus** [comment]
Add a call to `connection.close()` then the packet reader will be closed correctly.

**Comment by hierynomus** [comment]
Reason behind this: The connection supports running multiple (simultaneous) different sessions. That's why you need to close it separately.

**Comment by kprateek777** [comment]
okay. I will do that and check. 

Thanks a lot for the quick reply!

**Comment by kprateek777** [comment]
One more question, if i close the connection is there a need to close the session?

**Comment by hierynomus** [comment]
No, closing the connection will first log off and close all sessions. So that is safe if you're not multiplexing multiple sessions in your client.

**Comment by kprateek777** [comment]
There is no multiplexing Sir. I removed session.close and added connection.close. I still get the error:
![image](https://cloud.githubusercontent.com/assets/13343959/25342417/a501b8b0-2929-11e7-84f8-9a130f0ab76e.png)

**Comment by hierynomus** [comment]
I don't see this happening when I for instance run this code: https://github.com/hierynomus/smb-client/blob/master/src/main/groovy/com/hierynomus/smbj/client/SmbjClient.groovy

Can you post your code?

**Comment by kprateek777** [comment]
I got that issue fixed with the implementation in the above code, closing share, session, and connection.
Thanks for this help.

I'm trying to watch directory for new files. Once watched setlastmodifiedtime to a fixed time to avoid looping.
Is there a way to setlastmodifiedtime of a file on unc using fileinformation just like it can be done using jav.io.File.setLastModifiedTime?

**Comment by hierynomus** [comment]
I don't think I currently have support for that.
Shouldn't you only check for files newer than `now()`? Then you don't need
to touch anything.

2017-04-25 14:55 GMT+02:00 kprateek777 <notifications@github.com>:

**Comment by kprateek777** [comment]
Actually along with that, once the file is transferred to target, I'm deleting the file from watch directory and if delete fails then setlastmodifiedtimeto some random time and don't try to delete it again.

Also, the exception```

Exception in thread "Packet Reader for test " Exception in thread "main" com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.smbj.transport.TransportException: java.net.SocketException: Connection reset
	at com.hierynomus.smbj.transport.PacketReader.run(PacketReader.java:52)
	at java.lang.Thread.run(Thread.java:745)

```
is not handled when connecting to smbv1.

**Comment by hierynomus** [comment]
@kprateek777 Is there anything left in this issue?

**Comment by kprateek777** [comment]
No Sir! Thank you very much for creating this.
