### ISSUE TITLE
Encrypt files during transit of file transfer

### ISSUE THREAD

**Issue by VenkatPurush** [hierynomus/smbj#450]
We are currently using JCIFS to transfer files from client to Server. Now that our file servers are being migrated to cloud, we would be required to encrypt the files during the transit of file transfer. Does  SMBJ library caters this requirement?

**Comment by dwissk** [comment]
AFAIK, transfer encryption is part of SMBv3, which is currently not yet supported by smbj.

**Comment by VenkatPurush** [comment]
> AFAIK, transfer encryption is part of SMBv3, which is currently not yet supported by smbj.

Thanks, do you have any suggestion as to which library to use for transfer encryption?

**Comment by dwissk** [comment]
I just saw that there is a smb3-dev branch, which has been updated just yesterday by PR #438. I suggest to close this issue and check that branch out.

**Comment by ecki** [comment]
Just a general comment, the protocol part which is framing and handshaking outside the encrypted and signed packets looks pretty complex and risky to me. If I where you I would not trust this to be enough for communication over untrusted networks. So while it is good to get the SMB3.1 features and turn them generally on. but for the case of accessing cloud storage I would add a VPN layer or revert to TLS wrapped connections like https.

**Comment by VenkatPurush** [comment]
> I just saw that there is a smb3-dev branch, which has been updated just yesterday by PR #438. I suggest to close this issue and check that branch out.

When will this branch be released and available in Maven repository?

**Comment by hierynomus** [comment]
@VenkatPurush The branch is currently under development, and has no set time to be merged. First some cleanup, additional functionality and extensive testing is needed... You are free to build it yourself and give it a spin!

**Comment by ekfrozenlady** [comment]
Hello,

Do you have any updates when encryption (SMBv3) support should be officially released?

**Comment by hierynomus** [comment]
Merged to master with #455

**Comment by aroudi** [comment]
I need to encrypt the files during the transit of file transfer. Does SMBJ library caters this requirement?
can you please give me a sample code for encrypting files with SMBJ?

**Comment by aroudi** [comment]
also which version of smbj support encryption?

**Comment by saurabh2391** [comment]
@hierynomus please take a look at above question?
