### ISSUE TITLE
How to change the timestamp of a file ?

### ISSUE THREAD

**Issue by SubhasishDey** [hierynomus/smbj#453]
How to change the timestamp of a file.
When I upload a file,t takes the current timestamp, I want to later change it to a different timestamp.

**Comment by hierynomus** [comment]
You can use `File.setFileInformation(new BasicFileInformation(...))` to set the different timestamps of a File.

**Comment by SubhasishDey** [comment]
Hi hierynomus,

Thanks for the quick reply.

I was using this code
com.hierynomus.smbj.share.File file = share.openFile(filepath, EnumSet.of(AccessMask.FILE_WRITE_ATTRIBUTES, AccessMask.FILE_WRITE_EA), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null);
			FileAllInformation fi = file.getFileInformation();
			FileBasicInformation bfi = new FileBasicInformation(creationTime, lastAccessTime, lastWriteTime, changeTime, fileAttributes);
			
			renameFile.setFileInformation(bfi);

But getting Access denied, although I have full permissions.

Any suggestions on this ?

**Comment by SubhasishDey** [comment]
I mean what are the exact AccessMask should I give to setFileInformation

**Comment by pepijnve** [comment]
If you want to be able to get the current info you'll have to request `READ_ATTRIBUTES` as well. When querying the 'AllInformation' level you might need `READ_EA` as well.

**Comment by SubhasishDey** [comment]
Thanks  @hierynomus and @pepijnve the suggestion worked for me.
