### ISSUE TITLE
file poller auto download

### ISSUE THREAD

**Issue by edwin20022** [hierynomus/smbj#460]
what parameter i can control  the smbj endpoint download the file content or not ? i found 
protected boolean isRetrieveFile() {
        return false;
}
, but i need the file poller scan but not download file content, download file content  when i matched file name pattern. 
Or, anybody tell me if smbj can do file name patter control? how? thx.....

**Comment by hierynomus** [comment]
Can you please rephrase your question clearer? I have no idea which classes or functionality you're talking about...

**Comment by edwin20022** [comment]
when i run the smbj, i get the OutOfMemoryError: Java heap space

I found that because 

      protected boolean isRetrieveFile() {
        return true;
      }
smbj will auto download file

![smbj](https://user-images.githubusercontent.com/37377000/56883111-4a8f7680-6a98-11e9-88d5-1111a8cdad80.PNG)

**Comment by ecki** [comment]
The retrieving and the OOM bug seems Camel  If it would use smbj correctly it would not store larger files in array. Not much smbj can do here,

**Comment by hierynomus** [comment]
Yes, indeed @edwin20022, you're addressing the wrong OS project. I'm the maintainer of the SMBJ library, not of the Camel integration. That is https://github.com/jborza/camel-smbj
