### ISSUE TITLE
Implement .equals()-method for Directory and File

### ISSUE THREAD

**Issue by zedharper** [hierynomus/smbj#464]
Hi,
the Directory and File classes don't implement a proper .equals()-method and instead fall back to the almost useless hashsum-implementation from Object.
This can make working with Directories and Files rather cumbersome.

An implementation should probably compare the `fileName `and `diskShare`.
Mind that DiskShare does not either implement a proper .equals()-method. For that, a .equals()-method could probably be implemented in the Share-class, comparing the `smbPath`.

Thanks in advance.

**Comment by hierynomus** [comment]
Ticket #465 was merged, solving this.
