### ISSUE TITLE
com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for

### ISSUE THREAD

**Issue by jeepMan79** [hierynomus/smbj#468]
Hi,

I'm trying to open a file on a Redhat share.  The user does not have the Execute bit set, but it does have the Read/Write bits set.  When I try to access the file for reading, I get

com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed for

If I set the execute bit, I can open just fine.   Any ideas why I would need the execute bit set?

Thanks!

**Comment by hierynomus** [comment]
What is the code you're using? Esp. The AccessMask etc

Op wo 22 mei 2019 19:41 schreef Garrett Rogers <notifications@github.com>:

**Comment by jeepMan79** [comment]
Apologies, I just re-read the faqs and the AccessMask permissions were set to high.  I'm closing the issue.
