### ISSUE TITLE
How can we create a new file object and get its type with SMBJ

### ISSUE THREAD

**Issue by Nirothipan** [hierynomus/smbj#470]
I'm trying to do an implementation  with SMBJ to transfer files from samba server.

May I know how can we define the type of the file in samba server with SMBJ

Thanks in advnace

**Comment by Nirothipan** [comment]
For example whether the file is a folder or ordinary file or how we can check whether it exists or not.

@hierynomus Could you help me on this query

**Comment by hierynomus** [comment]
@Nirothipan The methods on `DiskShare` should help you with that. You can check whether a pre-known path is a file or folder using the `fileExists` and `folderExists` methods. 

Also you can use `getFileInformation(<path>, FileStandardInformation.class)` and check whether the returned `FileStandardInformation` has `isDirectory` set.

**Comment by Nirothipan** [comment]
Thank you @hierynomus . Is there any working example I can refer to transfer files withing smb servers

**Comment by hierynomus** [comment]
@Nirothipan What do you mean with transfer within smb servers?

If the files are on different servers, just copy the inputstream to the outputstream. If the files reside on the same server, you can use the `File.remoteCopyTo(File)` method.

**Comment by hierynomus** [comment]
@Nirothipan Can this be closed?

**Comment by Nirothipan** [comment]
Yes please . Thank you for the assistance . I'll reopen if further clarifications required .
