### ISSUE TITLE
Question : How to connect to local share (//localhost/D$, //localhost/share) without credentials

### ISSUE THREAD

**Issue by vnashkev** [hierynomus/smbj#475]
An attempt to authenticate fails for 

> Connection c = client.connect("localhost");
AuthenticationContext auth = new AuthenticationContext("", new char[0], null);
c.authenticate(auth);

whereas the following works

> Connection c = client.connect("localhost");
AuthenticationContext auth = new AuthenticationContext(user, password, domain);
c.authenticate(auth);
   
OS is Windows 10, user@domain is the currently logged user.
Is there any way get it authenticated without credentials?

Thank you in advance.

**Comment by hierynomus** [comment]
Does your server allow unauthenticated (anonymous) access, or only guest access?

You can use the `AuthenticationContext.guest()` and `AuthenticationContext.anonymous()` methods to obtain the right AuthenticationContext.

What message(s) are you getting?

**Comment by hierynomus** [comment]
@vnashkev Any update? Else I'm closing this issue.
