### ISSUE TITLE
Possiblity to user regex in list()

### ISSUE THREAD

**Issue by NadigNikhil** [hierynomus/smbj#476]
Hello,

In DiskShare#list(String path, String searchPattern), can we pass regular expression in the **searchPattern** parameter to filter files based on regex. If yes, kindly provide a sample code, if not, is there any other means to pass regex to fetch files list.

Thanks in advance.

**Comment by neoxpert** [comment]
According to the MS-SMB2 spec the search pattern is the same as the one defined in MS-CIFS (https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-cifs/dc92d939-ec45-40c8-96e5-4c4091e4ab43). There is support for two wildcard characters but no support for full regular expressions.

If you want to use a regular expression to filter a directories file list you might have to get the full list and filter it afterwards.

**Comment by hierynomus** [comment]
@neoxpert supplied your answer, closing this issue.
