### ISSUE TITLE
bouncycastle version

### ISSUE THREAD

**Issue by dingdonghk** [hierynomus/smbj#479]
Is it ok if I use bouncycastle version 1.62 (bcprov-jdk15on-162.jar) instead of 1.60 (bcprov-jdk15on-1.60.jar) for smbj dependency ?
because I cannot find version 1.60 in the bouncycastle official website. Only the latest version can be found.

**Comment by hierynomus** [comment]
@dingdonghk That shouldn't be a problem, unless they would've dropped support for a specific algorithm we need. Note that the use of BC is recommended, but optional. You can use the library without BC in the classpath, just ensure that you configure the correct SecurityProvider, i.e.

```
SmbConfig.builder().withSecurityProvider(new JceSecurityProvider())
```

**Comment by dingdonghk** [comment]
thanks for your reply! :)
I use another security provider instead.

`SmbConfig cfg = SmbConfig.builder().withSecurityProvider(new BCSecurityProvider()).build();`
