### ISSUE TITLE
怎么获取文件的总长度呢？

### ISSUE THREAD

**Issue by tubeuchiha** [hierynomus/smbj#480]
.........
File smbFileRead = share.openFile("file.db", EnumSet.of(AccessMask.GENERIC_READ),
                                   null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null);

                           InputStream in = smbFileRead.getInputStream();

                           int length=in.available();

                           Log.e("SMBClient","length="+length);

这里打印的length 是0，请问怎么获取文件总长度呢？

**Comment by ecki** [comment]
Sorry, can’t read the question, but I wanted to mention that it is not (never) correct to use InputStream#available() to get the length of the stream.

**Comment by yin19941005** [comment]
Get the `FileStandardInformation` to have the total file size.

Should be something like:
```
FileStandardInformation info = diskEntry.getFileInformation(FileStandardInformation.class)
long endOfFile = info.getEndOfFile()
```

Check [MS-FSCC] 2.4.38 FileStandardInformation for more details.

By the way, @tubeuchiha, I suggest you could use translator (e.g. google translate, baidu translate, etc.) to translate the question before asking.

**Comment by hierynomus** [comment]
Please ask your question in English.

**Comment by jerrychong25** [comment]
Question in English: **How to get total length of file?**

**Comment by jerrychong25** [comment]
> Get the `FileStandardInformation` to have the total file size.
> 
> Should be something like:
> 
> ```
> FileStandardInformation info = diskEntry.getFileInformation(FileStandardInformation.class)
> long endOfFile = info.getEndOfFile()
> ```
> 
> Check [MS-FSCC] 2.4.38 FileStandardInformation for more details.
> 
> By the way, @tubeuchiha, I suggest you could use translator (e.g. google translate, baidu translate, etc.) to translate the question before asking.

Thanks for the solution, it works!
