### ISSUE TITLE
How to play video files?

### ISSUE THREAD

**Issue by Jallv** [hierynomus/smbj#485]
I can get files through smbj, but I don't know how to play video, music and picture files.

**Comment by ecki** [comment]
This project has a very specific scope, playing video is not related to it. You might better ask the question on StackOverflow or a Android forum (you did not say what Os you are looking at). (However in both cases it is unlikely you get an answer if the question is this broad).

I don’t know the Android multi media API, but I guess they would need to be provided with a stream handler (which does buffering) of some sorts (if you ask somewhere else, you might want to specify if you talk about streaming or downloading and then displaying the local file which is much easier).

**Comment by Jallv** [comment]
Thank you. I found a solution to convert SMB streams to HTTP streams through ServerSocket for other apps to access.

**Comment by tubeuchiha** [comment]
> This project has a very specific scope, playing video is not related to it. You might better ask the question on StackOverflow or a Android forum (you did not say what Os you are looking at). (However in both cases it is unlikely you get an answer if the question is this broad).
> 
> I don’t know the Android multi media API, but I guess they would need to be provided with a stream handler (which does buffering) of some sorts (if you ask somewhere else, you might want to specify if you talk about streaming or downloading and then displaying the local file which is much easier).

master branch is support smb 3 ??

**Comment by Jallv** [comment]
I need 24s to download an 8M image through InputStream. Is this normal?

**Comment by ecki** [comment]
It is certainly not a good number, but it depends on client, network and server speed. So it’s hard to say if this is good or bad. Did you check if the time is wasted on connecting the share or when opening the file or when downloading the data. If the time is spent early it might be DNS or DFS Retries (missconfiguration). What block size did you use for reading?

**Comment by Jallv** [comment]
I counted the InputStream read time, and the block size was 16384.

**Comment by Jallv** [comment]
`try {
                    SMBClient smbClient = new SMBClient(SmbConfig.builder()
                                                                 .withSigningRequired(true)
                                                                 .withDfsEnabled(true)
                                                                 .withMultiProtocolNegotiate(true)
                                                                 .withBufferSize(1028*1024*8)
                                                                 .build());
                    Connection connection=smbClient.connect("192.168.31.127");
                    Session session = connection.authenticate(new AuthenticationContext("name", "passworld".toCharArray(), ""));
                    DiskShare diskShare= (DiskShare) session.connectShare("F");
                    com.hierynomus.smbj.share.File smbInFile=diskShare.openFile("DSC_8450.JPG",
                            EnumSet.of(AccessMask.GENERIC_READ), null, SMB2ShareAccess.ALL,
                            SMB2CreateDisposition.FILE_OPEN, null);

                    int maxReadSize = diskShare.getTreeConnect().getSession().getConnection().getNegotiatedProtocol().getMaxReadSize();
                    byte[] buffer = new byte[maxReadSize];
                    long offset = 0;
                    long remaining = smbInFile.getFileInformation(FileStandardInformation.class).getEndOfFile();
                    Log.i("SharedInputStream", "file size=" + remaining);
                    File localOutFile = new File(getFilesDir() + "DSC_8450.JPG");
                    if (!localOutFile.exists()) {
                        localOutFile.createNewFile();
                    }
                    FileOutputStream out = new FileOutputStream(localOutFile);
                    while(remaining > 0) {
                        mMethodAverageTime.start();
                        int amount = remaining > buffer.length ? buffer.length : (int)remaining;
                        allSize+=amount;
                        Log.i("SharedInputStream", "allSize=" + allSize);
                        int amountRead = smbInFile.read(buffer, offset, 0, amount);
                        if (amountRead == -1) {
                            remaining = 0;
                        } else {
                            out.write(buffer, 0, amountRead);
                            remaining -= amountRead;
                            offset += amountRead;
                        }
                        mMethodAverageTime.end();
                    }
                    Log.i("SharedInputStream", "end");
                    out.close();
                    smbInFile.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }`
I download the file through this code. A 3M picture needs 18s. Please help me analyze the following reasons.

**Comment by Jallv** [comment]
I found that different Android versions have different transmission speeds

**Comment by neoxpert** [comment]
Is there a reason why you are using File.read insteaf of an InputStream. If I got it right, every call to File.read will create a new InputStream and that is a quite expensive operation.

**Comment by Jallv** [comment]
I found the reason for the time-consuming. The default packet signature BCSecurityProvider is very time-consuming in some versions of Android, such as Android 6.0 1M packet signature verification, which takes 6s.

**Comment by hierynomus** [comment]
Is this really an SMBJ issue?

**Comment by hierynomus** [comment]
Closing as this is not an smbj issue as far as this is now.
Feel free to reopen if you think I'm mistaken.
