### ISSUE TITLE
How to make signing disable in smbj

### ISSUE THREAD

**Issue by namjaejeon** [hierynomus/smbj#487]
Hello,

I would like to make signing disable in smbj.
Is there any way ?

Thanks.

**Comment by sergey-senozhatsky** [comment]
What Namjae meant was that `[MS-SMB2] 3.2.5.3.1 Handling a New Authentication` requires `!guest ` && `!anon` sessions to be signed only for SMB 3.x dialects. I don't see such a requirement for SMB 2.x dialects, while validateAndSetSigning() treats both SMB 2.x and SMB 3.x in the same way.

With this simple patch

<pre>
```

diff --git a/src/main/java/com/hierynomus/smbj/session/Session.java b/src/main/java/com/hierynomus/smbj/session/Session.java
index b43d259..fbe00d4 100644
--- a/src/main/java/com/hierynomus/smbj/session/Session.java
+++ b/src/main/java/com/hierynomus/smbj/session/Session.java
@@ -99,6 +99,11 @@ public class Session implements AutoCloseable {
         if (guest || anonymous) {
             packetSignatory.init(null); // De-initialize the signatory if it was initialized with a bogus key during the auth
         }
+
+       if (!connection.getNegotiatedProtocol().getDialect().isSmb3x()) {
+               if (!connection.getConfig().isSigningRequired())
+                       packetSignatory.init(null);
+       }
     }
 
     /**

```
</pre>

I can create an SMB2.1 session with disabled signing:

```

                       SmbConfig config = SmbConfig.builder()
                                       .withDialects(SMB2Dialect.SMB_2_1)
                                       .withSigningRequired(sign)
                                       .build();

                       this.client = new SMBClient(config);

```

-ss

**Comment by sergey-senozhatsky** [comment]
It seems that Windows client does not enforce signing for SMB 2.1 sessions.

-ss

**Comment by ecki** [comment]
I think the signing requirements for the windows client are a group policy. The SmbConfig would be the equivalent for smbj. (However the question is is signing is actually negotiated, in that case the decision if signing is done should be based on the result of the negotiation (in case the server requires signing, like for example with domain controller shares)

**Comment by sergey-senozhatsky** [comment]
> However the question is is signing is actually negotiated, in that case the decision if signing is done should be based on the result of the negotiation

That's a good question.

So for SMB2.x the solution **probably** may look as follows:
```
- "server signing = mandatory"  - definitely has a higher priority than SmbConfig;
- "server signing = disabled"   - has higher priority than SmbConfig;
- "server signing = auto"       - SmbConfig .withSigningRequired() wins;
- "server signing = default"    - SmbConfig wins.

```

-ss

**Comment by hierynomus** [comment]
I've just looked through the code and compared it to the MS-SMB2 spec. Except for the yet unimplemented SMB3.x.x dialect support, everything is implemented according to spec, so I'm not sure what the problem here is.

Signing is being negotiated by the SMB2_SESSION_SETUP message sequence. Unless someone can more clearly (with spec in hand) tell me what's going wrong, I'm inclined to close this issue.

**Comment by hierynomus** [comment]
@ecki  @sergey-senozhatsky  Any thoughts?

**Comment by sergey-senozhatsky** [comment]
@hierynomus Please feel free to close this issue.

-ss

**Comment by hierynomus** [comment]
Ok! Thanks for responding :)
