### ISSUE TITLE
Maven pom.xml has compile-time dependency on org.bouncycastle:bcprov-jdk15on:1.60

### ISSUE THREAD

**Issue by kpshek** [hierynomus/smbj#495]
With #394, a direct dependency on Bouncy Castle was removed 🎉.

However, [line 40 of the build.gradle still references Bouncy Castle](https://github.com/hierynomus/smbj/blob/v0.9.1/build.gradle#L40):

```gradle
dependencies {
  signature 'org.codehaus.mojo.signature:java17:1.0@signature'

  compile SLF4J_API
  compile BCPROV_JDK15ON
...
}
```

This results in the [Maven pom.xml of 0.9.1](https://search.maven.org/artifact/com.hierynomus/smbj/0.9.1/jar) having a compile-time dependency on Bouncy Castle:

```xml
<dependency>
  <groupId>org.bouncycastle</groupId>
  <artifactId>bcprov-jdk15on</artifactId>
  <version>1.60</version>
  <scope>compile</scope>
</dependency>
```

Is this intentional? Or was this just something that was overlooked in the #394 changes to remove Bouncy Castle?

**Comment by yin19941005** [comment]
Base on my understanding, they were not trying to remove whole Bouncy Castle dependency.  They were trying to remove the ASN.1 (encoding) dependency from Bouncy Castle only. The `com.hierynomus.security.bc` package still remains (prevents the need to use strong cryptography extensions).

FYI, the Bouncy Castle had breaks the ASN.1 backward compatibility on 1.60.

**Comment by kpshek** [comment]
Thanks for clarifying my understanding on this @yin19941005. You're right. Closing this issue.
