### ISSUE TITLE
Remote Copy Fail for DFS resolved files

### ISSUE THREAD

**Issue by mikhasd** [hierynomus/smbj#496]
I'm currently facing an issue while trying to execute a remote file copy: `SMBRuntimeException: Remote copy is only possible between files on the same server`.

After debugging smbj's code, I found what I believe is the root cause: Everytime a path is resolved by _DFSPathResolver_, a new nested session is created, even if there is already a session for that server+share. Futher on File.remoteCopyTo, the `destination.share != share` succeeds as the sessions instances are different and throw the exception.

My suggestions to fix it would be:

1. On `com.hierynomus.smbj.session.Session.buildNestedSession(SmbPath resolvedSharePath)`, lookup for simliar session on cached on `nestedSessions` list and use it instead of creating a new;
2. On `com.hierynomus.smbj.share.File.remoteCopyTo(File destination)`, instead of doing `destination.share != share`, implements `equals` on `DiskShare` and use it instead;

I'm not familiar with the whole smbj architecture, so I'd like to have some input before fixing it and sending a PR.

I have also found a potential issue on `Session.buildNestedSession` as it does not take into account SMB servers which might be using different ports while creating new connections.

**Comment by damartin1** [comment]
Is there an update on this? Release timeframe?

**Comment by mikhasd** [comment]
> 
> 
> Is there an update on this? Release timeframe?

**Comment by mikhasd** [comment]
I have patched the "broken" class in my project.
Not sure if the latest smbj release has it fixed.

**Comment by hierynomus** [comment]
This should be fixed now indeed
