### ISSUE TITLE
Missing com.hierynomus.asn1.types.primitive.ASN1ObjectIdentifier in smbj-0.9.1

### ISSUE THREAD

**Issue by umangsamani** [hierynomus/smbj#500]
Hey,

I downloaded smbj from the link - https://search.maven.org/artifact/com.hierynomus/smbj/0.9.1/jar.
I am trying to connect to a local sharepoint site.

At time of connection.authenticate(), it is throwing classNotFoundException for ASN1ObjectIdentifier.
I checked the .classes in the .jar file, and I am unable to see that class.

Am I missing something?

Thanks,
UmanG

**Comment by hierynomus** [comment]
Yes, you're missing the com.hierynomus:asn-one:0.4.0 jar.
Instead of directly copying the jar, use a build-tool such as maven or
gradle.

**Comment by umangsamani** [comment]
Thank you for the quick reply. I will have to download the jar, as my project is not on maven/gradle. :(
