### ISSUE TITLE
Packet signature error on SMB2_CREATE

### ISSUE THREAD

**Issue by ny4i** [hierynomus/smbj#504]
Hello,

I am trying to connect to a server that supports SMB2.02. I get the following error message: Packet signature for packet SMB2_CREATE with message id << 4 >> was not correct

I was not quite sure how to debug this further (as in what is message id << 4 >>)?

Is there a log can enable for more detailed tracing? I ask that as it appears there is support for more logging as I received an error loading a logging class.

In the code below, I originally tried it with no .builder but then decided to try to force the dialect. That made no difference. I am connecting to server that has an SMB implementation so it is not a real Windows server. But I can connect to this same server from Windows 10 systems that support only SMB2. I am trying to figure out what this class does not like...

Here is the simple code I used:

``` java
package com.tom.testShare;

import java.util.concurrent.TimeUnit;

import com.hierynomus.msfscc.fileinformation.FileIdBothDirectoryInformation;
import com.hierynomus.mssmb2.SMB2Dialect;
import com.hierynomus.smbj.SMBClient;
import com.hierynomus.smbj.SmbConfig;
import com.hierynomus.smbj.auth.AuthenticationContext;
import com.hierynomus.smbj.connection.Connection;
import com.hierynomus.smbj.session.Session;
import com.hierynomus.smbj.share.DiskShare;

public class TestClass {
	
	public static void main(String []args){
		new TestClass().test();
	}
	
	public void test(){
		try{
			SmbConfig config = SmbConfig.builder().withDialects(SMB2Dialect.SMB_2_0_2)
		            .withTimeout(120, TimeUnit.SECONDS) // Timeout sets Read, Write, and Transact timeouts (default is 60 seconds)
		            .withSoTimeout(180, TimeUnit.SECONDS) // Socket Timeout (default is 0 seconds, blocks forever)
		            .build();

		    SMBClient client = new SMBClient(config);
		   Connection connection = client.connect("192.168.1.238");
		  AuthenticationContext ac = new AuthenticationContext("USERHERE", "PASSWORD".toCharArray(), "");
		     System.out.println("ac : " + ac);
		     Session session = connection.authenticate(ac);
		     System.out.println("session : " + session);
		     
		     DiskShare share = (DiskShare) session.connectShare("STATE");
		     System.out.println("share : " + share);
		     
		     for (FileIdBothDirectoryInformation f : share.list("", "*.*")) {
                        System.out.println("File : " + f.getFileName()); 
		     }
			
		 
		} catch(Exception e){
			System.out.println("Error is ...............:"+e.toString());
		}
		
	}
}
```

Here is the result of the run...

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ac : AuthenticationContext[USERHERE@]
session : com.hierynomus.smbj.session.Session@64c64813
share : DiskShare[\\192.168.1.238\STATE]
Error is ...............:com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.util.concurrent.ExecutionException: com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: Packet signature for packet SMB2_CREATE with message id << 4 >> was not correct

**Comment by hierynomus** [comment]
If you add logback to your dependencies, you should be able to see more logging. Which version of smbj are you using?

**Comment by ny4i** [comment]
Version 0.9.1 smbj-0.9.1.jar

I will look into the logging dependency.

**Comment by hierynomus** [comment]
Let me know if you have more logging

**Comment by hierynomus** [comment]
Do you have more logging? Or has it not occurred anymore?

**Comment by ny4i** [comment]
Sorry. We did not have more logging but we had to move on so we did this another way. If time permits, I will try again.
