### ISSUE TITLE
JCIFS to SMBJ

### ISSUE THREAD

**Issue by umangsamani** [hierynomus/smbj#508]
Team,

We are in a phase to move away from jcifs's usage and start using smbj implementation for the known obvious reasons.
After initial findings from existing codebase, we have found that we were mainly using three of jcifs classes viz. SmbFile, NtlmPasswordAuthentication & SmbException.

After going through the javadocs, there wasn't a clear understanding of how can I find the relevant match. Though I got the details of how to set the NTLM authentication by providing a config to the smbClient. 

Any help, will be helpful to me.

**Comment by hierynomus** [comment]
There is no direct 1-1 mapping. Have a look at the tests to see how the library can be used.

**Comment by ecki** [comment]
BTW, did you consider jCIFS-ng instead? I think the api won’t change and you can mix all SMB versions, so it might be the better solution for your case.

**Comment by umangsamani** [comment]
@hierynomus : Yes I have started looking at it. I thought if any guide or reference was available, I would have expedite the process. 
@ecki : Yes we tried to check jcifs-ng as well, but sensed as if much active development is not happening.

**Comment by hierynomus** [comment]
@umangsamani If you have any specific questions, feel free to ask them.
