### ISSUE TITLE
Access to encrypted drive

### ISSUE THREAD

**Issue by SubhasishDey** [hierynomus/smbj#510]
Hi,

      We are using the smbj library to access the SMB v2/v3 server.
      When the property Set-SmbServerConfiguration –RejectUnencryptedAccess is set to true, the login and upload fails.

     However when we disable this property, it starts working.

    When are the plans to cover the support for this in SMBJ.

Thanks and Regards,
Subhasish

**Comment by hierynomus** [comment]
This switch enforces the SMB3 dialect with encryption enforced. There is a WIP branch for this, which I do need to finish.

**Comment by SubhasishDey** [comment]
Thanks for the reply...
As we have some commitments for this, can I expect any near timeline for the release for this to the public ?

**Comment by ecki** [comment]
If you make commitments it’s probably best to compile the code yourself. It would actually help if you try it out before it is released.

**Comment by hierynomus** [comment]
Merged to master with #455
