### ISSUE TITLE
SMBApiException: STATUS_OTHER (0xc0000279): Create failed for

### ISSUE THREAD

**Issue by jz36** [hierynomus/smbj#514]
Hello!
I'm trying to create file on remote machine by SMB with your library. 
And i'm getting this error. Can you help me?

code example:

        `SMBClient client = new SMBClient();

        Connection connection = client.connect("machine.name");

        AuthenticationContext ac = new AuthenticationContext("username", "password".toCharArray(), "domain.com");

        Session session = connection.authenticate(ac);

        DiskShare share = (DiskShare) session.connectShare("shareName");

        Set<FileAttributes> fileAttributes = new HashSet<>();

        fileAttributes.add(FileAttributes.FILE_ATTRIBUTE_NORMAL);

        Set<SMB2CreateOptions> createOptions = new HashSet<>();

        createOptions.add(SMB2CreateOptions.FILE_RANDOM_ACCESS);

        Set<AccessMask> accessMasks = new HashSet<>(Collections.singletonList(AccessMask.GENERIC_ALL));

        share.openFile(
                "path/to/folder/test.txt",
                accessMasks,
                fileAttributes,
                SMB2ShareAccess.ALL,
                SMB2CreateDisposition.FILE_OVERWRITE_IF,
                createOptions
        );`

**Comment by hierynomus** [comment]
The returned status is:

```
0xC0000279   STATUS_IO_REPARSE_TAG_NOT_HANDLED | The layered file system driver for this I/O tag did   not handle it when needed.
```

I have no direct idea how to fix that. @pepijnve do you know what that means?

**Comment by jz36** [comment]
So, have any ideas what could be wrong?

**Comment by ecki** [comment]
What server and what configuration is this. Is there some DFS at play? Does it happen on all shares and path of this server? What reparse mountpoint are on the server?  Maybe named volume mounts? Cluster volumes? What Filesystem is it?

**Comment by hierynomus** [comment]
Closing this issue, I've added the status to make it more clear which status is returned, other than that this seems a server side issue.
