### ISSUE TITLE
Different implementations of TransportLayerFactory

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#517]
There are three different implementations of TransportLayerFactory
1. AsyncDirectTcpTransportFactory
2. DirectTcpTransportFactory
3. TunnelTransportFactory

I have seen a lot of examples using AsyncDirectTcpTransportFactory. I would like to know why AsyncDirectTcpTransportFactory is used always .

**Comment by hierynomus** [comment]
Mainly because that was the hardest to debug :) DirectTcpTansportFactory creates a synchronous transport, Async... makes for an asynchronous transport, better for multi-threaded apps. 

The TunnelTransport is for connecting through a tunnel or proxy host.

**Comment by felixRajkumar** [comment]
Thanks for your definition. This is my configuration 
`SmbConfig smbConfig = SmbConfig
                .builder()
                .withMultiProtocolNegotiate(true)
                .withTransportLayerFactory(new AsyncDirectTcpTransportFactory<>())
                .withSigningRequired(true).build();

My aim is to read a file and encrypt the data with maximum security. Does setting the withSigningRequired to true help me achieve the maximum security?
