### ISSUE TITLE
Implementation of  Session Encryption

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#518]
Hi,
    This is my code which reads a file read.txt and write it to the location writer.txt. Can anyone suggests any ways to make the session completely encrypted?.There are different ways like NTLM and GSS . But now SMBv3 could support AES-CCM. How can I implement it here? 

`        try (Connection connection = client.connect(myIP)) {

            AuthenticationContext ac = new AuthenticationContext(userName, passWord.toCharArray(), domain);
            Session session = connection.authenticate(ac);
            try (DiskShare share = (DiskShare) session.connectShare(SHARE_NAME))
            {
                Set<SMB2ShareAccess> s = new HashSet<>();
                s.add(SMB2ShareAccess.ALL.iterator().next()); 

                com.hierynomus.smbj.share.File remoteSmbjFile =  share.openFile("read.txt", EnumSet.of(AccessMask.GENERIC_READ), null, s, SMB2CreateDisposition.FILE_OPEN, null);
                java.io.InputStream is = remoteSmbjFile.getInputStream();
                java.io.OutputStream os = new FileOutputStream("D:\\writeHere\\writer.txt");
                Files.copy(Paths.get("D:\\read.txt"), os);
                                 remoteSmbjFile.close();      
               }
            }`

**Comment by ecki** [comment]
The smb3 and encryption support is not yet finished, it is developed here: https://github.com/hierynomus/smbj/commits/smb3-dev

**Comment by felixRajkumar** [comment]
May I know when it will be completed, because I have to implement the advanced encryption for file transfer.

**Comment by felixRajkumar** [comment]
Thanks for replying, I have gone through this link [](https://github.com/hierynomus/smbj/pull/438). May I now when this will be merged with master branch?

**Comment by felixRajkumar** [comment]
Thanks for replying, I have gone through this link [https://github.com/hierynomus/smbj/pull/438](url) . May I now when this will be merged with master branch?

**Comment by felixRajkumar** [comment]
> The smb3 and encryption support is not yet finished, it is developed here: https://github.com/hierynomus/smbj/commits/smb3-dev

I have gone through this link. May I know when this will be merged with master Thanks in advance

**Comment by felixRajkumar** [comment]
Hi @hierynomus . May I know when the encryption support will be merged with the master.

**Comment by hierynomus** [comment]
Merged to master with #455
