### ISSUE TITLE
Multichannel support SMBv3

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#519]
SMBv3 offers multichannel feature . Does smbj library has implemented Multichannel support? If yes what changes have to be done in below config.

`SmbConfig smbConfig = SmbConfig
                .builder()
                .withMultiProtocolNegotiate(true)
                .withTransportLayerFactory(new AsyncDirectTcpTransportFactory<>())
                .withSigningRequired(true).build();`

**Comment by hierynomus** [comment]
There is no support for this yet. First order of business is getting minimum required SMB3 support in. This is an optional part of the SMB3 dialect.

**Comment by niravravalhighq** [comment]
Hi @hierynomus ,
May we know, any expected timeline for new SMBJ release with minimum required SMB3 support ?
Thanks

**Comment by hierynomus** [comment]
Encryption support is merged to master with #455
