### ISSUE TITLE
File being held open after created and written to. 

### ISSUE THREAD

**Issue by djhamilton** [hierynomus/smbj#522]
I am using the latest version: com.hierynomus:smbj:0.9.1
But i am experiencing an issue i cannot figure out why. 
When i create the file and write to the file, After i close the action the file still appears to remain open by the application. 
This means nothing can open, append or delete the file as it is (In use) 
The only way to release the file is to close down the application, I have gone through everything an am a bit stuck, i don't know if this is me using the API incorrectly or if this is a known issue. 

import com.hierynomus.msdtyp.AccessMask;
import com.hierynomus.msfscc.FileAttributes;
import com.hierynomus.mssmb2.SMB2CreateDisposition;
import com.hierynomus.mssmb2.SMB2CreateOptions;
import com.hierynomus.mssmb2.SMB2ShareAccess;
import com.hierynomus.mssmb2.SMBApiException;
import com.hierynomus.smbj.SMBClient;
import com.hierynomus.smbj.SmbConfig;
import com.hierynomus.smbj.auth.AuthenticationContext;
import com.hierynomus.smbj.connection.Connection;
import com.hierynomus.smbj.session.Session;
import com.hierynomus.smbj.share.DiskShare;
import com.hierynomus.smbj.share.File;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Arrays;
import java.util.HashSet;

 public class NetworkLogon {

    // connection paramsStaticLoggerBinder
    static String sambaDomain = null; // can be null
    static String sambaUsername = "guest";
    static String sambaPass = "";
    static String sambaIP = "192.168.1.230";
    static String sambaSharedPath = "Folder";

    public static void main(String[] args, final String message) throws IOException {

        String filename = "test.txt";

        SmbConfig cfg = SmbConfig.builder().build();
        SMBClient client = new SMBClient(cfg);
        Connection connection = client.connect(sambaIP);
        Session session = connection.authenticate(new AuthenticationContext(sambaUsername, sambaPass.toCharArray(), sambaDomain));
        DiskShare share = (DiskShare) session.connectShare(sambaSharedPath);

        // this is com.hierynomus.smbj.share.File !
        File f = null;
        int idx = filename.lastIndexOf("/");

        // if file is in folder(s), create them first
        if (idx > -1) {
            String folder = filename.substring(0, idx);
            try {
                if (!share.folderExists(folder)) share.mkdir(folder);
            } catch (SMBApiException ex) {
                throw new IOException(ex);
            }

        }

        if (!share.fileExists(filename)) {
            f = share.openFile(filename,
                    new HashSet<>(Arrays.asList(AccessMask.GENERIC_ALL)),
                    new HashSet<>(Arrays.asList(FileAttributes.FILE_ATTRIBUTE_NORMAL)),
                    SMB2ShareAccess.ALL,
                    SMB2CreateDisposition.FILE_CREATE,
                    new HashSet<>(Arrays.asList(SMB2CreateOptions.FILE_DIRECTORY_FILE))
            );
        }
        if (f == null) return;

        OutputStream os = f.getOutputStream();
        os.write(message.getBytes());
        os.flush();
        os.close();
    }
}

**Comment by pepijnve** [comment]
You need to close the file handle as well, not just the output stream. Calling `f.close()` should do the trick.

**Comment by djhamilton** [comment]
Thank you kind sir!
