### ISSUE TITLE
Question about a shared file and STATUS_DELETE_PENDING

### ISSUE THREAD

**Issue by mikepoz59** [hierynomus/smbj#524]
Using this in a project and occasionally we get an exception with STATUS_DELETE_PENDING as the message for a "sharedfile" that was deleted when iterating through the results of directory.getFiles().

I looked for documentation (no wiki exists), and also in the actual code but it's unclear.

Will sharedFile.isExisting() return false if STATUS_DELETE_PENDING is set?

If the answer to the above question is no, how do I work around this? Any suggestions would be appreciated if a workaround is needed.

Thank you!
Mike Poz

**Comment by hierynomus** [comment]
`STATUS_DELETE_PENDING` will return `false` for `share.fileExists(file)` or `share.folderExists(folder)`.

The status means that the file is marked for deletion, and when all access to the file is closed, it will be deleted.

**Comment by hierynomus** [comment]
@mikepoz59 Does this answer the question?

**Comment by mikepoz59** [comment]
Yes, apologies for the late response. Been in crunch mode at work.  Thank you!
