### ISSUE TITLE
SMBJ to Azure file share: STATUS_ACCESS_DENIED

### ISSUE THREAD

**Issue by markharrisintellihub** [hierynomus/smbj#527]
Using SMBJ v 0.10.0, I am unable to connect to a file share created in Azure.

Code:

SmbConfig smbConfig = SmbConfig.builder().build();
try (SMBClient client = new SMBClient(smbConfig); //
  Connection connection = client.connect(serverName)) {
  AuthenticationContext authenticationContext = new AuthenticationContext(username, password.toCharArray(), domain);
  Session session = connection.authenticate(authenticationContext);

It fails on the connection.authenticate line with this message:

Exception in thread "main" com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Authentication failed for '--user name--' using com.hierynomus.smbj.auth.NtlmAuthenticator@11c9af63

Here's some debug:

[main] INFO  c.h.smbj.connection.Connection - Successfully connected to: --server name--
[main] DEBUG c.h.smbj.auth.NtlmAuthenticator - Initialized Authentication of --user name-- using NTLM
[main] DEBUG c.h.smbj.connection.Connection - Granted 1 (out of 1) credits to SMB2_SESSION_SETUP with message id << 1 >>
[main] TRACE c.h.s.t.t.direct.DirectTcpTransport - Acquiring write lock to send packet << SMB2_SESSION_SETUP with message id << 1 >> >>
[main] DEBUG c.h.s.t.t.direct.DirectTcpTransport - Writing packet SMB2_SESSION_SETUP with message id << 1 >>
[main] TRACE c.h.s.t.t.direct.DirectTcpTransport - Packet SMB2_SESSION_SETUP with message id << 1 >> sent, lock released.
[main] DEBUG c.h.p.commons.concurrent.Promise - Awaiting << 1 >>
[Packet Reader for --server name--] DEBUG c.h.smbj.transport.PacketReader - Received packet com.hierynomus.mssmb2.SMB2PacketData@155738fa
[Packet Reader for --server name--] DEBUG c.h.smbj.connection.Connection - Server granted us 1 credits for com.hierynomus.mssmb2.SMB2PacketData@155738fa, now available: 1 credits
[Packet Reader for --server name--] TRACE c.h.smbj.connection.Connection - Send/Recv of packet com.hierynomus.mssmb2.SMB2PacketData@155738fa took << 42 ms >>
[Packet Reader for --server name--] DEBUG c.h.p.commons.concurrent.Promise - Setting << 1 >> to `SMB2_SESSION_SETUP with message id << 1 >>`
[main] DEBUG c.h.smbj.transport.PacketReader - Stopping PacketReader...
[main] INFO  c.h.smbj.connection.Connection - Closed connection to --server name--

I have successfully mapped a Windows network drive to the Azure file share on the same machine that I'm running this code, so I know I have access to the share.

The credentials I am using (serverName, username, password) are the ones displayed by Azure when I navigate to the file share and select the 'Connect' option. Domain is null.

Any help would be greatly appreciated - thank you.

**Comment by hierynomus** [comment]
I think Azure requires the encryption part of the SMB3 dialect. This is in the works, I hope to get some time soon to finish it.

**Comment by nddipiazza** [comment]
@hierynomus  any luck on this? we need this so will likely contribute to your branch to get this working. 
i'm checking to see if https://github.com/TalAloni/SMBLibrary supports it - if so we can just port the relevant code from c# to java.

**Comment by nddipiazza** [comment]
nope that only supports smb3.

**Comment by hierynomus** [comment]
Merged to master with #455
