### ISSUE TITLE
Check for Directory in file Iteration

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#529]
Hi @hierynomus @pepijnve ,
I have been iterating through files using smbj. I would like to know if there is any directory check like (isDirectory).My code is here

` for (FileIdBothDirectoryInformation fileEntry : share.list(destinationFolder)) {
                    String fileName = fileEntry.getFileName(); }`

**Comment by ecki** [comment]
Not sure if it is populated, but you should normally see the `FileAttributes.   FILE_ATTRIBUTE_DIRECTORY` bit be set in `fileEntry.getFileAttributes()`

**Comment by andershermansen** [comment]
You can, like this:
```
if (EnumWithValue.EnumUtils.isSet(fileEntry.getFileAttributes(), FileAttributes.FILE_ATTRIBUTE_DIRECTORY)) {
  // this is a directory
}
```

**Comment by felixRajkumar** [comment]
Thanks a lot @andershermansen @ecki . This works
