### ISSUE TITLE
Dot characters shown while Listing all files in a share

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#530]
Hi @hierynomus @pepijnve, while iterating through  the file I am getting dot characters.May I know why am I getting this.My code is given below

`for (FileIdBothDirectoryInformation fileEntry : share.list("sample Logs\\")) {
System.out.println(fileEntry.getName());
}`

The following is my output

> .

> ..

> folder1

> testFile.txt

**Comment by pepijnve** [comment]
Because the servers send those entries in its response. Smbj is a low-level SMB library that pretty much hands you exactly what the server responded. If you don't want these entries you have to filter them out yourself.

**Comment by pepijnve** [comment]
See https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/ab8e7558-899c-4be1-a7c5-3a9ae8ab76a0 for more details on what `.` and `..` represent.

**Comment by felixRajkumar** [comment]
> See https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-fscc/ab8e7558-899c-4be1-a7c5-3a9ae8ab76a0 for more details on what `.` and `..` represent.

This helps thanks a lot.
