### ISSUE TITLE
listing only shared Folders

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#532]
Hi ,
     Is it possible to list only the files that are shared by the administrator by means of smbj library.For Example if the user has shared only D drive . Only the D drive should be listed while listing the files

**Comment by ecki** [comment]
Can you define what you mean with "files shared by administrator"? Do you mean files in a share owned by Administrator, do you mean files in a share readable to you or do you mean a list of shares on the server?

**Comment by felixRajkumar** [comment]
Okay, I will explain that with an illustration. For Example ,there are 3 local drives C:\\ , D:\\ ,E:\\. I have shared only my E:\\ to everyone for reading. I haven't shared C:\\ or D:\\ . In this case while using listfiles functions of smbj is it possible not to list the files that are not shared by me @ecki .Here I would like to show only E:\\ while I am listing and not any other due to security purposes.

**Comment by ecki** [comment]
This is what is called *listing shares* and it is not provided by smbj, since it does not use the SMB protocol.

Here is an add-on which does that: https://github.com/rapid7/smbj-rpc#ms-srvs-server-service-remote-protocol-httpsmsdnmicrosoftcomen-uslibrarycc247080aspx

**Comment by felixRajkumar** [comment]
> This is what is called _listing shares_ and it is not provided by smbj, since it does not use the SMB protocol.
> 
> Here is an add-on which does that: https://github.com/rapid7/smbj-rpc#ms-srvs-server-service-remote-protocol-httpsmsdnmicrosoftcomen-uslibrarycc247080aspx

So what you are saying is I have to use remote calls to get shares, am I right?. I found this code there, is this what you meant

`final SMBClient smbClient = new SMBClient();
try (final Connection smbConnection = smbClient.connect("aaa.bbb.ccc.ddd")) {
    final AuthenticationContext smbAuthenticationContext = new AuthenticationContext("username", "password".toCharArray(), "");
    final Session session = smbConnection.authenticate(smbAuthenticationContext);

    final RPCTransport transport = SMBTransportFactories.SRVSVC.getTransport(session);
    final ServerService serverService = new ServerService(transport);
    final List<NetShareInfo0> shares = serverService.getShares();
    for (final NetShareInfo0 share : shares) {
        System.out.println(share);
    }
}`

**Comment by felixRajkumar** [comment]
` try (final Connection smbConnection = smbClient.connect("felix-9050")) {
            final AuthenticationContext smbAuthenticationContext = new AuthenticationContext("username", "password".toCharArray(), "");
            final Session session = smbConnection.authenticate(smbAuthenticationContext);

            final RPCTransport transport = SMBTransportFactories.SRVSVC.getTransport(session);
            final ServerService serverService = new ServerService(transport);
            final List<NetShareInfo1> shares = serverService.getShares1();
            for (final NetShareInfo1 share : shares) {
                System.out.println(share+"   "+share.getType());


            }
        }`
With the above code we can get the specific type of a share and determine if it is a disk drive admin or IPC admin. If the admin has shared the folders the type will be 0. Therefore we can differentiate between the admin shared folders or drives and admin drives. Thanks a lot @ecki 

For more info on type check this [https://docs.microsoft.com/en-us/windows/win32/cimwin32prov/win32-share](url)

**Comment by pepijnve** [comment]
@felixRajkumar the document you want to consult for this is actually the [[MS-SRVS] specification](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/accf23b0-0f57-441c-9185-43041f1b0ee9). In particular see [2.2.2.4 Share Types](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/6069f8c0-c93f-43a0-a5b4-7ed447eb4b84)

**Comment by felixRajkumar** [comment]
> @felixRajkumar the document you want to consult for this is actually the [[MS-SRVS] specification](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/accf23b0-0f57-441c-9185-43041f1b0ee9). In particular see [2.2.2.4 Share Types](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/6069f8c0-c93f-43a0-a5b4-7ed447eb4b84). You'll get to the same values in the end, but [MS-SRVS] is the specification that actually describes the interface of the RPC service you're communicating with.

Yes I do agree with you. But my motto is to differentiate between the resources shared by the admin and the resources that are not shared by the admin.
