### ISSUE TITLE
Listing drives and shared folders

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#533]
Hi,
     Is it possible to list drives and shares by means of smbj. When I try to list the shares of a host, I should get their drives and their shared paths.

`
        try (Connection connection = client.connect("host")) {

            AuthenticationContext ac = new AuthenticationContext(userName, passWord.toCharArray(), domain);

            Session session = connection.authenticate(ac);

            try (DiskShare share = (DiskShare) session.connectShare(""))
            {

                for (FileIdBothDirectoryInformation f : share.list(""))
                {
                    System.out.println("File : " + f.getFileName());
                }
            }
        }`
why does this doesnt work?

**Comment by ecki** [comment]
As already explained, smbj does not have a function to do this. With the RPC add-On You can only list shares, not the drives which are not shared. The listing only shows drives the user has access to. If you have problems with the RPC method, I would ask in that project. BtW it's better to not open multiple Tickets for the same questions.

**Comment by felixRajkumar** [comment]
Got it
