### ISSUE TITLE
DiskShare already Closed

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#534]
Hi, While trying ti read a file I am getting the following exception. Can anyone help me with it.

> `Caused by: java.lang.NullPointerException
|
[16:43:45:042]|[02-26-2020]|[SYSERR]|[INFO]|[218]: com.hierynomus.smbj.common.SMBRuntimeException: DiskShare has already been closed|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.Share.send(Share.java:351)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.Share.readAsync(Share.java:244)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.File.readAsync(File.java:149)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.FileInputStream.sendRequest(FileInputStream.java:147)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.FileInputStream.loadBuffer(FileInputStream.java:117)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.FileInputStream.read(FileInputStream.java:72)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at java.io.BufferedReader.fill(BufferedReader.java:161)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at java.io.BufferedReader.readLine(BufferedReader.java:324)|
[16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at java.io.BufferedReader.readLine(BufferedReader.java:389)|`

**Comment by felixRajkumar** [comment]
> Hi, While trying ti read a file I am getting the following exception. Can anyone help me with it.
> 
> > `Caused by: java.lang.NullPointerException | [16:43:45:042]|[02-26-2020]|[SYSERR]|[INFO]|[218]: com.hierynomus.smbj.common.SMBRuntimeException: DiskShare has already been closed| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.Share.send(Share.java:351)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.Share.readAsync(Share.java:244)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.File.readAsync(File.java:149)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.FileInputStream.sendRequest(FileInputStream.java:147)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.FileInputStream.loadBuffer(FileInputStream.java:117)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at com.hierynomus.smbj.share.FileInputStream.read(FileInputStream.java:72)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at java.io.InputStreamReader.read(InputStreamReader.java:184)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at java.io.BufferedReader.fill(BufferedReader.java:161)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at java.io.BufferedReader.readLine(BufferedReader.java:324)| [16:43:45:043]|[02-26-2020]|[SYSERR]|[INFO]|[218]: 	at java.io.BufferedReader.readLine(BufferedReader.java:389)|`

My code goes below

` try (Connection connection = smbClient.connect(username)) {
                AuthenticationContext ac = new AuthenticationContext(username, importProtocolBean.getPassword().toCharArray(), domain);
                Session session = connection.authenticate(ac);
                DiskShare diskShare = (DiskShare) session.connectShare(shareName);
                InputStream inputStream;
                ImportFileProperties fileProperties;
                Set<SMB2ShareAccess> s = new HashSet<>();
                s.add(SMB2ShareAccess.ALL.iterator().next());
                File remoteFile = diskShare.openFile(extractedFilePath, EnumSet.of(AccessMask.GENERIC_READ), null, s, SMB2CreateDisposition.FILE_OPEN, null);
                inputStream = remoteFile.getInputStream();
                fileProperties = new ImportFileProperties(false, location + java.io.File.separator + fileName, logProperties);
                fileSource = FileUtils.getBufferReaderList(inputStream, fileProperties, logProperties);
                InputStream finalInputStream = inputStream;`

**Comment by felixRajkumar** [comment]
The following is my code

` try (Connection connection = smbClient.connect(username)) {
                AuthenticationContext ac = new AuthenticationContext(username,importProtocolBean.getPassword().toCharArray(), domain);
                Session session = connection.authenticate(ac);
                DiskShare diskShare = (DiskShare) session.connectShare(shareName);
                InputStream inputStream;
                ImportFileProperties fileProperties;
                Set<SMB2ShareAccess> s = new HashSet<>();
                s.add(SMB2ShareAccess.ALL.iterator().next());
                File remoteFile = diskShare.openFile(extractedFilePath, EnumSet.of(AccessMask.GENERIC_READ), null, s, SMB2CreateDisposition.FILE_OPEN, null);
                inputStream = remoteFile.getInputStream();
                fileProperties = new ImportFileProperties(false, location + java.io.File.separator + fileName, logProperties);
                fileSource = FileUtils.getBufferReaderList(inputStream, fileProperties, logProperties);
                InputStream finalInputStream = inputStream;`

**Comment by felixRajkumar** [comment]
The following is my code

`AuthenticationContext ac = new AuthenticationContext(username, importProtocolBean.getPassword().toCharArray(), domain);
                Session session = connection.authenticate(ac);
                DiskShare diskShare = (DiskShare) session.connectShare(shareName);
                InputStream inputStream;
                ImportFileProperties fileProperties;
                Set<SMB2ShareAccess> s = new HashSet<>();
                s.add(SMB2ShareAccess.ALL.iterator().next());
                File remoteFile = diskShare.openFile(extractedFilePath, EnumSet.of(AccessMask.GENERIC_READ), null, s, SMB2CreateDisposition.FILE_OPEN, null);
                inputStream = remoteFile.getInputStream();`

**Comment by felixRajkumar** [comment]
I saw this [https://github.com/hierynomus/smbj/issues/531](url) .Actually I am using a single smbclient instance for every fileoperations like getting file size, reading ,checking file existence. Will this really could cause the issue.

**Comment by hierynomus** [comment]
It definitely can be, or you're calling `close` somewhere on the diskshare after which you're trying to re-use it.

**Comment by felixRajkumar** [comment]
May I know why the error occurs when the smbclient object is reused @hierynomus

**Comment by pepijnve** [comment]
The root cause is not the reuse in and of itself. It's most likely caused by reusing a client or share object that you're accidentally closing somewhere in your code.

A similar question was asked in #395.

**Comment by felixRajkumar** [comment]
> The root cause is not the reuse in and of itself. It's most likely caused by reusing a client or share object that you're accidentally closing somewhere in your code.
> 
> A similar question was asked in #395.

I check my code. I haven't closed the diskshare . Actually I could get the inputfilestream when I read the file. But when I use bufferedReader.readLine() I am getting the error

**Comment by andershermansen** [comment]
> I check my code. I haven't closed the diskshare . Actually I could get the inputfilestream when I read the file. But when I use bufferedReader.readLine() I am getting the error

I saw in your earlier code snippets that you used try-with-resources, that will close. You should share your complete code sample for review.

**Comment by felixRajkumar** [comment]
Here is my code

` try (Connection connection = smbclient.connect(username)) {
                AuthenticationContext ac = new AuthenticationContext(username, importProtocolBean.getPassword().toCharArray(), domain);

                Session session = connection.authenticate(ac);

                DiskShare diskShare = (DiskShare) session.connectShare(shareName);

                java.io.InputStream inputStream;

                ImportFileProperties fileProperties;

                Set<SMB2ShareAccess> s = new HashSet<>();

                s.add(SMB2ShareAccess.ALL.iterator().next());

                File remoteFile = diskShare.openFile(extractedFilePath, 
EnumSet.of(AccessMask.GENERIC_READ), null, s, SMB2CreateDisposition.FILE_OPEN, null);

                inputStream = remoteFile.getInputStream();

                fileProperties = new ImportFileProperties(false, location + java.io.File.separator + fileName, logProperties);

                fileSource = FileUtils.getBufferReaderList(inputStream, fileProperties, logProperties);

                java.io.InputStream finalInputStream = inputStream;

                fileSource.addFutureTasks(new FutureTask<>(() -> {
                    if (finalInputStream != null) {
                        finalInputStream.close();
                    }
                    return null;
                }));`

**Comment by andershermansen** [comment]
fileSource is used outside of the try-with-resources for the connection?

**Comment by felixRajkumar** [comment]
Man @andershermansen . You really saved my day. I removed the try block in connection, it worked. But I have a doubt . After I got the inputstream even If I close the connection it should work right?

**Comment by felixRajkumar** [comment]
> fileSource is used outside of the try-with-resources for the connection?

Yeah It was

**Comment by hierynomus** [comment]
@felixRajkumar Not to sound condescending, but you might want to read up on how Java IO and try-with-resources work... This has little to do with any library, but is plain basic Java knowledge.

**Comment by felixRajkumar** [comment]
> @felixRajkumar Not to sound condescending, but you might want to read up on how Java IO and try-with-resources work... This has little to do with any library, but is plain basic Java knowledge.

Actually I haven't implemented try with resources anywhere before I started using smbj. I am familiar with try catch statements alone. Anyway I will make sure I will learn that.Thanks a lot

**Comment by pepijnve** [comment]
> After I got the inputstream even If I close the connection it should work right?

You could implement it that way, but that would make the internal state tracking of the library much more complicated. Closing the connection closes the underlying TCP connection at which point you simply can't send requests to the server anymore.
The way smbj works is pretty standard as far as I know. For instance, this would not work either and is essentially the same thing:

```
InputStream i;
try (Socket s = new Socket(InetAddress.getByName("someserver"), somePort)) {
  i = s.getInputStream();
}
i.read();
```

To implement what you're describing, the connection would have to keep track of every open share. Each share would have to keep track of every open file. Every open file would have to keep track of every open input stream. And on and on.
When you close the connection it then needs to notice there are still open shares, files, ... and defer the actual close request. So the connection is kind of closed then but not really.
When you then close the input stream it would have to go back up the chain. Tell the file the stream was closed. If there are no more streams open, check if a deferred close of the file was requested and if so close the file. Then the file tells the share it closed. And so on. All the way up to the connection which can then finally really close itself. I don't think there's really a need for this added complexity.

**Comment by felixRajkumar** [comment]
> > After I got the inputstream even If I close the connection it should work right?
> 
> You could implement it that way, but that would make the internal state tracking of the library much more complicated. Closing the connection closes the underlying TCP connection at which point you simply can't send requests to the server anymore.
> The way smbj works is pretty standard as far as I know. For instance, this would not work either and is essentially the same thing:
> 
> ```
> InputStream i;
> try (Socket s = new Socket(InetAddress.getByName("someserver"), somePort)) {
>   i = s.getInputStream();
> }
> i.read();
> ```
> 
> To implement what you're describing, the connection would have to keep track of every open share. Each share would have to keep track of every open file. Every open file would have to keep track of every open input stream. And on and on.
> When you close the connection it then needs to notice there are still open shares, files, ... and defer the actual close request. So the connection is kind of closed then but not really.
> When you then close the input stream it would have to go back up the chain. Tell the file the stream was closed. If there are no more streams open, check if a deferred close of the file was requested and if so close the file. Then the file tells the share it closed. And so on. All the way up to the connection which can then finally really close itself. I don't think there's really a need for this added complexity.

I can understand this. But I need to surely close the connection before I send the inputstream to the next function.

I used the below code to copy my inputstream. Is there is any other efficient way of handling this
`Connection connection = null;
        try {
            connection = smbClient.connect(getUserCredentials().get("HOSTNAME"));
            AuthenticationContext ac = new AuthenticationContext(getUserCredentials().get("USERNAME"), getUserCredentials().get("PASSWORD").toCharArray(), getUserCredentials().get("DOMAIN"));
            Session session = connection.authenticate(ac);
            DiskShare diskShare = (DiskShare) session.connectShare(getShareInfo().get("SHARENAME"));
            java.io.InputStream inputStream;
            ImportFileProperties fileProperties;
            Set<SMB2ShareAccess> s = new HashSet<>();
            s.add(SMB2ShareAccess.ALL.iterator().next());
            File remoteFile = diskShare.openFile(getShareInfo().get("EXTRACTEDFILEPATH"), EnumSet.of(AccessMask.GENERIC_READ), null, s, SMB2CreateDisposition.FILE_OPEN, null);
            inputStream = remoteFile.getInputStream();
            PipedInputStream in = new PipedInputStream();
            TeeInputStream tee = new TeeInputStream(inputStream, new PipedOutputStream(in));
            fileProperties = new ImportFileProperties(false, location + java.io.File.separator + getShareInfo().get("FILENAME"), logProperties);
            fileSource = FileUtils.getBufferReaderList(tee, fileProperties, logProperties);
            java.io.InputStream finalInputStream = inputStream;
                return fileSource;
        } catch (BaseStatusCode baseStatusCode) {
            baseStatusCode.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }
        finally {
            try {
                connection.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }`

I used TeeInputStream and it worked. But it reduces the performance to extent. Is there is anyway of doing this

**Comment by pepijnve** [comment]
You have two options

1. Stream the file content to somewhere else (disk, in memory, ...) and return a stream pointing to that somewhere else
2. Stream the file contents directly from the server. In that case, create a wrapper InputStream that calls Connection#close when InputStream#close is called.

Which one makes the most sense depends on your application.

I do agree with @hierynomus that this is Java resource management 101. This is not really the appropriate forum for this type of question.

**Comment by felixRajkumar** [comment]
> You have two options
> 
> 1. Stream the file content to somewhere else (disk, in memory, ...) and return a stream pointing to that somewhere else
> 2. Stream the file contents directly from the server. In that case, create a wrapper InputStream that calls Connection#close when InputStream#close is called.
> 
> Which one makes the most sense depends on your application.
> 
> I do agree with @hierynomus that this is Java resource management 101. This is not really the appropriate forum for this type of question.

Understood. Thanks for the knowledge sharing everyone @pepijnve  @hierynomus  @andershermansen
