### ISSUE TITLE
Connecting to a local machine that is in workgroup

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#537]
Hi,
    Can anyone tell how to connect how to connect a machine which is in domain to a machine that is in workgroup.

` try(Connection connection = smbClient.connect(credential.getMachineName()))
            {
                AuthenticationContext ac = new AuthenticationContext(credential.getUserName(),credential.getPassword().toCharArray(), credential.getDomain());
                Session session = connection.authenticate(ac);
                DiskShare diskShare = (DiskShare) session.connectShare("C$");
            }`

**Comment by felixRajkumar** [comment]
This is my config

>         SmbConfig smbConfig = SmbConfig
                .builder()
                .withMultiProtocolNegotiate(true)
                .withEncryptData(true)
                .build();

**Comment by felixRajkumar** [comment]
I would like to elaborate on this. Example I am in a domain abc, and there was a Device that is a standalone which is not connected to any domains. Can I access that by means of smbj

**Comment by hierynomus** [comment]
What have you tried? What is the exception you're getting?

**Comment by ecki** [comment]
When you connect to/against a local windows account you normally sent the hostname of the target machine as the domain part HOSTNAME\User. This works with workgroups or stand-alone. Some implementations are a bit picky and would require instead the workgroup name or empty string "" or "." a single dot. Note that the hostname is the netbios name not the fully qualified name or address.
