### ISSUE TITLE
Creating a file on a network share

### ISSUE THREAD

**Issue by Simon192** [hierynomus/smbj#539]
Hey, 

I have a very simple question I guess.  I´m connecting to a network share and want to store pictures taken by my camera on this share.

I´ve set up the connection, removing files works fine, but how do I create files on the share?

Thanks in advance!

**Comment by ecki** [comment]
You open the file on the share and write to its output stream:

    c.h.smbj.share.File file = share.openFile(
      "file",
      EnumSet.of(AccessMask.GENERIC_WRITE),
      EnumSet.of(FileAttributes.FILE_ATTRIBUTE_NORMAL),
      SMB2ShareAccess.ALL,
      SMB2CreateDisposition.FILE_OPEN_IF,
      EnumSet.noneOf(SMB2CreateOptions.class)
    )
    OutputStream os = file.getOutputStream(); // or file.write()

**Comment by Simon192** [comment]
Thank you very much! Works perfectly
