### ISSUE TITLE
Closing DiskShare

### ISSUE THREAD

**Issue by felixRajkumar** [hierynomus/smbj#543]
Hi,
    I know that smb uses cached connections.I have a doubt related to that
    If I read a file in device A from D$ and I didn't close the connection.
    And I read a file in device B.
    Now if I again read a file from D$ or C$ , will it cause any issue.
    Also I have an another issue, I am reading a file through inputstream, If I close the diskShare will it 
    affect my input stream.

**Comment by hierynomus** [comment]
If device `A` and `B` are different clients, there is no cacheing between those
If you're reading an InputStream, you'd better not close the `DiskShare` until you're done with the stream. Closing it means that the resources are no longer reachable.

**Comment by felixRajkumar** [comment]
But if I access D$ of device A and with out closing the connection or diskShare , if I access the C$ of device A. It wont cause any issue due to caching right?

**Comment by hierynomus** [comment]
Not directly, but you will have 2 shares open. Keep in mind that teh server has a max opens typically

**Comment by hierynomus** [comment]
Can this be closed?

**Comment by hierynomus** [comment]
Closing as this seems answered.
