### ISSUE TITLE
DiskShare.mkdir creates only one directory 

### ISSUE THREAD

**Issue by AndreyFomichev** [hierynomus/smbj#544]
***DiskShare.mkdir*** creates only one directory in one call.

It is not possible to create several subdirectories per one call.
The request to implement ***DiskShare.mkdirs*** procedure which could create several nested directories in one call, for example, 2345 \ 3456 \ 4453 \ 123123.txt

**Comment by hierynomus** [comment]
Such a method could easily be implemented in a utility class, but I don't think it is necessarily a part of the DiskShare api

**Comment by hierynomus** [comment]
@AndreyFomichev I suggest you change the PR to move this utility method to the `SmbFiles` class.

**Comment by hierynomus** [comment]
This has been merged with #545
