### ISSUE TITLE
use guest account connect to MacOs floder error

### ISSUE THREAD

**Issue by zabio** [hierynomus/smbj#554]
Cannot require message signing when authenticating with a guest account

 val client = SMBClient()
            client.connect("192.168.0.140").use { connection ->
                val ac = AuthenticationContext.guest()
                val session: Session = connection.authenticate(ac)
                (session.connectShare("share") as DiskShare?).use {
                    val name = it?.smbPath?.path.noneNullStringValue()
                }
            }

**Comment by tooptoop4** [comment]
did u solve @zabio ?

**Comment by hierynomus** [comment]
Indeed, missed this issue, thanks for posting the solution @tooptoop4.

**Comment by dkocher** [comment]
- I don't see how `withMultiProtocolNegotiate(true)` should relate to this issue
- This is still reproducible with the following negotiated connection context where the server requires signing (macOS 13.5)

```
2023-09-01 22:18:43,951 [Thread-110] DEBUG com.hierynomus.smbj.connection.SMBProtocolNegotiator - Negotiated the following connection settings: ConnectionContext{
  serverGuid=b1561070-edef-9450-9ecf-a3fd46de52b6,
  serverName='silverbullet.local',
  negotiatedProtocol=NegotiatedProtocol{dialect=SMB_3_0_2, maxTransactSize=4194304, maxReadSize=4194304, maxWriteSize=4194304},
  clientGuid=5207d5fe-024d-4c03-bcb3-151ad0b276d6,
  clientCapabilities=[SMB2_GLOBAL_CAP_DFS, SMB2_GLOBAL_CAP_LARGE_MTU],
  serverCapabilities=[SMB2_GLOBAL_CAP_LEASING, SMB2_GLOBAL_CAP_LARGE_MTU],
  clientSecurityMode=1,
  serverSecurityMode=3,
  server='com.hierynomus.smbj.server.Server@1740b4de'
}
```
