### ISSUE TITLE
Treeing out entire directory 

### ISSUE THREAD

**Issue by david-upham** [hierynomus/smbj#555]
Can someone help me understand how smbj could allow me to search the entire share tree for folders of a specific name? So far I can only seem to search one folder deep.

**Comment by neoxpert** [comment]
Afaik there is no way to read or filter a whole directory tree within the SMB protocol itself. The easiest way would be to traverse the directory tree programatically.

**Comment by david-upham** [comment]
> 
> 
> Afaik there is no way to read or filter a whole directory tree within the SMB protocol itself. The easiest way would be to traverse the directory tree programatically.

The only issue with that is that there is a large overhead in traversing each folder structure one at a time. I need a tool designed to grab it all and then search the results. Thanks for your help though. :)

**Comment by hierynomus** [comment]
Closing this at it seems solved.
