### ISSUE TITLE
SMBv3 Features

### ISSUE THREAD

**Issue by eseanucristian** [hierynomus/smbj#556]
Hi,

What smb v3 features does the current version support?

Thanks.
Cristian

**Comment by ecki** [comment]
I think the master branch does not contain smb3 features, with the pending merge of the smb3 branch it will negotiate 3.1.1 dialect and support encryption an pre auth. integrity (As well as compressed and encrypted packets). See here https://github.com/hierynomus/smbj/pull/455/files

**Comment by willemvd** [comment]
@hierynomus any plans on finishing up on this feature?

**Comment by hierynomus** [comment]
Hi Willem, I had just started work on this again this week. Current progress is on the smb3 branch.

**Comment by Anju1610** [comment]
Hi @hierynomus ,

I am using smbj library 0.10.0 in my project. I want to know are there any features of SMB v3 supported by smbj as of now ?

Thanks,
Anju

**Comment by hierynomus** [comment]
Hi @Anju1610, I'm working on the #455 PR/branch to implement all of that. A lot of the plumbing is now done. The encryption of SMB3 is next.

**Comment by Anju1610** [comment]
Hi @hierynomus  ,

Is there any update/new features of SMV v3 added in smbj library ?

Thanks,
Anju

**Comment by niravravalhighq** [comment]
Hi @hierynomus , looks like  #455 seems ready to merge in Master branch.
Can you please provide info when to plan to release in master branch?
Thanks

**Comment by hierynomus** [comment]
Encryption and pre-auth is merged to master with #455. Compression is not done yet.
