### ISSUE TITLE
SMBRuntimeException : .Buffer$BufferException: Underflow

### ISSUE THREAD

**Issue by khilisharma** [hierynomus/smbj#565]
I'm trying to connect to Apple Time Capsule, and I'm facing Runtime Exception. For starter, I'm just using a simple scenario of listing down files from the Time Capsule. and below is my function. I have attached the stacktrace in here too. Smbj version is 0.10.0. Appreciate your help and time! Thank You. 
[stacktrace.txt](https://github.com/hierynomus/smbj/files/4842690/stacktrace.txt)
 

public void listFiles() throws IOException {
    SmbConfig cfg = SmbConfig.builder().build();
    SMBClient client = new SMBClient(cfg);

    try {
      Connection connection = client.connect(IP);
      AuthenticationContext ac = new AuthenticationContext(Username, Password.toCharArray(), null);
      Session session = connection.authenticate(ac);

      // Connect to Share
      DiskShare share = (DiskShare) session.connectShare(ShareName);
        for (FileIdBothDirectoryInformation f : share.list(SharedPath, "*")) {
          System.out.println("File : " + f.getFileName());
        }
    }
    catch (SMBException ex) {
      throw new IOException(ex);
    }
  }

**Comment by ecki** [comment]
Looks like TC somehow violates the SMB protocol. You would need to provide an network dump for more details.

However a quick search made me think that TC might only support SMB1 anyway, for this you  would need to use another library anyway.

BTW I do think smbj should catch the buffer under flow and wrap it as a protocol violation exception.

**Comment by khilisharma** [comment]
@ecki Hmm! I read more about it and looks like Apple has officially discontinued the TC long back ,and they apparently never offered any additional updates for the product, so no SMB2 or SMB3.1 support from Apple on this product. Also, I guess Windows does not authorize SMB1 anymore , and to set PC to SMB1 is not recommended as it is a significant security risk!!  I'm not sure if SMB 1.x on any local network should not be a security issue if  the local network is already secure. I never saw this coming when I thought of working on this! Sad day!! I'm trying to see how to capture the network dump though!

**Comment by Talwvs** [comment]
@khilisharma, @ecki  
I can confirm. In 2006 Apple has integrated a very old SMB1 only version and never upgraded to newer dialects.
The product was discontinued officially a couple of years ago.
This is true for the Time Capsule and Time machine.

**Comment by ecki** [comment]
If you use a java library for smb1 (jcifs(ng)) you don't need to enable smb1 on the Windows machine for it,

Dump would be good because this lib won't implement smb1, but it could produce better errors for your handshake case.

**Comment by khilisharma** [comment]
I added the dependency in my pom , this is how it looks like. Still getting the same error. I'm kind of a newbie here I'm sorry 
@ecki 
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.example</groupId>
    <artifactId>TimeCapsuleAdapter</artifactId>
    <version>1.0-SNAPSHOT</version>
    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>6</source>
                    <target>6</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    
    <dependencies>
    <dependency>
        <groupId>jcifs</groupId>
        <artifactId>jcifs</artifactId>
        <version>1.3.17</version>
    </dependency>
        
        <dependency>
            <groupId>com.hierynomus</groupId>
            <artifactId>smbj</artifactId>
            <version>0.10.0</version>
        </dependency>
        
        <dependency>
            <groupId>eu.agno3.jcifs</groupId>
            <artifactId>jcifs-ng</artifactId>
            <version>2.1.4</version>
        </dependency>
    </dependencies>
</project>

**Comment by khilisharma** [comment]
I added the dependency in my pom but it still gives me the same error. I'm sorry I'm a newbie here! 
@ecki 
<dependency>
            <groupId>eu.agno3.jcifs</groupId>
            <artifactId>jcifs-ng</artifactId>
            <version>2.1.4</version>
</dependency>

**Comment by ecki** [comment]
You will need to change your code, jCIFS is used differently than smbj. It's an other project.

**Comment by khilisharma** [comment]
okay so, I completely changed my code and you were right about how it can produce better errors!! Got a few errors and after some workarounds I'm finally able to read the contents of the file! 
@ecki Appreciate your help and time! Thank you so much! Now that I'm able to establish connection, I will now start on writing the APIs that I actually wanted to! 

Thanks once again!

[listFiles.txt](https://github.com/hierynomus/smbj/files/4848925/listFiles.txt)
