### ISSUE TITLE
Get list of all shares in a machine

### ISSUE THREAD

**Issue by kvk484** [hierynomus/smbj#566]
Hi 
Do smbj latest versions support listing of all shares in a machine?

**Comment by ecki** [comment]
No, this is not a smb function. The smbj-Rpc project supports that, see #274

**Comment by kvk484** [comment]
Thanks for the reply. Is smbj api backward compatible? 
Since smbj-rpc latest version using  0.8 version of smbj. But latest version of smbj is 0.10. In my env i want to use latest version of smbj for other use cases. So I want to understand if i can use smbj-rpc with 0.10 version of smbj

**Comment by ecki** [comment]
I guess you need to try it, maybe the smbj-rpc project would like to know the result as well.

**Comment by kvk484** [comment]
thank you. Closing this issue.

**Comment by kvk484** [comment]
Hi @ecki 
can you please tell the minimum user permissions required to list down all the shares ? I can get info level 0 , but not able to get info level 2.  what permission do i require for listing down level 0 infos  and what do i require for 2?

**Comment by ecki** [comment]
Sorry, no idea what level 0/2 is. And I don't know what the various server implementations have for permission requirements.

Just to be sure, shares are not hierarchical and shares/directories are differnt things.

**Comment by pepijnve** [comment]
@kvk484 this isn't really the appropriate forum for this type of question IMO. The smbj developers can help with issues in the library itself, but the basic workings of the SMB protocol and related RPC services is out of scope for a client library.

The documentation you're looking for is the [MS-SRVS specification](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/accf23b0-0f57-441c-9185-43041f1b0ee9). In particular the [NetrShareGetInfo](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/b2c2b995-8c42-4502-b7d7-646d1b295c5b#Appendix_A_Target_60) RPC call. All the way at the bottom you'll find

> The server SHOULD<60> enforce security measures to verify that the caller has the required permissions to execute this routine. If the caller does not have the required credentials, the server SHOULD<61> fail the call.

[Footnote 60](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-srvs/ebb74ff2-abb1-4e1b-a76a-563a5cbbea9a#Appendix_A_60) in turn links to the 'Product behaviour' which describes what the Windows SMB server specifically does:

> <60> Section 3.1.4.10: If the requested level is 2, 502, or 503, the Windows implementation checks to see whether the caller is in the Administrators, Server or Print Operators, or Power Users local group. No special group membership is required for other levels.

**Comment by kvk484** [comment]
Hi team
Thanks a lot for the info provided.  That was quite helpful. Will make sure , I will ask only smbj relevant questios here.
