### ISSUE TITLE
DiskShare.getFile does not set fileId on returned File

### ISSUE THREAD

**Issue by Pernicies** [hierynomus/smbj#57]
Hi folks,

I just started digging into smbj and the whole smb topic on the technical level and encountered a behaviour that I would not have expected when it came down to using an input stream.

So I connected to a share and retrieved a File object via the getFile method of the DiskShare class. Unfortunately this File object could not be used to create an input stream as it would fail with a NullPointerException when calling read on the input stream.

If I get it correctly it seems that the fileId of the underlying File object was not set by getFile method although the fileId was available in the retrieved FileInfo. Is there a reason that the fileId from the FileInfo was not used in the created File object or is it just missing?

Regards,

Pernicies

**Comment by hierynomus** [comment]
Indeed, it is a bug/shortcoming :) Fixing it in #58

**Comment by hierynomus** [comment]
Just did some checking, the FileId returned from the FileInformation object is not an actual SMB2FileId (it is only 8 bytes), it might be part of it.

I'll fix it by having File/Directory open on demand.

**Comment by pepijnve** [comment]
@hierynomus I fixed this in a branch I'm working on by opening the object and then determining if it's a file or directory based on the metadata in the create response.
See https://github.com/pepijnve/smbj/blob/fileops/src/main/java/com/hierynomus/smbj/share/DiskShare.java#L86

**Comment by hierynomus** [comment]
The PR for this is #71 now
