### ISSUE TITLE
smb2_query_dir:3608: no right to enumerate directory (/) 

### ISSUE THREAD

**Issue by Mile-Lile** [hierynomus/smbj#576]
When I try to connect to my server I get  autheticated and I can see my sharing folder. But when I try to view folder content I get: "STATUS_ACCESS_DENIED (32221225506 ///LAN/mile-lile/nas)" on my client side. Server throws: **smb2_query_dir:3608: no right to enumerate directory (/)** 

protocol used is SMB2_02

**Comment by hierynomus** [comment]
`STATUS_ACCESS_DENIED` means that the user you're doing this with does not have sufficient access rights to execute that on the share. Also your server indicates that.

**Comment by hierynomus** [comment]
This is not a problem with SMBJ, so closing this issue.
