### ISSUE TITLE
Is there a way to limit list of files when using DiskShare.list(String path, String searchPattern)?

### ISSUE THREAD

**Issue by skrradev** [hierynomus/smbj#581]
I have directory in SMB share where can exist over 100k .xml files. Right now I'm using `DiskShare.list(String path, String searchPattern)` method to list directory files.  I assume this method  loads all files information to memory, which is affects badly to performance. Is there a way to limit a list of files at server-side, like this example using `java.nio` ?
```
try(Stream<Path> walk = Files.walk(Paths.get(configuration.getMessages().getIn().getPath()))) {
            filesList = walk.limit(10000).map(x -> x.getFileName().toString())
                    .filter(it -> it.endsWith(".xml"))
```

**Comment by krivanekm-javlin** [comment]
Hi,

you can use [Directory.iterator()](https://www.javadoc.io/static/com.hierynomus/smbj/0.10.0/com/hierynomus/smbj/share/Directory.html#iterator-java.lang.Class-).

`
DiskShare share;
try (Directory d = share.openDirectory(path, of(FILE_LIST_DIRECTORY, FILE_READ_ATTRIBUTES, FILE_READ_EA), null, ALL, FILE_OPEN, null)) {
    return d.iterator(informationClass, searchPattern);
}
`
