### ISSUE TITLE
Automatic module name

### ISSUE THREAD

**Issue by jensli** [hierynomus/smbj#582]
Hello!

This project would befit from adding an automatic module name to the manifest of its jar-file.

```
ext.moduleName = "com.hierynomus.smbj"
jar {
    inputs.property("moduleName", moduleName)
    manifest {
       attributes  'Automatic-Module-Name': moduleName
   }
}
```
See this article:
http://branchandbound.net/blog/java/2017/12/automatic-module-name/

Without an automatic module name client code gets the following warning when building using Java >= 9:

```
Name of automatic module 'smbj' is unstable, it is derived from the module's file name.
```

**Comment by hierynomus** [comment]
Thanks, added this!

**Comment by jensli** [comment]
Nice! Thanks for a great library.

**Comment by jensli** [comment]
Is there any chance of a new release to Maven Central so I can start using this?

**Comment by hierynomus** [comment]
Yes, I'm merging a few long overdue PR's (#499 and #474) after which I wanted to carve out a new release.

**Comment by jensli** [comment]
Thanks for your work hiery!
