### ISSUE TITLE
Trouble reading image file as Java.io.File

### ISSUE THREAD

**Issue by jacattau** [hierynomus/smbj#593]
I am trying to retrieve a .png file type from a file share and read it as a java.io.File but I am having some trouble doing that.  I am able to access the drive and print out the list of files with no issues, so I am just confused on how to read the images as a File.

The code I trying to use to access the image is:
```
def getImageFromFileShare(String sourceImage){
     SMBClient client = new SMBClient(SmbConfig.createDefaultConfig())
     Connection c = client.connect("ip address")
     Session s = c.authenticate(new AuthenticationContext("user", "pass".toCharArray(), "") )
     DiskShare share = s.connectShare("share")
     return share.openFile("path/to/screenshots/image.png", EnumSet.of(AccessMask.FILE_READ_DATA), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null)
}
```

and then I need to be able to pass this to 
`BufferedImage bImage = ImageIO.read(src)`

but I am getting an error "Constructor 'File' in 'java.io.File' cannot be applied to '(com.hierynomus.smbj.share.File)'".  So I am just looking for some advice on how to do this. 

Thanks!

**Comment by ecki** [comment]
Java does not allow to extend java.io.File and there is no virtual interface. So if you need a file object you would need to copy the data to a temporary file or use a system under path or similar.

With jsmb you only can get Streams or RandomAccess interfaces to remote data.

**Comment by jacattau** [comment]
Thanks for the reply.  I could work with copying the file from the share to a local folder.  Is there a standard way of doing this?  I will fully admit I know enough java/groovy for automated testing but I am not super great when it gets to this more in depth and difficult stuff.

**Comment by ecki** [comment]
The java-like method is to open a input stream to the file and pump it to the FileOutputStream of a temp file. However i thin kthere is a more fancy buffer api (which is also used under the hoods of the input stream), we really should add a sample or maybe even a helper to do that pumping.

here for example are unofficial samples and some discussion with it.  https://github.com/hierynomus/smbj/issues/311

**Comment by hierynomus** [comment]
Something like this should get the job done. Note that all of the resources are closeable, so it's best to wrap them in a try-with-resources block.

```
def getImageFromFileShare(String sourceImage, java.io.File localImage) {
  SMBClient client = new SMBClient(SmbConfig.createDefaultConfig())
  try(Connection c = client.connect("ip address")) {
    try(Session s = c.authenticate(new AuthenticationContext("user", "pass".toCharArray(), ""))) {
      try(DiskShare share = s.connectShare("share")) {
        try(File remoteFile = share.openFile("path/to/screenshots/image.png", EnumSet.of(AccessMask.FILE_READ_DATA), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null))) {
          try (OutputStream os = new FileOutputStream(localImage)) {
            remoteFile.read(os)
          }
        }
      }
    }
  }
}
```

**Comment by hierynomus** [comment]
Does this solve it for you @jacattau ?

**Comment by jacattau** [comment]
I have not had a chance to try it yet, will try to find some time this week.

**Comment by hierynomus** [comment]
Any update? Then I can close this ;)

**Comment by jacattau** [comment]
I was able to get this to work.  Thank you!

**Comment by hierynomus** [comment]
Great!
