### ISSUE TITLE
Connect to the cifs server occur the error:Unable to parse the explicit Tagged Object With ASN1Tag[CONTEXT_SPECIFIC,CONSTRUCTED,1]...]

### ISSUE THREAD

**Issue by hello-willy** [hierynomus/smbj#595]
![微信图片_20201224123737](https://user-images.githubusercontent.com/9379589/103061020-e9110980-45e4-11eb-8282-5743aaea7cfe.jpg)

I don't know what the problem is?help！

**Comment by hierynomus** [comment]
Which version of SMBJ are you using?

**Comment by hello-willy** [comment]
the version that i used was 0.10.0, thank you!

**Comment by hello-willy** [comment]
> Which version of SMBJ are you using?

another fact was when i used the jcifs-ng:2.1.5, it worked! but i really like smbj, i don't want to replace it with jcifs-ng, help me pls, thank you!

**Comment by hierynomus** [comment]
I've pushed an update to master which depends on a new version of the `asn-one` library. Can you check to see whether that fixes you problem?

**Comment by hello-willy** [comment]
> I've pushed an update to master which depends on a new version of the `asn-one` library. Can you check to see whether that fixes you problem?

It Worked!!!Thank you!!, by the way, the current features would not be affected, am i right?

**Comment by hierynomus** [comment]
Nope, I'll close this issue!
