### ISSUE TITLE
Question: Is it possible to work with acl permissions on the connected shares? 

### ISSUE THREAD

**Issue by taijidude** [hierynomus/smbj#597]
Hello smb noob here, :-) 

i would like to connect to a share, create a new Folder and set the ACL rights to a certain user Group and a specific user.
I already figured out how to connect and create the new folder. But i'm struggling with working with the acl.  Is this possible with smbj? And if yes, how can i do this? Or where should i start to look?

**Comment by hierynomus** [comment]
This is possible using `DiskShare.setSecurityInformation(...)`

**Comment by taijidude** [comment]
Thank you. Will look it up.
