### ISSUE TITLE
DFSPathResolver.sendDfsReferralRequest does not cache IPC$ share connections causing slowness

### ISSUE THREAD

**Issue by nddipiazza** [hierynomus/smbj#604]
I notice that this is in a try-with-resources block. 

https://github.com/hierynomus/smbj/blob/accae9ea1a934e2755bff98bd26f4c0c54d9943e/src/main/java/com/hierynomus/smbj/paths/DFSPathResolver.java#L424

This makes it so that the DFS share resolution immediately removes this share from the `treeConnectTable` after getting the referral. 

The result of this is when DFS referrals are honored, smbj is many times slower because it constantly checks that over and over. 

Can we cache this and release share after a given time?

**Comment by hierynomus** [comment]
Your PR has been merged!
