### ISSUE TITLE
Logging is too verbose

### ISSUE THREAD

**Issue by sopak** [hierynomus/smbj#62]
I think we should change all occurrences of logger.info to logger.debug. With few exceptions as connect, disconnect and authenticate.

**Comment by gidravlic** [comment]
I support this issue

**Comment by sopak** [comment]
@hierynomus what is your opinion? Can I do this change?

**Comment by hierynomus** [comment]
Merged #83 to make logging a bit less verbose on INFO level. Now you just see the connecting/closing of the different domain objects.
