### ISSUE TITLE
Spnego token rejected

### ISSUE THREAD

**Issue by lukeisontheroad** [hierynomus/smbj#621]
Hi,

We do have our own custom implementation of the SpnegoAuthenticator which obtains a valid service token in a different way than from your provided sample. This used to work perfectly in version v0.10.0.

As we have the requirement for SMB 3.0 with encryption we upgraded to the latest master build, unfortunately our implementation is no longer working now. The commit that breaks the functionality is 78da5c8c9468efca37bfe631c03eacb807ea8e0e, and I tried to identify what might cause this issue, unfortunately without success so far. Do you have anything in mind that could be a breaking change that has been introduce with the refactoring?

**Comment by hierynomus** [comment]
Without knowing your code, or the exact problem you're seeing it is pretty hard to guess.
There are a number of changes to the Authenticator interface and classes:

- Authenticator no longer takes a `Session` on `authenticate(...)`, but rather the `ConnectionContext`

https://github.com/hierynomus/smbj/blob/78da5c8c9468efca37bfe631c03eacb807ea8e0e/src/main/java/com/hierynomus/smbj/auth/Authenticator.java#L29

- `AuthenticateResponse` no longer has a `signingKey`, but rather the `sessionKey` to make the terminology in line with the spec.

https://github.com/hierynomus/smbj/blob/78da5c8c9468efca37bfe631c03eacb807ea8e0e/src/main/java/com/hierynomus/smbj/auth/AuthenticateResponse.java#L20-L64

**Comment by dcale** [comment]
One thing worth noting (I'm working with @lukeisontheroad): 

- The new version works with some installations so the sessionKey can be negotiated successfully for _some_ environments.
- For this specific environment we manage to do the first "roundtrip" in GSS context establishment however when inputting the second input token our kerberos client complains and no context is established hence no session key is available.

As mentioned before this very environment works with older verisons of the lib, this brings up the question did something change in the GSS parameters/configurations?

**Comment by hierynomus** [comment]
GSS/SPNEGO is not directly changed. I don't think I can help without having more info. The authentication loop itself is moved from `Connection` to `SMBSessionBuilder`. It might be that if you compare those two you can find some discrepancy, but I cannot help you there I think. Your best bet is to do some debugging of your own authetnicator, or comparing that with the current implementation.

**Comment by hierynomus** [comment]
@dcale @lukeisontheroad Any progress on this?
