### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by 151058580845** [hierynomus/smbj#622]
Hello ,I have a lot of questions about How to use this library. Where can I refer to some examples

**Comment by hierynomus** [comment]
There are a lot of integration tests showing how to use the library to do various things. These can be found in the `src/it/groovy` directory. Furthermore there are a few basic examples in the README. 
If these are not sufficient, please describe more closely what you want to achieve.

**Comment by 151058580845** [comment]
Thank you for your reply. I'll have a look
