### ISSUE TITLE
samba version

### ISSUE THREAD

**Issue by 151058580845** [hierynomus/smbj#626]
How do I know the version of the connection Samba protocol

**Comment by hierynomus** [comment]
I'm not sure I understand the question. The protocol version is negotiated, depending on what the server supports and what you have configured in smbj to be allowed. In the logging you can see which protocol was selected.

**Comment by 151058580845** [comment]
The server comes in Samba 1,2,3 versions, but I now want to know which version of Samba I'm connecting to

**Comment by hierynomus** [comment]
You can configure SMBJ to require a certain SMB Dialect. For example:

```
SmbConfig config = SmbConfig.builder().withDialects(SMB2Dialect.SMB_3_0).withSecurityProvider(new BCSecurityProvider()).build();
SMBClient client = new SMBClient(config);
```

**Comment by jansohn** [comment]
This is how we log it:

```java
log.info("Connected to {} with Samba protocol {}", remoteSourceDir.getHostname(), connection.getNegotiatedProtocol().getDialect());
```

**Comment by hierynomus** [comment]
Once the connection is established, you can do the following:

```
Connection c = client.connect(host, ip);
SMB2Dialect dialect = c.getConnectionContext().getNegotiatedProtocol().getDialect();
```

This will get you the dialect that the connection is using.

**Comment by 151058580845** [comment]
I used this method, but when I connected to different versions of Samba, I always got the same data

**Comment by hierynomus** [comment]
I think you're mistaken the server version vs the negotiated protocol. The server version we cannot detect. And most samba server versions accept all versions of the SMB protocol (2.0, 2.0.2, 3.x)... So that just depends on what's negotiated during the connection setup.

**Comment by jansohn** [comment]
> 
> 
> Once the connection is established, you can do the following:
> 
> ```
> Connection c = client.connect(host, ip);
> SMB2Dialect dialect = c.getConnectionContext().getNegotiatedProtocol().getDialect();
> ```
> 
> This will get you the dialect that the connection is using.

Has this been refactored? Because I cannot find a `connection.getConnectionContext()` with latest version smbj 0.10.0...

**Comment by hierynomus** [comment]
Cool, can this be closed?

**Comment by vipsikka** [comment]
I'm currently utilizing the smbj 0.12 library for Scala. I have a question regarding the default SMB version: if I don't explicitly pass any dialect, will it default to SMBv2 or SMBv3?
