### ISSUE TITLE
Copy PDF file from internal storage to shared folder

### ISSUE THREAD

**Issue by matej-dostal** [hierynomus/smbj#629]
Hi, I can't seem to be able to copy pdf file located in internal storage of tablet to shared folder on PC. Could you please give me a push on how to do it?

**Comment by hierynomus** [comment]
I'm not sure what you're doing? But smbj is not an android app, so without a bit more involvement from your side on this ticket I cannot help you.

**Comment by matej-dostal** [comment]
I know it isn't app. I am using the library in my android app to connect to shared folder and create text files, etc. in the shared folder. It works just fine with text files. My app is also generating a pdf file from user input and saves it to internal storage of the device it's running on. And I need to copy/move this generated pdf file to the shared folder using smbj. Sorry for not describing it more specifically the first time. I hope it's clear now, if not, I will try to describe it more :)

**Comment by hierynomus** [comment]
What have you tried? What is the error that you're getting? Using `SmbFiles.copy(...)` it should "just work".

**Comment by matej-dostal** [comment]
I made stupid mistake, it works just fine. Thank you!
