### ISSUE TITLE
smb2 and smb3 config

### ISSUE THREAD

**Issue by tooptoop4** [hierynomus/smbj#639]
how to set smbconfig so that it supports reading from both smb2 and smb3? I guess below won't be able to read from both types?

```
SmbConfig
                            .builder()
                            .withMultiProtocolNegotiate(true).withDfsEnabled(true)
                            .withTransportLayerFactory(new AsyncDirectTcpTransportFactory<>())
                            .withSigningRequired(true).withSecurityProvider(new BCSecurityProvider()).build();

File smbFileRead = share.openFile(filePath, EnumSet.of(AccessMask.GENERIC_READ), null, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OPEN, null);
```

**Comment by hierynomus** [comment]
Yes, this should be enough, as the default setting for `withDialects` includes both SMB2 and SMB3 dialects.

**Comment by tooptoop4** [comment]
even these names with 2 in it? SMB2ShareAccess and SMB2CreateDisposition

**Comment by hierynomus** [comment]
Yes, SMB3 is just an extension of the SMB2 dialect. All class names are taken directly from the specification, they do not interfere with the SMB3 compatibility.

**Comment by hierynomus** [comment]
Does thsi answer your question?
