### ISSUE TITLE
Does hierynomus api's support Signed SMB

### ISSUE THREAD

**Issue by asivam** [hierynomus/smbj#651]
Hi ,

I would like to know if SMBJ10 supports signed SMB.Will hierynomus API's support operations like reading the file,browsing directory etc..

**Comment by hierynomus** [comment]
What is SMBJ10?
What do you mean with signed SMB?
Have you even looked at examples and README?

**Comment by asivam** [comment]
SMB signing essentially signs each packet with a digital signature so the client and server can confirm where they originated from as well as the authenticity of the call. When SMB signing is enabled, 
So will I be able to use hierynomus api's to read ..Yes I did look into the the examples, but nothing explicitly has been mentioned if signed SMB is supported.

**Comment by hierynomus** [comment]
SMBJ can both sign and encrypt traffic (if connecting to a SMB3 dialect compatible host)

**Comment by asivam** [comment]
Thanks for clarifying

**Comment by asivam** [comment]
1. Should any changes be done from the application side to handle the signed traffic or this will be handled internally by Smbj
2. Any version from which version of smbj the support for signed smb is provided.

Thanks

**Comment by hierynomus** [comment]
You can ensure that traffic is signed by passing `SmbConfig.builder().withSigningRequired(true).build()`
Signing is supported for all dialects.

**Comment by asivam** [comment]
Thanks once again for clarifying
