### ISSUE TITLE
Regression from 0.10.0: connecting to DFS no longer works 

### ISSUE THREAD

**Issue by bangert** [hierynomus/smbj#668]
in our SmbConfig object we enable DFS.

we give our smbj application urls like //domain.local/dfsbla/Sharename/folder/

and extract the servername to connect and authorize against - this works successfully in both 0.10.0 and 0.11.3, 
but then connect to the share. this works for 0.10.0 but fails with 0.11.3 (at least). 

i can also see, that my tests for SmbPath in versions from 0.11.0 and up seem to no longer add backslashes to the path - i guess this might be related.

**Comment by iwek7** [comment]
Had the same issue, in my case what caused issues was SMB3 enabled by default by https://github.com/hierynomus/smbj/commit/a7e9e074cd129aec61c6ce9cd41734887e4e8674 . Setting dialects to `SMB2Dialect.SMB_2_1, SMB2Dialect.SMB_2_0_2` fixed issue. Of course this is just workaround.

**Comment by hierynomus** [comment]
@bangert Can you provide some test scenario? It could very well be we missed some (corner) case.

**Comment by kayloos** [comment]
The current codebase cannot handle the extended referral format, which seems to be necessary when handling DFS referrals in SMB3xx versions.

**Comment by nddipiazza** [comment]
Confirmed. I'll try to get some wireshark dumps but I don't have an environment to get these from at the moment.

**Comment by nddipiazza** [comment]
@hierynomus any chance for a minor version publish to maven for this one?
