### ISSUE TITLE
How to write remote location files using SMB3

### ISSUE THREAD

**Issue by HistoAdmin** [hierynomus/smbj#673]
Sorry if i am asking basic question. Unfortunately I could not find any document for this. I have 2 Synology server and wanted to transfer remotely. Kindly guide me what api should i need to use for this transfer.
Thanks in advance

**Comment by vrr6** [comment]
Hi @HistoAdmin 
You can try the program given by jansohn in https://github.com/hierynomus/smbj/issues/654 
or try using copy method from below class if source is not SMB https://github.com/hierynomus/smbj/blob/bd3d6ad18bb7c31499364db8c1eb7903fe976ebc/src/main/java/com/hierynomus/smbj/utils/SmbFiles.java

Thanks,
R Ramarajan.

**Comment by HistoAdmin** [comment]
Hi @vrr6 
Thanks for your answer.
#654 already tried. It support only with same server. I am expecting source and destination different server. Another link you shared it does copy locally then paste in remote.

**Comment by vrr6** [comment]
Smbj doesn't support remote copy between 2 shares.
Not possible.

**Comment by hierynomus** [comment]
@HistoAdmin What @vrr6 said indeed. As far as I know the SMB protocol has no support for copying remotely between servers. You would need to somehow pass your authentication to the other server downstream. So the flow of data will always be through your client.

**Comment by HistoAdmin** [comment]
> @HistoAdmin What @vrr6 said indeed. As far as I know the SMB protocol has no support for copying remotely between servers. You would need to somehow pass your authentication to the other server downstream. So the flow of data will always be through your client.

Thank you for your clarification.
