### ISSUE TITLE
Is it possible to move/copy files from an SMBv1 network share to an SMBv2/v3 resource?

### ISSUE THREAD

**Issue by bobsag** [hierynomus/smbj#674]
Hi @hierynomus @pepijnve,

Is it possible to move/copy files from an SMBv1 network share to an SMBv2/v3 resource?
I'm trying to copy & move files from an SMBv1 network share to an SMBv2/v3 resource and I'm facing 2 separate issues:
1) For move: I get the error "Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_OBJECT_NAME_NOT_FOUND (0xc0000034): Create failed"

2) For copy: It works fine for the first attempt but it fails with "Caused by: com.hierynomus.mssmb2.SMBApiException: STATUS_ACCESS_DENIED (0xc0000022): Create failed" for subsequent attempts.

Any pointers on this?

Thanks!

**Comment by vrr6** [comment]
Kindly paste your code for suggestions.

**Comment by pepijnve** [comment]
If you want to understand why certain errors happen, you'll have to read through the [server processing rules](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/e1d08834-42e0-41ca-a833-fc26f5132a6f) section of the specification. The library is simply telling you what the server responded.

Note that SMBJ is an SMB2+ only library. It does not support SMB1.x/CIFS.

**Comment by bobsag** [comment]
> If you want to understand why certain errors happen, you'll have to read through the [server processing rules](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/e1d08834-42e0-41ca-a833-fc26f5132a6f) section of the specification. The library is simply telling you what the server responded.
> 
> Note that SMBJ is an SMB2+ only library. It does not support SMB1.x/CIFS.

So @pepijnve , it means that it's **not** possible to move/copy files from an SMBv1 network share to an SMBv2/v3 resource right?

**Comment by hierynomus** [comment]
@bobsag Not using _just_ smbj indeed. You could try using jcifs to obtain an `InputStream` from a file hosted on an SMBv1 server, and copy the bytes to an `OutputStream` from smbj that points to a location on an SMBv2 share.

**Comment by bobsag** [comment]
@hierynomus
Got it. Thanks!
