### ISSUE TITLE
com.hierynomus.mssmb2.SMBApiException: STATUS_TOO_MANY_OPENED_FILES (0xc000011f): Create failed for

### ISSUE THREAD

**Issue by hfjdkedf** [hierynomus/smbj#678]
I am trying to copy several thousand files to the Server using a simple recursive algorithm. After about 8800 copied files, I get multiple exceptions:

com.hierynomus.mssmb2.SMBApiException: STATUS_TOO_MANY_OPENED_FILES (0xc000011f): Create failed for \\192.168.42.97\B\\project\data\com\files\test\7\07.bin
        at com.hierynomus.smbj.share.Share.receive(Share.java:371)
        at com.hierynomus.smbj.share.Share.sendReceive(Share.java:351)
        at com.hierynomus.smbj.share.Share.createFile(Share.java:159)
        at com.hierynomus.smbj.share.DiskShare.createFileAndResolve(DiskShare.java:97)
        at com.hierynomus.smbj.share.DiskShare.resolveAndCreateFile(DiskShare.java:79)
        at com.hierynomus.smbj.share.DiskShare.open(DiskShare.java:66)
        at com.hierynomus.smbj.share.DiskShare.exists(DiskShare.java:193)
        at com.hierynomus.smbj.share.DiskShare.fileExists(DiskShare.java:172)

Again and again, all time: STATUS_TOO_MANY_OPENED_FILES.
What does this exception mean?

**Comment by hierynomus** [comment]
That there's too many files being opened. Are you closing all the Opens?

**Comment by hfjdkedf** [comment]
I create a thread in which I call a class with `SmbConfig` next I call:
```
try (Connection connection = client.connect(hostname,port)) {
........
       try (DiskShare share = (DiskShare) session.connectShare(shareName)) {

              for (file : fileMassive) {
                    SmbFiles.copy(file, share, path_for_server, true);
              }

       // And already in DiskShare, I recursively copy the entire array of folders and files
       }
}
```

As I understand from your words, with each new copy of the file, the connection to the server remains open, and with subsequent copies, new connections are created, did I understand correctly? If so, how can I close these files?

**Comment by hierynomus** [comment]
The real question is here how does the rest of this loop look? Most probably you're forgetting a single close (or closing that too late), leading to a massive buildup of open files.

**Comment by hierynomus** [comment]
Every resource you open (Connection, Session, Share, File) has an associated `close()` method (i.e. it is a `java.io.Closeable`). Once you're done with it, you should be calling htat method to free up the resources. Usually you do that in a `finally` block

**Comment by hfjdkedf** [comment]
Thank you very much for the help. It worked:
```
    share.close();
    session.close();
    connection.close();
```
Because of this, a decrease in copying speed is observed. But I think I’ll come up with something.

**Comment by Zaodianshui0928** [comment]
Have you solved the problem? When I copy the folder, I use a recursive way to nearby files and create folders, and the error is the same as yours
