### ISSUE TITLE
Bug in SmbFiles mkdirs always causes STATUS_OBJECT_NAME_COLLISION

### ISSUE THREAD

**Issue by f-de** [hierynomus/smbj#679]
There is a bug in com.hierynomus.smbj.utils.SmbFiles mkdirs which always causes SMBApiException: STATUS_OBJECT_NAME_COLLISION. This method is supposed to check if a folder and its parents exist and create them otherwise. But it will try to create an already existing directory.

```
public void mkdirs(DiskShare diskShare, SmbPath path) throws SMBApiException {
	if (!diskShare.folderExists(path.getPath())) {
		// Ensure the parent path exists
		mkdirs(diskShare, path.getParent());
	}
	diskShare.mkdir(path.getPath());
}
```

This should be correct:

```
public void mkdirs(DiskShare diskShare, SmbPath path) throws SMBApiException {
	if (!diskShare.folderExists(path.getPath())) {
		// Ensure the parent path exists
		mkdirs(diskShare, path.getParent());
		diskShare.mkdir(path.getPath());
	}
}
```

The error was apparently introduced in this change:
https://github.com/hierynomus/smbj/commit/5cf73b2bd76380dad927aaa48e89d806a898cb20#diff-dd81c4aafc6bf89377f022a5f6f2e7f471e39d82054313db1a7e91325cbea733

**Comment by hierynomus** [comment]
This should be fixed with #685
