### ISSUE TITLE
Question: Delete on Close

### ISSUE THREAD

**Issue by iremugurlu** [hierynomus/smbj#680]
Hi,

We are facing issues regarding the deletion of a file. The file is not removed as long as the connection is open. However we believe that files should also be removed when the connection is still open. But from your code, it seems like you do deletion on close. But this assumes that after deletion it is not wanted to do other actions on that directory based on content.

In our case we have a directory and a file inside it. We first remove the file and then the directory but since the connection is still open the file is not removed thus when we try to remove the directory we get an exception. But we don't want to do a recursive deletion since we have parallel processes inside our code. And we also don't want to do unnecessary open and close share actions to solve this problem.

My question is why do you do deletion on close and what do you advice in this scenario?

**Comment by hierynomus** [comment]
Hi @iremugurlu, the File should be deleted as soon as the File resource itself is closed, i.e. as long as you still have an open handle to the File, SMB will not delete the underlying data. As soon as you call `File.close()` the resource is released, and the file will actually be removed from the remote file system.

**Comment by iremugurlu** [comment]
Hi @hierynomus,

Thanks for your answer. Let me be more clear about how we use smbj. Currently, after we open a share, we do multiple actions via this open share which is only closed when no more actions need to be made. We don't want to open/close multiple shares and/or files unnecessarily. 

E.g. we open a share and we do a file delete, after a couple of actions when we need to delete another directory that uses the same share we get an exception since the file we previously deleted is not removed in practice because we didn't close the share. So, we do not want this to happen. But as I already mentioned we also don't want to open/close multiple shares and/or files unnecessarily.

**Comment by neoxpert** [comment]
Do you have some code (exapmple) available? At least I could not reproduce any problem with deleting files or recursive deletion of whole directory structures on a persistent and reused share connection.

**Comment by iremugurlu** [comment]
Hi, I have created a code example for this. You can check the following project I attached. There is a simple method and test case for the scenario we live:
[example-smbj.zip](https://github.com/hierynomus/smbj/files/7871717/example-smbj.zip)

**Comment by iremugurlu** [comment]
This solved our issue. Thanks a lot!

**Comment by isakulaksiz** [comment]
> Hi, I have created a code example for this. You can check the following project I attached. There is a simple method and test case for the scenario we live: [example-smbj.zip](https://github.com/hierynomus/smbj/files/7871717/example-smbj.zip)

thanks
