### ISSUE TITLE
[smbj] VeraCode scan show "Use of Hard-coded Cryptographic Key" and "Use of a Broken or Risky Cryptographic Algorithm" ?

### ISSUE THREAD

**Issue by HendryLai** [hierynomus/smbj#689]
VeraCode show smbj 0.11.3 have 2 risky vunlerabilities :

**1. Use of Hard-coded Cryptographic Key(CWE ID 321)**
> JceAEADCipher.java line 55 
` cipher.init(javax.crypto.Cipher.DECRYPT_MODE, new SecretKeySpec(bytes, cipher.getAlgorithm().split("/")[0]), gcmParameterSpec);`

> JceAEADCipher.java line 57
`cipher.init(javax.crypto.Cipher.ENCRYPT_MODE, new SecretKeySpec(bytes, cipher.getAlgorithm().split("/")[0]), gcmParameterSpec);`

> SMBSessionBuilder.java line 307
`cipher.init(javax.crypto.Cipher.ENCRYPT_MODE, new SecretKeySpec(bytes, cipher.getAlgorithm().split("/")[0]), gcmParameterSpec);`

**2. Use of a Broken or Risky Cryptographic Algorithm(CWE ID 327)**
> PacketEncryptor.java line 71
`aeadBlockCipher.init(Cipher.CryptMode.DECRYPT, decryptionKey.getEncoded(), new GCMParameterSpec(128, realNonce));`

> PacketEncryptor.java line 138
`final GCMParameterSpec parameterSpec = new GCMParameterSpec(128, nonceField);`

is any new version fixing vunlerabilities ?

**Comment by HendryLai** [comment]
I have no idea why code listed below were scan as a hard-coded cryptographic key,  try to ask veracode if any suggestion 
`cipher.init(javax.crypto.Cipher.DECRYPT_MODE, new SecretKeySpec(bytes, cipher.getAlgorithm().split("/")[0]), gcmParameterSpec);`

**Comment by hierynomus** [comment]
In essence VeraCode is right, the encryption (and decryption) keys are hardcoded in `SmbSessionBuilder`. However these are the keys that are precisely needed to get the SMB protocol to work, as specified in the MS-SMB2 docs. As is the "broken or risky algorithm". That is indeed not as secure as you would want it to be, but the SMB protocol offers no support for more advanced (elliptic) algorithms as of yet.

**Comment by hierynomus** [comment]
Please close the issue if this question has been answered.

**Comment by HendryLai** [comment]
ok,I see, totally agree.

I tried rebuilding code mentioned above for testing purpose  :
1.  add new string variable outside cipger.init 
2.  add key length in GCMParameterSpec to 512 

and it seems work ,  i just wonder if some restriction for detecting vulnerabilities in that scan rule. 
anyway, i still using 0.11.3 version, and just explain it's not that high risky.

> In essence VeraCode is right, the encryption (and decryption) keys are hardcoded in `SmbSessionBuilder`. However these are the keys that are precisely needed to get the SMB protocol to work, as specified in the MS-SMB2 docs. As is the "broken or risky algorithm". That is indeed not as secure as you would want it to be, but the SMB protocol offers no support for more advanced (elliptic) algorithms as of yet.
