### ISSUE TITLE
[Question]: isFile method?

### ISSUE THREAD

**Issue by isabsent** [hierynomus/smbj#690]
As I understand

    boolean isFolder = EnumWithValue.EnumUtils.isSet(f.getFileAttributes(), FileAttributes.FILE_ATTRIBUTE_DIRECTORY)
is a way to define is **f** a folder. But what is a way to define is **f** a file? Or do you mean a file is all that is not a folder?

**Comment by hierynomus** [comment]
Yes, anything that's not a folder is per definition a file.
