### ISSUE TITLE
no documentation how to use with spring framework (or how to do pool or long-live connections)

### ISSUE THREAD

**Issue by degr** [hierynomus/smbj#692]
All examples in main "readme" contains such code:

```java
try(SmbClient client = new SmbClient()) {
try(Connection connection = client.getConnection()) {
try(Session session = connection.getSession()) {
try(DiskShare share = session.getShare()) {
...
}
}
}
}
```
and almost everywhere I can see - "{client|connection|session|share} opened in try-catch block, so it will be closed by itself".

Here - https://github.com/hierynomus/smbj/issues/300
people talk DiskShare is tread safe object, and could be used by multiple threads.

From my experiments, if I store "DiskShare" object in spring context, and use it in multuple (30) threads, everything work more then 2 times faster (at least for "read"), compare if I will create new client-connection-session each time I need DiskShare. Is it ok to store it as a bean? Or after a while "DiskShare" will be closed because of timeout or something? Is there some kind of api or wrapper for spring or at least documentation with examples?

**Comment by HendryLai** [comment]
for me i don't think smbj need a  strong relation tied to spring ,  for me most use cases smbj would be utilities for remote shared folder read / write operation , i guess you could write your own bean owning authentication object and autowired in your service implementation

**Comment by degr** [comment]
Question is not about spring itself, question more how to do something like a "pool" which will be able to hold and recreate connections if previous one was closed. Shall I keep references to all objects like "connection, session and share", or I can use only "share" in combination "share.isConnected()"?

**Comment by hierynomus** [comment]
Sorry, this will end up so low on my priority list that I will never get to it. Though I do agree we could use more documentation, adding documentation on how to use this within Spring is not going to be added.
