### ISSUE TITLE
Cannot read data in a file

### ISSUE THREAD

**Issue by tvessiere** [hierynomus/smbj#699]
Hello there. 

I'm a bit confuse... I'm not able to read the data in a file, the InputStream returned as no bytes inside. 

Here is the code : 
`
		        try (DiskShare share = (DiskShare) session.connectShare("MyShare"))
		        {

		        	File file = share.openFile("testPGMVT.txt",
		        			EnumSet.of(AccessMask.GENERIC_READ),
		        			null,
		        			SMB2ShareAccess.ALL,
		        			SMB2CreateDisposition.FILE_OPEN,
		        			null);
		        	
		        	InputStream is =  file.getInputStream();
		        	System.out.println("bytes available : " + is.available());
		        	byte [] data = new byte[is.available()];
		        	is.read(data);
		        	String S = new String(data);
		        	System.out.println("Data in file : " + S);
		        	
		        	file.close();
		        	is.close();

		        } 
		        catch (IOException e) 
		        {
				e.printStackTrace();
			}
		    } 
`
The output : 
`
Bytes available : 0
Data in file : 
`

Can you help me ? 

Thanks you.

**Comment by isakulaksiz** [comment]
```
 Session session = startConnection(context);
        DiskShare share = (DiskShare) session.connectShare("YOUR_SHARED_FOLDER_NAME");

        ArrayList<H3CashOut> fileContentArrayList = new ArrayList<>();
        com.hierynomus.smbj.share.File f = share.openFile(path2, of(FILE_READ_DATA), null, SMB2ShareAccess.ALL, FILE_OPEN, null);
        InputStream in = f.getInputStream();

        BufferedReader reader = new BufferedReader(new InputStreamReader(in));
        String line;

        while ((line = reader.readLine()) != null) {
            H3CashOut h3 = new H3CashOut(line.split(";")[0].replace("\"", ""), line.split(";")[1].replace("\"", ""), line.split(";")[2].replace("\"", ""));
            fileContentArrayList.add(h3);
        }

        in.close();
        f.close();
```

**Comment by tvessiere** [comment]
Hello, what is H3CashOut class ?

**Comment by isakulaksiz** [comment]
Hi @tvessiere ,
You must have a data class where you define the values you hold in the HS3CASH.OUT file as variables

```
var reservationNumber: String,
 var objectNumber: String,
var guestName: String,
etc...
```

**Comment by isakulaksiz** [comment]
> what is H3CashOut

You must have a data class where you define the values you hold in the HS3CASH.OUT file as variables

**Comment by hierynomus** [comment]
The `FileInputStream` will always return `0`, as per the contract of `java.io.InputStream`, which is:

> Note that while some implementations of InputStream will return the total number of bytes in the stream, many will not. It is never correct to use the return value of this method to allocate a buffer intended to hold all data in this stream.

**Comment by isakulaksiz** [comment]
> The `FileInputStream` will always return `0`, as per the contract of `java.io.InputStream`, which is:
> 
> > Note that while some implementations of InputStream will return the total number of bytes in the stream, many will not. It is never correct to use the return value of this method to allocate a buffer intended to hold all data in this stream.

Can you give some advice on what I can use for this?

**Comment by hierynomus** [comment]
```
File file = share.openFile("testPGMVT.txt",
	        			EnumSet.of(AccessMask.GENERIC_READ),
	        			null,
	        			SMB2ShareAccess.ALL,
	        			SMB2CreateDisposition.FILE_OPEN,
	        			null);
ByteArrayOutputStream baos = new ByteArrayOutputStream();
file.read(baos);
byte[] b = baos.toByteArray();
```

**Comment by isakulaksiz** [comment]
> File file = share.openFile("testPGMVT.txt",
> 	        			EnumSet.of(AccessMask.GENERIC_READ),
> 	        			null,
> 	        			SMB2ShareAccess.ALL,
> 	        			SMB2CreateDisposition.FILE_OPEN,
> 	        			null);
> ByteArrayOutputStream baos = new ByteArrayOutputStream();
> file.read(baos);
> byte[] b = baos.toByteArray();

thanks :)

**Comment by tvessiere** [comment]
> > File file = share.openFile("testPGMVT.txt",
> > EnumSet.of(AccessMask.GENERIC_READ),
> > null,
> > SMB2ShareAccess.ALL,
> > SMB2CreateDisposition.FILE_OPEN,
> > null);
> > ByteArrayOutputStream baos = new ByteArrayOutputStream();
> > file.read(baos);
> > byte[] b = baos.toByteArray();
> 
> thanks :)

Thansk you man, i was busy at work, can't check it now, but i will run it quickly in the next days :) 

have a nice week all of you.
