### ISSUE TITLE
Support Signing

### ISSUE THREAD

**Issue by sbellan** [hierynomus/smbj#7]
Windows Server 2012 seems to have 'Required Signature' enabled by default.  So need to implement that. MS-SMB2 3.2.4.1.1 Signing the Message

**Comment by dhoehmann** [comment]
Yes need that, too! SMBv1 gets switched off in many environments for security reasons - and that only makes sense if message signing is enforced

**Comment by hierynomus** [comment]
Intention is certainly to implement this in the future. It's not trivial, but also not impossible.

**Comment by ckherrmann** [comment]
I've been working on SMBv2 signing with SMBJ.  I just created a fork to share the code and will be putting it out for review soon.

**Comment by hierynomus** [comment]
Wow, great! Looking forward. You do need to change the authentication interface, to return more than just a `sessionId`, but that would be perfect. Bring it on!

**Comment by ckherrmann** [comment]
I submitted the pull request.  Look forward to hearing your comments.  Also, would appreciate suggestions for how to add tests to your test framework for this.

**Comment by sbellan** [comment]
@ckherrmann @hierynomus 
I also created a new pull request for the smb2 signature stuff :( https://github.com/hierynomus/smbj/pull/27 
But I'm having issues with supporting signatures with SMB2WriteRequest because of the streaming model.

**Comment by sbellan** [comment]
@hierynomus Feel free to decline the pull request for signing. I got some ideas from @ckherrmann about delayed signature computation. I have couple of other changes (list Directory, Nt error codes) in the same pull request, I can submit a new pull request for it.

**Comment by hierynomus** [comment]
Please do split it! The pr from @ckherrmann os already in a pretty good
shape. Need to review the changes.

Thanks!

Op 8 nov. 2016 2:16 a.m. schreef "sbellan" <notifications@github.com>:

**Comment by hierynomus** [comment]
Was implemented with #26
