### ISSUE TITLE
performance needs

### ISSUE THREAD

**Issue by tangxuGoGoGo** [hierynomus/smbj#703]
If after I create a DiskShare object, multiple threads use this object to construct a large number of File or other file operation requests, will it have a performance impact?

**Comment by hierynomus** [comment]
I cannot tell based on what you're asking, what have you tried/measured?

**Comment by tangxuGoGoGo** [comment]
I didn't do a measurement, just thinking about whether it would be more efficient to create multiple diskShares when doing multithreading to upload multiple files. I hope you can give advice

**Comment by hierynomus** [comment]
I think that depends on too many variables to give an answer to. i.e. your bandwidh, server's bandwidth, server's implementation, per connection tcp settings. 

It is anyway faster to use either a single DiskShare, or a pool of pre-connected shares, than connecting and authenticating for each request.

**Comment by tangxuGoGoGo** [comment]
OK, the feasibility of multithreaded connections has been verified. Everything works fine except for the window10 smb share limit of 20 connections. Thank you very much for your reply！
