### ISSUE TITLE
SMB Encryption

### ISSUE THREAD

**Issue by sepspring** [hierynomus/smbj#708]
Hi,

Thank you for a great SMB library.

Does smbj support SMB 3's end-to-end encryption ?
https://docs.microsoft.com/en-us/windows-server/storage/file-server/smb-security

Thanks for your help,
Sep

**Comment by hannosgit** [comment]
Yes it does support encryption, you can configure this in the [SmbConfig](https://github.com/hierynomus/smbj/blob/c1a8392502c2e32968004566a3dd7ad2031f2d97/src/main/java/com/hierynomus/smbj/SmbConfig.java#L448) class.

**Comment by hierynomus** [comment]
Closing as answered.
