### ISSUE TITLE
Login with non existing user succeed when server supports Guest/Anonymous users

### ISSUE THREAD

**Issue by TsvetanBogoev** [hierynomus/smbj#713]
I expect to receive SMBApiException: STATUS_LOGON_FAILURE whenever the provided username is wrong (non existing user)
Instead it seems that authentication fallback to the guest user when it's enabled. Do we have some control over this? Or do I miss something?

    SMBClient client = new SMBClient();
    try (Connection connection = client.connect("100.100.100.100")) {
        AuthenticationContext ac = new AuthenticationContext("UnExistingUser", "PASSWORD".toCharArray(), "DOMAIN");
        Session session = connection.authenticate(ac);
        //success!!!!
    }

**Comment by hierynomus** [comment]
I think this is server specific, The SMBJ client has no such logic to fallback or detect this.
