### ISSUE TITLE
share.list("path", "*.*") , can i get files which starts with a or starts with b 

### ISSUE THREAD

**Issue by sdabing** [hierynomus/smbj#714]

**Comment by hierynomus** [comment]
This is the documentation on the `searchPattern`:

     * Two wild card characters are supported in the search pattern. The "?" (question mark) character matches a single>>
     * character. If a search pattern contains one or more "?" characters, then exactly that number of characters is
     * matched by the wildcards. For example, the criterion "??x" matches "abx" but not "abcx" or "ax", because the two
     * file names do not have enough characters preceding the literal. When a file name criterion has "?" characters
     * trailing a literal, then the match is made with specified number of characters or less. For example, the
     * criterion "x??" matches "xab", "xa", and "x", but not "xabc". If only "?" characters are present in the file name
     * selection criterion, then the match is made as if the criterion contained "?" characters trailing a literal.
     * The "*" (asterisk) character matches an entire file name. A null or empty specification criterion also selects
     * all file names. For example, "*.abc" or ".abc" match any file with an extension of "abc". "*.*", "*", or empty
     * string("") match all files in a directory.

As you can read from there it will not be possible using a single list. You have 2 options:
1. Do 2 `list`s, one with `a*` and one with `b*`
2. Do a single `list` and filter the files clientside.
