### ISSUE TITLE
STATUS_ACCESS_DENIED (0xc0000022): Authentication failed when accessing AWS S3 SMB share with SMB_3_1_1

### ISSUE THREAD

**Issue by mandarb1988** [hierynomus/smbj#728]
Getting authentication failed while trying to connect to the AWS S3 SMB path using SMB_3_1_1. 
Getting below error: 
STATUS_ACCESS_DENIED (0xc0000022): Authentication failed for '[username]' using [com.hierynomus.smbj.auth.NtlmAuthenticator@4b5189ac](mailto:com.hierynomus.smbj.auth.NtlmAuthenticator@4b5189ac)

Using Below Code: 
SmbConfig cfg = SmbConfig.builder()
	    		.withTimeout(120000, TimeUnit.SECONDS)
	    		.withTimeout(120000, TimeUnit.SECONDS) 
	    		.withSoTimeout(180000, TimeUnit.SECONDS)
	    		.withMultiProtocolNegotiate(true)
	    		.withSecurityProvider(new JceSecurityProvider(new BouncyCastleProvider()))
	    		.build();
        try (SMBClient client = new SMBClient(cfg)){
    	    
    	    **connection = client.connect(smbIP);
Session session = connection.authenticate(new AuthenticationContext(smbUserName, smbPassword.toCharArray(), smbDomain));** // from this line getting above exception
    	   
    	    
    	    DiskShare share = (DiskShare) session.connectShare(smbSharePath);
    	   
    	    
    	    if(!share.folderExists(destinationFolderName)) {
            	share.mkdir(destinationFolderName);
           }
    	    
            fileName = destinationFolderName+"\\"+fileName;
            
            
            f = share.openFile(fileName,
	                new HashSet<>(Arrays.asList(AccessMask.GENERIC_ALL)),
	                new HashSet<>(Arrays.asList(FileAttributes.FILE_ATTRIBUTE_NORMAL)),
	                SMB2ShareAccess.ALL,
	                SMB2CreateDisposition.FILE_CREATE,
	                new HashSet<>(Arrays.asList(SMB2CreateOptions.FILE_DIRECTORY_FILE))
	        );
            
           

    	    try(OutputStream os = f.getOutputStream()){
    	    	os.write(fileContent);
    	    }catch (Exception e) {
    	    	
    		}
}

**Comment by hierynomus** [comment]
This should now be fixed on the latest master.
