### ISSUE TITLE
Unresolved reference: SMBApiException

### ISSUE THREAD

**Issue by LeafyLappa** [hierynomus/smbj#785]
There's this section in README.md:

<img width="860" alt="Screenshot 2023-08-17 at 7 43 08 PM" src="https://github.com/hierynomus/smbj/assets/31704619/cf9d1ec7-45bd-407c-add4-e0a931de9cee">

However the SMBApiException class does not seem to exist. There only seems to be SMBException.

**Comment by andershermansen** [comment]
Its there in the com.hierynomus.mssmb2  package. 

Ref: https://github.com/hierynomus/smbj/blob/master/src/main/java/com/hierynomus/mssmb2/SMBApiException.java

**Comment by LeafyLappa** [comment]
Hmm okay. Thank you

**Comment by andershermansen** [comment]
It’s a low level library. You would have to iterate through the files in a directory one by one and download.
