### ISSUE TITLE
Support DFS Referrals

### ISSUE THREAD

**Issue by sbellan** [hierynomus/smbj#8]
Machines using the SMB 2 Protocol can use the Distributed File System (DFS): Referral Protocol as specified in [MS-DFSC] to resolve names from a namespace distributed across many servers and geographies into local names on specific file servers.

DFS clients communicate with DFS servers via referral requests/responses conveyed in SMB2 IOCTL messages, analogous to a file system client performing control operations on a remote object store via requests/responses conveyed in SMB2 IOCTL messages. The communication between the SMB2 server and the DFS server (or SMB2 server and object store), for the purpose of performing the specified IOCTL operations, is local to the server machine, and takes place via implementation-dependent means.

**Comment by ckherrmann** [comment]
I've been working on DFS Referrals.  It's not quite all done, but it is pushed to a branch of my fork, if you're interested.

**Comment by hierynomus** [comment]
Wow, great! Will have a look. Looking forward to the pr!

Op 19 nov. 2016 2:01 a.m. schreef "ckherrmann" <notifications@github.com>:

**Comment by hierynomus** [comment]
@ckherrmann Any chance you are able to send a PR before Friday? I want to try to release a new version Friday end of day with all the new features.

**Comment by ckherrmann** [comment]
No, it needs a lot more testing.  (Plus, it's a holiday here.)

**Comment by gidravlic** [comment]
Hello guys! How goes implementation of dfs in you library?

**Comment by hierynomus** [comment]
@gidravlic It keeps me awake in the evenings... Currently cleaning up the code on a separate branch. Hopefully somewhere next week that I have something that I feel comfortable merging :).

**Comment by gidravlic** [comment]
Nice! Good news! :)

**Comment by hierynomus** [comment]
@sbellan @gidravlic @ckherrmann #46 has been merged. By default DFS is disabled currently but it can be turned on with the `SmbConfig.withDfsEnabled(true)` configuration setting.
