### ISSUE TITLE
How excute the command on remover server 

### ISSUE THREAD

**Issue by selvakumartvsk** [hierynomus/smbj#802]
We have requirement, we have to execute the bat file on remote server in java ,  so how to achieve that by 
SMBclient

**Comment by selvakumartvsk** [comment]
@hierynomus Could you help me on this? 
Whether this is achievable  by using   SMBclient()

**Comment by hierynomus** [comment]
@selvakumartvsk No, the SMB protocol is not suited for command execution. For that you would need WinRM.

**Comment by selvakumartvsk** [comment]
@hierynomus Thanks for the information.
