### ISSUE TITLE
SMBJ Performance

### ISSUE THREAD

**Issue by proxymus89** [hierynomus/smbj#817]
I noticed that using Windows file explorer I have speeds up to 4 times faster than smbj. why is smbj so slow? I tried to change all the possible parameters of smbj but to no avail. Is there something I'm missing or is it actually a limitation of the library?

**Comment by hierynomus** [comment]
It highly depends on your method of testing... What types of streams are you using? Are you using the same dialect and encryption standards?

**Comment by nashkevichv** [comment]
Thank you for the hint.
Below is output for the SmbFiles.copy(sourceFile, share, targetPath, true) try 
 
### smbJ with Smbfiles.copy
time [763] ms. speed [48472320] B/s size [36984380]
time [719] ms. speed [51438636] B/s size [36984380]
time [708] ms. speed [52237824] B/s size [36984380]
time [678] ms. speed [54549236] B/s size [36984380]
time [724] ms. speed [51083400] B/s size [36984380]
time [696] ms. speed [53138476] B/s size [36984380]
time [757] ms. speed [48856512] B/s size [36984380]
time [771] ms. speed [47969364] B/s size [36984380]
time [741] ms. speed [49911444] B/s size [36984380]
time [714] ms. speed [51798852] B/s size [36984380]
### smbJ with Smbfiles.copy 

overall performance is approximately the same.

**Comment by nashkevichv** [comment]
I started test with all versions of smbj. Release 0.10.0 was 10% faster  than 0.13.0.

On pc with 10Gb network i got the following results :

### smbJ
buffer [12288] time [319] ms. speed [115938496] B/s size [36984380]
buffer [12288] time [302] ms. speed [122464832] B/s size [36984380]
buffer [12288] time [300] ms. speed [123281264] B/s size [36984380]
buffer [12288] time [298] ms. speed [124108656] B/s size [36984380]
buffer [12288] time [297] ms. speed [124526528] B/s size [36984380]
buffer [12288] time [290] ms. speed [127532344] B/s size [36984380]
buffer [12288] time [284] ms. speed [130226688] B/s size [36984380]
buffer [12288] time [285] ms. speed [129769760] B/s size [36984380]
buffer [12288] time [283] ms. speed [130686848] B/s size [36984380]
buffer [12288] time [285] ms. speed [129769760] B/s size [36984380]
### end of smbJ
### smbJ with Smbfiles.copy
time [440] ms. speed [84055408] B/s size [36984380]
time [447] ms. speed [82739104] B/s size [36984380]
time [451] ms. speed [82005272] B/s size [36984380]
time [437] ms. speed [84632448] B/s size [36984380]
time [360] ms. speed [102734392] B/s size [36984380]
time [331] ms. speed [111735288] B/s size [36984380]
time [445] ms. speed [83110968] B/s size [36984380]
time [397] ms. speed [93159648] B/s size [36984380]
time [437] ms. speed [84632448] B/s size [36984380]
time [435] ms. speed [85021560] B/s size [36984380]
### smbJ with Smbfiles.copy
### local
buffer [16777216] time [77] ms. speed [480316640] B/s size [36984380]
buffer [16777216] time [89] ms. speed [415554848] B/s size [36984380]
buffer [16777216] time [85] ms. speed [435110336] B/s size [36984380]
buffer [16777216] time [93] ms. speed [397681504] B/s size [36984380]
buffer [16777216] time [107] ms. speed [345648416] B/s size [36984380]
buffer [16777216] time [103] ms. speed [359071648] B/s size [36984380]
buffer [16777216] time [83] ms. speed [445594944] B/s size [36984380]
buffer [16777216] time [86] ms. speed [430050944] B/s size [36984380]
buffer [16777216] time [71] ms. speed [520906752] B/s size [36984380]
buffer [16777216] time [92] ms. speed [402004128] B/s size [36984380]
### end of local

So copy to mounted share is really 4 times faster than copy with smbj.

**Comment by nashkevichv** [comment]
Hallo @hierynomus, after some debugging sessions i got a feeling that encryption is a performance killer.

My setup 
	java			  : 17
	smbj		  :	0.13.0
	file upload, size : 344010288 Bytes
	 
SmbConfig smbConfig = SmbConfig.builder()
		.withEncryptData(false)
		.withSigningRequired(false)
		.withTransportLayerFactory(new AsyncDirectTcpTransportFactory<>())
		.withDialects(SMB2Dialect.SMB_3_1_1)
		.build()
;
	Method AsyncDirectTcpTransport.prepareBufferToSend is called 331 times. Each call lasts about 6 ms. ( 331*6 = 1986 ms just for prepareBufferToSend ) 
	In debugger i can also see that the method AESEngine.encryptBlock is called for each 64k chunk (see stack trace below). 
	
![stacktrace](https://github.com/hierynomus/smbj/assets/134144284/8df7070e-b4e9-4e64-80b4-10a3a5de221d)
	Is it possible to disable encryption somehow?  
	It seems calling AsyncDirectTcpTransport.prepareBufferToSend asynchronously can also bring some performance boost.
	
	Thank you in advance, Vitali

**Comment by nashkevichv** [comment]
I do call SmbConfig..withEncryptData(false) but it changes nothing. 
AESEngine.encrypt is called anyway!

**Comment by nashkevichv** [comment]
First of all, @hierynomus, thanks a lot for the SMBJ-library.
  
As described above we can observe pure SMBJ performance comparing to performance Windows  provides by default.

The steps below helped me to improve SMBJ performance.

### SmbConfig
```
final SmbConfig config = SmbConfig.builder()
	.withTransportLayerFactory(new AsyncDirectTcpTransportFactory<>())
     	.build();
```
By default encryptData = false and signingRequired = false. 

### 1 Gbit network
AsyncDirectTcpTransport solves the problem for 1 G/bit network. 
Application test showed average rate 110 - 115 MBytes/s. 

### 10 Gbit network
AsyncDirectTcpTransport did not help. The transfer rate was a little bit higher ( about 140 Mbyres/s ) but far from 10Gbits/s.

After some debugging sessions I found that SMBJ signs data pakages (SMB2WriteRequest).
SmbConfig does not REQUIRE signing but SMBJ simply SIGNS!
Signing takes about 60% of the time. It is 2 times slower than data transfer!
	
I could not find a way how to disable signing with existing SMBJ api,
but the following trick in the `com.hierynomus.smbj.connection.PacketSignatory` class effectively disables signing for data packages :

```
...
private final boolean signDataPackets;

PacketSignatory(SecurityProvider securityProvider, final boolean signDataPackets) {
    this.securityProvider = securityProvider;
    this.signDataPackets = signDataPackets;
  }
  ...
  public SMB2Packet sign(SMB2Packet packet, SecretKey secretKey) {
    if ( secretKey!=null ) 
    {
      if ( packet instanceof SMB2WriteRequest && this.signDataPackets==false )
      {
           return packet;
      }
      return new SignedPacketWrapper(packet, secretKey);
    } 
    logger.debug("Not wrapping {} as signed, as no key is set.", packet.getHeader().getMessage());
    return packet;
  }  
```
After this change the trasfer rate was 650 - 750 Mbytes/s. 
This is a little bit faster than windows does.

### How does Windows work?

In my corporate environment after command

```
net user x: \\server\share 
```
Windows does neither encryption nor signing.
To activate encryption and signing a `/REQUIREPRIVACY` switch is required for the net use command.

If '/REQUIREPRIVACY' is set, then Windows performs significantly slower ( ~ 200-250 Mbytes/s ).

**Comment by tooptoop4** [comment]
amazing! can u raise a PR @nashkevichv ?

**Comment by tooptoop4** [comment]
@hierynomus would you be keen on this?

**Comment by nashkevichv** [comment]
Yes, i would.

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by manish-pai** [comment]
I have raised a PR https://github.com/hierynomus/smbj/pull/824.

**Comment by proxymus89** [comment]
Hi @hierynomus @nashkevichv 

thanks first of all for the update

I updated the library from 0.12 to 0.14 and updated the initialization by adding ".withSigningEnabled(false)"

I noticed a nice performance increase of almost 100%

however the speed of the windows file explorer by copying and pasting remains twice as fast

from what I understood this fix was supposed to make the library as fast as if not faster than the file explorer, is that correct?

another thing I noticed is that in the logs I see:

- Connection : Signing is disabled for this connection.
- PacketEncryptor : Initialized PacketEncryptor with Cipher << AES_128_CCM >>

is it normal that the PacketEncryptor is initialized anyway even if I have

.withSigningEnabled(false)
.withEncryptData(false)

set?do you have any suggestions on how to improve the performance to match that of the file explorer?

PS. actually my upload implementation is

```
Set<FileAttributes> fileAttributes = new HashSet<>();
fileAttributes.add(FileAttributes.FILE_ATTRIBUTE_NORMAL);
Set<SMB2CreateOptions> createOptions = new HashSet<>();
createOptions.add(SMB2CreateOptions.FILE_RANDOM_ACCESS);
File f = diskShare.openFile(remotePath, new HashSet<>(List.of(AccessMask.GENERIC_WRITE)), fileAttributes, SMB2ShareAccess.ALL, SMB2CreateDisposition.FILE_OVERWRITE_IF, createOptions);

var out = new BufferedOutputStream(f.getOutputStream(), uploadBufferSize);
IOUtils.copy(transcodedSrcStream, out, uploadReadBufferSize);
```
