### ISSUE TITLE
dreprecated  SmbConfig.withWorkStationName(...)

### ISSUE THREAD

**Issue by araneolus** [hierynomus/smbj#842]
Hi,

I wanted to replace the dreprecated method withWorkStationName with the method described in the java api documentation, but I cannot do this because the method withNtlmConfig(NtlmConfig.builder().withWorkstationName(..).build()) does not exist.
There is only the method withNtlmConfig() without parameters.
Is this a bug or a feature :-)

**Comment by hierynomus** [comment]
It should be `withNtlmConfig().withWorkstationName(...)`

**Comment by araneolus** [comment]
How do I add withNtlmConfig().withWorkstatationName(...) to the following command ?

					final SmbConfig config = SmbConfig.builder().withSocketFactory(factory)
							.withDialects(supportedSmdDialects).withWorkStationName(this.getWorkstaionName())
							.withSecurityProvider(new BCSecurityProvider())
							.withTransactTimeout(this.getTransactionTimeout(), TimeUnit.SECONDS)
							.withTimeout(this.getTransactionTimeout(), TimeUnit.SECONDS)
							.withSoTimeout(this.getSoTimeout(), TimeUnit.SECONDS)
							.withMultiProtocolNegotiate(this.getMultiProtocolNegotiate())
							.withEncryptData(this.getEncryptData())
							.withDfsEnabled(this.getDfsEnabled().equals(Feature.ENABLE) ? true : false).build();

**Comment by hierynomus** [comment]
You can't in 1 go.. It's a nested builder

**Comment by araneolus** [comment]
I have looked at the sources and unfortunately have not found a way to integrate the NtlmConfig into the SmbConfig :-(
Can you just show me an example of how to get the workstation name into the SmbConfig. That would be very helpful for me.

**Comment by hierynomus** [comment]
```
SmbConfig.Builder builder = SmbConfig.builder().withSocketFactory(factory)
						.withDialects(supportedSmdDialects)
						.withSecurityProvider(new BCSecurityProvider())
						.withTransactTimeout(this.getTransactionTimeout(), TimeUnit.SECONDS)
						.withTimeout(this.getTransactionTimeout(), TimeUnit.SECONDS)
						.withSoTimeout(this.getSoTimeout(), TimeUnit.SECONDS)
						.withMultiProtocolNegotiate(this.getMultiProtocolNegotiate())
						.withEncryptData(this.getEncryptData())
						.withDfsEnabled(this.getDfsEnabled().equals(Feature.ENABLE) ? true : false);
builder.withNtlmConfig().withWorkstationName(this.getWorkstationName());
final SmbConfig config = builder.build();
```
