### ISSUE TITLE
org.bouncycastle version update

### ISSUE THREAD

**Issue by Apisero-Connectors** [hierynomus/smbj#847]
Hi @hierynomus,

We are facing below issue while using the SMBJ library -
![Issue](https://github.com/user-attachments/assets/cf7be1cf-0f85-4a1d-825a-e1e594b469b0)

Below dependency needs to updated from 1.75 version to 1.78 version as the current provided version is having security vulnarabilities.

<dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk18on</artifactId>
      <version>1.75</version>
      <scope>runtime</scope>
    </dependency>

Thanks

**Comment by hierynomus** [comment]
The just released 0.14.0 upgrades bcprov to 1.79
