### ISSUE TITLE
No timeout while waiting on SMB2TreeDisconnect and SMB2Logoff responses

### ISSUE THREAD

**Issue by oranoran** [hierynomus/smbj#85]
I've run into a case where for some reason no response was received from the SMB server to a SMB2TreeDisconnect request.
As a result, my calling thread hung. Also a PacketReader thread probably remains open in this case (haven't verified that).

I think there should definitely be a timeout in the Future.get() call that is waiting for the response.
Not sure what kind of configuration / API changes should govern this - any suggestions?

BTW the same thing seems to happen during Session.close() with waiting for the SMB2Logoff response, should probably add a timeout there too.

**Comment by pepijnve** [comment]
There were quite a few places in the code where indefinite waits were being used. PR #86 adds configurable timeouts for (distinct values for read, write and everything else). Defaults to 60s for all three.

**Comment by hierynomus** [comment]
PR #101 is merged now.
