### ISSUE TITLE
DiskShare.list() not working if client requires signing

### ISSUE THREAD

**Issue by Pernicies** [hierynomus/smbj#94]
If the method list of the DiskShare class is used with a SMBClient instance, that was configured to require signing, an exception will be thrown as an invalid packet signature was received.

Tracking it down in the debugger the exception is raised in the queryDirectory method of the Directory class when the server responds with a message having the nt-status STATUS_NO_MORE_FILES.

This behaviour is/was reproducable on shares hosted on Windows 10 and Windows Server 2012 machines.

**Comment by hierynomus** [comment]
I've seen this happen before on non- NtStatus.SUCCESS responses.

Will dig into it.

2017-06-20 12:57 GMT+02:00 Pernicies <notifications@github.com>:

**Comment by bli-r7** [comment]
This is likely related to https://github.com/hierynomus/smbj/issues/112
