### ISSUE TITLE
Do we support SMB3?

### ISSUE THREAD

**Issue by Git-Koushik** [hierynomus/smbj#96]
I see from the connection/negotiation code, we do not support SMB3 version of the protocol. This version of protocol has end-end encryption capability and other performance enhancements. Do you plan to support?

**Comment by hierynomus** [comment]
It is the intention to support it. However I first want to get smb support
stable.

Op 20 jun. 2017 5:37 p.m. schreef "Git-Koushik" <notifications@github.com>:

**Comment by hierynomus** [comment]
Unless you have any additional questions, I will close this issue.

**Comment by JhaShardendu** [comment]
@hierynomus,
Has the support for SMB 3.0 added to the library?

Regards,
Shardendu.

**Comment by hierynomus** [comment]
No, as of yet, no additional support beyond SMB2.1 has been added.

**Comment by NiravR** [comment]
Hi, @hierynomus,
I have tried SMBJ and it works fine with SMB 2.X protocol. Thanks for this.
Now, Can you please confirm that with SMBJ library, as of now SMB 3 Protocol is supported or any plan in future or not?

**Comment by saranya1988** [comment]
@hierynomus,
Has the support for SMB 3.0 added to the library?

Regards,
SN

**Comment by 3c71** [comment]
I tried disabling SMB 2.x, and it results in SMB 3.x not supported exception. Guess it's not supported. I checked smb3 branch, but I'm not sure it's usable?

**Comment by hierynomus** [comment]
Merged to master with #455
